### ISSUE TITLE
Form Ajax goes to json object

### ISSUE THREAD

**Issue by Panguino** [wpninjas/ninja-forms#1003]
submitting form goes to http://greensock.com/wp-admin/admin-ajax.php?action=ninja_forms_ajax_submit instead of staying in same page.

Page contents of new page look like a json object 

{"form_id":5,"errors":{"required-16":{"msg":"This is a required field","location":16},"required-general":{"msg":"Please ensure all required fields are completed.","location":"general"},"required-17":{"msg":"This is a required field","location":17}},"success":false,"fields":{"14":" \u003Ch2\u003EFill out the information below to request a training session:\u003C\/h2\u003E","16":"","17":"","18":"","19":"","23":"","25":""},"form_settings":{"form_url":"http:\/\/greensock.com\/wp-admin\/admin-ajax.php?action=ninja_forms_ajax_submit","email_from":"","success_msg":"Your form has been successfully submitted.","hide_complete":"0","clear_complete":"1","ajax":"1","append_page":"","logged_in":"0","save_subs":"1","show_title":"0","form_title":"Corporate Training Request Form","date_updated":"2015-12-16 06:04:13","email_type":"html","user_email_msg":"Thank you so much for contacting us. We will get back to you shortly.","user_email_fields":"0","admin_email_msg":"","admin_email_fields":"1","admin_attach_csv":"0","email_from_name":"","status":"","not_logged_in_msg":"","sub_limit_number":"","sub_limit_msg":"","last_sub":"1","sub_id":"","admin_attachments":[],"user_attachments":[],"admin_mailto":[]},"extras":{"_wpnonce":"b12e42dfbd","_wp_http_referer":"\/corporate-training\/","_ninja_forms_display_submit":"1","_form_id":"5","_4WitY":"","_hp_name":"_4WitY","_ninja_forms_field_23":"Submit Request"}}

**Comment by Panguino** [comment]
### Environment ###

Home URL:                http://greensock.com
Site URL:                http://greensock.com
Ninja Forms Version:     2.9.30
WP Version:              4.4
WP Multisite Enabled:    No
Web Server Info:         Apache/2.2.29 (Unix) mod_ssl/2.2.29 OpenSSL/1.0.1e-fips mod_bwlimited/1.4 mod_qos/11.5
PHP Version:             5.4.35
MySQL Version:           5.6.27
PHP Locale:              decimal_point: .thousands_sep: int_curr_symbol: currency_symbol: mon_decimal_point: mon_thousands_sep: positive_sign: negative_sign:
WP Memory Limit:         40 MB
WP Debug Mode:           No
WP Language:             Default
WP Max Upload Size:      2 MB
PHP Post Max Size:       8 MB
Max Input Nesting Level: 64
PHP Time Limit:          30
PHP Max Input Vars:      1000
SUHOSIN Installed:       No
SMTP:                    localhost
smtp_port:               25
Default Timezone:        Default timezone is UTC

### Plugins ###

Installed Plugins:       Advanced Custom Fields: Repeater Field by Elliot Condon version 1.1.1
                         Advanced Custom Fields: WP WYSIWYG by Elliot Condon version 1.0.1
                         Admin Menu Editor by Janis Elsts version 1.5
                         Advanced Custom Fields Repeater Collapser by Mark Root-Wiley version 1.4.3
                         Advanced Custom Fields by Elliot Condon version 4.4.4
                         Akismet by Automattic version 3.1.6
                         BAW Post Views Count by Juliobox version 3.0.2
                         Custom Content Type Manager : Advanced Custom Post Types by Everett Griffiths version 0.9.8.6
                         Custom Permalinks by Michael Tyson version 0.7.21
                         Google XML Sitemaps by Arne Brachhold version 4.0.8
                         (Pro) WordPress IPSConnect by Provisionists version 1.1.3
                         Kimili Flash Embed by Michael Bester version 2.5.3
                         Ninja Forms reCAPTCHA by Aman Saini version 1.2.5
                         Ninja Forms by The WP Ninjas version 2.9.30
                         Post Duplicator by Metaphor Creations version 2.13
                         Raw HTML Pro by Janis Elsts version 1.7
                         Rename wp-login.php (unmaintained) by avryl version 2.5.1
                         Simple Page Sidebars by Cedaro version 1.2.0
                         Simple Taxonomy by Amaury Balmer version 3.5
                         Tag Pages by Bjorn Wijers  version 1.0
                         TinyMCE Advanced by Andrew Ozz version 4.2.8
                         WP Migrate DB Pro by Delicious Brains version 1.5.3
                         WP Show IDs by PriMoThemes.com / WebSharks
                         Inc. version 110709
                         WTI Like Post PRO by webtechideas version 2.1

**Comment by Panguino** [comment]
Tried Disabling other plugins, didn't help.

**Comment by kstover** [comment]
Can you give me a link to your live form?

**Comment by foosfam** [comment]
Did anyone figure this out?  I am seeing the same thing..... :?

If the inputs are good it the message gets submitted but all I get is an ajax string back.

**Comment by saetia** [comment]
#578

**Comment by eikeland** [comment]
I have this issue, but its not related to #578, js is enabled in my browser. the form get submitted and stored in database but the success response just shows the json response on wp-admin/admin-ajax.php?action=ninja_forms_ajax_submit.

**Comment by phongnhat19** [comment]
Have anyone found a solution for this? I have this issue too, JS is enabled (same as @eikeland ). Can anyone help me ?

**Comment by saetia** [comment]
Are you pulling in your form after the initial page load with something like $.load()? 
The issue might be that your form's submit handlers aren't getting attached. either because ninja forms doesn't bind events to the document so forms can be added to the dom late or you're missing the JavaScript that gets included in the footer when you assign a form to a page.

**Comment by svincoll4** [comment]
SOLUTION:
We need to move Ninja Form JS to bottom of page (before closing BODY tag), like this:

```
add_action('wp_enqueue_scripts', 'we_enqueue_scripts');
function we_enqueue_scripts(){
wp_enqueue_script( 'ninja-forms-display',
            NINJA_FORMS_URL . 'js/min/ninja-forms-display.min.js?nf_ver=' . NF_PLUGIN_VERSION,
            array( 'jquery', 'jquery-form', 'backbone', 'underscore' ), false, true );
}
```

Hope this help.

**Comment by phongnhat19** [comment]
Thanks a lot for your help, it works perfectly now.

2017-01-20 16:37 GMT+07:00 svincoll4 <notifications@github.com>:
