### ISSUE TITLE
Default Actions for a newly created form

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#1010]
When a new form is created we need to make sure the following actions are added by default:

- Admin Email
- Success Message
- Save Submissions

**Comment by kjohnson** [comment]
@jameslaws We could probably localize configuration for these, so that @kstover could add them to the actions collection when the form is a new form.

**Comment by jameslaws** [comment]
@kjohnson That sounds good to me. If you want to get your part in place and then assign it to @kstover that would be great.
