### ISSUE TITLE
Add a key_name option for Forms

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#1020]

**Comment by kjohnson** [comment]
@jameslaws do you mean to say a key name for forms? Are forms supposed to have keys?

**Comment by jameslaws** [comment]
@kjohnson Yes. Think about writing custom code that needs to be portable. You have to check that you are working with the write form and form_id could change when moving forms from one site to another. a key_name means that can be ported anywhere.

**Comment by kjohnson** [comment]
@jameslaws that makes sense. Just didn't remember.
