### ISSUE TITLE
Ninja forms doesn't work when the cookie wp_woocommerce_session is set

### ISSUE THREAD

**Issue by rmarpozo** [wpninjas/ninja-forms#1027]
I've been having problem using ninja forms within pages in my woocommerce. If the user has the wp_woocommece_session cookie set the submit buttons stays in processing for ever. The AJAX response from the server is

access-control-allow-credentials:true
access-control-allow-origin:https://latiendafantabulosa.es
cache-control:no-cache, must-revalidate, max-age=0
content-type:text/html; charset=UTF-8
date:Tue, 22 Dec 2015 23:34:29 GMT
expires:Wed, 11 Jan 1984 05:00:00 GMT
host-header:192fc2e7e50945beb8231a492d6a8024
pragma:no-cache
server:nginx
set-cookie:wpSGCacheBypass=0; expires=Tue, 22-Dec-2015 22:34:29 GMT; Max-Age=-3600; path=/
status:200
x-cache-enabled:True
x-content-type-options:nosniff
x-frame-options:SAMEORIGIN
x-robots-tag:noindex

0

There's no JSON in the response.

If I remove the cookie everything works fine.

I have the page excluded from cache because I see a comment in your FAQ saying the cache might be the problem, but it is still not working.

Any idea?

Thanks

**Comment by wpnzach** [comment]
@BFTrick @gedex What are the odds of this being the root of the elusive WooCommerce issue?  With the 3.0 development this issue fell through the cracks.  @rmarpozo We are really sorry for ignoring this, we usually handle support issues through our site but you may have cracked something we've been trying to track down for a few weeks now.  We'll be looking into this in the morning.  @kstover @kjohnson

**Comment by rmarpozo** [comment]
Ok, no problem. Glad to help

**Comment by gedex** [comment]
Setting a cookie shouldn’t break AJAX - There is nothing special there, and no other ajax requests are affected. In fact, we've an example page where we run WC + NF, see https://wpjobmanager.com/contact/

**Comment by kjohnson** [comment]
Yeah, I can't imagine that the cookie itself causes any issue. However, WooCommerce may being acting on that cookie, which causes in interference with the WP AJAX Action.

**Comment by serteckian** [comment]
Hi, I am experiencing a similar issue.

The problem arises when I add a product to my WooCommerce cart. In this case, the following cookies are generated:
- wp_woocommerce_session_xxx...xxx   
- woocommerce_items_in_cart   
- woocommerce_cart_hash   

With these cookies the forms stop working. If they are Ajax, then the undefined typeError is thrown. While if they are Ajax, the form page simply reloads without even checking the mandatory fields. 

Now, if I manually remove the cookie wp_woocommerce_session_xxx...xxx, then the forms start working just fine again.

This error does not happen for logged users, even though the same cookies are created.

Any idea how to fix or workaround this?

Thanks!!

**Comment by kstover** [comment]
Thanks for submitting such detailed reproduction steps. We're pretty sure that we've fixed this in master, and it will be released in version 2.9.48 on Monday morning EST.

**Comment by serteckian** [comment]
Great! The patch has fixed the issue. Thank you very much for your support!
