### ISSUE TITLE
Textarea encoding issue

### ISSUE THREAD

**Issue by perrywortman** [wpninjas/ninja-forms#1050]
Possible Bug:

When label text is set to display inside of a textarea, apostrophes will display as UTF-8 decimal code. Literally, `&#39;`. I checked the database tables and the encoding is set to UTF-8 General. I also tried a bunch of other html codes like `&#8217;`, and `&apos;`, and even `&lsquo;` to no avail.

**Comment by kstover** [comment]
Can you confirm this with version 3.0?

**Comment by kstover** [comment]
I apologise for coming back to this ticket a year later. I'm going to close it; if it's an issue, feel free to open it again with current details.
