### ISSUE TITLE
Merge Tags and WP Editor

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#1071]
I've added the 'rte' setting type, but we need to get merge tags working with the RTE. The first step will be positioning the merge tags button over the RTE in the same way that it is for the textarea.

**Comment by kstover** [comment]
You can see the RTE on the Email or Success Message action.

**Comment by jameslaws** [comment]
@kstover I pulled the latest and IO don't see them.

**Comment by jameslaws** [comment]
I've adjusted the styling to any option that uses RTE. When you click on the merge tags nothing happens though so I think the ball is back in your court.
