### ISSUE TITLE
Processing Shortcodes

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#1074]
We need to make sure that actions and other appropriate settings process shortcodes. Kenny could probably help with this.

**Comment by kjohnson** [comment]
When localizing a form (`/includes/Display/Render.php`), field settings should be checked for a settings of `use_merge_tags`. If `use_merge_tags` is set to true, then the `value` of that settings should be processed with [do_shortcode](https://developer.wordpress.org/reference/functions/do_shortcode/) (which should update the setting `value`).
