### ISSUE TITLE
Tables aren't saved in editor

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#1077]
When adding a table to the editor and publishing when you return to the editor the table has been stripped.

**Comment by kjohnson** [comment]
Seems more like new HTML isn't being saved.

**Comment by kjohnson** [comment]
This issue was with calling `$wpdb->replace`, which requires a db key for comparison. Instead, use `$wpdb->update`, if `0` rows are affected, call `$wpdb->insert`.

**Comment by kjohnson** [comment]
Now it seems that the setting is not being updated if a table is in the value.

**Comment by kjohnson** [comment]
The problem was ACTUALLY with the types set on the migrations. Instead of `tinytext`, should use `longtext` due to uncertainty of input.
