### ISSUE TITLE
Videomail integration?

### ISSUE THREAD

**Issue by binarykitchen** [wpninjas/ninja-forms#1078]
Hello there

I have a cool idea here! How about adding videomail support?
https://github.com/binarykitchen/videomail-client

Check out the live site https://videomail.io which explains it pretty much.

That would enhance Wordpress forms enormously. With the videomail client this recording feature can be included anywhere with one Javascript file only. No need for Flash. Works on all modern browsers (except Safari) and even on Androids.

Another good reason is to support Sign Language (Deaf people). They prefer to sign instead of writing, i.E. in a contact form. Here an example: https://binarykitchen.com/contact/action/add/

If you are open to this idea, I am more than happy to assist or even to submit a PR.

Let me know ...

**Comment by kstover** [comment]
Hey. Thanks for the suggestion! This is definitely something that we'd be happy to explore. I think it probably fits in an add-on rather than in the core plugin, but once we release 3.0, it would be pretty easy to implement.

**Comment by binarykitchen** [comment]
thanks @kstover ... but this is something I d like to do real soon without much delay. can you estimate when v3 might be released?

**Comment by jameslaws** [comment]
We're not doing anything new in the 2.9.x branch of the plugin as 3.0 is a complete rewrite. Our best guess is about 4 weeks out and something like this wouldn't be able to be pursued until a little after that release.

**Comment by binarykitchen** [comment]
understood. how about i fork your 3.0 branch and experiment myself. and whenever you are ready in about4f-6 week weeks, we can discuss again?

**Comment by binarykitchen** [comment]
@kstover @jameslaws ping?

**Comment by kjohnson** [comment]
Hey @binarykitchen, would this work as a Ninja Forms extensions?

**Comment by jameslaws** [comment]
I think this would have to be an extension. It's not going to be so widely used as to require it in core.

**Comment by binarykitchen** [comment]
@kjohnson @jameslaws sure, very happy to make an extension for this. just point me where to start (documentation + examples for v3.0) and i ll give it a try

**Comment by binarykitchen** [comment]
hellooo @kjohnson @jameslaws ??

**Comment by binarykitchen** [comment]
ping?

do you think it is possible to add custom post types below a ninja-form, i.e. a video input field (using videomail-client)?

**Comment by kjohnson** [comment]
Hey @binarykitchen,

Sorry I didn't see the ping. Here are the developer docs: developer.ninjaforms.com

And it would be easy enough to add submenus under the main Ninja Forms menu.

**Comment by binarykitchen** [comment]
Hmmm, @kjohnson, the videos under the quick start guides aren't captioned :( I am Deaf here you know ...

**Comment by kjohnson** [comment]
I have transcripts for the videos, which I created for captioning, just haven't gotten to it yet. I'll move that up the list.

**Comment by binarykitchen** [comment]
@kjohnson @kstover @jameslaws do you have any example code of ninja form extensions that run on v3? does not have to be stable and can be a prototype. would help me greatly to write one. thanks!

**Comment by kjohnson** [comment]
@binarykitchen we have a code generator, which gives you an example structure, with an example field, action, and payment gateway: http://developer.ninjaforms.com/kozo/

**Comment by binarykitchen** [comment]
@kjohnson after a second thought I think I prefer to pay a passionate wp-ninja-developer to write that plugin for me! Do you have any recommendations/ideas who it could be? Happy to discuss that further by email.

**Comment by kjohnson** [comment]
Sure, @binarykitchen. kyle@wpninjas.com

**Comment by binarykitchen** [comment]
cool, wil email ya
