### ISSUE TITLE
Dashicon overlays text in default value textarea with Firefox

### ISSUE THREAD

**Issue by tw2113** [wpninjas/ninja-forms#1083]
![screen shot 2016-01-16 at 12 06 28 am](https://cloud.githubusercontent.com/assets/484075/12370833/1a4a624c-bbe5-11e5-82a5-c7b361958567.png)

**Comment by kstover** [comment]
Can you confirm that this is an issue in version 3.0.x?

**Comment by tw2113** [comment]
Will do what I can soon, thanks Kevin.

**Comment by tw2113** [comment]
This is very likely resolved. I can't quite recall how to recreate, and NF3 was a big enough change that it's likely not an issue any more.
