### ISSUE TITLE
Network Activation

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#1090]
When a network admin attempts to network activate Ninja Forms, there is no message explaining that network activation is not supported.

We should probably display an admin notice, until such a feature could be implemented.

**Comment by garand** [comment]
Looks like there's actually already code for this.

https://github.com/wpninjas/ninja-forms/blob/db20516b54c90dc6fc4e2460bc7507d78104bf72/deprecated/includes/activation.php#L208-L217

**Comment by garand** [comment]
It supposedly get's added to the admin notice hook, but I don't see an associated `do_action(...)`.

**Comment by kjohnson** [comment]
Ah, I see that. I'll take a look and make sure to port the intended functionality to Ninja Forms THREE.

**Comment by garand** [comment]
Aha! I think I'm getting somewhere... I got the message to show up.

If you don't have the plugin activated on ANY sites, and try to network activate it, the message does not display.

If you do have it activated on at least one site, and then try to network activate it, the admin notice displays properly.

**Comment by kstover** [comment]
Is this still an issue with 3.0.x?

**Comment by garand** [comment]
I honestly don't even remember what project I was using this on anymore.

**Comment by caseypatrickdriscoll** [comment]
Just discovered this issue today. Network activate will not create necessary database tables, but when deactivated and activated per site then 'nf3_' tables are created.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
