### ISSUE TITLE
Query String Merge Tags do not support Action Settings

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#1095]
The AJAX submission is outside of the context of the Query String variables, therefor the query string merge tags are not getting parsed.

**Comment by kjohnson** [comment]
Not sure if this should be 3.0 or 3.x, but will come back to it.

**Comment by kjohnson** [comment]
If needed, query string data can be passed with the submission AJAX request.

**Comment by kstover** [comment]
@kjohnson Is this still an issue?
