### ISSUE TITLE
Export to Excel Sometimes not adding fields under correct headers

### ISSUE THREAD

**Issue by StephanAtG2** [wpninjas/ninja-forms#1099]
When exporting to excel the plugin sometimes does not add the fields under the correct headers.

Keep in mind that this is on forms that has fields that are only populated under certain conditions, 

Another thing is this is being used in conjunction with the multipage form plugin also..

**Comment by StephanAtG2** [comment]
[form-submissions (2).xlsx](https://github.com/wpninjas/ninja-forms/files/103151/form-submissions.2.xlsx)

**Comment by kstover** [comment]
Can you confirm that this is an issue for version 3.0.x?
