### ISSUE TITLE
Remove "Add form" button and "Append a Ninja form" metabox

### ISSUE THREAD

**Issue by ZwaarContrast** [wpninjas/ninja-forms#1106]
Is there a way to remove the "Add form" button and "Append a Ninja form" metabox from the Wordpress backend?

**Comment by ZwaarContrast** [comment]
Used this to remove the Metabox:
`remove_action('add_meta_boxes','ninja_forms_add_custom_box' );`

Would like a way to remove the add form button above the wysiwyg editor.

**Comment by fcponline** [comment]
@ZwaarContrast this is great but is there a way to remove all the queries to check if the "Add form" button and "Append a Ninja form" on every page? I have one form with 2 fields in the footer and I am getting 63 queries just checking if these items have been used.

thanks

Netivity

**Comment by kstover** [comment]
Closed due to inactivity. If you are still having a problem, feel free to open a new issue.
