### ISSUE TITLE
Allow for the submit button to be a button element.

### ISSUE THREAD

**Issue by ZwaarContrast** [wpninjas/ninja-forms#1107]
The input[type=submit] element is limited in it's styling options, for example it doesn't allow the usage of pseudo-elements. Giving an option to choose a <button> element would be very helpful.

**Comment by gthapar** [comment]
Or allow to change the markup using a filter.

**Comment by kstover** [comment]
Version 3.0 will use Underscore templates for creating the front-end display, so it would be trivial to change the way that submit buttons are displayed. i.e. making them a button, etc.
