### ISSUE TITLE
Input and Text Area Background Color

### ISSUE THREAD

**Issue by wilsonwc** [wpninjas/ninja-forms#1110]
With all the other styling options available I am curious why there isn't an option for the background color of input/textarea elements.  I can do it as custom CSS, but would like to see it made easier for the code-illiterate user to choose.

**Comment by kjohnson** [comment]
We can look at adding that to the Layouts and Styles extension.

**Comment by kjohnson** [comment]
@wilsonwc I copied this issue over to the Layouts and Styles add-on, although it is currently a private repo. https://github.com/wpninjas/ninja-forms-layout-styles/issues/20
