### ISSUE TITLE
Title attributes on icon links

### ISSUE THREAD

**Issue by polevaultweb** [wpninjas/ninja-forms#1115]
Needed to know what things are on hover, eg.

<img width="310" alt="screen shot 2016-02-12 at 21 03 50" src="https://cloud.githubusercontent.com/assets/1770201/13020253/46d7c3ca-d1cc-11e5-8a86-a71001094197.png">

**Comment by jameslaws** [comment]
Done

**Comment by polevaultweb** [comment]
@jameslaws is there a link to a PR or commit for this?
