### ISSUE TITLE
Make form navigation use URL hashing for direct access

### ISSUE THREAD

**Issue by polevaultweb** [wpninjas/ninja-forms#1116]
<img width="492" alt="screen shot 2016-02-12 at 22 35 58" src="https://cloud.githubusercontent.com/assets/1770201/13022393/24bb14a6-d1d9-11e5-80c7-9f9c5678b74f.png">

eg. 
`admin.php?page=ninja-forms&form_id=2#email-actions`

**Comment by kjohnson** [comment]
Routing would be awesome. I think @kstover has already looked into this, but not sure if it was feasible or not, with bundled Backbone in the WP Admin.

**Comment by polevaultweb** [comment]
Maybe even with simple `window.location.hash` checking?

**Comment by kjohnson** [comment]
Working example implementation on branch 3.0-hashes.

**Comment by polevaultweb** [comment]
@kjohnson did this ever make it to `master`?

**Comment by kjohnson** [comment]
It was lost in a merge somewhere. I need to dig it back out.

**Comment by polevaultweb** [comment]
@kjohnson ping :)
