### ISSUE TITLE
Radio list will not submit if given a default value. 

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1128]
Issue:
If a radio list has a default value checked, the php is returning an error on the front end upon submission. 

Reproduction Steps:
- Create new form.
- Add radio list. 
- edit radio list and give it a default value.
- Preview form and try to submit

Screen Shot:
![screen shot 2016-02-25 at 4 11 35 pm](https://cloud.githubusercontent.com/assets/9393977/13413093/fef9c812-df15-11e5-9626-a27d45c62b6b.png)

**Comment by kjohnson** [comment]
I believe that this was resolved. Can you confirm, @klhall1987 .

**Comment by klhall1987** [comment]
Yes, this was resolved. I just tested again in the 3.0 branch and it is working correctly.
