### ISSUE TITLE
Merge tags in email actions are being duplicated on conversion and the email message field references are not being converted to merge tags.

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1133]
Merge tags in email actions are being duplicated on conversion and the email message field references are not being converted into merge tags.

Reproduction Steps: 
- Create a form that includes an email action in 2.9.x 
- In the email action add field references to the "to" field and the email message. 
- export the form form 2.9.x
- import the form into 3.0

![screen shot 2016-03-01 at 12 59 57 pm](https://cloud.githubusercontent.com/assets/9393977/13436613/11fb6662-dfae-11e5-8bf9-e193be51e082.png)

**Comment by kjohnson** [comment]
@klhall1987 Could not replicate.
