### ISSUE TITLE
Example Opt-in Field throwing error if added through the field reservoir 

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1135]
If an example opt-in field is added through the field reservoir the JS error in the screenshot below is being thrown. If the field is drug from the drawer it works properly. 

![screen shot 2016-03-02 at 9 29 28 am](https://cloud.githubusercontent.com/assets/9393977/13463233/534c4e82-e059-11e5-983d-8b390ac76840.png)

**Comment by kjohnson** [comment]
@klhall1987 updated the base class. Re-test.
