### ISSUE TITLE
ReCaptcha is failing to display on the front end.

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1136]
ReCaptcha field is failing to display on the front end. I'm seeing "Uncaught ReferenceError: desc_pos is not defined" in the console.

**Comment by kstover** [comment]
It looks like this is being thrown by the description template on the front-end. The description is added to the fields-label and fields-wrap template. Either a check there to ensure it is set or a default value should take care of the issue.

**Comment by klhall1987** [comment]
Fix Confirmed
