### ISSUE TITLE
Label position selector causing form to fail publishing

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1137]
Reproduction Steps:
- Create new form
- Add a field with label position setting.
- Change label position.
- publish the form. 
- Change label position a second time.
- publish the form
- I received the error in the following screen shot. 

![screen shot 2016-03-02 at 9 29 28 am](https://cloud.githubusercontent.com/assets/9393977/13464440/43f8ffba-e05f-11e5-8a4f-2d96e49174ff.png)

**Comment by kstover** [comment]
It looks like the field type isn't being set properly. That isn't the actual error, so I don't know what the error says, only what line it's on.

**Comment by klhall1987** [comment]
Sorry I think I uploaded the wrong screenshot there. I'll be more careful about that from here on out. Here is the correct screen shot. 

![screen shot 2016-03-02 at 10 26 55 am](https://cloud.githubusercontent.com/assets/9393977/13464949/63f8480a-e061-11e5-9107-9a085a0fca47.png)

**Comment by kstover** [comment]
Ah. Ok. That's definitely a PHP error.

**Comment by kjohnson** [comment]
@klhall1987 pushed a fix to update the table name. Re-test?

**Comment by klhall1987** [comment]
Fix confirmed
