### ISSUE TITLE
Checkbox element not aligned correctly

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1140]
If the checkbox label position is changed from form default or description text is added to the field the checkbox element is not aligning properly. 

Test without Description
![screen shot 2016-03-02 at 11 18 17 am](https://cloud.githubusercontent.com/assets/9393977/13466639/de03b4ca-e068-11e5-8aa7-8b21e226c621.png)

Test with Description 
![screen shot 2016-03-02 at 11 22 34 am](https://cloud.githubusercontent.com/assets/9393977/13466729/2f115822-e069-11e5-9292-36995ba017c7.png)

**Comment by jameslaws** [comment]
I believe this is corrected from the massive front end styling changes we made.
