### ISSUE TITLE
Textarea - Right of element Label position is displaying incorrectly

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1141]
The Textarea field right of element label position is displaying the text under the element. 

![screen shot 2016-03-02 at 12 26 54 pm](https://cloud.githubusercontent.com/assets/9393977/13468753/3e932ace-e072-11e5-8dcd-24ebfaa671c1.png)

**Comment by kstover** [comment]
Is this still an issue?
