### ISSUE TITLE
Cannot submit form in PHP 5.2

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1142]
Cannot submit a form in PHP 5.2, the PHP function json_last_error is not supported until PHP 5.3. The function is used on ninja-forms/includes/AJAX/Controllers/Submission.php line 27. 

here is the full error I receive when trying to submit a form in PHP 5.2: 
Fatal error: Call to undefined function json_last_error() in /Applications/MAMP/htdocs/WordPress/wp-content/plugins/ninja-forms/includes/AJAX/Controllers/Submission.php on line 27

**Comment by kjohnson** [comment]
Added some function checks.

**Comment by klhall1987** [comment]
I'm now getting "Uncaught TypeError: Cannot read property 'get' of undefined" on submit.

**Comment by kjohnson** [comment]
@klhall1987 pull down branch `issue#1142` and test the submission on php5.2.

**Comment by kjohnson** [comment]
Other Alternative:
- https://developer.wordpress.org/reference/functions/json_last_error_msg/

**Comment by klhall1987** [comment]
Fix confirmed.
