### ISSUE TITLE
Textarea - Left of label position not displaying correctly with description text

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1144]
The issue: 
Textarea fields that contain descriptions and a label position of left of element are not displaying correctly on the front end.

Reproduction steps:
- Add textarea
- change label position to left of label
- add description text 
- change display position to anything but none. 
- preview form

Screenshot:
![screen shot 2016-03-02 at 2 14 33 pm](https://cloud.githubusercontent.com/assets/9393977/13472290/2e435fbc-e082-11e5-89dc-9f281605e3c2.png)

**Comment by kstover** [comment]
@klhall1987 Is this still an issue?
