### ISSUE TITLE
Textarea - input limit with Left of label position not displaying correctly

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1145]
The issue: 
Textarea fields that contain descriptions and a label position of left of element are not displaying correctly on the front end.

Reproduction steps:
- Add textarea
- change label position to left of label
- add input text limit
- preview form

Screenshot:
![screen shot 2016-03-02 at 2 29 04 pm](https://cloud.githubusercontent.com/assets/9393977/13472686/0322cd3e-e084-11e5-8a07-b565cf4c0532.png)

**Comment by kstover** [comment]
@klhall1987 Is this still an issue?
