### ISSUE TITLE
Word input limit functioning as if it were character input limit

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1146]
Issue:
Word Input limit only allows you to input the amount of characters you've input, instead of the amount of words. 

Reproduction Steps:
- Create a field with an input limit
- Change limit type from character(s) to Word(s) 

Screenshot: 
![screen shot 2016-03-02 at 2 44 19 pm](https://cloud.githubusercontent.com/assets/9393977/13473280/ae640c92-e086-11e5-974b-559c18d20bac.png)

**Comment by kstover** [comment]
Ah. I know what's going on there.

**Comment by kstover** [comment]
I'll take a look when I get time.

**Comment by kjohnson** [comment]
The maxlength attribute only works for characters.

I added basic support for word limiting (on keyup).

**Comment by klhall1987** [comment]
fix confirmed
