### ISSUE TITLE
Recaptcha will not process

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1149]
Issue:
Recaptcha is failing to process on form submission.  

Screenshot: 
![screen shot 2016-03-02 at 5 17 51 pm](https://cloud.githubusercontent.com/assets/9393977/13477546/f13511ec-e09a-11e5-9403-89352c7802c6.png)

**Comment by kjohnson** [comment]
Looks like it is either a local host issue, or the host is not listed with the registration.

**Comment by klhall1987** [comment]
@kjohnson Recaptcha is still failing validation in php 5.2 and 5.3. Anything 5.4 or above seems to be working correctly.
