### ISSUE TITLE
Custom input masks are throwing an error and not displaying on the front end

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1159]
Any field that has a custom input mask will not display on the front end, it also throws this error "Uncaught TypeError: mask.split is not a function". It can be seen in the screenshot below. 

Screenshot:
![screen shot 2016-03-02 at 9 15 09 pm](https://cloud.githubusercontent.com/assets/9393977/13482609/394ba86c-e0bc-11e5-8016-4d0a87c762a4.png)

**Comment by kjohnson** [comment]
Confirmed. Error being thrown by the libraryitself.

**Comment by kstover** [comment]
@klhall1987 Can you specify what the custom mask was? I just added one: 999-999-99 and it worked. We need to make sure that we add help text that says basically the same thing as 2.9.x and describes the characters that can be used in masking.

**Comment by klhall1987** [comment]
@kstover I tried 999 and 999-999-99 I'm still seeing the error. Let me nuke my DB and pull a fresh copy of NF 3.0, then I'll retest and let you know if I still see it.

**Comment by klhall1987** [comment]
Okay, now I'm only seeing the error if my custom mask doesn't have any dashes.

**Comment by klhall1987** [comment]
I just tested 9, 99, 999, and 9999 none of those have worked; however, 9- does work.

**Comment by kstover** [comment]
Fixed in 3d1d05b088a0484a1d30ef0686adfe91b555ab35.
