### ISSUE TITLE
"Please enter a valid email address!" on valid field

### ISSUE THREAD

**Issue by sumobi** [wpninjas/ninja-forms#1160]
v3.0 beta

I noticed if you try and use an email address such as `something+else@email.com` you cannot submit the form and it shows `Please enter a valid email address!`. I use +'s all the time in testing forms. 

<img width="866" alt="screen shot 2016-03-03 at 5 58 30 pm" src="https://cloud.githubusercontent.com/assets/52581/13485155/99f69bec-e169-11e5-9627-f1831352ef2f.png">

**Comment by martinkrcho** [comment]
I also noticed that the validation logic doesn't trim whitespaces around the email address. Could this be changed? Could you introduce a filter to allow me to change this from outside your plugin? A lot of people type their email address in with a trailing space without even realizing. Thanks

**Comment by ZeroBeeOne** [comment]
Just a note that I am also seeing this validation failure (marking emails with plus sign [+] invalid) in 3.0 on WP 4.5.2. It looks like this originates in the definition of controllers/changeEmail - the following line: `var emailReg = /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i;`
dictates that plus symbols are not allowed in the local part of emails - only word characters (alphanumeric + underscore [_]) and the hyphen (-), and dots (.) where they are not consecutive, or the first or last characters of the local portion.

My naive first-glance suggestion to fix this would be to amend this to:
`var emailReg = /^([\w-+]+(?:\.[\w-+]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i;`
