### ISSUE TITLE
3.0 - Undo manager, sporadic issues 

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1176]
1. Undo Manager - Undo All button takes two clicks to work

2. Next change after undo all button used does not get added to the undo list

I don't have repro steps for this but I've seen both happen a few times.

**Comment by wpnzach** [comment]
I usually see these two in this order.  Not sure what triggers the undo manager doing this exactly but it just happened again and is easy to reproduce after some time tinkering, I'm just not sure what exact action of mine is breaking this.  I DO have this error in my console: 

4settingsTitle.js:51Uncaught TypeError: Cannot read property 'show' of undefined

**Comment by wpnzach** [comment]
REPRO STEPS - 

Open default contact form

Change label in first field.  Go to undo manager, undo all changes.  It will take two clicks. 

Change name of label again, undo manager will not detect change

**Comment by wpnzach** [comment]
I was able to reproduce this in a form I created instead of the default contact form.

**Comment by kstover** [comment]
Working on this now.

**Comment by kstover** [comment]
Should be fixed in: a3f67f84ad8961163ead91f321ba7b2d68b2ac03

@wpnzach Can you test please?

**Comment by wpnzach** [comment]
This looks to be resolved with that change
