### ISSUE TITLE
Summer Note is not saving.

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1178]
Any changes that are being made inside summer note are not being saved.

**Comment by kstover** [comment]
@klhall1987 Please be more specific. Followed these steps and summernote saved just fine:

1. Edit Contact Form
2. Edit Name field.
3. Modify Help text and Description text.
4. Preview form; Help text and Description text show up.
5. Publish and Reload; text still present.

**Comment by kjohnson** [comment]
@kstover I think Kenny was specifically editing with the code view.

**Comment by klhall1987** [comment]
@kstover Yes, @kjohnson is correct. Sorry I thought summer note was the name of the code editor. I didn't know it was the entire WYSIWYG editor. 

Reproduction steps:
1. Edit Contact Form
2. Edit Name field.
3. Goto help text
4. Select the code view.
5. Add text to the code view 
6. Press done on the name field
7. Go back to name field and edits should be gone.

**Comment by kstover** [comment]
Ok. I will take a look.

**Comment by kstover** [comment]
Fixed in 36b16388ce5347fc670a0aff955c4db699ff30bd
