### ISSUE TITLE
Forms submissions are not converting properly 

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1186]
Form submissions are not converting correctly to Three. The correct number of submissions are converted, but none of the submission data is converting. Each submission shows up empty. If rolled back to 2.9.x the submission data is still present, but in Three the submission data is empty.

Reproduction Steps:
1. Create a form in 2.9.x
2. Fill out form and submit 
3. Upgrade to Three using the upgrade page
4. View converted forms submissions 

Screenshots:
Form Submission data in 2.9.x:
![screen shot 2016-03-05 at 2 11 55 pm](https://cloud.githubusercontent.com/assets/9393977/13549837/896ad698-e2dc-11e5-8900-a1a52d631952.png)

Form Submission Data in 3.0:
![screen shot 2016-03-05 at 2 12 53 pm](https://cloud.githubusercontent.com/assets/9393977/13549838/8d27045a-e2dc-11e5-9aa2-5e6fa56036e1.png)

**Comment by kstover** [comment]
Are the field ids being preserved?

**Comment by kjohnson** [comment]
@klhall1987 and I did a screen share, wiped the database after testing and all is well.
