### ISSUE TITLE
Gulp Install

### ISSUE THREAD

**Issue by polevaultweb** [wpninjas/ninja-forms#1206]
Should there not be a `package.json` file in the root with the gulp depenencies? Instead of manually running something like `npm install gulp gulp-rename gulp-uglify`

**Comment by jameslaws** [comment]
Yeah, that sounds so much easier than what m they had me do. ;-)

**Comment by polevaultweb** [comment]
Fixed by https://github.com/wpninjas/ninja-forms/commit/31a1dc78099d99e88ef81b7ea55402038661c00d
