### ISSUE TITLE
Calc variables can be re-ordered to use variables that are created later in the variable list.

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1214]
Calculation variables can be re-ordered to use variables that are created later in the variable list. 

Reproduction Steps: 
For example lets say we have a calc variable called calc-1 that adds 10 to field-1. We could then make a new variable called calc-2 that adds 10 to calc-1 and move it above calc-1 in the variable list. I've added a screen to help with reference below. 

Screenshot: 
![screen shot 2016-03-08 at 1 37 10 pm](https://cloud.githubusercontent.com/assets/9393977/13612126/dd127ea0-e533-11e5-8d2c-0d9808c2a706.png)

**Comment by kstover** [comment]
I get a console error of: `n.get is not a function` when I try to re-order this way. This is definitely a bug that needs to be addressed.
