### ISSUE TITLE
Switching fields without closing the draw may lose data

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1223]
When I was switching between 5 fields changing input limit numbers only the first and last field would save when I closed the drawer. 

Reproduction steps:
1. create form with 5 fields(I used phone, textbox, first name, address, address 2 and a submit button) 
2. Go through fields and change "LIMIT INPUT TO THIS NUMBER" without closing the drawer. 
3. Check to see if all the input limits were saved.

**Comment by kstover** [comment]
I have this tagged in another issue, I think. It's at least on my notepad. I'm working on it.

**Comment by kstover** [comment]
This was fixed in 3.0.0.
