### ISSUE TITLE
Clear successfully complete forms and hide successfully completed forms not working

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1226]
Neither the "Clear Successfully Completed Form" or the "Hide Successfully Completed Form" is working. If these settings are used, nothing changes on the front end upon form submission. I did not see any errors being thrown in the console. 

Reproduction steps:
1. Create a form
2. Add a textbox field and submit button.
3. Go to Advanced tab.
4. Active either setting.
5. Preview form. 
6. Fill in text box and submit

**Comment by kstover** [comment]
This is something that I specifically worked on last week. Make sure that you're on the 3.0 branch and up to date.

**Comment by kstover** [comment]
You may have to blast your cache. It's all in JS.

**Comment by kstover** [comment]
I'm still not home.

**Comment by kjohnson** [comment]
I saw it also.  I'll take a look.

**Comment by kstover** [comment]
It looks like the variables referenced in this file might be wrong: assets/js/front-end/controllers/coreSubmitResponse.js

The parts of the if might be the wrong vars. Check those against what is localised.

**Comment by kstover** [comment]
Fixed in 90cb31665738bbf5ec571c887082849d474ffe8d. The variable names were changed at some point and broke things.
