### ISSUE TITLE
Limit restrictions not honored unless page reloaded

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#1228]
If you load a form that has some number restriction and the user submits the form and the restriction is then met, if the form isn't hidden, the form can be resubmitted multiple times past the limit. The only way the restriction message is displayed is if the page is reloaded. We need to consider hiding the form and displaying the restriction message anytime the form is submitted and the limit has already been reached.

**Comment by kstover** [comment]
@jameslaws Is this still an issue in 3.0.x?
