### ISSUE TITLE
Remove developer files to reduce plugin size

### ISSUE THREAD

**Issue by fjarrett** [wpninjas/ninja-forms#1246]
Now that 2.9.x is being bundled alongside 3.0, it would be nice to do a little housekeeping to keep the final plugin package size down to a minimum.

There are some files making it to the SVN trunk that are really just for developers/contributors. It stands to reason that these folks will probably come visit this GitHub repo anyway where they can get all the things.

Adding up the sizes of all these dev files amounts to ~4.2 MB of savings uncompressed, and ~1 MB compressed.

**PO/POT files** - 1 MB savings
```
deprecated/lang/ninja-forms-*.po
deprecated/lang/ninja-forms.pot
```

**SCSS directory** - 2.3 MB savings
```
assets/scss/*
```

**Source map files** - 893 KB savings
```
assets/css/*.css.map
assets/js/min/*.js.map
```

**Codekit config file** - 86 KB savings
```
assets/config.codekit
```

**Comment by kstover** [comment]
This is something that we've been discussing both internally and with the powers that be at the .org repo. We've gotten the all-clear to do something like this, so it will be coming in the next version (2.9.37), and of course to the 3.0 codebase.

**Comment by fjarrett** [comment]
I see the SCSS directory was removed in the `2.9.37` release, nice! However, the PO/POT and source maps still remain, which would equal another 2MB in savings.

**Comment by kjohnson** [comment]
@fjarrett Yes, @kstover is looking at removing the PO/POT files. However, I we may want to keep the maps for troubleshooting purposes, being that the JS is minified.
