### ISSUE TITLE
Fix hard-coded English strings in HTML templates

### ISSUE THREAD

**Issue by fjarrett** [wpninjas/ninja-forms#1247]
There are a few templates using the `.html` extension that need to use the `.html.php` extension so that the English strings that are currently hard-coded inside can be wrapped in a [WordPress i18n function](https://codex.wordpress.org/I18n_for_WordPress_Developers#Strings_for_Translation).

I didn't check all the templates, but here are some I found right off the bat:

[field-input-limit.html](https://github.com/wpninjas/ninja-forms/blob/370400ec6554634c2ace232d1691c667424e5846/includes/Templates/field-input-limit.html#L2)
[fields-file.html](https://github.com/wpninjas/ninja-forms/blob/370400ec6554634c2ace232d1691c667424e5846/includes/Templates/fields-file.html#L17)
[fields-submit.html](https://github.com/wpninjas/ninja-forms/blob/370400ec6554634c2ace232d1691c667424e5846/includes/Templates/fields-submit.html#L8)
[fields-textarea.html](https://github.com/wpninjas/ninja-forms/blob/370400ec6554634c2ace232d1691c667424e5846/includes/Templates/fields-textarea.html#L28)
[form-layout.html](https://github.com/wpninjas/ninja-forms/blob/370400ec6554634c2ace232d1691c667424e5846/includes/Templates/form-layout.html#L9)

**Comment by kstover** [comment]
There are tons of non-translated strings at the moment. We're still in RC and have a pass for translation string planned. :)

**Comment by kstover** [comment]
We are still debating internally whether or not to translate those in the template or in localisation variables that are output with JS.
