### ISSUE TITLE
Question about lack of indexes database schema

### ISSUE THREAD

**Issue by fjarrett** [wpninjas/ninja-forms#1252]
Hey guys, I just had a question about the lack of indexes found in the v3 tables.

It seems to me that the meta tables should have a similar schema to `postmeta` and the main entry tables should have a similar schema to `posts`.

The performance of any `WHERE` clause on these tables will be negatively impacted by not indexing the `key` column - WordPress core demonstrates by indexing the `meta_key` and `post_name` columns in `postmeta` and `posts`, respectively.

Just wondering if there is a deeper explanation as to why this schema was decided on. Thanks!

**Comment by fjarrett** [comment]
As an example for [`nf3_form_meta` indexes](https://github.com/wpninjas/ninja-forms/blob/370400ec6554634c2ace232d1691c667424e5846/includes/Database/Migrations/FormMeta.php#L20), I would consider doing:

```sql
PRIMARY KEY (`id`)
KEY (`parent_id`)
KEY (`key`)
```

**Comment by kstover** [comment]
@kjohnson Where are we on this?

**Comment by kstover** [comment]
@kjohnson ?

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
