### ISSUE TITLE
Use generic shortcode name when possible and/or allow custom ones

### ISSUE THREAD

**Issue by fjarrett** [wpninjas/ninja-forms#1254]
You've just created a new site for your extremely novice client. They're thrilled. You're glad it's over.

They login and see the **Forms** section on the left in their Admin bar. Imagine their surprise when they discover a `[ninja_forms id=1]` shortcode in their content!

What the heck is a Ninja?! I guess I better call Frankie... :smiley_cat: 

This story made me think of this:

``` php
if ( ! shortcode_exists( 'form' ) ) {

    add_shortcode( 'form', array( $this, 'display_form_front_end' ) );

}
```

Now my client sees `[form id=1]`, and while they don't know what the heck a shortcode is, they can see there is a form on their site in the same place that mysterious bracket-business is.
### Custom shortcodes

In addition to [the defaults](https://github.com/wpninjas/ninja-forms/blob/370400ec6554634c2ace232d1691c667424e5846/includes/Display/Shortcodes.php#L7-L8) and generic one, it would be cool to allow custom shortcodes to be registered:

``` php
// Defaults
add_shortcode( 'ninja_form',  array( $this, 'display_form_front_end' ) );
add_shortcode( 'ninja_forms',  array( $this, 'display_form_front_end' ) );

// Generic
if ( ! shortcode_exists( 'form' ) ) {

    add_shortcode( 'form', array( $this, 'display_form_front_end' ) );

}

// Custom
$custom = sanitize_key( apply_filters( 'ninja_forms_custom_shortcode', false ) );

if ( $custom && ! shortcode_exists( $custom ) ) {

    add_shortcode( $custom, array( $this, 'display_form_front_end' ) );

}
```

Now developers can register whatever makes sense for their client:

``` php
add_filter( 'ninja_forms_custom_shortcode', function() { return 'acme_client_form'; } );
```

**Comment by jameslaws** [comment]
First, I just want to say thank you. It's awesome having someone like you go through the code and offer suggestions and insights. Honored to have you doing that.

For me this issue is about brand. Having the shortcode without name in it keeps our brand in the minds eye of the user, which seems helpful from a business perspective. On the flip side of that, we have a collaborating developer who has released a white label add-on that replaces all references to of Ninja Forms with some other string. In this was someone could theoretically offer the firm builder like it's their own solution for their client. 

I just want to capture my thoughts in the thread. :-)

**Comment by kstover** [comment]
I think I can see how having a generic shortcode could be helpful for maintainers or builders, but I think the second solution is best: register our shortcode using a filter.

That seems to satisfy both our branding issues and he needs of devs/clients.

**Comment by fjarrett** [comment]
Thanks, guys!

I can see the branding angle, but then again, the user's content area may not be the place for that. This idea kind of spawned from the fact that it says "Forms" in the admin menu - which is typically where plugins would be branding themselves.

To clarify a bit beyond my silly user story above...

### Generic shortcode

For our purposes, we'd like to see the generic `form` shortcode made available in core NF. If it's not already reserved by something else, no reason not to take it. Woo does this with their shortcodes, [such as `[product id="1"]`](https://docs.woothemes.com/document/woocommerce-shortcodes/#section-7).

If NF is installed then it should assert itself as the defacto solution for forms inside the WP site. No prefixing required. It's highly unlikely someone would be running multiple forms plugins, but if so, there's no chance of conflict with the conditional check, and the default `ninja_form` shortcode can be used.

### Custom shortcode

Just to be clear, I don't think filtering the default shortcodes is particularly a good idea. The `ninja_form` and `ninja_forms` shortcodes should always be registered and reserved IMO.

This custom shortcode idea is just a ways to give developers the option of creating an _additional_ shortcode name. Maybe a better word is alias.

This is actually already possible with a little cleverness:

```php
add_shortcode( 'frankie_form', function( array $atts = [] ) {

	$shortcode[] = 'ninja_forms';

	foreach ( $atts as $key => $value ) {

		$shortcode[] = "{$key}={$value}";

	}

	return do_shortcode( '[' . implode( ' ', $shortcode ) . ']' );

} );
```

So hey, why not just make it easy for developers and make it a filter :smiley:

**Comment by jameslaws** [comment]
That doesn't bother me too much.

**Comment by kstover** [comment]
I don't have a problem with checking to see if form exists and using it by default. I hadn't thought of the "forms" menu item angle, but that makes sense. In the interests of compatibility, obviously ninja_form should still work.

Giving developers a method for customising the shortcode is fine with me.

**Comment by kstover** [comment]
@kjohnson Where are we on this?

**Comment by kstover** [comment]
@kjohnson ?

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
