### ISSUE TITLE
jBox positioning for Help Text

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#1255]
The jBox is absolutely positioned to lineup with the help-text icon, but then scrolling breaks the alignment. 

<img width="482" alt="screenshot 2016-03-17 23 34 30" src="https://cloud.githubusercontent.com/assets/10858303/13867784/fd6ec976-ec98-11e5-9378-cf3be9fce81f.png">

Can the jBox instead be relatively positioned inside of a wrapper?

**Comment by kstover** [comment]
I'll have to dig into jBox, but I imagine that there is a setting to keep it aligned to the trigger.
