### ISSUE TITLE
Automatically show the submissions when only one form

### ISSUE THREAD

**Issue by polevaultweb** [wpninjas/ninja-forms#1260]
When viewing the submissions page, it would be great to not have to select the one form to filter it to show the submissions.

**Comment by kstover** [comment]
I think this is a good idea. We could show the most popular form.

**Comment by kjohnson** [comment]
@kstover what about a stats over view? Not sure what it would look like, but it would probably be better than guessing.

**Comment by kstover** [comment]
I'm moving this over to our internal tracker. We'll create a dashboard kind of view, I think.
