### ISSUE TITLE
Forms in widget area are being hidden on form submission

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1262]
Forms in the widget area are being set to display: "none" when a form in the main content area is submitted. 

Reproduction steps: 
- Create two forms
- Add one to post or page.
- add the other to sidebar or footer in the widget area
- Fill out and submit the form on the post or page and the form in the widget area will disappear.

**Comment by kjohnson** [comment]
The submit button now only submits its own form.
