### ISSUE TITLE
Receiving Database error when loading a form from the all forms page

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1263]
In 3.0 I am seeing a database error when I load a form in the builder from the all forms page. The error just flashes for a brief second, and form builder loads fine. 

Reproduction Steps:
- Create a form in 3.0
- Go back to the all forms page.
- Reload the form and the error should flash across the screen. 

Screen Shot: 
![screen shot 2016-03-22 at 11 24 03 am](https://cloud.githubusercontent.com/assets/9393977/13957060/6e20942a-f021-11e5-9840-276607941112.png)

**Comment by kjohnson** [comment]
Looks like it might be missing an `AND or `OR` statement.
