### ISSUE TITLE
Delete All Ninja Forms Settings option not working

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1265]
The settings to remove all ninja forms data don't seem to work in 3.0.  If I deactivate and delete with that checked, when I reinstall I'm on 3.0 still by default instead of defaulting to 2.9

**Comment by kstover** [comment]
Is this still an issue in 3.0.x? @klhall1987

**Comment by jmcelhaney** [comment]
This is still an issue in the 3.0.6 version of Ninja Forms.

### Environment ###
Home URL:                http://localhost/3
Site URL:                http://localhost/3
Ninja Forms Version:     3.0.6
WP Version:              4.6.1
WP Multisite Enabled:    No
Web Server Info:         Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/7.0.8 mod_ssl/2.2.29 OpenSSL/0.9.8zh DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0
PHP Version:             7.0.8
MySQL Version:           5.5.42
PHP Locale:              negative_sign:
WP Memory Limit:         40
WP Debug Mode:           No
WP Language:             Default
WP Max Upload Size:      32 MB
PHP Post Max Size:       32
Max Input Nesting Level: 64
PHP Time Limit:          30
PHP Max Input Vars:      1000
SUHOSIN Installed:       No
Server IP Address:       ::1
Host Name:               localhost
SMTP:                    localhost
smtp_port:               25
Default Timezone:        

### Plugins ###
Installed Plugins:       Ninja Forms by The WP Ninjas version 3.0.6

**Comment by kstover** [comment]
Closing in favour of the ticket linked above.
