### ISSUE TITLE
Inconsistent Field Ordering - Textbox - Default Value/Placeholder

### ISSUE THREAD

**Issue by SWBennett06** [wpninjas/ninja-forms#1267]
In Ninja Forms 3, the majority of fields which have the 'Default Value' and 'Placeholder' options when edited display them in that order. Textboxes appear to be the inexplicable exception to this rule. Should be a quick fix.

**Comment by jameslaws** [comment]
I'm not sure I follow what you mean. Can you help clarify this a little further?

**Comment by SWBennett06** [comment]
For most fields, the options under 'Advanced' are ordered 'Default Value', then 'Placeholder':
![image](https://cloud.githubusercontent.com/assets/8584584/13994204/b14bee04-f0f1-11e5-848b-27e205d0b885.png)

For textbox forms, it's the opposite:
![image](https://cloud.githubusercontent.com/assets/8584584/13994173/96722dbe-f0f1-11e5-876e-34874bc6fbb8.png)

**Comment by jameslaws** [comment]
Ah, I see that now. Thanks. We'll get that taken care of.

**Comment by kstover** [comment]
Is this still an issue in 3.0.x?
