### ISSUE TITLE
NF 3.0 - Date field causes form display to fail

### ISSUE THREAD

**Issue by bucketpress** [wpninjas/ninja-forms#1270]
Adding a date field causes a form to fail in displaying on the front end.
My form contains a text, email, textarea and date field. Removing the date field 'solves' the issue.

I have tried to first display the form inserting a shortcode [ninja_form id=1] in the WP editor.
I have also tried to display the form using Ninja_Forms()->display(1) in my template.

Both fails when there is a date field, and both works when the date field is removed.

**Comment by kjohnson** [comment]
@bucketpress are you still seeing this issue? I am not able to replicate it locally.
![screenshot 2016-04-13 13 46 51](https://cloud.githubusercontent.com/assets/10858303/14503461/3336c424-017e-11e6-9a72-d2fd4a0df5cb.png)

**Comment by bucketpress** [comment]
@kjohnson Alright, I've currently updated to the latest NF on WP 4.5. The current situation on my side is that all form fields that are placed before the date field is rendered, but all fields after (including the date field itself) are not rendered.

Inspecting the html source, I see that for each field that have not been rendered, <div> have been generated, but div.nf-field is empty.

And console logs a js error: 'TypeError: Modernizr.inputtypes is undefined' while trying to run pikaday-responsive.min.js 

Seems that running a custom build modernizr.js that doesn't detect 'Form inputtypes' has caused the error. I've since included an updated modernizr.js that includes inputtypes detection, and everything is rendered properly now.

**Comment by kjohnson** [comment]
Glad to hear that it is working now.

Solution:
> ...running a custom build modernizr.js on my website that doesn't detect 'Form inputtypes' overrides the modernizr used by Ninja Forms, and caused the error...
