### ISSUE TITLE
NF 3.0 - Form fails to display on a page loaded via Ajax

### ISSUE THREAD

**Issue by bucketpress** [wpninjas/ninja-forms#1271]
I'm using Ninja_Forms()->display( $form_id ) to display a form on a WP template. When the page is loaded via ajax, the form fails to render. The NF form wrapper structure is inserted in the dom, but no fields are rendered, and the user sees nothing (where the form should be).

**Comment by kstover** [comment]
Have you tested doing something similar with 3.0.x?

**Comment by AnagramEngineering** [comment]
Why was this closed. I'm actually facing a similar problem. 

I'm using nf 3.0.30.
