### ISSUE TITLE
No filter for the submission value when editing the sub

### ISSUE THREAD

**Issue by polevaultweb** [wpninjas/ninja-forms#1279]
There doesn't seem to be a filter for getting to the submission field value when editing a form submission:

![screen shot 2016-04-05 at 14 32 44](https://cloud.githubusercontent.com/assets/1770201/14283451/632aa090-fb3b-11e5-853d-860a37365d48.png)

**Comment by kjohnson** [comment]
In the "File Upload" field registration, you can override the `admin_form_element()` method to return different HTML.

Checkbox Example:
```php
public function admin_form_element( $id, $value ){
    $checked = ( $value ) ? "checked" : "";
    return "<input type='checkbox' name='fields[$id]' id='' $checked>";
}
```
https://github.com/wpninjas/ninja-forms/blob/master/includes/Fields/Checkbox.php#L37
