### ISSUE TITLE
How To Translate This Plugin? 

### ISSUE THREAD

**Issue by Shmasya** [wpninjas/ninja-forms#1283]
How To Translate This Plugin?

**Comment by Shmasya** [comment]
I created from .pot file new two files ru_RU.po and ru_RU.mo. But not working.

**Comment by kjohnson** [comment]
@Shmasya Translations are now managed on [WordPress.org](https://translate.wordpress.org/projects/wp-plugins/ninja-forms).

https://translate.wordpress.org/projects/wp-plugins/ninja-forms
