### ISSUE TITLE
Field icons hiding start of field label

### ISSUE THREAD

**Issue by polevaultweb** [wpninjas/ninja-forms#1288]
<img width="541" alt="screen shot 2016-04-09 at 07 44 43" src="https://cloud.githubusercontent.com/assets/1770201/14402240/13b35cac-fe27-11e5-8314-cf60dd5af891.png">

**Comment by jameslaws** [comment]
These should be in two columns at that screen size. Make sure yiuve pulled everything and your caches are all cleared. That view should never be possible.

**Comment by polevaultweb** [comment]
Hadn't rebased fork - apologies
