### ISSUE TITLE
Allow scrolling of page inside the builder sidebar

### ISSUE THREAD

**Issue by polevaultweb** [wpninjas/ninja-forms#1290]
Can only currently scroll down the page if cursor is in the white left hand part of the builder, but if I am trying to see fields below the fold on the right hand sidebar I can't scroll down if the cursor is (naturally) inside the sidebar:

![ninja-scroll](https://cloud.githubusercontent.com/assets/1770201/14402294/ec644236-fe28-11e5-91a9-586e9d2f1c9d.gif)

**Comment by jameslaws** [comment]
Did this just break recently? It was working for me. It seems like something that happened in one of the last 4 commits.

**Comment by kjohnson** [comment]
I'm seeing something similar when the console is open and docked at the bottom of the screen, but not otherwise.

@polevaultweb is the console open at the bottom? Is that what I'm seeing in the screengrab?

**Comment by jameslaws** [comment]
I see it with the console open or if the side admin bar is not collapsed. This was not the case for me until I pulled your last 4 commits.

**Comment by polevaultweb** [comment]
Ah let me pull the latest maybe that's it. No console open just on 13inch MBP

**Comment by polevaultweb** [comment]
Fetched and pulled and it has improved but not 100% working. It seems like the max height the sidebar can scroll to when inside is the window height. So if you scroll all the way down to the bottom of the main bar you can then scroll all the way down in the sidebar:

![ninja-scroll](https://cloud.githubusercontent.com/assets/1770201/14410898/1a176e42-ff32-11e5-8c5c-aa43f7953b89.gif)

This is on a MBP 13inch, no console open
