### ISSUE TITLE
Using CheckboxList in Form Builder

### ISSUE THREAD

**Issue by polevaultweb** [wpninjas/ninja-forms#1293]
Trying to add a field of type `listcheckbox` to an action in the form builder and realised the controller JS for it is only loaded for the front end. 

Shouldn't all field types be available to be used when building a form? Unless I've missed something? :smile: 

Ping @kjohnson @kstover

**Comment by kjohnson** [comment]
We've been opting for a `fieldset` with setting `toggles`, instead of a `listcheckbox`.

Part of the reason is to avoid storing multiple values (multiple selected options) in a single setting that then needs to be parsed. With a series of toggles, each value can be checked individually.

**Comment by polevaultweb** [comment]
Great, thanks
