### ISSUE TITLE
v2.9.41: Issue with 403 on Deprecated CSS/JS 

### ISSUE THREAD

**Issue by brandbrilliance** [wpninjas/ninja-forms#1295]
I get CSS/JS loading errors on version v2.9.41. The system can't find the default nina-forms css/js files.

```
[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (ninja-forms-display.css, line 0)

http://www .website .com/wordpress/wp-content/plugins/ninja-forms/deprecated/css/ninja-forms-display.css?nf_ver=2.9.41&ver=4.4.2
```

**Comment by jameslaws** [comment]
If this is a live server you may need to check with your host to see if something went weird with the update. I can't reproduce this on any local or live servers.

**Comment by someone1** [comment]
I had a similar issue, turned out the Wordpress All-In-One Security plugin added a .htaccess rule for certain words that ninja forms uses in its filenames (e.g. ninja-forms-display.css matches rule `RedirectMatch 403 display\.`)
