### ISSUE TITLE
Submissions table missing data

### ISSUE THREAD

**Issue by polevaultweb** [wpninjas/ninja-forms#1297]
When viewing the subs in the table I see no data for each column, but when i edit a specific sub i see it -

![screen shot 2016-04-13 at 14 42 17](https://cloud.githubusercontent.com/assets/1770201/14495222/79d67ff2-0186-11e6-8c1b-26370956e424.png)

![screen shot 2016-04-13 at 14 45 06](https://cloud.githubusercontent.com/assets/1770201/14495228/7f8894f8-0186-11e6-8723-00b6b234bbee.png)

**Comment by kjohnson** [comment]
Not seeing that locally. Can you post an export of your form, @polevaultweb ?

**Comment by kjohnson** [comment]
@polevaultweb I wasn't able to replicate this. Do you have other plugins installed that you could temporarily de-activate?

**Comment by polevaultweb** [comment]
Conflict with Yoast SEO. Running WP 4.5 - to be investigated
