### ISSUE TITLE
Allow multiple recaptcha fields on the same page

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1298]
A user has requested the ability to add multiple recaptcha fields on a page. Currently if a page has multiple recaptcha fields on a page, only one recaptcha field will show and a console error is thrown that states, "Uncaught Error: ReCAPTCHA placeholder element must be empty".  The user( Revxx14 ) sent us a gist showing us how they modified the ninja-forms-recaptcha.php in 2.9.x to solve this issue. 

Revxx14's GIst:
https://gist.github.com/revxx14/544a72290e042293164d169b10a92318

**Comment by hitittome873** [comment]
Found a fix to this issue by adding the explicit render flag on the recaptcha api.js file call from google.

<script type="text/javascript" src="https://www.google.com/recaptcha/api.js?**render=explicit**&hl=<?php echo $lang; ?>"> </script>

**Comment by hitittome873** [comment]
Anyone able to implement a change on this? I've managed to get it working by using a random id per captcha container as a selector as well as the explicit render option to load the captcha script.

Here's my current display function:
`function ninja_forms_field_recaptcha_display( $field_id, $data, $form_id = '' ) {
	$settings = get_option( "ninja_forms_settings" );
	$lang = $settings['recaptcha_lang'];
	$siteKey = $settings['recaptcha_site_key'];
	$field_class = ninja_forms_get_field_class( $field_id, $form_id );
	$rand = wp_rand(0, 99999);
	wp_enqueue_script(
		'g-recaptcha',
		'https://www.google.com/recaptcha/api.js?onload=nf_grecaptcha_explicit_render&render=explicit&hl='.$lang, ['nf-grecaptcha-explicit-render'] );
	if ( !empty( $siteKey ) ) { ?>
		<input id="ninja_forms_field_<?php echo $rand;?>" name="ninja_forms_field_<?php echo $field_id;?>" type="hidden" class="<?php echo $field_class;?>" value="" rel="<?php echo $field_id;?>" />
		<div id="g-recaptcha-<?php echo $rand; ?>" class="g-recaptcha" data-field-id="<?= $rand; ?>" data-callback="nf_recaptcha_set_field_value" data-sitekey="<?php echo $siteKey; ?>"></div>
		<script type="text/javascript">
            function nf_recaptcha_set_field_value(inpval){
            	jQuery("#ninja_forms_field_<?php echo $rand;?>").val(inpval)
            }
            </script>
		<?php
	}
}`

And here is the render function (included in a separate script file which is registered in the child theme):
`function nf_grecaptcha_explicit_render(){
    jQuery('.g-recaptcha').each(function(){
        var id = jQuery(this).data('field-id');
        grecaptcha.render('g-recaptcha-'+id, {
            'sitekey':'[insert site key]'
        })
    });
}`
I would like to contribute but not sure how to go about it as I've never submitted anything on github before.

**Comment by amonger** [comment]
In case anyone else comes up against this, they can use my hacky work around
```javascript
window.onload = function () {
    document.querySelectorAll('.g-recaptcha').forEach(function (el) {
        el.innerHTML = "";
        var div = document.createElement('div');
        el.appendChild(div);
        var relValue = el.previousSibling.previousSibling.getAttribute('rel');
        eval(`
            window.nf_callback_${relValue} = function (response) {
                document.getElementById('ninja_forms_field_${relValue}').value = response;
            }
        `);
        try {
            grecaptcha.render(div, {
                'sitekey' : el.getAttribute('data-sitekey'),
                'callback': `nf_callback_${relValue}`
            });
        } catch (e) {}
    });
};
```

**Comment by wpnzach** [comment]
This appears to still be an issue.  In 3.0.25, the first form will submit but the second/subsequent forms will not.

**Comment by MyTheValentinus** [comment]
Any update ?

**Comment by kstover** [comment]
This should be taken care of in the latest version. If you still see an issue with multiple reCaptchas on a page, feel free to re-open.

**Comment by dbmpls** [comment]
@kstover with 3.1.1 I'm still having trouble with multiple reCaptchas on a single page. In my case, I have a visible contact form, and then a second form in pop up that also has reCaptcha. 

On my forms created prior to 3.1.1 I'm still getting "Uncaught TypeError"
![image](https://cloud.githubusercontent.com/assets/28467361/25769081/c19a5152-31d6-11e7-92f2-8eb113f7d4fb.png)

On Newly created forms, both of the ReCaptchas clear, and there is no errors listed in the Console, but I'm getting an error when trying to submit the form that says "please correct errors before submitting" - even though all fields are filled in and ReCaptcha has been cleared.

**Comment by raptor235** [comment]
Same here, just ran into the same issue... I think the reCaptcha data is being assigned to the wrong form... the $_POST req doesn't transmit the code from google.

**Comment by klhall1987** [comment]
I was able to replicate this issue in the current version of Ninja Forms.

**Comment by kstover** [comment]
I've set this as a high-priority bug. It should be taken care of as soon as all Easy/High priority bugs are dealt with.

**Comment by georgeinggs** [comment]
Don't suppose we have a fix for this yet by any chance?

**Comment by anjanavk1** [comment]
I'm having the same issue and its not working

**Comment by anjanavk1** [comment]
how to do only one captcha is showing

**Comment by TheoryGeorgiou** [comment]
Hello this is still an issue. Cannot have recaptcha on multiple forms on the same page.
