### ISSUE TITLE
'This keyword is reserved by WordPress' validation error

### ISSUE THREAD

**Issue by joehatchdesign** [wpninjas/ninja-forms#1300]
If you attempt to use a restricted keyword in a field's 'Default Value - Query String Variable' field, and it's restricted - it will highlight the box you're editing - but the validation messages appears on all other variable fields.

Screenshot here - http://i.imgur.com/dBQj8lQ.png

Note: I'm using 2.9.x with Zapier and Multi-part addons enabled but I've not tested or attempted to replicate this issue.

**Comment by kjohnson** [comment]
@joehatchdesign haven't seen this with v3, which has been launched publicly. Is this still an issue?
