### ISSUE TITLE
PHP Warnings in Submissions Table with Textbox fields

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#1309]
- `PHP Warning: nl2br() expects parameter 1 to be string, array given in /var/www/intevac.com/wp-content/plugins/ninja-forms/deprecated/includes/fields/textbox.php on line 352`
- `PHP Warning: strlen() expects parameter 1 to be string, array given in /var/www/intevac.com/wp-content/plugins/ninja-forms/deprecated/includes/fields/textbox.php on line 349`

**Comment by kstover** [comment]
Is this still an issue in 3.0.x? @kjohnson
