### ISSUE TITLE
Recaptcha not stopping the form from being submitted

### ISSUE THREAD

**Issue by kiwiot** [wpninjas/ninja-forms#1310]
Ninja Forms build : 2.9.42

Before updating to the latest version recaptcha was a required field and would prevent the form from being submitted.

Example Form

Note all fields are required, and not filling them in disables the submit button

http://www.awesomescreenshot.com/image/1177233/0284802162755f5c64559cb96b4e776b

However filling all the fields in correctly the first time does not disable the send button (of course)

http://www.awesomescreenshot.com/image/1177237/67ef0ed8b7035422691fbb94fa1fab58

But upon click (without clicking the recaptcha) the form submits, but does not show the success message. It is however logged in the backend.

http://www.awesomescreenshot.com/image/1177240/b5109069650545627fa1a7160341c94f

Clicking the recaptcha works as normal.

In the previous version of NF recaptcha would ahve been caught as a required field

**Comment by yeetien** [comment]
Still having same issue in 2.9.52 for 3.0 form. Recaptcha working as expected after reverted back to 2.9.

**Comment by kstover** [comment]
This should be taken care of in version 3.0.x.
