### ISSUE TITLE
reCaptcha API called on every form load

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1311]
even if recaptcha field is not included, the API is being called.

**Comment by fcponline** [comment]
@wpnzach I have noticed this as well plus the “Append a Ninja Form” and “Add form to this page” queries are being called as well.  I am only using the [shortcode ] to add forms to pages. These queries  are not necessary. Any ideas on how to turn them off?

Thanks

Netivity

**Comment by kstover** [comment]
I apologise for coming back to this ticket a year later. I'm going to close it; if it's an issue, feel free to open it again with current details.
