### ISSUE TITLE
Disconnect field names from ID's in field output

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1313]
By defaulting to the field label for the field name instead of the field ID number, we can proper utilize browser autocomplete features in Ninja Forms.  This could be really big.

**Comment by kjohnson** [comment]
Recent article for investigation: http://blog.cloudfour.com/autofill-what-web-devs-should-know-but-dont/

**Comment by wpnzach** [comment]
duplicate https://github.com/wpninjas/ninja-forms/issues/1558
