### ISSUE TITLE
Ninja Forms 3.0 prevents user deletion

### ISSUE THREAD

**Issue by ericnicolaas** [wpninjas/ninja-forms#1315]
I am using NF after upgrading to 3.0. After attempting to delete a user via Users > All Users, the script is dying with this: 

`
Go get a life, script kiddies
`

URL looks like http://site.com/wp-admin/users.php?action=delete&user=6&_wpnonce=30357fa016

Looks like `NF_Admin_AllFormsTable::process_bulk_action()` is being a bit too greedy :)

**Comment by kiwiot** [comment]
Same issue
