### ISSUE TITLE
Preview form double loading of shortcodes

### ISSUE THREAD

**Issue by polevaultweb** [wpninjas/ninja-forms#1317]
To recreate

* Add a NF shortcode to the homepage
* Edit the form and preview it
* The form is loaded twice, once by the shortcode and once by the preview shortcode

**Comment by polevaultweb** [comment]
As discussed with @kjohnson

**Comment by kstover** [comment]
@polevaultweb Is this still an issue with 3.0.x?

**Comment by polevaultweb** [comment]
@kstover i believe @kjohnson fixed it - but i couldn't tell you which commit. Not seeing it
