### ISSUE TITLE
In 3.0 Newsletter lists are not updating when switching between newsletter actions

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1322]
When a newsletter action is selected and the newsletter list is populated by clicking the "spin" icon. If you then switch to another newsletter action or add a new newsletter action the new newsletter action's list will be populated with the previous action's list until repopulate the list. 

Reproduction Steps: 
1. Create a new form
2. Add MailChimp action
3. Populate list on action close action drawer.
4. Create an Emma Action (You'll need to switch to the 3.0 branch of emma, it's currently not merged into core.)
5. Click the list dropdown and you should see the MailChimp list options still being populated

**Comment by kjohnson** [comment]
@klhall1987 I think the issue is newsletters not setting a transient name, therefor they all end up sharing a transient. I'll need to add a fallback in the base class.
