### ISSUE TITLE
multiple recaptchas on page error

### ISSUE THREAD

**Issue by thomaslittle** [wpninjas/ninja-forms#1324]
When there are more than one recaptchas on one page (in my instance a contact page that also has a site-wide modal with a form in it as well) I'm seeing an the error `ReCAPTCHA placeholder element must be empty`. The modal recaptcha works fine, but the second does not.

I know this is an issue with recaptcha that I could fix if I were implementing with a custom form using seperate unique IDs (http://stackoverflow.com/questions/1241947/how-do-i-show-multiple-recaptchas-on-a-single-page), I'm just not sure how to fix this issue within NJF.

Any ideas?

**Comment by kjohnson** [comment]
Closing in favor of #1298.
