### ISSUE TITLE
Adding classes to various input types via filters

### ISSUE THREAD

**Issue by JacobDB** [wpninjas/ninja-forms#1330]
I'm sure I'm missing something pretty obvious, but how would I go about adding custom classes to various input types? For example, I want to add the class `button` to any submit buttons, the class `input` to any text inputs, and the class `user-content` to text Layout "inputs."

I found the documentation on the [`ninja_forms_field` hook](http://docs.ninjaforms.com/customer/en/portal/articles/1981032-filters-ninja_forms_field?b_id=9172), but it doesn't return any data about what the actual field is, just the data it contains. For example, when I echo back the data on a text field on a site I'm working on, this is all it shows:

```
Array
(
    [label] => Introduction
    [input_limit_msg] => character(s) left
    [default_value] => Signup for important news, events, information and cancellations within the River Trails Park District!
    [desc_el] => div
    [class] =>
    [show_desc] => 0
    [desc_pos] => none
    [desc_text] =>
    [conditional] =>
    [style] => Array
        (
            [colspan] => 4
        )

    [field_class] => ninja-forms-field
)
```

Nothing in that indicates that it's a "text layout" field. It doesn't even contain all the classes it actually has, which are `ninja-forms-field` as well as `nf-desc`.

**Comment by JacobDB** [comment]
Can anyone help with this? I'm revisiting it today, still running in to the same problem. I need to have a way to identify what type of field I'm filtering.

**Comment by kjohnson** [comment]
@JacobDB we introduced a field setting for custom wrapper classes and custom element classes in v3.
