### ISSUE TITLE
Excessive padding below form

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#1338]
The honeypot field seems to be creating excessive padding below the form.

<img width="1261" alt="screenshot 2016-05-10 16 19 32" src="https://cloud.githubusercontent.com/assets/10858303/15161215/4895045e-16cb-11e6-9f81-00827dd72172.png">

**Comment by kjohnson** [comment]
The `.nf-hp` class has `visibility: hidden`, but this still holds space in the flow.

Possible solution: `.nf-hp { position: absolute; }` removes it from the flow.

**Comment by jameslaws** [comment]
Where is this honey pot appended. I don't see it in my forms on 3.0.

**Comment by kjohnson** [comment]
It is programmatically added in after-fields.

**Comment by jameslaws** [comment]
That's weird. I can't reproduce: https://db.tt/C3gVbWU0

**Comment by kjohnson** [comment]
I'm seeing it on twenty-sixteen, without layouts and styles.

**Comment by jameslaws** [comment]
I'm on whatever default theme I am on with the new layouts.

**Comment by kjohnson** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/visibility
> The visibility property can be used to hide an element while leaving the space where it would have been.

**Comment by jameslaws** [comment]
Sure. I just don't know why I wouldn't see it the same thing.

**Comment by kjohnson** [comment]
Just posting for reference. I'll take a look at how after-fields are used with layouts.

**Comment by jameslaws** [comment]
If you found the fix, I would apply and for further testing with and without layouts.

**Comment by kjohnson** [comment]
Testing #1340 with Layouts.
