### ISSUE TITLE
Reduce DB Queries - Remove “Append a Ninja Form” feature and the “Add form to this page” feature 

### ISSUE THREAD

**Issue by fcponline** [wpninjas/ninja-forms#1341]
Can these features and their queries on each page be turned off?  We only use the shortcode or the php insert to call on a form. We are getting 63 queries a page with only 1, 2 field form in the footer.

Why does NF need to check on each page for these items when the shortcode works just fine?

Thanks

**Comment by kjohnson** [comment]
@fcponline The "Add form to this page" setting has been removed as of v3.
