### ISSUE TITLE
Multiple countdown timers. Using an object instead of an array

### ISSUE THREAD

**Issue by saetia** [wpninjas/ninja-forms#1349]
Was the intention of line 5 to support multiple forms / countdown buttons on one page? Because this isn't creating an array, it's just assigning the timer to a property named "index".

```js
1 var countdown = {};
2 jQuery('.countdown-timer').each(function( index ) {
3 	jQuery(this).attr('disabled', 'disabled').prev('input.no-js').remove();
4 	id = jQuery(this).attr('id');
5 	countdown.index = window.setInterval(function(){ninja_forms_countdown(id, index)},1000);
6 });
```
https://github.com/wpninjas/ninja-forms/blob/f93a26e1ab218f7dfe7a3f3f85bf8fa83fe97986/deprecated/js/dev/ninja-forms-display.js#L197

**Comment by kjohnson** [comment]
The `timer_submit` field type has been removed from v3.
