### ISSUE TITLE
PHP outputted on fresh multisite (subfolder) installation

### ISSUE THREAD

**Issue by tacoverdo** [wpninjas/ninja-forms#1354]
I just installed a fresh Dutch multisite installation (subfolder installation) and created a subsite.
Immediately after, I installed Ninja Forms. This resulted in the following:

<img width="1288" alt="formulieren_ _contacten_ _wordpress" src="https://cloud.githubusercontent.com/assets/5147598/15300533/721691de-1ba9-11e6-98f5-bba747af9218.png">

This happened on `http://mysite.com/subsite/wp-admin/admin.php?page=ninja-forms`.

The visible code: 
`if( function_exists( 'ninja_forms_display_form' ) ){ ninja_forms_display_form( 1 ); }`.

**Used versions**
WordPress: v4.5.2
Ninja Forms: v2.9.45

**Comment by kjohnson** [comment]
@tacoverdo What you are seeing is an intentional output for displaying forms directly in the theme file. 

This is being removed from v3.0.
