### ISSUE TITLE
Export CSV Catchable Error. 

### ISSUE THREAD

**Issue by devinbalram** [wpninjas/ninja-forms#1356]
When Trying to Export CSV : 

Catchable fatal error: Argument 1 passed to NF_Abstracts_ModelFactory::export_subs() must be of the type array, string given, called in /home/content/p3pnexwpnas14_data02/41/3267641/html/wp-content/plugins/ninja-forms/includes/Admin/Menus/Submissions.php on line 290 and defined in /home/content/p3pnexwpnas14_data02/41/3267641/html/wp-content/plugins/ninja-forms/includes/Abstracts/ModelFactory.php on line 382

http://handymanplusdesign.com/wp-admin

https://wpninjas.desk.com/web/agent/case/16432

**Comment by kstover** [comment]
Should be fixed in version 3.0.x.
