### ISSUE TITLE
option-repeater cannot be used in action settings

### ISSUE THREAD

**Issue by ZeroBeeOne** [wpninjas/ninja-forms#1364]
Hello,

I am developing an action for Ninja Forms 3 based on the documentation available in the codex. In the `$_settings` for my action I have the following:

```
'mappings' => array(
		'name'		=> 'mappings',
		'type'		=> 'option-repeater',
		'label'		=> __('Field Mappings') . ' <a href="#" class="nf-add-new">' . __('Add New') . '</a>',
		'width'		=> 'full',
		'group'		=> 'primary',
		'columns'	=> array(
			'f_key'		=> array(
				'header'	=> __('Meta Key'),
				'default'	=> '',
			),
			'f_val'		=> array(
				'header'	=> __('Value'),
				'default'	=> '',
			),
		),
		'tmpl_row'	=> 'nf-tmpl-2col-repeater-row'
	)
```

I add the row template as follows:

```
add_action('ninja_forms_builder_templates', array($cls,'add_row_template'));
public static function add_row_template()
		{
			?>

			<script id="nf-tmpl-2col-repeater-row" type="text/template">
					<div>
						<span class="dashicons dashicons-menu handle"></span>
					</div>
					<div>
						<input type="text" class="setting" value="<%= f_key %>" data-id="f_key">
					</div>
					<div>
						<input type="text" class="setting" value="<%= f_val %>" data-id="f_val">
						<span class="dashicons dashicons-list-view merge-tags"></span>
					</div>
					<div>
						<span class="dashicons dashicons-dismiss nf-delete"></span>
					</div>
				</script>

			<?php
		}
```

However I get a fatal javascript error on the form editor page when adding my action: Uncaught ReferenceError: f_key is not defined.

Is the option-repeater setting type just not supported for actions? #1002 suggests that it may be intended to be general, and nothing I found in the documentation would suggest that it is not supported, however it seems as though the `obj` passed to the generated function for template rows in the action settings drawer does not contain properties for the columns defined in `$_settings`.

I don't mind hearing that it is just not supported, if so I would just suggest the documentation be updated to reflect that. (Although certainly I think it is worthwhile to have access to a repeated row setting type for actions)

**Comment by kjohnson** [comment]
@ZeroBeeOne, the error is being thrown because `f_key` does not yet exist. You'll want to add a value check, or add a default row.

```js
<%= ( 'undefined' != typeof f_key ) ? f_key : null; %>
```

**Comment by ZeroBeeOne** [comment]
Thanks @kjohnson, that's got me sorted.
