### ISSUE TITLE
Default message for submissions limit

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1376]
We get a lot of supprot requests from people whose forms are not displaying because they have forgotten they set a submissions limit.  If a default value were in this field, such as "This form has already been completed the maximum number of times allowed by the site administrator.  Please ask the site administrator to increase the limit if you require access to this form." I think it has the potential to reduce support requests.

**Comment by kjohnson** [comment]
@wpnzach is this for 2.9.x or 3.0?
