### ISSUE TITLE
Set "Opinionated Styles" to light by default on new 3.0 installs

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1380]
Once 3.0 is live, on new installs we need to change the "Opinionated Styles" setting to be set to "Light" by default. It is currently being set to "none".

**Comment by kjohnson** [comment]
@jameslaws are we still wanting to do this? It didn't make our launch list, but we could include it in an update for new users.

**Comment by jameslaws** [comment]
I'm not worries about this one at the moment. We can revisits after we get through our initial couple of weeks past launch.
