### ISSUE TITLE
In version 2.9.47, adding a character limit to a field, when Stripe is enabled, causes a JS error.

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#1389]
There is a bug with adding a character limit to a field when Stripe is active on the form.
It causes a javascript error: "Uncaught TypeError: jQuery(...).counter is not a function" which is coming from the file ninja-forms-display.min.js
This is only the case in version 2.9.47

**Comment by klhall1987** [comment]
Bug confirmed assigning to @kjohnson 

Replication steps:
In 2.9.x code base 
1. Create a new form
2. Add first name, last name, credit card field, and submit field. 
3. Goto the settings tab and enable stripe and stripe sandbox mode. 
4. Preview form on frontend and inspect element.
