### ISSUE TITLE
NF 3.0 - Locale

### ISSUE THREAD

**Issue by StaggerLeee** [wpninjas/ninja-forms#1390]
Can you make some tutorial in documentation how to translate new 3.0 version ? 
Specially new Pikaday calendar. Absolute nothing in 3.0 is localized. Language is not some unknown, German.

It doesnt help with all files in "deprecated" folder, very confusing.

I used:
**'ninja_forms_forms_display_datepicker_args'**
for preventing chosing date back in time in calendar.

And for localizing. Dififcult to find new one for all this.

**Comment by kjohnson** [comment]
We are still working on localizing the THREE codebase. WordPress does not yet support JS localization, so we are needing to develop our own system.

**Comment by StaggerLeee** [comment]
Thanks for clarification. 

I will revert back, need it for one live project. Dont like idea to meddle with plugin core files, despite it is easy. You confused me with statesment that it is raedy for production sites. It is for english ones,

Man how mad was I at you for that code needed to type to upgrade. I almost smashed my notebook.. Then I found it on Google how to do it. :)

Anyway congratulations for 3.0, it is very special piece of art.

Here are some problems for you to be aware, to not to open new issues. I see others have mentioned them:

- Typing help text (bubble ?) prevent form showing.
- Making checkboxes required prevent form showing.
-  HTML field makes its own huge spacing between fields, unnatural.
