### ISSUE TITLE
Checkboxes - Changed class when box is checked

### ISSUE THREAD

**Issue by StaggerLeee** [wpninjas/ninja-forms#1391]
It was main reason I forced upgrade to 3.0, to see is it solved in 3.0. And it is actually. Checking one checkbox adds new class something-checked to both label and input, brilliant. As it is now I cannot use 3.0 and have to revert back, I need to ask about this problem.

Why it doesnt work in 2.9.x versions ?

I did it with jQuery sensing mouse events. Working fine, but main problem is I have on other page 2 buttons redirecting to same form, and making one od those 2 checkboxes checked via URL. So if visitor clicks on already checked box javascript will trigger (mouse event) and change color of text, despite box is not checked anymore. If I did not have those URLs populating checkbox I would be fine with jQuery solution.

DId you ever noticed field doesnt add checked class or something when box is checked ?
When arriving at form via URL and box is populated then it ads "checkied", It doesnt sense mouse events.
I tried to disable all plugins with Plugin Organizer plugin, problem is the same. Did not change theme, but if I remember right on one demo site I saw same problem.

Explained with real life example it is like this:

- Have one Page with Info and images of 2 Appartements.
- Made under each Info one (2) buttons with custom URL to go to form and populate one of two checkboxes. 
- When visitor is redirected to form it needs to change color of label (to red) of populated one box. For visitor, to exclude any confusion.
- It works fine. Except it eliminates Javascript solution for sensing mouse event when clicked on box. You can end in some situation with red label and empty box.

Anyway, is it a bug for "checked" class missing when checking one box ?
Or did you not implemented something like this at all in 2.9.x versions ?
I see 3.0 handle it well.

**Comment by kstover** [comment]
This is purely a 3.0.x feature.
