### ISSUE TITLE
Forms stop working when cookie wp_woocommerce_session_ is created and user is not logged in

### ISSUE THREAD

**Issue by serteckian** [wpninjas/ninja-forms#1407]
I have a number of ninja forms in a  WooCommerce site, some of them Ajax enabled. If a fresh user access the page, the forms work fine.

When the  the user adds some product to the cart, the following cookies are generated:
- wp_woocommerce_session_xxx...xxx	
- woocommerce_items_in_cart	
- woocommerce_cart_hash	

Once these cookies have been created, if the user is not logged in yet, the forms stop working. In particular, If the form is Ajax enabled, the submit button says "processing" and an "undefined typeError cannot read some property" is thrown; nothing else happens, neither the form is submitted, nor the mandatory fields are checked. If the form is Ajax disabled, the form page simply reloads; again, neither the data is submitted, nor the mandatory fields are checked.

I remark that these errors do not happen if the user is logged in. In this case, the forms work just fine, even when the WooCommerce cookies have been generated.

Now, coming back to the not logged user case. As I wrote above, if the cookies have been created and the user is not logged, the forms stop working and they do not work anymore even if I reaload the page. Nevertheless, if the user manually removes the cookie "wp_woocommerce_session_xxx" and then reload the pages, the forms start working just fine after reloading!

Any idea how to workaround this?
Thanks in advance!

**Comment by kstover** [comment]
Thanks for submitting such detailed reproduction steps. We're pretty sure that we've fixed this in master, and it will be released in version 2.9.48 on Monday morning EST.

**Comment by serteckian** [comment]
Great! The patch has fixed the issue. Thank you very much for your support!
