### ISSUE TITLE
Add-Ons page throws an error if PHP cannot connect to URLs

### ISSUE THREAD

**Issue by walterebert** [wpninjas/ninja-forms#1410]
I get the following message if go to the Add-ons and PHP cannot connect to an external URL.

`Warning: stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /var/www/html/wp/wp-includes/class-wp-http-streams.php on line 150 Warning: stream_socket_client(): unable to connect to ssl://ninjaforms.com:443 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /var/www/html/wp/wp-includes/class-wp-http-streams.php on line 150 Warning: Invalid argument supplied for foreach() in /var/www/html/wp-content/plugins/ninja-forms/deprecated/includes/admin/pages/ninja-forms-addons/tabs/addons/addons.php on line 32 Warning: Invalid argument supplied for foreach() in /var/www/html/wp-content/plugins/ninja-forms/deprecated/includes/admin/pages/ninja-forms-addons/tabs/addons/addons.php on line 48 `

This happens when a server is inside a DMZ and is not allowed to communicate with the outside world.

This error can be reproduced by adding the following to wp-config.php:
define( 'WP_HTTP_BLOCK_EXTERNAL', true );

**Comment by kstover** [comment]
We've moved to a localised copy of the add-ons feed. When we change it back to fetched, we'll have a fall-back.
