### ISSUE TITLE
Add a filter to force loading of 2.x

### ISSUE THREAD

**Issue by Shelob9** [wpninjas/ninja-forms#1425]
I recently ran into an issue where the site got opted into 3.0 beta and I couldn't get it back to loading 2.x without hacking the plugin, which worked but was not desirable.

A filter that would force it to load the old code would have been really helpful. I will submit a PR with this filter.

**Comment by kstover** [comment]
This shouldn't be an issue with version 3.0.x being the official version. If you still need this taken care of, you can re-open and we'll talk about it.
