### ISSUE TITLE
Bulleted List

### ISSUE THREAD

**Issue by devinbalram** [wpninjas/ninja-forms#1428]
User desires bulleted list items : 

A response from James in ticket 18130 : 

In the list field, checkboxes and radios are an unordered list so they would generally show bullets which would not be desired for the individual items in the list. Because of this we've added some CSS to prevent that undesired display. The problem is that the CSS we added also impacts the description in those specific fields.

**Comment by jameslaws** [comment]
This was resolved in the 2.9.x codebase as of 2.9.49
