### ISSUE TITLE
dot company(.company) domain is failing email validation in 3.0 

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1429]
In the 3.0 code base If a user has an email address with a dot company(.company) domain the address is failing email validation.

Screenshot: 
![screen shot 2016-06-15 at 12 54 27 pm](https://cloud.githubusercontent.com/assets/9393977/16089278/5115cfe8-32f8-11e6-8308-98ff5376babf.png)

Replication Steps:
(in the 3.0 code base)
1. Create a new form. 
2. Add a email field and submit button.
3. Preview the form and try submit the form with an email address that has a .company domain.

**Comment by kstover** [comment]
Closing in favour of a newer ticket about longer/new tlds in email addresses.
