### ISSUE TITLE
Querystring Value not filling on reload. 

### ISSUE THREAD

**Issue by devinbalram** [wpninjas/ninja-forms#1435]
They querystring populates the fields just fine on initial load, but if the form is submitted with an error, it reloads and the querystringed values aren't filling out the desired fields as expected. 

https://wpninjas.desk.com/web/agent/case/18437

**Comment by kjohnson** [comment]
Disabled fields do not submit. Use hidden fields instead.

**Comment by jameslaws** [comment]
Can you clarify this a bit for me? What do you mean, disabled fields don't submit?

**Comment by kjohnson** [comment]
@jameslaws a field with the restriction of 'disable' does not submit, which is an expected HTML behavior.
