### ISSUE TITLE
Submission Notes

### ISSUE THREAD

**Issue by devinbalram** [wpninjas/ninja-forms#1438]
Adding a "notes," section in the back end. 

We've had a few users ask for the ability to comment on the form in the back end, to dynamically add notes after the submission. 

https://wpninjas.desk.com/web/agent/case/18684

**Comment by kjohnson** [comment]
This could currently be handled with another plugin like [WP Noteup](https://wordpress.org/plugins/wp-noteup/) as opposed to duplicating functionality.

**Comment by kjohnson** [comment]
Still something to consider.
