### ISSUE TITLE
Maybe allow registering fields later then on 'plugins_loaded'

### ISSUE THREAD

**Issue by sebet** [wpninjas/ninja-forms#1450]
While trying to extend your `terms` field I've noticed I cannot populate the taxonomies with terms from custom taxonomies since the filter for registering fields is called on `plugins_loaded` which means that custom taxonomies from plugins are not yet registered at that time.

Changing to a later hook like `init` with a priority greater then the default would fix this.

**Comment by kstover** [comment]
Have you tried extending a form in version 3.0.x?

**Comment by sebet** [comment]
This is not longer a problem in 3.0 (it was for the previous NF version). 

Thank you!

On ter, 13/09/2016 at 21:05 Kevin Stover

<
mailto:Kevin Stover <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Have you tried extending a form in version 3.0.x?

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/wpninjas/ninja-forms/issues/1450#issuecomment-246806562
, or
