### ISSUE TITLE
Preview form URL incorrect on a multisite installation with custom WordPress folder

### ISSUE THREAD

**Issue by jlambe** [wpninjas/ninja-forms#1454]
Found another minor issue on a multisite instance with custom WordPress folder.

I have WordPress installed at this URL: `mydomain.dev/cms/` but the public URL (front page) is still `mydomain.dev/`. When hovering/clicking the « Preview form » link, its URL is `mydomain.dev/cms?nf_preview_form=1` where it should be `mydomain.dev/?nf_preview_form=1`

**Comment by kjohnson** [comment]
@jlambe this should be resolved along with #1661 . Can you confirm?
