### ISSUE TITLE
Second form not loading

### ISSUE THREAD

**Issue by DustinWStout** [wpninjas/ninja-forms#1455]
When two of the same form is used (via shortcode) on the same page, the second form is failing to load. See: http://sd.dustn.co/time-management-guide/

**Comment by kstover** [comment]
Hey Dustin,

Two of the same form on the same page is tricky, since they would have the same ID. This would require a bit of thinking on our part. Not sure how we'd handle it at the moment.

**Comment by kjohnson** [comment]
Closing in favor of #1730.
