### ISSUE TITLE
Show only actions that have been converted to 3.0 in "Available" actions. 

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1457]
Currently in the "Available" actions section in the "Add New Action" drawer we are showing add-ons that were hard coded into the section(see screen shot below). Could we change this to only show the add-ons that have been converted to 3.0? 

Screenshot:
Available Actions Section: 
http://goo.gl/6qZzH2

Replication Steps:
(in 3.0)
1. Create a new form.
2. Go to the "Email and Actions" tab
3. Create a new action and go to the "Available" actions section.

**Comment by wpnzach** [comment]
It was pointed out by people who I demo'd this for that the wording "Available" is potentially misleading/confusing as without an understanding of our business model it implies that they are available in plugin.  Perhaps changing the wording here to something like "Add These Actions" instead?  Open to discussion on better wording.
