### ISSUE TITLE
Create Templating System

### ISSUE THREAD

**Issue by BFTrick** [wpninjas/ninja-forms#146]
Ninja Forms should have some sort of templating system. This system would allow:

* allow extensions to easily load templates
* allow users to override templates in their theme
* templates to only be loaded when they're needed
* actions the fire before / after templates are loaded
* filters to allow the template file path to be modified

I think one of the most useful features here is that users can override these template in their theme so if you had a template for an input box a user would have the ability to override that template and add a wrapper div around that input box. They would just have to know HTML - nothing to do with filters.

I already have a prototype templating system running here: https://github.com/BFTrick/ninja-forms/commit/22c037c3dca5ceef7d4eb4eb4749b3e57d319cd8

Would love to try it out some more and then make a pull request. Let me know about any questions / concerns

**Comment by kstover** [comment]
Closed. Not applicable to version 3. (We do have a pretty sweet Underscore.js templating system there.)
