### ISSUE TITLE
If Conditional Logic and Layout and Styles are active the upgrade to 3.0 banner is being shown

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1462]
If Conditional Logic and Layout and Styles are installed or active the banner to upgrade to three is being shown and the user is able to upgrade. 

Screencast: 
https://goo.gl/dzqMAB

Screenshot:
http://goo.gl/IV2dpr

**Comment by klhall1987** [comment]
Sorry, I forgot to add replication steps to the original post. 

Replication steps:
(In 2.9.x)
1. Install Ninja Forms
2. Upload Conditional Logic and Layout and styles(I downloaded these via ninjaforms.com) 
3. Active the Plugin and Add-ons
4. You should see the upgrade banner at the top of the page.

**Comment by kstover** [comment]
@klhall1987 Please test against Master to confirm that this is fixed.

**Comment by klhall1987** [comment]
@kstover Tested and the fix is working. I no longer see the upgrade banner if conditional logic is installed on the site and I can no longer use the Konami code.
