### ISSUE TITLE
If conditional logic is installed or active users can upgrade to Three using the Konomi

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1463]
If Conditional Logic is active or installed either by itself or with other add-ons that have been converted to Three users can upgrade to Three using the Konomi code. I've detailed this behavior in a screen cast below with the Emma and Conditional Logic add-ons active. 

Screencast:
https://goo.gl/fMmFXA

Replication Steps: 
(in 2.9.x)
1. Install Ninja Forms.
2. Upload both Continual Logic and Emma(I got these via zip files from Ninjaforms.com) 
3 Activate the plugin and the add-ons. 
4. Go to the all forms page and input the konomi code.

**Comment by kstover** [comment]
There are currently two functions that handle checking for add-ons and versions for update purposes. These are nearly identical, with the exception that `ninja_forms_three_addons_version_check()` does not work properly, while `ninja_forms_three_addons_check()` does. Replacing the call to `ninja_forms_three_addons_version_check()` on line 828 of deprecated/ninja-forms.php with a call to `ninja_forms_three_addons_check()` fixes this issue.

**Comment by kstover** [comment]
Ok. Turns out I was dead wrong. The actual problem is in Core with our add-on json file. In it, Conditional Logic is listed as ninja-forms-conditional-logic instead of ninja-forms-conditionals, as it has been previously. Changing this to ninja-forms-conditionals fixes the issue.

**Comment by kstover** [comment]
@klhall1987 Please test against Master to confirm that this is fixed.

**Comment by klhall1987** [comment]
Tested, fix confirmed.
