### ISSUE TITLE
Webhooks plugin admin JS enqueued before Underscore

### ISSUE THREAD

**Issue by penguinstampede** [wpninjas/ninja-forms#1464]
I hope this is an okay place to post this.

I was having trouble with the latest versions of NF 2 (2.9.50) and Webhooks 1.0.2, when in the Admin area, trying to add a Webhook action, clicking "Add Field" did nothing.
I noticed that the problem was related to Underscore and the Webhooks plugin's admin.min.js, specifically the file was set to load before Underscore.

so I modified action-webhooks.php:

`wp_enqueue_script( 'nf-wh-admin',
        NF_WH_URL . 'assets/js/' . $src .'/admin' . $suffix . '.js',
        array( 'nf-notifications' ) );
`
to

`wp_enqueue_script( 'nf-wh-admin',
        NF_WH_URL . 'assets/js/' . $src .'/admin' . $suffix . '.js',
        array( 'nf-notifications', 'underscore' ) );
`

and the error is gone.  Still testing things out so I don't know if this is the 100% right fix, just wanted to bring this up.

**Comment by penguinstampede** [comment]
Still an issue with the update, though I'm still running NF 2.9.55 :)

**Comment by kstover** [comment]
Is this still an issue in 3.0.x?

**Comment by penguinstampede** [comment]
Sorry, haven't had time to test until now.  Updated a second site to NF 3.0.5 today, and now I can't enable the Webhooks plugin. :( "Oops! That addon is not yet compatible with Ninja Forms THREE."

This is Webhooks 1.0.2, is an update to the addon just not showing up as available in WP?

**Comment by penguinstampede** [comment]
Looks like Webhooks 3.0.2 still has this issue.

**Comment by kstover** [comment]
I apologise for coming back to this ticket a year later. I'm going to close it; if it's an issue with the 3.0 UI/Codebase of Ninja Forms, feel free to open it again with current details.
