### ISSUE TITLE
If a post has multiple copies of the same form, the actions are being fired twice. 

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1466]
If a post has a form used multiple times on a post/page, for instance if the user inputs the form short code in the post editor and adds the same form via the "Append a Ninja Form" metabox. The form only displays once on the frontend; however, the form's actions seem to fire multiple times. So the user will get two emails and see two submissions from a single form submission. I've added a screencast and screenshots below to detail the behavior. I'm not seeing any JS errors in the console or on the network tab nor am I seeing any PHP Errors in the error log. 

Screencast:
https://goo.gl/a3j5DY

Screenshots:
A post with the same form being set to display in two places:
http://goo.gl/tH2Hve

The form being viewed on the front end. 
http://goo.gl/J3GgY5

The submissions table after the form for was submitted:
http://goo.gl/23Tsl1

Replication steps:
(in the 3.0 codebase)
1. Create a new form. 
2. Add a first name, last name, and submit field. 
3. Goto the "Emails and Actions" tab.
4. Add a Save action if one is not already present. 
5. Publish the form. 
6. Create a new post. 
7. Add the short code from the form you just created to the post.
8. Add the form to the post via the "Append a ninja form" meta box.
9. Preview the post and submit the form. 
10. Check your form submissions.

**Comment by kjohnson** [comment]
This would have been because the submit button was triggering all forms with the same ID, which has been resolved.
