### ISSUE TITLE
Input field labels not showing in NF 3

### ISSUE THREAD

**Issue by ramiabraham** [wpninjas/ninja-forms#1468]
In NF 3, the default labels don't show on the front-end for most inputs:

A regular NF form:

A saved form, with a variety of fields, embedded on a page:

Back
![alt text](http://i.imgur.com/3JrV0J3.png "back end")

Front
![alt text](http://i.imgur.com/t5BOs1P.png "front end")

----

A NF 3 form using the AffiliateWP integration fields:

A saved form, with a variety of fields, embedded on a page:

Back
![alt text](http://i.imgur.com/dCWAynr.png "back end")

Front
![alt text](http://i.imgur.com/Mrp044s.png "front end")

----

This can be replicated by creating a new form, specifying fields normally, assigning the form to a page, and viewing it on the front-end.

**Comment by jameslaws** [comment]
Can you link to a live version of that form because I can't reproduce this in Ninja Forms. 

And just a heads up. The screenshots you posted are for 2.9.x of Ninja Forms.

**Comment by ramiabraham** [comment]
If that's the case, then the upgrade process failed. Mind confirming the branch to use? In [this AffiliateWP thread](https://github.com/AffiliateWP/AffiliateWP/issues/1106) it was indicated we should be using master.

Once I can confirm NF3 is running ok I'll test again.

**Comment by jameslaws** [comment]
http://developer.ninjaforms.com/access-ninja-forms-three-today/

It's the master branch. It's not automatic.

**Comment by ramiabraham** [comment]
Thanks @jameslaws

**Comment by ramiabraham** [comment]
Closing, as this was created against 2.9.x
