### ISSUE TITLE
UI hangs when saving a new form in NF 3

### ISSUE THREAD

**Issue by ramiabraham** [wpninjas/ninja-forms#1469]
When saving a new form in NF 3, the process hangs and does not exit from the popup:

![alt text](http://i.imgur.com/0SBzGdGl.png "spinner")

The spinner continues iterating, as no success indicator is sent back to the browser when the fields are saved:
![alt text](http://i.imgur.com/cpGRL9K.gif "spinner")

**Comment by jameslaws** [comment]
Looks like your server might be having issues or showing an error.

Also, your screenshots are for 2.9.x and not v3.0.

**Comment by ramiabraham** [comment]
This was tested in `vvv`, using PHP versions `5.4`, `5.5`, `5.6`, and `7`. The server isn not indicating any other issues, or generating any runtime errors.


However, a moot point, since this is still 2.9.x apparently, and likely related to: https://github.com/wpninjas/ninja-forms/issues/1468

**Comment by ramiabraham** [comment]
Closing, as this was created against 2.9.x
