### ISSUE TITLE
NF 3 upgrade process ambiguous, hangs if forms exist

### ISSUE THREAD

**Issue by ramiabraham** [wpninjas/ninja-forms#1470]
The NF 3 upgrade process displayed a few primary issues:

- There is no visual indicator that the process has completed successfully (or not). In the following process:
    - Visit `All Forms` page
    - Enter Konami code*
    - If you have _one or more forms_, the process hangs in Chrome, and never shows the upgrade button
    - If you have _no_ forms, the upgrade button shows.
    - When clicking the upgrade button, the page is reloaded
    - When the page reloads after clicking the upgrade button, there is no indicator that the codebase has been adjusted to use the NF 3 files. 

(`master` at `70276324`)

_*thanks for introducing me to cheet.js_ 💯

**Comment by ramiabraham** [comment]
In some other issues I've created today, it appears I'm using 2.9.x, since the upgrade routine consistently fails. These issues are:

https://github.com/wpninjas/ninja-forms/issues/1471
https://github.com/wpninjas/ninja-forms/issues/1469
https://github.com/wpninjas/ninja-forms/issues/1468

I'll re-test once the upgrade can complete successfully and close if resolved etc.

I see the methods relating to the NF 3 upgrade; could you recommend an alternate means of performing the NF3 upgrade, instead of the Konami-code method?

**Comment by jameslaws** [comment]
That's the best way because it will upgrade all of your current forms. You set the NF_DEV constant to true. You can also upgrade under certain conditions as stated in the post I shared.

**Comment by pippinsplugins** [comment]
I have not yet been able to get the upgrade to 3.0 to work. Is there a manual process I can use? I've set the DF_DEV constant to true and I've manually set the version number in the DB. No bueno.

**Comment by pippinsplugins** [comment]
The Switch to 3.x in the toolbar doesn't do anything for me, just reloads the page.

**Comment by kjohnson** [comment]
The `NF_DEV` flag enables an admin bar tool for switching codebases, although as a precaution the THREE codebase cannot be accessed until the tables have been created by the upgrade process.

**Comment by kjohnson** [comment]
@ramiabraham The upgrade process uses sequential AJAX requests. Are you seeing any JS errors in the console?

**Comment by pippinsplugins** [comment]
Can you tell me how to manually trigger the process?

**Comment by kjohnson** [comment]
You should be able to access the [upgrade page](https://wp:8890/wp-admin/admin.php?page=ninja-forms-three) directly under the following requirements.

With:
- Ninja Forms installed and active

Either:
- No Ninja Forms Add-ons, using the Konami Code
- Atleast one (1) v3+ Ninja Forms Add-on, using the Admin Notice

Without:
- Calculations
- Country Fields
