### ISSUE TITLE
Duplicate forms on one page with required fields triggers required field error. 

### ISSUE THREAD

**Issue by devinbalram** [wpninjas/ninja-forms#1478]
https://wpninjas.desk.com/web/agent/case/19395

On users site, he had both the short code & the form appended : https://goo.gl/Mt6FsP

This triggered an error that only one form showed, but when the form was submit, the processing was looking for the required field on the form that wasn't shown & caused the error to show.

**Comment by kstover** [comment]
Is this still a bug? @klhall1987
