### ISSUE TITLE
Sort Actions Error

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1479]
In Ninja Forms 3.0 a form has an action from a plugin that has been deactivated, then it's causing a 500 error to be thrown in the console and creating errors in the PHP error log upon form submission. I've added a screenshot of the errors I'm seeing in the PHP error logs. 

PHP error log screen shot: 
![screen shot 2016-07-06 at 11 47 14 am](https://cloud.githubusercontent.com/assets/9393977/16624737/df2648bc-436f-11e6-928a-4bba50b57dd7.png)

Replication Steps(in the 3.0 codebase with any add-on that has an action, I used the Slack add-on):
1. Create a new form
2. Add first name, last name, and submit field.
3. Goto "Email and Actions" tab.
4. Create a slack action.
5. Publish the form. 
6. Preview and submit the form. (Everything should work as expected.)
7. Go to plugins page and deactivate the Slack add-on.
8. Go back to you form and preview and try to submit the form again.

**Comment by kstover** [comment]
Should be fixed in the current version.
