### ISSUE TITLE
Calling init_all_the_ninja_things() too early is a bad idea ...

### ISSUE THREAD

**Issue by wloske** [wpninjas/ninja-forms#1487]
Hey Ninjas ...

we have a WP installation where things work a little differently because we have a custom implementation which uses ACF heavily and rendering is "handmade". We add forms to the output stream by calling `ninja_forms_display_form($id);` at the appropriate location. Everything works fine then. But when we use short codes the scripts NF needs to work and which are normally added to the footer section are now added to the head section. I have no good explanation why this is the case but it leads to a complete malfunction of NF because the script `ninja-forms-display.min.js` is not able to register the submit handler to the forms in the DOM tree.

We then realized that NF's functionality is being added by a function `init_all_the_ninja_things()` which resides in the global namespace and is being called right when the script is being loaded.

We tried to force the action into the footer with 

```
remove_action( 'ninja_forms_display_js', 'ninja_forms_display_js', 10, 2 );
add_action( 'wp_footer', 'ninja_forms_display_js', 10, 2 );
```

but this didn't work either. The best solution would be to wait on DOM ready and call the function then. I changed to script to 

```
$(document).ready(function(){init_all_the_ninja_things()});function...
```

and everything works fine then. I think this would be a good behaviour anyways.

Let me know what you think ...

**Comment by kstover** [comment]
@kjohnson ?

**Comment by wloske** [comment]
This is a funny thread ;-)

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.

**Comment by wloske** [comment]
This is a meh thread ;-/
About a year old and not one single piece of action on the topic.
