### ISSUE TITLE
Add GET variable in url submit redirect URL

### ISSUE THREAD

**Issue by nicoesiea** [wpninjas/ninja-forms#1497]
Hello,
I need to validate a second form after a first one. But I need keep the email adresse of the user in order to know how accepte the second form.
I'm looking to add one of the field value in the redirect URL parameter.
My first idea was to use a GET variable. 

In the second form, I added a hidden email field and I used *JQuerystring Varaible ->* option in the second form.
But now, I have to add this variable in the URL.... I do not know how to do this.
In Email & Action, I create a redirect action and I tried to add :
email=[ninja_forms_field id=36]

But the value of [ninja_forms_field id=36] is not auto replace by the user email value.

Could you please help me ???

Regards,
Nicolas

**Comment by nicoesiea** [comment]
Any idea??? I almost sure this is already possible... maby by adding a specific variable at the end of the URL in the input field for the URL....
HELP

**Comment by klhall1987** [comment]
Hi @nicoesiea,

This is possible using Ninja Forms, but would you mind to submit this question to our support team and they will be happy to assist you. You can submit a support request at the link below. 

Ninja Forms Contact
https://ninjaforms.com/contact/

Our github repo is primarily used for bug reporting. I'm sorry for any confusion, but I'm going to close this issue and we look forward to hearing from you. 

Thanks,
Kenny

**Comment by nicoesiea** [comment]
Hello Ionut,
I just followed the advice of Devin Barlram to contact one of "our
collaborating developers" to see if they can help me. See the answer below:
*******************
*Devin Balram* replied:

Nicolas,

Unfortunately we do not have an out of the box way of doing this currently
within Ninja Forms. We are working on making this a feature in Ninja Forms
Three & Webhooks, but at this time it would take custom code. Unfortunately
we do not have the resources to provide custom code. You may be able to
connect with one of our Collaborating Developers,
<https://ninjaforms.com/about> to see if they can provide you with a custom
solution.

I apologize that I don’t have a better answer for you.
Devin Balram
Happiness Ninja
The WP Ninjas Support Team
*******************

Thank you for your guidelines, I will continue to search.

Regards,
Nicolas


Respectueusement,

DUMONT Nicolas <http://copocorp.free.fr/>
0033 6 75 45 10 10 (FR)
00352 621 451 409 (LU)
2 allée des rossignols, 57535 Marange-Silvange
<https://www.google.fr/maps/place/2+All%C3%A9e+des+Rossignols,+57535+Marange-Silvange/@49.2133346,6.1161331,17z/data=!3m1!4b1!4m2!3m1!1s0x4795278df5de235d:0x51d54276486b2c67>

2016-07-18 11:09 GMT+02:00 Ionut Staicu <notifications@github.com>:
