### ISSUE TITLE
Page should jump to form location when required event fires

### ISSUE THREAD

**Issue by leecollings** [wpninjas/ninja-forms#1498]
If a form is submitted, with required fields that have not been completed, the page reloads and the required errors are shown. However, the page does not scroll down the location of the form, so the user has no idea what's happened.

The page should scroll to the location of the form containing the errors, if there are multiple forms on the page.

**Comment by leecollings** [comment]
Or, something else I've thought about.. I've seen in the docs you offer a function to get the response messages:

    $ninja_forms_processing->get_all_errors()

How could this be placed in a function to posssible show a Bootstrap modal when there are error messages detected?

**Comment by kstover** [comment]
I've added "Better Error Handling" to our internal feature tracker. Version 3.0.x uses inline error handling, which helps on this.

**Comment by leecollings** [comment]
That's something else, I'm running version 3 on a few sites, and I can't see anything that's different. There's supposed to be a whole brand new drag-drop system isn't there? It literally looks no different in WP Admin than before I updated. Is there a known error?

**Comment by mariodabek** [comment]
is this ever going to get fixed ? users should be directed to the validation errors and should not hav to scroll around the page looking for validation errors, what is this 1995 ?
