### ISSUE TITLE
Add Smart Address Fields for selecting State / Province Dropdowns for Other Countries

### ISSUE THREAD

**Issue by pippinsplugins** [wpninjas/ninja-forms#15]
Currently there is a State drop down field, but no drop downloads for other country's state / provinces:
![screen shot 2013-06-08 at 9 37 02 am](https://f.cloud.github.com/assets/1034109/627650/f9f98d90-d048-11e2-9dbd-401323a57f84.png)

In order to be more friendly to non-US users, additional options should be added for major countries that have states or provinces.

**Comment by kjohnson** [comment]
We would need a convention for implementing a `datalist`.

**Comment by jameslaws** [comment]
I think this is definitely needed.

**Comment by jameslaws** [comment]
Maybe 3.1 as I don't think we have time for it to be fully implemented in 3.0.

**Comment by cinghaman** [comment]
+ 1

**Comment by kstover** [comment]
Moved to internal feature tracking.
