### ISSUE TITLE
Unable to save Japanese Characters as a label in 3.0

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#1500]
Unable to save Japanese Characters as a label in 3.0

Replication Steps:
Running Ninja Forms 2.9.51 (3.0 code base) on WordPress 4.5.3
Add a text field to your form.
Try to set the label as 教会の名前
The Done button will turn gray and you will be unable to save the field settings

System Status:
### Environment ###
Home URL:                http://localhost/wordpress3
Site URL:                http://localhost/wordpress3
Ninja Forms Version:     3.0
WP Version:              4.5.3
WP Multisite Enabled:    No
Web Server Info:         Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/5.6.10 mod_ssl/2.2.29 OpenSSL/0.9.8zh DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0
PHP Version:             5.6.10
MySQL Version:           5.5.42
PHP Locale:              negative_sign:
WP Memory Limit:         40
WP Debug Mode:           Yes
WP Language:             Default
WP Max Upload Size:      32 MB
PHP Post Max Size:       32
Max Input Nesting Level: 64
PHP Time Limit:          30
PHP Max Input Vars:      1000
SUHOSIN Installed:       No
Server IP Address:       ::1
Host Name:               localhost
SMTP:                    localhost
smtp_port:               25
Default Timezone:        America/New_York

### Plugins ###
Installed Plugins:
Ninja Forms - Layout & Styles by The WP Ninjas version 3.0.0
Ninja Forms - Slack by The WP Ninjas version 3.0
Ninja Forms by The WP Ninjas version 2.9.51

**Comment by kjohnson** [comment]
WordPress requires the Database CHARACTER SET to be `utf8_general_ci` for multi-byte characters.
