### ISSUE TITLE
Checkbox list calc values are not being added to calculation variables

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1501]
In 3.0, Checkbox list field's calc values are not being added to calculation variables. 

Screencast:
https://goo.gl/X5jDBl

Replication Steps(In 3.0):
1. Create a new form.
2. Add a checkbox list field and an html field.
3. Edit the checkbox list field and add calc values 
4. Go to the "Advanced" Tab.
5. Select "Calculations"
6. Create a new Calc Variable and use the merge tag dropdown to select the checkbox list field you created earlier.
7. Go back the form build and edit the HTML field. 
8. Add the Calc merge tag to the field and preview the form.

**Comment by kstover** [comment]
Closed with b368d1adc935e481b92de06401bd797fe83f78dc
