### ISSUE TITLE
nf_wp_session set on page load

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#1502]
The cookie `nf_wp_session` is set on page load, which can create issues with Varnish Cache.

**Comment by kstover** [comment]
Is this an issue with 3.0? I know that 2.9.x had the issue of this being set on every page load, but I thought we had taken care of it a while back.

**Comment by kstover** [comment]
@kjohnson Is this the same issue? https://github.com/wpninjas/ninja-forms/issues/954
