### ISSUE TITLE
3: Required Product fields without Quantity cannot be submitted

### ISSUE THREAD

**Issue by pippinsplugins** [wpninjas/ninja-forms#1503]
I've created a product field, set it to required, and disabled the quantity input.
![screen shot 2016-07-15 at 10 59 06 am](https://cloud.githubusercontent.com/assets/1034109/16880525/47cb2e66-4a7b-11e6-9e1f-c9dbf0ddb78a.png)
The form won't accept it:
![screen shot 2016-07-15 at 11 00 10 am](https://cloud.githubusercontent.com/assets/1034109/16880534/4ffc782e-4a7b-11e6-90bf-e4a75aec69a9.png)
If I add the quantity field, I can submit the form fine.

**Comment by kjohnson** [comment]
Related: [Add dependent required setting for the product field](https://github.com/wpninjas/ninja-forms/issues/1647) #1647 

Currently the `required` setting has been removed until #1647 has been resolved.
