### ISSUE TITLE
Paragraph Text field character input limits are behaving like word input limits

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1506]
In 3.0, Paragraph Text field character input limits are behaving as word input limits. Instead of limiting the amount of characters that can be used in a text area, it is limiting it to the number of words that can be used. 

Sceenshots:
Backend:
http://goo.gl/0aBmIO

Frontend:
http://goo.gl/kYww0Z

Replication Steps(in 3.0):
1. Create new form
2. Add a Paragraph Text field and submit button.
3. Edit the Paragraph Text field and add a character limit. 
4. Preview the form and add some text.

**Comment by jameslaws** [comment]
Another report of this.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
