### ISSUE TITLE
Product field quantities are being calculated improperly when used in calculations

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1509]
In 3.0, If a product field that uses the quantity setting is used in a calculation the quantity does not multiple the value. Instead it adds the value of the quantity field. I've detailed the behavior in a screenshots below. 

Screenshots: 

Quantity setting:
http://goo.gl/6V8RKz

Calculation variable:
http://goo.gl/Avk8am

Total on the Frontend:
http://goo.gl/4xPxvB

Replication Steps(in 3.0):
1. Create a new form
2. Add a radio list, product field, html field, and submit button. 
3. Edit the radio list and add calc values to each item. 
4. Edit the Product field and enable the quantity field setting, then set a value for the product. 
5. Go to the advanced tab. 
6. Create a new calculation and add together the product and the radio list. 
7. Go back to the form builder and edit the HTML field. 
8. Add the value of the calculation to the HTML field. 
9. preview on the front end select a value from the radio list and add a quantity to the product.

**Comment by kjohnson** [comment]
Mis-closed by wrong commit message.
