### ISSUE TITLE
Calculation variables are not showing up in the Form Acttion Merge Tag dropdown

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1510]
In 3.0, Calculation variables are not showing up in the merge tag list in the Payment Total field under the Collect Payment action. I've detailed the behavior in a screencast below. 

Screencast:
https://goo.gl/yQX4AM

Replication Steps(in 3.0):
1. Create a new form. 
2. add two single checkbox fields and give them both checked values. 
3. Goto "Advanced" tab and add a calculation that adds both of the checkbox fields together. 
4. Go to the "Emails and Actions" tab and create a new "Collect Payment" action. 
5. Open the Merge tag's list in the Payment total field. The calculation variables list will not be there.

**Comment by kjohnson** [comment]
This seems to be related to Actions in general, not specifically the Collect Payment Action.
