### ISSUE TITLE
Two products on a page breaks the JS when changing quantities.

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1548]
[nf_form_07-27-2016.txt](https://github.com/wpninjas/ninja-forms/files/386596/nf_form_07-27-2016.txt)

Form attached.

![image](https://cloud.githubusercontent.com/assets/7498743/17183596/3f18ccae-53f6-11e6-9a25-9c6ed8d5c253.png)

Add "1" to widgets, then to jangles.  Form will error.

**Comment by kjohnson** [comment]
@wpnzach Did you map the quantity fields to the product fields?

**Comment by wpnzach** [comment]
@kjohnson I did, however https://github.com/wpninjas/ninja-forms/issues/1547 seems to have broken them.
