### ISSUE TITLE
Set "name" attribute to custom value or field key

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1558]
Browser autocomplete works from the name attribute.  If we make ours user readable/changable, we'll be the only WordPress form builder I know if that fully supports auto complete.

**Comment by wpnzach** [comment]
From @kjohnson "Recent article for investigation: http://blog.cloudfour.com/autofill-what-web-devs-should-know-but-dont/"

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.

**Comment by wpnzach** [comment]
reopening

**Comment by kstover** [comment]
For the moment, let's add a setting in "advanced" for each field for "input name." If that isn't present, then default to the field key.

**Comment by wpnzach** [comment]
As a reference: https://stackoverflow.com/questions/7223168/how-to-trigger-autofill-in-google-chrome/9795126#9795126

In the current release, name attribute cannot be set in email, first name, or last name fields.

I'd also recommend using the article above to set those input names automagically to things like "email" "fname" "lname" etc.  We should also prepopulate with a sanitized version of the label like the field key does, sans number.

**Comment by wpnzach** [comment]
In addition to above, can we rename this option to "Input Name (For Browser Autocomplete)" or something similar?  I don't think users will understand the implications of this option otherwise.
