### ISSUE TITLE
Inconsistant Submission Sequence Numbers

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#1560]

**Comment by sjorsroelofs** [comment]
Any progress on this one? The submission sequence sometimes stays on the same number for a few submissions, or goes back to a previous number.

**Comment by kstover** [comment]
I think we have been able to track this down and have a fix in for the next version.

**Comment by ilamp** [comment]
I'm not sure if it's the same bug but it happens when a user is not logged in. #2709
