### ISSUE TITLE
Add the "Append a Ninja Form" meta box to Custom Post Types

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1561]
Currently in both 2.9.x and 3.0 the "Append a Ninja Form" meta-box does not show up on Custom Post Types. 

Screenshot: 
Default WordPress Post Type: 
http://goo.gl/sqh1AT

Custom Post Type: 
http://goo.gl/SCuhSQ

**Comment by Zodiac1978** [comment]
There is a solution:
http://kylebjohnson.me/custom-post-types-and-the-ninja-forms-meta-box/

but it is [deprecated](https://github.com/wpninjas/ninja-forms/blob/c2cf72107a02764cac0f67367307611de72a7361/deprecated/includes/admin/post-metabox.php) and doesn't work anymore.

Any ideas how to achieve that now?

**Comment by kstover** [comment]
@kjohnson ?

**Comment by mithri** [comment]
Any news on this one?

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.

**Comment by quornik** [comment]
This is still an issue, currently meta box does not show on custom post types.

**Comment by leecollings** [comment]
This issue needs to be re-opened

**Comment by leecollings** [comment]
Bump

**Comment by leecollings** [comment]
So what’s the end solution for being able to assign a Ninja Form to the end
of the content for custom post types, the same way that currently happens
for posts and pages?

What exactly is stopping this from being do-able?
-- 


Kind regards,



Lee Collings | Graphic Designer & Web Developer
www.leecollings.co

This email and any attachments to it may be confidential and are intended
solely for the use of the individual to whom it is addressed. Any views or
opinions expressed are solely those of the author and do not necessarily
represent those of Lee Collings. If you are not the intended recipient of
this email, you must neither take any action based upon its contents, nor
copy or show it to anyone. Please contact the sender if you believe you
have received this email in error.

**Comment by jameslaws** [comment]
Let’s back up. Have you heard about Gutenberg and it’s impact on the WordPress content editor experience?

**Comment by leecollings** [comment]
I've heard about it, and have seen a demo of it. But I've also seen there's still going to be the Classic view/editor available, which I would believe is the existing layout.

But okay, so with Gutenberg on the horizon then, what's going to happen to the existing meta box append form method? Will that be ported over to a 'block' as Gutenberg docs suggest will happen to meta boxes?

Am I right in thinking a 'block' will essentially be the same as inserting a shortcode wherever you want the component to be placed?

**Comment by jameslaws** [comment]
We already have a Gutenberg block in core. You would had a form almost in the same way you would add a paragraph or any other display element to the form. In the block you can select which form you want to display and then it will be automatically rendered in the editor.

The classic editor will be available for a short period of time for a transition period, but it will no longer be the recommended way and will go away in the future.

**Comment by leecollings** [comment]
@jameslaws I appreciate the explanation and the recap about the future of WP.

I understand now why this issue was closed. It's a shame because I could really do with having this enabled now so I can append forms to the bottom of my custom post types.

For now, I'll make do with using shortcodes.
