### ISSUE TITLE
Drawer is showing on larger screens

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1562]
In 3.0 the drawer is showing in the builder until the drawer is opened and closed. This behavior only happens when I view the builder on my Thunderbolt display. I've detailed the behavior in a screenshot and screencast below. 

Screenshot:
http://goo.gl/4bmxgE

Screencast:
https://goo.gl/x3Zy2s

Replication steps:(In 3.0 on a Thunderbolt Display)
1. View a form, you should see a part of the drawer sticking out on the edge.

**Comment by kstover** [comment]
Appears to be taken care of. I can't point to a specific commit, but I don't see this happening anymore.
