### ISSUE TITLE
Force positioning of label in checkbox field

### ISSUE THREAD

**Issue by JacobDB** [wpninjas/ninja-forms#1565]
Is there a way, through a filter, to force the label to always come after the checkbox in the "checkbox" field type? If I could just filter the output HTML before it's printed, that'd be enough for me to figure this out I think. Any suggestions?

**Comment by jameslaws** [comment]
In 3.0, this is already the case. In 2.9, no it's not possible. Won't be changing that in 2.9 since that will be sunset,

**Comment by JacobDB** [comment]
Hmm. Any way for me to install 3.0 then? I'm working on re-building my custom framework and this needs to be a part of it.

**Comment by jameslaws** [comment]
Absolutely! http://developer.ninjaforms.com/access-ninja-forms-three-today/

**Comment by JacobDB** [comment]
Fantastic, thank you!

**Comment by JacobDB** [comment]
@jameslaws okay, got v3 working, but the v3 documentation seems much more user oriented than developer. I can't find any info on filters, actions, templates, etc. Am I missing something?

**Comment by klhall1987** [comment]
@JacobDB I've linked all of our current Dev docs below. We are still working toward getting everything documented. If there is something that isn't documented or if you have any questions. You should consider joining our Dev slack group, that's where we have been handling most development based questions. I've also added a link where you can join the slack group below. 

Ninja Forms Three Dev Docs:
http://developer.ninjaforms.com/codex/

Ninja Forms Three Dev Slack Signup: 
http://developer.ninjaforms.com/slack/

**Comment by JacobDB** [comment]
Great, thanks so much :)
