### ISSUE TITLE
Creating new actions causing fields to be duplicated

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1571]
If a user adds a "Create Payment" action and assigns a "Payment Total" using the merge tag selector. Then publishes the form and reloads. All the fields on the form are duplicated. I've detailed the issue in a screencast below. 

Screencast:
https://goo.gl/4Xmktv

Replication steps(in 3.0): 
1. Create a new form
2. Add a total and submit field.
3. go to the "Emails and Actions" tab. 
4. Add a new collect payment action, and assign the total field to the "Payment Total" action setting. 
5. Click done on the collect payment action and publish the form. 
6. Refresh the page and all fields should be doubled.

**Comment by kjohnson** [comment]
Seems to duplicate any field type, not just totals.

**Comment by kjohnson** [comment]
Ok, so it looks like when the action is saved, the temporary fields are receiving values (as if the form was being saved). However, the temporary fields remain associated with the form (not just the persistent fields).

What we are seeing is both the temporary and saved versions of each field.

**Comment by kjohnson** [comment]
Seems to happen when any new actions is added.
