### ISSUE TITLE
Once a form is restricted it can never be unrestricted

### ISSUE THREAD

**Issue by fjarrett** [wpninjas/ninja-forms#1572]
We are running **Ninja Forms 2.9.55.1** and have discovered that the `logged_in` form meta value is not being saved to the database correctly.

If you turn the toggle ON, the `logged_in` value is set to `1`.
If you turn the toggle OFF, the `logged_in` value is set to `on`.

The result is that once you restrict a form to logged in users, it can never be _unrestricted_. You have to manually set the value in the database to `0` to fix it.

<img width="287" alt="screen shot 2016-08-03 at 3 48 36 pm" src="https://cloud.githubusercontent.com/assets/522158/17381518/ef90ed00-5991-11e6-9817-fe52ac84c369.png">
#1198 is possibly related.

**Comment by kjohnson** [comment]
Should be resolved by 73eef55.

@klhall1987 can you confirm?

**Comment by kstover** [comment]
Should be fixed.
