### ISSUE TITLE
Cannot drag fields from reservoir if the user clicks directly on the field 

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1576]
In 3.0 if a user clicks and drags a specific field in the reservoir to the form the field goes under the builder when it leaves the drawer. I've detailed this behavior in the screencast below. 

Screencast: 
https://goo.gl/c55cpA

Replication Steps(In 3.0):
1. Create a new form.
2. Open the fields drawer and add a few fields to the reservoir.
3. Click and drag one of the fields to the builder.

In order to get the fields from the reservoir you have to click a small distance way from the fields to drag them from the reservoir to the builder.

**Comment by kjohnson** [comment]
@klhall1987 The dragging from within the reservoir was intended for re-ordering, however, I can see the use case for dragging form the reservoir to the field list.
