### ISSUE TITLE
Column classes being trumped for @media queries

### ISSUE THREAD

**Issue by DustinWStout** [wpninjas/ninja-forms#1577]
Just noticed that Genesis theme column class elements are not obeying their @media queries because they are being trumped by CSS located in Ninja Forms' `/display-structure.css` file. So instead of columns being 100% width @media 1024px they are staying in their columns looking quite squished. (Pinging @jameslaws because @kjohnson said so.)

**Comment by jameslaws** [comment]
@DustinWStout Try the attached commit and let me know if that solves the issue. You may need to clear browser cache for the new CSS file.

**Comment by DustinWStout** [comment]
@jameslaws confirmed--that DOES fix it.
