### ISSUE TITLE
"You do not have sufficient permissions to access this page." on 3.0 Download Submissions

### ISSUE THREAD

**Issue by yeetien** [wpninjas/ninja-forms#1579]
I encountered "You do not have sufficient permissions to access this page." when accessing "admin.php?page=nf-processing&action=download_all_subs". 

Seems like 3.0 doesn't have add_submenu_page for "nf-processing"?

NF version: 2.9.55.1 (running 3.0)
WP version: 4.5.3

**Comment by kjohnson** [comment]
@yeetien this has been resolved in the public release of v3.
