### ISSUE TITLE
Creating an NF 3.0 field and section via 3rd party plugin [question]

### ISSUE THREAD

**Issue by ramiabraham** [wpninjas/ninja-forms#1581]
Just wondering if you guys happen to have an example handy of the ideal manner to register new form fields, as well as a new form field section?

Thanks!

**Comment by kjohnson** [comment]
@ramiabraham we have a [quick start](http://developer.ninjaforms.com/quick-start-quides/) video as well as some [documentation](http://developer.ninjaforms.com/codex/registering-fields/).

**Comment by ramiabraham** [comment]
This is great, thanks @kjohnson

**Comment by ramiabraham** [comment]
@kjohnson I noticed that, even with no customizations, the _Kozo_ template generator does not work. Are you able to replicate this?

**Comment by kjohnson** [comment]
@ramiabraham there may be a bug with the `instance` method not returning the instance.

**Comment by ramiabraham** [comment]
Thanks @kjohnson - we'll pause on extension compatibility for now. Please ping a brotha when we're ok to continue? 🎉

**Comment by kjohnson** [comment]
@ramiabraham until I can get to it, I would suggest just adding the line:

`return self::$instance`

to the end of the `instance()` method in the main class. That should get you started.

**Comment by kjohnson** [comment]
Reference: https://github.com/wpninjas/ninja-forms-kozo/issues/36
