### ISSUE TITLE
trim fields that validate as emails

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1582]
trim() fields that validate as emails in 3.0.  empty spaces currently cause emails to fail validation.

**Comment by kjohnson** [comment]
@wpnzach JS or PHP?

**Comment by kjohnson** [comment]
Could not reproduce in THREE.

**Comment by jameslaws** [comment]
I also cannot reproduce this. Closing and we can reopen if it resurfaces.
