### ISSUE TITLE
Dragging a new field to staging is broken

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#1583]
When you drag a field it get's covered by some layer. Perhaps related to a ps scrollbar issue?

https://www.dropbox.com/s/sv0azn8bcps8z80/2016-08-08_13-23-43.gif?dl=0

**Comment by jameslaws** [comment]
This is still broken, but in a different way. Simply try and drag a field to the staging area and you can see that you can't actually drop it there.

**Comment by kstover** [comment]
This was broken with the introduction of the hidden staging area. The drag:start of the field type draggable is too late to add the class. I'm not certain what the best solution is, but I think it will take a bit longer to solve this issue. Either we can hide the staging when not in use, or the dropping won't work. @jameslaws What do you think?

**Comment by jameslaws** [comment]
I guess at this point if you want to go in and comment the code that shows it on dragging. That seems like the only option right now.

**Comment by kstover** [comment]
Rolled back the change for now. The staging will be visible again.

**Comment by jameslaws** [comment]
?

It should be hidden unless there is something in it. The class that shows it on field being dragged needs to be removed.

**Comment by kstover** [comment]
Yeah. I just made that change.
