### ISSUE TITLE
"Download All Submissions" crashes

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#1598]
After clicking the "Download All Submissions" button you are redirected to a processing screen which crashed after the first step.

The developer console shows a JavaScript error suggesting a bad network response.

Upon further inspection, the step request throws a PHP warning.

With `WP_DEBUG` enabled the warning message is returned with the response which breaks.

> Warning: Missing argument 2 for wp_kses(), called in /wp-content/plugins/ninja-forms/deprecated/classes/download-all-subs.php on line 42 and defined in /wp-includes/kses.php on line 524

**Comment by kjohnson** [comment]
`wp_kses()` requires two (2) arguments with the second argument being the allowed HTML for scrubbing.

This was introduced during a security sweep.

See: https://github.com/wpninjas/ninja-forms/commit/463699a50835d5fbc25e426c51c7b265aeb30da3#diff-ec7f0fd1ad84c3e18af529fab4d68a15R42

**Comment by kjohnson** [comment]
We need to either specify allowed HTML or use an appropriate wrapper function, like `wp_kses_post()`. @kstover thoughts? This does touch a security issue, so I would like a second opinion.

**Comment by kstover** [comment]
We should swap it to wp_kses_post.

**Comment by kjohnson** [comment]
Ok, that was what I was thinking, being that this is a Custom Post Type. I will make the change and submit a Pull Request for v2.9.56
