### ISSUE TITLE
fields in the builder have lost their styling in the newest version of WordPress

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1615]
Fields in the builder in 2.9.x have lost some of their styling in the WordPress 4.6.1 update. I'm seeing this in both 2.9.56 and 2.9.56.1, I've not tested any further versions back yet. I've attached a screenshot to detail what I'm seeing. 

Screenshot: 
http://goo.gl/DnxLav

Replication Steps(in 2.9.x on WordPress 4.6.1):
1. Create a new form.
2. Add a first name field. 
3. Open the field to edit and the background styling of the field should be missing.

**Comment by saetia** [comment]
looks better

**Comment by kjohnson** [comment]
So, uh, its a feature... yeah, not a bug :P
