### ISSUE TITLE
Performance audit for 3.0

### ISSUE THREAD

**Issue by pippinsplugins** [wpninjas/ninja-forms#162]
I'm going to be digging through to see what kind of performance improvements can be made for 3.0 (perhaps some pre 3.0).

I'm opening this issue just as a place to log my findings.

The first thing I want to look at is conditionally loading as many files as possible.

**Comment by kstover** [comment]
Our roadmap for Ninja Forms has a large number of performance increases scheduled for later this year. Once those are done, I think we can revisit this. For now, I'm going to close the issue.
