### ISSUE TITLE
Make use of <form> tag for better semantics + accessibility

### ISSUE THREAD

**Issue by binarykitchen** [wpninjas/ninja-forms#1624]
While working on a plugin I realised that the ninja forms aren't surrounded with the `<form>` element at all. Sure it works that way with JavaScript but isn't recommended. For better accessibility and semantics I suggest to replace the top level `<div>` element with a `<form>` instead.

I could count plenty of reasons. Here some:
- Many assistive technologies or browser plugins can discover `<form>` elements and can implement special hooks to make them easier to use
- Autocompletion can be enabled and customized more efficiently within the browser
- Easier to serialize inputs with jQuery.serialize()

Thoughts? cc @kjohnson

**Comment by kjohnson** [comment]
While the `<form>` tag wasn't necessary for the Backbone Application implementation of a form, we have talked about adding the tag back in.

Will need to discuss this with @kstover .

**Comment by kstover** [comment]
We are still considering adding a <form> tag. Once we have a better idea of the repercussions, we will make a decision.

**Comment by binarykitchen** [comment]
@kstover really think a form tag is important - when you are discussing about it, please involve me. curious to read the arguments if someone is hesitant to include it.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
