### ISSUE TITLE
No matter what currency marker is selected, "$" always shows in form (3.0)

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1626]
No matter what currency marker is selected, "$" always shows in form

**Comment by wpnzach** [comment]
To clarify, this does not appear to affect processing (PayPal express passes currency set in PayPal settings).

The currency selection in Ninja Forms does not apply anywhere I can see.  It does not apply when setting up product fields, and it does not apply on the display of product or total fields.

**Comment by kjohnson** [comment]
Still an issue with the Number Mask settings not updating the currency symbol until blur.
