### ISSUE TITLE
Multiple Queries On Page Load

### ISSUE THREAD

**Issue by saulhudson** [wpninjas/ninja-forms#1627]
Hi

We are seeing a lot of queries (50+) on every page relating to ninja forms (Version 2.9.56.2 + Conditional Logic 1.4.0). These appear on every page regardless of whether there is a ninja form on the page or not.

Using Query Monitor I've traced the queries that ninja form is running and I can see that they are mostly running get_option() for very transient option. e.g.

SELECT option_value
FROM wp_options
WHERE option_name = '_transient_timeout_nf_form_117'
LIMIT 1

SELECT option_value
FROM wp_options
WHERE option_name = '_transient_nf_form_117'
LIMIT 1

etc ...

I've managed to fix the issue by commenting the hook in /plugins/ninja-forms/deprecated/includes/display/form/display-form.php line 100

```php
//add_action('wp_head', 'ninja_forms_page_append_check');
```

Everything seems to work fine. The forms still submit OK and the queries are gone from every page load but I'm not sure if I've broken anything else.

This feels like a bug as I'm sure we shouldn't running 50+ queries on every page load and it's in deprecated code so I would guess this has already been resolved? 

Can I leave the line commented out and when will the deprecated code be removed entirely?

**Comment by kjohnson** [comment]
@saulhudson this feature has been removed in v3.
