### ISSUE TITLE
Fields disappearing from builder after switching tabs. 

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1628]
In 3.0, if you switch from the form builder to any other tab then come back go back to the builder fields will no longer be present in the builder and there is a JS error in the console. I'm on the most current version of the master branch. I've detailed the behavior in the screenshots below. 

Screencast:
https://goo.gl/0fh46W

Screenshots: 
![screen shot 2016-08-22 at 10 23 15 am](https://cloud.githubusercontent.com/assets/9393977/17858151/8a671010-6852-11e6-8859-79ec1127a38b.png)

Replication Steps(in 3.0):
1. Create a new form. 
2. Add a first name and submit field. 
3. Switch to the "Emails and Actions" tab. 
4. Switch back to the "Form Fields" tab, and the fields that were on the form should no longer be present.

**Comment by jameslaws** [comment]
It looks like this was introduced by this commit: https://github.com/wpninjas/ninja-forms/commit/afce224349e8b7bb6d43905c6ec409d9fecab962
