### ISSUE TITLE
Need ability to hook in async custom fn before submission

### ISSUE THREAD

**Issue by binarykitchen** [wpninjas/ninja-forms#1633]
While working on a plugin, I hit a snag which gives me headaches: the ability to run some async code before submission.

With the videomail-client plugin I want to run some custom AJAX stuff upon submit button click first before doing the normal submission through the ninja form code.

In https://github.com/kjohnson/ninja-forms-videomail/blob/master/assets/js/videomail.js I tried to override the custom behaviour of the submit controller in https://github.com/wpninjas/ninja-forms/blob/master/assets/js/front-end/controllers/submit.js but I do not have a reference to that controller.

How can I change

```
registerSubmitHandler: function( formModel ) {
    nfRadio.channel( 'form-' + formModel.get( 'id' ) ).reply( 'submit', this.submit );
},
```

into something like

```
registerSubmitHandler: function( formModel ) {
    var customAsyncFunction = function(cb) {
        sleep(1000)
        cb()
    }

    customAsyncFunction(function() {
        nfRadio.channel( 'form-' + formModel.get( 'id' ) ).reply( 'submit', this.submit );        
    })
},
```

?

I think I can try a PR unless someone else has a better idea?

cc @kjohnson

**Comment by kjohnson** [comment]
@binarykitchen I have an example of stopping a submission, running code, then re-starting the submission.

**Comment by kjohnson** [comment]
@binarykitchen https://gist.github.com/kjohnson/e6dcd0ba5b3f56217144b61cc51c0e5f

**Comment by kjohnson** [comment]
Adding to the docs: http://developer.ninjaforms.com/codex/startstop-submission/

**Comment by binarykitchen** [comment]
ah, wonderful @kjohnson, many thanks - will check out tonight

**Comment by binarykitchen** [comment]
@kjohnson a couple of questions:

* what's the difference between `Backbone.Radio.channel(...)` and `nfRadio.channel(...)`?
* probably a bug? `this.formModel` is undefined at https://gist.github.com/kjohnson/e6dcd0ba5b3f56217144b61cc51c0e5f#file-pause-submission-js-L23

**Comment by kjohnson** [comment]
`nfRadio` is a reference to `Backbone.Radio` inside of Ninja Forms core, which is not available within addons, unless specifically specified.

**Comment by binarykitchen** [comment]
ok, all good - thanks for your help
