### ISSUE TITLE
Do not select by default for radio lists

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1637]
In 2.9, if a user does not select a prechecked item in a radio list, the form output does not have a preselected item.  This is incredibly useful for users especially with required fields.

In 3.0, this behavior is not present and the first item in the list is selected by default even if the user wishes to leave it blank.

**Comment by kstover** [comment]
This was taken care of a bit ago.

**Comment by wpnzach** [comment]
This is not working in the current version, 3.0.2.  Reopening.

**Comment by kstover** [comment]
So, I think that this is also causing a return of the "must have a default selected" bug when forms with lists are converted.
