### ISSUE TITLE
cURL request to ninja_forms_ajax_submit

### ISSUE THREAD

**Issue by razcakappa** [wpninjas/ninja-forms#1638]
Normal ajax form sending request is something like this for a form.

`http://yourdomain/wp-admin/admin-ajax.php?action=ninja_forms_ajax_submit`

This request works fine on the website form submissions and I can get a proper JASON reply. However when I'm testing the same request with curl with same parameters and same headers and with same POST method, the reply was always 0. Which means WP not firing the `wp_ajax_nopriv_ninja_forms_ajax_submit` action and it default goes to admin-ajax.php's bottom `die('0');`

The strange, mysterious behavior is, after doing some debug work and reset the `wp-content/plugins/ninja-forms/deprecated/includes/display/form/display-form.php` file. Some times the curl requests are getting proper JASON reply.

Do anyone have idea of whats the inaccurate here? Is this something WP caching to be blamed of?

**Comment by kjohnson** [comment]
@razcakappa `admin-ajax.php` returns either `-1` or `0` if there is an error. In this case, `0` usually means that the registered WP AJAX action was not found.

However, Admin AJAX is not intended to respond to a cURL request, but rather for on site functionality.

What are you wanting to accomplish?

Reference: https://codex.wordpress.org/AJAX_in_Plugins#Error_Return_Values
