### ISSUE TITLE
Bug: upon successful POST, form is initialized over again

### ISSUE THREAD

**Issue by binarykitchen** [wpninjas/ninja-forms#1639]
Upon form submit, when POST was successful, this code is executed

```
nfRadio.channel( 'forms' ).trigger( 'submit:response', response, textStatus, jqXHR, formModel.get( 'id' ) );
```

and that will trigger this in coreSubmitResponse:

```
formModel.get( 'fields' ).reset( formModel.get( 'loadedFields' ) );
```

which will trigger this in the fieldModel:

```
nfRadio.channel( this.get( 'type' ) ).trigger( 'init:model', this );
```

I think it does not make sense. Upon submit the user (here the developer) expects something else rather than the same form I think?

cc @kjohnson

**Comment by kjohnson** [comment]
@binarykitchen there is a form setting in the Advanced domain of the form builder, under Display Settings, that allows you to clear/hide the form after submission.

**Comment by binarykitchen** [comment]
ah, thx
