### ISSUE TITLE
NF_AddonChecker method forcing deactivation of NF 3 add-on

### ISSUE THREAD

**Issue by ramiabraham** [wpninjas/ninja-forms#1640]
We're working on supporting NF 3 in one of our AffiliateWP add-ons, and noticed that the `NF_AddonChecker::check_plugins()` method is now forcing deactivation of this add-on.

In [this method](https://github.com/wpninjas/ninja-forms/blob/master/lib/NF_AddonChecker.php), it appears that _any_ addon will be deactivated, since the `NF_AddonChecker` class is called globally in the main Ninja Forms plugin file when NF 3 or greater is found:

https://github.com/wpninjas/ninja-forms/blob/master/ninja-forms.php#L44

```php
public function check_plugins()
    {
        if ( ! function_exists( 'get_plugins' ) ) {

            require_once ABSPATH . 'wp-admin/includes/plugin.php';

        }

        $plugins = get_plugins();

        foreach( $plugins as $plugin => $data ){

            if( 'ninja-forms/ninja-forms.php' != $plugin && 0 === strpos( $plugin, 'ninja-forms' ) && version_compare( $data[ 'Version' ], '3', '<' ) ){

                if( ! is_plugin_active( $plugin ) ) continue;

                deactivate_plugins($plugin);

                wp_redirect( admin_url( 'plugins.php?nf-deactivated=' . $plugin ) ); exit;
            }
        }
    }
```

Is this file planned to be removed or updated to allow for Ninja Forms extensions to be created?

Is there anything I can do to assist in resolving this?

Worth noting that merely commenting out the `new NF_AddonChecker` instance [here](https://github.com/wpninjas/ninja-forms/blob/master/lib/NF_AddonChecker.php#L49) completely resolves the issue.

Thanks!

**Comment by kjohnson** [comment]
@ramiabraham for compatibility reasons, with the Ninja Forms THREE codebase active we disable an plugins prefixed with `ninja-forms-` if the plugin version is less than 3. The WordPress.org repository does not allow for trademarks to prefix plugins names, so we haven't run into any false positives yet.

What is the add-on of yours that is being deactivated? Is it prefixed with `ninja-forms`?

**Comment by ramiabraham** [comment]
Thanks @kjohnson. The plugin slug is `affiliatewp-affiliate-forms-ninja-forms`.

**Comment by ramiabraham** [comment]
Added a small pr on this @kjohnson :)

**Comment by kstover** [comment]
I think that this issue is closed by merging the PR?

**Comment by ramiabraham** [comment]
Working here! Thanks @kstover.
