### ISSUE TITLE
Maybe update Software Licensing

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#1646]
https://easydigitaldownloads.com/development/2016/08/28/software-licensing-theme-plugin-examples-updated-to-fix-php-compatibility-bug/?utm_source=Facebook&utm_medium=social&utm_term=software-licensing-theme-plugin-examples-updated-to-fix-php-compatibility-bug&utm_content=0&utm_campaign=PostPromoterPro

**Comment by kstover** [comment]
Has this been updated? @kjohnson

**Comment by kstover** [comment]
Updated in recent version.
