### ISSUE TITLE
Session regenerated on every page - version 2.9.56.2

### ISSUE THREAD

**Issue by ericnicolaas** [wpninjas/ninja-forms#1649]
This has been an issue before with the 2.9 branch. See #1236, #954, #1502. It's an issue again, with version 2.9.56.2 (not using v3).

I was able to check this with a clean install of WP with no other plugins installed and the default theme.

**Comment by kjohnson** [comment]
Hm... thought we had taken care of that. I'll take another look.

**Comment by kstover** [comment]
This should be taken care of in version 3.0.x.

**Comment by ericnicolaas** [comment]
@kstover Nope, I can still reproduce this. Try adding this to a site running NF: 

```
add_action( 'init', function() {
    if ( class_exists('WP_Session') ) {
        echo WP_Session::get_instance()->session_id;
    }    
});
```

**Comment by ericnicolaas** [comment]
I'm on `3.0.5`

**Comment by ericnicolaas** [comment]
Here's the problem: 

<img width="520" alt="screenshot_2016-09-15_12_53_58" src="https://cloud.githubusercontent.com/assets/676582/18537309/bb4ac15a-7b43-11e6-917c-50abb9e42b35.png">

What is the reasoning behind _not_ setting the cookie? 

You're using `WP_Session`, which is a library that many other plugins use. Your version of `WP_Session` will break any other plugin that relies on `WP_Session`. We're hitting this problem in Charitable because we store a key in the user's session after they make a donation; this provides them with access to their donation receipt without needing to be logged in. But this is broken for anyone who uses Ninja Forms as well as Charitable.
