### ISSUE TITLE
THREE IE 11 Error : Object doesn't support property or method 'isInteger'.

### ISSUE THREAD

**Issue by devinbalram** [wpninjas/ninja-forms#1653]
https://wpninjas.desk.com/web/agent/case/21817

User reported issues of her form not showing up on IE 11 on Three. Form functioned correctly on Chrome & Firefox. 

Asked user to test with a default WordPress theme & other plugins disabled. Issue persisted. 

Asked user for export of the form to test locally & recreated the issue on my environment. The form shows on a default WordPress theme & with other plugins disabled on Chrome & Firefox, on IE 11 however, it doesn't show & throws this error in the console : https://goo.gl/49FZOd

**Comment by kjohnson** [comment]
Looks like `isInteger` is an ES6 feature that is not supported by IE11. [1][2]

--
[1] [isInteger Browser Compatibility](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger#Browser_compatibility)
[2] [isInteger Polyfill](http://stackoverflow.com/a/31720368)

**Comment by kjohnson** [comment]
@devinbalram Can you send the customer a copy of the [issue#1653 branch](https://github.com/wpninjas/ninja-forms/tree/issue%231653)?

**Comment by devinbalram** [comment]
@kjohnson I've just sent the copy to the user. I'll update when I hear back.

**Comment by devinbalram** [comment]
Uploaded the copy of issue#1653 branch & the forms that previously didn't work on IE 11 are now appearing as expected on the front end of her site.
