### ISSUE TITLE
Adding a credit card field crashes the builder

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#1665]
When you add a credit card field by dragging it in you see this: https://www.dropbox.com/s/8jfsx4ina6zt8xo/Screenshot%202016-09-02%2021.27.44.png?dl=0

If you click to add it adds the fields, but then the form get's reloaded after publish there is nothing present in the form. They also do not display on the front-end.

This is the error in the console: ReferenceError: Can't find variable: id

Reproduction Steps:

1. Drag or Click to add the credit card fields. 
2. Publish your form.
3. Reload the form.

**Comment by kjohnson** [comment]
@jameslaws could not replicate. Are you using any add-ons, or just Ninja Forms?

**Comment by jameslaws** [comment]
Layout and Multi-Part

**Comment by jameslaws** [comment]
It doesn't appear to happen with core alone.

**Comment by jameslaws** [comment]
After speaking to Kevin, he thinks this is something to do with what he's doing so I've reassigned it to him.

**Comment by kstover** [comment]
Closed in a commit to Multi-Part Forms.
