### ISSUE TITLE
3.0 Launch List

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#1671]
Here is a checklist of all the things we need to be working for launch on Tuesday.

- [x] First time fresh install of 3.0
- [x] Rollback from a 3.0 only install
- [x] Full conversion with 4 main add-ons from 2.9 to 3.0
- [x] Rollback from a 3.0 conversion to 2.9
- [x] Builder Pro with included add-ons activated
- [x] Builder Pro with included add-ons deactivated 
- [x] Translations
- [x] List of deprecated functions, actions, filters

**Comment by kjohnson** [comment]
- [ ] First time fresh install of 3.0
- [ ] Rollback from a 3.0 only install
- [ ] Full conversion with 4 main add-ons from 2.9 to 3.0
- [ ] Rollback from a 3.0 conversion to 2.9
- [ ] Builder Pro with included add-ons activated
- [ ] Builder Pro with included add-ons deactivated 
- [ ] Translations
- [ ] List of deprecated functions, actions, filters

**Comment by klhall1987** [comment]
I'll work through testing through this list first thing in the morning.

**Comment by kstover** [comment]
I'm working on the conversion between MP, Layouts, and Vanilla. I'm going to finish before I go to bed.

**Comment by klhall1987** [comment]
[] First time fresh install of 3.0
[] Rollback from a 3.0 only install
[] Full conversion with 4 main add-ons from 2.9 to 3.0
[] Rollback from a 3.0 conversion to 2.9
[] Builder Pro with included add-ons activated
[] Builder Pro with included add-ons deactivated
[] Translations
[] List of deprecated functions, actions, filters
