### ISSUE TITLE
In 3.0 sub menus an pages are bleeding into a single page

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#1672]
https://www.dropbox.com/s/skskcw4ng2htt9a/Screenshot%202016-09-04%2000.27.15.png?dl=0

From import / export to Add-ons sub menu pages they there seems to be an issue that is causing them all to be a single settings page regardless of which one you click on.

**Comment by kjohnson** [comment]
Ok, I think I know what is causing it.
