### ISSUE TITLE
Max attribute of number element not working in builder

### ISSUE THREAD

**Issue by polevaultweb** [wpninjas/ninja-forms#1679]
Have tried setting properties of 'max', 'max_number' etc.

**Comment by jameslaws** [comment]
@polevaultweb Is this has a setting attribute or the number field?

**Comment by polevaultweb** [comment]
This is a field setting of type 'number' for the builder in FU https://github.com/wpninjas/ninja-forms-file-uploads/blob/develop/includes/config/field-settings.php#L53

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
