### ISSUE TITLE
Actions no longer stay active

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1680]
This is a two part issue. I can break it up in to different parts if need be, but I think it's all stemming from the same 

Default actions are no longer enabled when a new form/template form is created. if you enable the action then change domains then, the action is revert back to being toggled off. 

If you enable an action then edit, the action as soon as the drawer opens the action is toggled off again. I attached a screencast below that details this behavior.

Screencast:
https://goo.gl/HsmMKW

Replication steps(in 3.0): 
1. Create a new form. 
2. Go to the emails and actions tab.
3. Enable an action. 
4. Go to the builder. 
5. Go back to emails and actions. The action you will be disabled.

**Comment by klhall1987** [comment]
The undo manger drawer no longer works either. When you try to open the drawer you get a JS error in the console. I've detailed the error in a screenshot below. 

Screenshot: 
![screen shot 2016-09-05 at 2 27 55 pm](https://cloud.githubusercontent.com/assets/9393977/18255211/0fa3c6ce-7375-11e6-905e-9f5de0556397.png)

Replication Steps: 
1. Create a new form. 
2. Add first name field. 
3. Try to open the undo manager you should get the JS error above in your console.

**Comment by kjohnson** [comment]
Fixed: I was using the evaluation tags, because of the `if()`, so it wasn’t actually outputting the `checked` attribute in the view.
