### ISSUE TITLE
Responsiveness of builder

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#1681]
Hey

I am looking at the responsiveness of the form. Using newest version of Chrome on a Macbook Pro 15.4" screen.

![screen shot 2016-09-05 at 20 46 20](https://cloud.githubusercontent.com/assets/5323259/18255431/d4e9341c-73a9-11e6-97a8-54ca551e6dac.png)

Then pushing the browser a little further in (really not noticeable) the words Preview Form goes away to leave the eye.

![screen shot 2016-09-05 at 20 46 44](https://cloud.githubusercontent.com/assets/5323259/18255447/f8b5c162-73a9-11e6-886a-6a6412919591.png)

But there is still a lot of space between the eye and the Publish button. Meaning there is still space for keeping the words Preview Form in place.

I will continue to look at other pages.

**Comment by kjohnson** [comment]
There are also translations to account for:

<img width="1037" alt="screenshot 2016-09-06 00 51 04" src="https://cloud.githubusercontent.com/assets/10858303/18262051/0966f64e-73cc-11e6-8acb-a4e561c7d03b.png">

**Comment by paaljoachim** [comment]
Good point!
