### ISSUE TITLE
Calculation drawer not opening after upgrade, if form has Calculations

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1683]
Starting in 2.9.x, If a form has calculations and is upgraded to three. Once you're in three you cannot will get a JS error when you try to open the calculations settings drawer and the settings drawer will not open.

screenshot: 
![screen shot 2016-09-05 at 3 06 06 pm](https://cloud.githubusercontent.com/assets/9393977/18255815/6795cb92-737b-11e6-8f4f-5da7e325d1e6.png)

Form Export: 
[Calctest---09-05-2016-.nff.zip](https://github.com/wpninjas/ninja-forms/files/455534/Calctest---09-05-2016-.nff.zip)

Replication Steps(starting in 2.9.x):
1. import the form that is attached. 
2. upgrade to 3.0. 
3. Edit the form, and go to the advanced settings tab. 
4. Try to open the calculation settings drawer.

**Comment by kstover** [comment]
I can confirm that this has been fixed in 4954a9efe46e8c286e566f1f794843af6745514c.
