### ISSUE TITLE
Undo icon?

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#1684]
Removing a field is very simple and there is no confirmation. If one happens to click the trash icon under the edit button a field is removed. It would be good to have a simple way to do undoes. One way to get it back is refreshing the page. Another can be something like this:
To add a half circle arrow that shows up next to Advanced.

(I noticed the undo icon show up when closing the sidebar panel.)

Mockup suggestion:

![undo-ninja-forms-3](https://cloud.githubusercontent.com/assets/5323259/18255839/f773903c-73ad-11e6-8a7b-47fa12ded8ef.jpg)

**Comment by jameslaws** [comment]
There is a simple way to undo: 

https://www.dropbox.com/s/hke0e8ck2xulzds/2016-09-05_15-20-05.png?dl=0

https://www.dropbox.com/s/5b9euwgcv7t4z5d/2016-09-05_15-20-50.png?dl=0
