### ISSUE TITLE
Previewing form while edit field sidebar is open?

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#1685]
The user edits the fields testing various things...

The sidebar edit field is open. The user makes a change and wants to see what the change looks like. Looks to the left and there is no preview form link. The user clicks Done and the sidebar panel closes and the Preview form link is once again visible.

When the sidebar panel is open it would be helpful to have the eye show next to Advanced so one does not need to close the sidebar panel to click the button to preview the form.

Like so:

![preview-form-ninjaforms3](https://cloud.githubusercontent.com/assets/5323259/18256062/9534e8fa-73b0-11e6-9426-10f0efe8eb58.jpg)

**Comment by jameslaws** [comment]
The problems is that until that particular drawer is closed or the user moves to a new context, the changes they made are now viewable as they have not yet been sent to the preview model. We opted to simply not show the preview link in these cases so the user does not wonder why they are not seeing their changes reflected. It's assumed they are not done and ready to preview if they have not yet clicked "done."

**Comment by paaljoachim** [comment]
Lets say I already have an open preview tab. Jumping between editing the form and seeing the preview. 

Default:  One makes an adjustment in the right sidebar edit panel. Clicks Done (save) and the right sidebar panel closes. One goes to the preview tab, refreshes and sees the change.

Option: One makes an adjustment in the right sidebar edit panel. Clicks outside of the panel (left area etc) and changes are saved. The right sidebar panel is still open. One goes to the preview tab, refreshes and sees the change. Decides to go back to the edit tab to continue the adjustment of the same field still having the right sidebar panel open.

Or so is my thought on this, but it might be a better tightness if what I suggest is just not allowed.
