### ISSUE TITLE
Turn off attach CSV in the "Contact Me" template

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1688]
Currently in the Contact Me template the attach CSV setting is turned on in the Email Notification email action. We need to disable this before launch. 

Screenshot:
http://goo.gl/nwcbFf

**Comment by jameslaws** [comment]
Can we also confirm that this setting is being honored when emails are sent.

**Comment by klhall1987** [comment]
Yea, let me test that really quick.

**Comment by klhall1987** [comment]
The setting is being honored.
