### ISSUE TITLE
Calc conversions are getting a leading plus sign

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1690]
When converting calculations I'm seeing a leading plus sign before the calculations in 3.0. I know we used to have a 0 + before the calcs. This doesn't affect the calculation but does generate a PHP notice in error log. 

Replication steps(in 2.9.x):
1. Create a form. 
2. Add two number fields, a calculation field, and submit.
3. Make the two numbers add together using the calc field there is various ways to do this so have fun doing.
4. Save the form.
5. Upgrade to 3.0.
6. Check the calculations in you advanced tab in your form.

**Comment by jameslaws** [comment]
Is this still an issue?

**Comment by kstover** [comment]
Appears to be fixed for me locally in the current version. Closing. If this comes back up again, we can re-open.
