### ISSUE TITLE
Unknown field types are causing forms not to process in 3.0

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1691]
If a form has artifact fields the form when fail to submit and throw a PHP fatal error in the error log. I've added a form import to help illustrate the issue. 

Form Import: 
[nf_form_09-06-2016.nff.zip](https://github.com/wpninjas/ninja-forms/files/455989/nf_form_09-06-2016.nff.zip)

Replication steps(import the form above with only ninja forms core active):
1. Import the form above. 
2. Preview the form on the front end and try to submit the form.

**Comment by kjohnson** [comment]
@kstover @klhall1987 I'm not seeing the form load on the front end, unless I create add part in the builder.

**Comment by klhall1987** [comment]
Do you have all your add-ons disabled? Multi-part and layouts won't work with the uninterpreted data.

**Comment by kstover** [comment]
I don't think that this is a blocker. Just something to keep in mind as we go forward. Maybe we could have a meeting about how we handle unknown fields and such as a general approach.

**Comment by wpnzach** [comment]
To clarify, this is not only on imported forms.  This occurs with new forms on 3.0 when the plugin is deactivated.

For example, adding a File Upload field to a form means the form will break if "File Uploads" is deactivated.

**Comment by kstover** [comment]
We've fixed this by adding an "unknown" field type in a recent version.
