### ISSUE TITLE
Input Mask reverts to None -bug?-

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#1692]
Hey

I am going through the various options for a Single Line text field and am testing out Input Mask. Changing this to date or US Phone. I have to select it a few times before the option stays in place. I click Done then click the field to go back into edit field mode. Input Mask has reverted to None.
(Btw selecting Custom and the Custom Mask opens to the right of it. The Custom Mask stays in place but once again the Input Mask reverts to None.)

![screen shot 2016-09-06 at 11 02 43](https://cloud.githubusercontent.com/assets/5323259/18267873/74d09566-7421-11e6-8ac0-25d3e5ae3bf6.png)

**Comment by klhall1987** [comment]
Issue confirmed passing to @kjohnson.
