### ISSUE TITLE
Help text icon

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#1693]
Hey

I am taking a closer look at the Help Text icon. 

![screen shot 2016-09-06 at 11 12 19](https://cloud.githubusercontent.com/assets/5323259/18268130/cb73dbfc-7422-11e6-894e-0a2a54168b91.png)

A little black circle with a i in it.
This is probably a tutorial for another time, but it would be great to be able to change the icon or perhaps have the i a little more clear and white.
![help-text-icon](https://cloud.githubusercontent.com/assets/5323259/18268194/10b90570-7423-11e6-8435-5bc285e41f12.jpg)

**Comment by kstover** [comment]
Should be a lot clearer in the current version, since we changed the icon set we use.
