### ISSUE TITLE
Help text grid -not working-

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#1694]
I am testing the grid inside the Help text area.
As I test it in Chrome it is not working.

![screen shot 2016-09-06 at 11 16 07](https://cloud.githubusercontent.com/assets/5323259/18268294/6925f628-7423-11e6-8b87-2d9cfcbbb373.png)

The preview:

![screen shot 2016-09-06 at 11 16 26](https://cloud.githubusercontent.com/assets/5323259/18268305/724c34ba-7423-11e6-91a9-49aa46942e80.png)

My suggestion would be to remove the grid from the Help Text and Description and add it to a 3.1 release.

**Comment by kstover** [comment]
I agree that we should remove the setting until we get it working properly.

**Comment by kstover** [comment]
This works for me in the current version in Chrome. If it's still an issue, we can re-open.
