### ISSUE TITLE
Aligning the Description text.

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#1695]
It would be good to also have a simple way to align the Description area to top, right, bottom or left of the specific field. A setting inside the description toolbar/menubar area.

**Comment by kstover** [comment]
@jameslaws Can you comment on this? We had a discussion about it, but I don't remember where we landed.

**Comment by jameslaws** [comment]
@paaljoachim This isn't something we are going to add to core. We offered it in 2.9.x and it was rarely used and it's extremely complicated to pull off with all of the other possible label positions. We've decided to go with an opinionated approach and if a user needs more than that they would need to write their own CSS or use something like Layout & Styles to pull off similar results.

**Comment by paaljoachim** [comment]
Ok. I am thinking you guys could always just add an example to your docs page for anyone who needs to make the adjustment. I will have to make a note out of and perhaps add it to a Ninja Forms tricks and tips tutorial.
