### ISSUE TITLE
Email Notification - Attach CSV - please have it default to off.

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#1696]
Hey

It would be nice to have Email Notification - Attach CSV default to **off**.
As I believe most often this will be turned off. On occasion whens someone needs the CSV then they can go in and turn it on, and make the choice to have it included.

**Comment by kjohnson** [comment]
Done.

**Comment by paaljoachim** [comment]
Awesome..:)
Thanks Kyle!
