### ISSUE TITLE
Redefining the Add New Form screen

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#1697]
I made an alternative Add New Form screen.

The original:
![add-new-form-ninja-forms-3](https://cloud.githubusercontent.com/assets/5323259/18273051/aca9d974-743b-11e6-9f9a-220a242a381c.png)

A mockup:
![2add-new-form-ninja-forms3](https://cloud.githubusercontent.com/assets/5323259/18273690/dd3ed366-743e-11e6-8d16-c61ed5ea45ec.jpg)

**Comment by jameslaws** [comment]
Thanks. Not sure that something we will do because I don't like moving the add-new button to a new location in different contexts. We want to build expectations so users are trained to know where things will always be. 

I'll look over the other stuff later.

**Comment by paaljoachim** [comment]
An adjustment.

![3add-new-form-ninja-forms3](https://cloud.githubusercontent.com/assets/5323259/18273757/4565f51e-743f-11e6-99dd-25351e7e40bd.jpg)

**Comment by kstover** [comment]
Adding this to our internal tracker. Will revisit once I get our GitHub issues cleaned up.
