### ISSUE TITLE
Contact Me template is not loading

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1698]
If you try to use the "Contact Me" template you get redirected to a page that says, "no error". I'm not seeing any JS errors or PHP errors in the error log. 

Replication Steps(in 3.0):
1. Create a new form. 
2. Use the "Contact Me" template.

**Comment by kjohnson** [comment]
@klhall1987 Do you mean the "Contact Us" template? If so, I cannot replicate.
