### ISSUE TITLE
Max width and truncate merge tag selector

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#1699]
The merge tag selector seems to scale, infinitely, to match the longest field label. We probably need to determine a max-width and truncate.

![screenshot 2016-09-06 17 06 47](https://cloud.githubusercontent.com/assets/10858303/18291139/6926464c-7454-11e6-993e-9992633f028f.png)

**Comment by kstover** [comment]
Closing in favour of merge tag re-work currently in process.
