### ISSUE TITLE
"State" fields are not converting to Ninja Forms 3.0

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1702]
Give JS error: https://goo.gl/pjAn7U

fieldSelect.js:41 Uncaught TypeError: Cannot read property 'value' of undefined

Happens with a state field in a 2.x form after conversion to 3.0.  Form will not display on the front end.

**Comment by kjohnson** [comment]
@wpnzach could not replicate.

Can you give more details about the State Field configuration?
