### ISSUE TITLE
Form title not appended to 3.0 exports as in 2.9

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1703]
In 2.9, the form name was appended to form export files.

In 3.0, only the date seems to be used, making it difficult to determine which form is which when exporting several files at once.

**Comment by kstover** [comment]
@klhall1987 I think you can get this one sorted.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.

**Comment by wpnzach** [comment]
reopening
