### ISSUE TITLE
Empty Step value not being ignored in number fields

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#1704]
In the number field, the step value setting should be ignored if empty, otherwise it shows an error.

**Comment by kjohnson** [comment]
<img width="334" alt="screenshot 2016-09-06 19 31 59" src="https://cloud.githubusercontent.com/assets/10858303/18294619/9a9f8da0-7468-11e6-94d9-4036175ab76b.png">

Ref: https://wpninjas.desk.com/web/agent/case/22215

**Comment by kstover** [comment]
Closing because I can't replicate. If this is reported again, we can re-open.
