### ISSUE TITLE
JS Console Errors when Loading Quote Request Template

### ISSUE THREAD

**Issue by iansvo** [wpninjas/ninja-forms#1705]
I just updated to 3 from a previous installation and I'm seeing what appears to be a bug when I choose the "Quote Request Template"

**Issue Description**

When choosing the Quote Request template, the page loads to a white screen after choosing the template. I then see a JS console error:

`rowCollection.js:16 Uncaught TypeError: this.collection.on is not a function - rowCollection.js`

**Replication Steps**
1. Login to WP and Add a New Form
2. Choose Quote Request Template from the list of template choices
3. Observe behavior on the next screen
### Environment

Home URL:                https://titanhost.io
Site URL:                https://titanhost.io
Ninja Forms Version:     3.0.0
WP Version:              4.6
WP Multisite Enabled:    No
Web Server Info:         Apache
PHP Version:             5.6.24
MySQL Version:           5.5.5
PHP Locale:              negative_sign:
WP Memory Limit:         40
WP Debug Mode:           No
WP Language:             Default
WP Max Upload Size:      8 MB
PHP Post Max Size:       8
Max Input Nesting Level: 64
PHP Time Limit:          30
PHP Max Input Vars:      1000
SUHOSIN Installed:       No
Server IP Address:       158.69.67.163
Host Name:               atlas
SMTP:                    localhost
smtp_port:               25
Default Timezone:        America/New_York
### Plugins

Installed Plugins:       Shield by iControlWP version 5.5.0
                         Advanced Custom Fields PRO by Elliot Condon version 5.4.2
                         All In One SEO Pack by Michael Torbert version 2.3.9.1
                         GreensockJudo by Ian Svoboda version 1.0.0
                         Imagify by WP Media version 1.5.8
                         Ninja Forms - Builder Pro by The WP Ninjas version 3.0.0
                         Ninja Forms by The WP Ninjas version 3.0
                         UpdraftPlus - Backup/Restore by UpdraftPlus.Com
                         DavidAnderson version 2.12.20.0
                         iControlWP by iControlWP version 2.13.0
                         WP Maintenance Mode by Designmodo version 2.0.7
                         WP Rocket by WP Rocket version 2.8.11

Please advise if any additional information is needed.

**Comment by kstover** [comment]
Is this still an issue in 3.0.x and the newest Builder Pro?

**Comment by kstover** [comment]
I can't replicate this with the individual add-ons. Closing because we've deprecated Builder Pro.
