### ISSUE TITLE
No "User Name" merge tag

### ISSUE THREAD

**Issue by pippinsplugins** [wpninjas/ninja-forms#1709]
The `User` merge tags contain almost all necessary user fields, but it's missing a really important one: `User Name`.

Could a tag be added to display the `user_login` value for the current user please?

**Comment by jameslaws** [comment]
@pippinsplugins Do you see these options under the User merge tags? https://www.dropbox.com/s/iibrmmg750bgxta/2016-09-07_12-28-13.png?dl=0

We have First, Last, and Display Name.

Is there a specific location that's possibly missing these options?

**Comment by pippinsplugins** [comment]
Yes I see those but those do not include a tag for the `user_login` property of `WP_User`.

It'd be great to have a tag to show the user's login name.

**Comment by jameslaws** [comment]
Ahhh. The username. I get you now. I'lll get this added.

**Comment by pippinsplugins** [comment]
Awesome, thanks!

**Comment by kstover** [comment]
@pippinsplugins We have this in a PR; Kenny is testing.

**Comment by mstearne** [comment]
Was this ever merged?  I am using 3.0.19 and don't see an option for user:login.
