### ISSUE TITLE
Undefined Settings Index

### ISSUE THREAD

**Issue by BFTrick** [wpninjas/ninja-forms#171]
I updated my Ninja Forms dev environment today and got this error

> Notice: Undefined index: timed_submit_error in /ninja-forms/wp-content/plugins/ninja-forms/includes/ninja-settings.php on line 14

> Notice: Undefined index: javascript_error in /ninja-forms/wp-content/plugins/ninja-forms/includes/ninja-settings.php on line 15

I believe this happens because we've added these two settings *after* I activated Ninja Forms so the new settings being set in the activation function in [activation.php](https://github.com/wpninjas/ninja-forms/blob/6ee4b26631daf20b27ed991f0ef3577152c8125d/includes/activation.php#L182-L183) never happens. I'm basically stuck with my existing settings.

A couple of solutions here.

1. **Reactivate the plugin**. Lame - boring - and not every user will know to do this.
1. **Update the database**. Do some fancy database work that automatically saves new settings
1. **Use getter functions**. The getter functions can check for existing settings, if they don't exist then use the default, then run that value through a filter and return it.

I prefer option 3.

**Comment by kstover** [comment]
This should be fixed in the latest version.
