### ISSUE TITLE
PHP warning on debug

### ISSUE THREAD

**Issue by davettt** [wpninjas/ninja-forms#1713]
Testing upgrade to Ninja Forms 3 on a local installation first, getting a few PHP notices including:
-  undefined index: honeypot
- PHP warning: array_merge() Argument#1 is not an array in xxx/wp-content/plugins/ninja-forms/includes/Admin/Menus/Forms.php on line 306

**Comment by helgatheviking** [comment]
Also seeing the following warning on plugin update:

>Warning: Invalid argument supplied for foreach() in /home/ubuntu/workspace/wp-content/plugins/ninja-forms/includes/Database/Models/Form.php on line 262 Call Stack: 48.8665 12070216 1. shutdown_action_hook() /home/ubuntu/workspace/wp-includes/load.php:0 48.8665 12070264 2. do_action() /home/ubuntu/workspace/wp-includes/load.php:671 48.8666 12071816 3. call_user_func_array:{/home/ubuntu/workspace/wp-includes/plugin.php:524}() /home/ubuntu/workspace/wp-includes/plugin.php:524 48.8666 12071888 4. _nf_removed_hooks() /home/ubuntu/workspace/wp-includes/plugin.php:524 48.8728 12507976 5. apply_filters() /home/ubuntu/workspace/wp-content/plugins/ninja-forms/includes/deprecated.php:254 48.8728 12509368 6. call_user_func_array:{/home/ubuntu/workspace/wp-includes/plugin.php:235}() /home/ubuntu/workspace/wp-includes/plugin.php:235 48.8728 12509488 7. NF_Database_Models_Form->import_form_backwards_compatibility() /home/ubuntu/workspace/wp-includes/plugin.php:235

**Comment by jameslaws** [comment]
@helgatheviking Try updating to version 3.0.2 to remove that warning.

**Comment by kstover** [comment]
Is this still an issue in 3.0.3?

**Comment by davettt** [comment]
@kstover after upgrading to 3.0.3 and going back to edit forms the undefined index: honeypot notice and array_merge(): Argument #1 warning come up again in debug log. Additionally there is also now also:

`PHP Notice:  Undefined index: settingDefaults in /xxx/xxx/Documents/Websites/xxx/wp-content/plugins/ninja-forms/includes/Admin/Menus/Forms.php on line 305`

**Comment by helgatheviking** [comment]
fwiw, I didn't see any notices when updating to 3.0.5

**Comment by kstover** [comment]
This has been taken care of in a recent version. If it re-appears, we can re-open.
