### ISSUE TITLE
Ninja Forms and Avada Conflicting

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1717]
Ninja Forms seems to be closing Avada modal pop ups immediately after they open.

**Comment by kjohnson** [comment]
Does Avada by chance use the Twitter Bootstrap modal? There is a similar issue with TWBS, #1743.

**Comment by kstover** [comment]
@kjohnson My guess is that this is the same as the bootstrap modal issue you were investigating earlier. For the moment, if we limit our bootstrap output to only forms with rtes, that will bandaid while we investigate a real fix.

**Comment by kstover** [comment]
Closing because we only load boostrap when an RTE is present on the front-end. Will re-open if this appears again.
