### ISSUE TITLE
Ninja Forms version showing incorrectly in the System Status

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#1722]
Ninja Forms version showing incorrectly in the System Status
The user has version 3.0.2 and is using the 2.9.x codebase, but the version under environment is showing 3.0.1
### Environment

Home URL:                https://register.teenmissions.org
Site URL:                https://register.teenmissions.org
Ninja Forms Version:     3.0.1
WP Version:              4.6.1
WP Multisite Enabled:    No
Web Server Info:         Apache
PHP Version:             5.5.38
MySQL Version:           5.6.25
PHP Locale:              decimal_point: .thousands_sep: int_curr_symbol: currency_symbol: mon_decimal_point: mon_thousands_sep: positive_sign: negative_sign:
WP Memory Limit:         40 MB
WP Debug Mode:           No
WP Language:             Default
WP Max Upload Size:      64 MB
PHP Post Max Size:       65 MB
Max Input Nesting Level: 64
PHP Time Limit:          30
PHP Max Input Vars:      1000
SUHOSIN Installed:       No
SMTP:                    localhost
smtp_port:               25
Default Timezone:        Default timezone is UTC
### Plugins

Installed Plugins:
                         Ninja Forms - Conditional Logic by The WP Ninjas version 3.0.1
                         Ninja Forms - File Uploads by The WP Ninjas version 3.0.1
                         Ninja Forms by The WP Ninjas version 3.0.2

**Comment by kjohnson** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ZwGiVNfi&#x2F;9-ninja-forms-version-showing-incorrectly-in-the-system-status-1722"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Ninja Forms version showing incorrectly in the System Status #1722</a>

**Comment by kjohnson** [comment]
This issue is an outdated version constant in the deprecated codebase, which would be fixed in the next release.

Although, it would be better to make this moot by externalizing the version number into a main file, setting the version number in one place.

**Comment by jameslaws** [comment]
This settings is really just for identifying the codebase, correct? For identification purposes couldn't we set them in stone to something more like 2.9.x and 3.x? Because the exact version number here doesn't matter.

**Comment by kjohnson** [comment]
The exact version number may still be important in the future.

We should probably add a new line to the System Status to identify a deprecated codebase, but that is a separate issue.

**Comment by jameslaws** [comment]
We spend time spinning our wheels in support because we don't actually know which code base we are working with when provided the system status. This needs to be fixed immediately. 

Something like:

Ninja Forms Codebase: 2.9.x

or 

Ninja Forms Codebase: 3.x

**Comment by jameslaws** [comment]
I would add that we don't need Ninja Forms Version at all since that's in the plugin list.

**Comment by jameslaws** [comment]
This has got to get taken care of immediately!

**Comment by kjohnson** [comment]
I added a new line in the deprecated codebase, to show that it is the deprecated codebase.

-- 

<img width="1071" alt="screenshot 2016-10-25 20 26 49" src="https://cloud.githubusercontent.com/assets/10858303/19709185/ac943a32-9af2-11e6-851e-45f75d4e960c.png">
