### ISSUE TITLE
Activating a non 3.0 plugin throws an error

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#1723]
Activating a non 3.0 plugin, such as Front-End Editor, when using the 3.0 codebase, throws an error:

Warning: require_once(/Applications/MAMP/htdocs/wordpress3/wp-content/plugins/ninja-forms-front-end-editor/includes/admin/ajax.php): failed to open stream: No such file or directory in /Applications/MAMP/htdocs/wordpress3/wp-content/plugins/ninja-forms-front-end-editor-1.0.8/front-end-editor.php on line 65

Fatal error: require_once(): Failed opening required '/Applications/MAMP/htdocs/wordpress3/wp-content/plugins/ninja-forms-front-end-editor/includes/admin/ajax.php' (include_path='.:/Applications/MAMP/bin/php/php5.6.10/lib/php') in /Applications/MAMP/htdocs/wordpress3/wp-content/plugins/ninja-forms-front-end-editor-1.0.8/front-end-editor.php on line 65

**Comment by kstover** [comment]
This should be fixed in the latest version of core. I can't replicate locally. If it re-appears, we can re-open.
