### ISSUE TITLE
Refactor save functions for tabs

### ISSUE THREAD

**Issue by pippinsplugins** [wpninjas/ninja-forms#174]
Each tab registered to the settings screen has its own save function.

For example: 
```php
function ninja_forms_register_tab_label_settings(){
	$args = array(
		'name' => __( 'Labels', 'ninja-forms' ),
		'page' => 'ninja-forms-settings',
		'display_function' => '',
		'save_function' => 'ninja_forms_save_label_settings',
	);
	ninja_forms_register_tab( 'label_settings', $args );

}
.....

function ninja_forms_save_label_settings($data){
	$plugin_settings = get_option("ninja_forms_settings");
	foreach($data as $key => $val){
		$plugin_settings[$key] = $val;
	}
	update_option("ninja_forms_settings", $plugin_settings);
	$update_msg = __( 'Settings Saved', 'ninja-forms' );
	return $update_msg;
}
```

The default save functions are all identical, with the extension of the `Licenses` tab, which only changes the `$update_msg`.

I'd like to propose that these be refactored to all use one unified save function. The update message can be determined by the tab that is being saved in a `switch` statement.

Extensions should still be allowed to register their own save function, but there's no need for core to use separate ones for each tab.

If no save function is passed to the `ninja_forms_register_tab()` call, it should just use the default save function.

**Comment by kjohnson** [comment]
The v3 settings registration now has a single save function.
