### ISSUE TITLE
Add setting for custom, per form labels

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1741]
Add setting for custom, per form labels.  If filled in, these will override the translations.

**Comment by kjohnson** [comment]
@wpnzach this was previously handled by the [Custom Form Lables](https://ninjaforms.com/extensions/custom-form-labels/) add-on, which currently has an unknown update status for v3 compatibility.

Instead, I would rather offer a free plugin to support feature parody for the plugin-wide labels.

**Comment by kjohnson** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;NfkBhSX1&#x2F;30-add-setting-for-custom-per-form-labels"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add setting for custom, per form labels</a>

**Comment by kstover** [comment]
I've moved this over to our internal feature tracker.
