### ISSUE TITLE
Currency Symbol doesn't change from "$" 

### ISSUE THREAD

**Issue by devinbalram** [wpninjas/ninja-forms#1742]
https://wpninjas.desk.com/web/agent/case/22481

Go into Forms -> Settings -> General Settings -> Currency Symbol. If you change it to anything other than the default "$", it doesn't reflect on the front end. 

Replicated on local environment & users site.

**Comment by kjohnson** [comment]
Duplicate of #1626 , which is closed by #1715.

Patched known issue: https://trello.com/c/TzvLwEKF/31-currency-symbol-doesn-t-change-from
