### ISSUE TITLE
Ninja Forms needed message when it is already activated

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#1745]
With Builder Pro and Ninja Forms enabled, there is a message the Ninja Forms is required even though it is active. https://goo.gl/hJmkSg
### Environment

Home URL:                http://localhost/wordpress3
Site URL:                http://localhost/wordpress3
Ninja Forms Version:     3.0.2
WP Version:              4.6.1
WP Multisite Enabled:    No
Web Server Info:         Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/5.6.10 mod_ssl/2.2.29 OpenSSL/0.9.8zh DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0
PHP Version:             5.6.10
MySQL Version:           5.5.42
PHP Locale:              negative_sign:
WP Memory Limit:         40
WP Debug Mode:           Yes
WP Language:             Default
WP Max Upload Size:      32 MB
PHP Post Max Size:       32
Max Input Nesting Level: 64
PHP Time Limit:          30
PHP Max Input Vars:      1000
SUHOSIN Installed:       No
Server IP Address:       ::1
Host Name:               localhost
SMTP:                    localhost
smtp_port:               25
Default Timezone:        America/New_York
### Plugins

Installed Plugins:
Ninja Forms - Builder Pro by The WP Ninjas version 3.0.1
Ninja Forms by The WP Ninjas version 3.0.2

**Comment by kjohnson** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;dwaCgsuf&#x2F;34-ninja-forms-needed-message-when-it-is-already-activated"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Ninja Forms needed message when it is already activated</a>

**Comment by kjohnson** [comment]
@jmcelhaney how is the plugin folder setup? Has the `ninja-forms` folder been renamed or is has the `plugins` folder been externalized from the `wp-content` folder?

**Comment by jmcelhaney** [comment]
This was due to an incorrectly named Ninja Forms plugin folder. I deleted and reinstalled Ninja Forms and the issue went away.

**Comment by kjohnson** [comment]
@jmcelhaney this could still present an issue for users, like @jameslaws, with non-traditional plugin folder setups. We need to look into how TGMPA checks for plugins.

**Comment by kstover** [comment]
Closed because we've deprecated the Builder Pro plugin.
