### ISSUE TITLE
reCaptcha loads over HTTP, will not load on SSL secured sites

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1746]
Example from user:

Mixed Content: The page at 'https://imffa.org/register/' was loaded over HTTPS, but requested an insecure script 'http://www.google.com/recaptcha/api/js/recaptcha_ajax.js?ver=4.6.1'. This request has been blocked; the content must be served over HTTPS.

**Comment by kjohnson** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;HsfFOwNr&#x2F;36-recaptcha-loads-over-http-will-not-load-on-ssl-secured-sites"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> reCaptcha loads over HTTP, will not load on SSL secured sites</a>

**Comment by kjohnson** [comment]
@wpnzach That doesn't look like one of ours.

Ninja Forms enqueues:
`https://www.google.com/recaptcha/api.js`
not
`http://www.google.com/recaptcha/api/js/recaptcha_ajax.js`

**Comment by kjohnson** [comment]
Seems to be the [um-recaptcha](https://ultimatemember.com/extensions/google-recaptcha/) plugin, instead.
