### ISSUE TITLE
Notify user that rollback causes data loss

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1747]
We need to inform users that the rollback to 2.9 removes all 3.0 data.  This is not currently understood and has caused some users data loss since it's currently our first recommended troubleshooting step.

I would suggest this notice:

"Please note that all 3.0 data will be removed.  Please export any forms or submissions you do not want to be lost during this process."

**Comment by kjohnson** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;dSrSsRiB&#x2F;37-notify-user-that-rollback-causes-data-loss"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Notify user that rollback causes data loss</a>
