### ISSUE TITLE
Date-Format-Bug with Mailchimp Extension

### ISSUE THREAD

**Issue by nimus** [wpninjas/ninja-forms#1748]
following case scenario:

a valid Date-Field in the Format (d/m/Y)
is set back to (m/d/Y) AFTER the submission when sent to Mailchimp.

to reproduce this:
when in Mailchimp the requested field is set to the Format (d/m/Y) and the received date is something like the 30th of January the data gets lost because there is no 30th Month.

same scenario tested without this problem in the embedded MC-Form and the plugin "easy forms"

**Comment by kjohnson** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;iNzV6Hsy&#x2F;38-date-format-bug-with-mailchimp-extension"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Date-Format-Bug with Mailchimp Extension</a>

**Comment by nimus** [comment]
sorry for the buzz.

I guess this is one of those "Bug" where someone just needs to add a "Warning Notice" for inexperienced users.

something like:
"If you use the MailChimp-Extension make sure to keep the Date-Format to m/d/Y to avoid Data-Loss."
