### ISSUE TITLE
Rounding Calculations

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#1755]
If users are creating payment calculations, they probably want to limit the result to two decimal places. We should add an option to limit the number of decimal places. Maybe adding it to the top of the calculation settings drawer?

**Comment by kjohnson** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;eJJa5008&#x2F;49-rounding-calculations"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Rounding Calculations</a>

**Comment by rsmith4321** [comment]
If you get a version of this for testing please let me know, I can't use my Stripe checkout form until I can round the calculation.

**Comment by kstover** [comment]
I think for the time-being, we are going to create a new calc merge tag that will let you specify rounding to 2 decimals. This will let us solve the most common use-case for rounding without the added overhead of adding settings.
