### ISSUE TITLE
License key for Builder Pro not working. 

### ISSUE THREAD

**Issue by devinbalram** [wpninjas/ninja-forms#1756]
https://wpninjas.desk.com/web/agent/case/22691

User reported that his Builder Pro Key wasn't validating when he entered it in in Forms -> Settings -> Licenses. 

Tested on his site & confirmed the behavior.

**Comment by kjohnson** [comment]
@devinbalram last that I talked @wpnzach Builder Pro did not have license keys for me to test with.

@wpnzach have these license keys been generated?

**Comment by kjohnson** [comment]
Also, @devinbalram Builder Pro has its own repo. wpninjas/ninja-forms-builder-pro

**Comment by wpnzach** [comment]
It does have license keys and you should have one. It's called "Individual membership" or "professional membership" and is not labelled pro builder on the purchase page.

Membership bundle users do not currently have license keys.

**Comment by kstover** [comment]
Closing because we've deprecated the Builder Pro add-on.
