### ISSUE TITLE
Our setting page needs to be prefixed

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#1757]
If any other plugin uses the generic settings query it could override our own or we could override theirs: https://www.dropbox.com/s/f92htywdkq6twji/2016-09-11_18-34-52.png?dl=0

Ticket for reference: https://wpninjas.desk.com/web/agent/case/22426

**Comment by kjohnson** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;C9JJDhiZ&#x2F;54-our-setting-page-needs-to-be-prefixed"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Our setting page needs to be prefixed</a>
