### ISSUE TITLE
Deprecate v2.9.x Functions

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#1762]
## API Function

- [x] ninja_forms_insert_field()
- [x] ninja_forms_get_form_ids_by_post_id()
- [x] ninja_forms_get_field_by_id()
- [x] ninja_forms_get_fields_by_form_id()
- [x] ninja_forms_get_all_fields()
- [x] ninja_forms_update_field()
- [x] ninja_forms_delete_field()

- [x] nf_get_sub_count()
- [x] nf_get_fields_by_form_id()

## Helper Functions

- [x] ninja_forms_addslashes_deep()
- [x] utf8_encode_recursive()
- [x] ninja_forms_str_replace_deep()
- [x] ninja_forms_html_entity_decode_deep()
- [x] ninja_forms_htmlspecialchars_deep()
- [x] ninja_forms_stripslashes_deep()
- [x] ninja_forms_esc_html_deep()
- [x] nf_wp_kses_post_deep()
- [x] ninja_forms_strip_tags_deep()

**Comment by kjohnson** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;z3SGgglT&#x2F;61-deprecate-v2-9-x-functions"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Deprecate v2.9.x Functions</a>

**Comment by klhall1987** [comment]
[ ]- ninja_forms_insert_field()
 ninja_forms_get_form_ids_by_post_id()
 ninja_forms_get_field_by_id()
 ninja_forms_get_fields_by_form_id()
 ninja_forms_get_all_fields()
 ninja_forms_update_field()
 ninja_forms_delete_field()
 nf_get_sub_count()
 nf_get_fields_by_form_id()
Helper Functions

 ninja_forms_addslashes_deep()
 utf8_encode_recursive()
 ninja_forms_str_replace_deep()
 ninja_forms_html_entity_decode_deep()
 ninja_forms_htmlspecialchars_deep()
 ninja_forms_stripslashes_deep()
 ninja_forms_esc_html_deep()
 nf_wp_kses_post_deep()
 ninja_forms_strip_tags_deep()
