### ISSUE TITLE
Genesis preview form preview

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#1766]
The previewed form is not always showing with the Genesis Framework.

Example sites: https://amandadoula.com/

**Comment by kjohnson** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;5fQ6BldG&#x2F;65-genesis-preview-form-preview"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Genesis preview form preview</a>

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
