### ISSUE TITLE
Newsletter action spinner no longer present

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1769]
Newsletter action spinner is no longer present on actions. In order to get the newsletter lists to populate you have to change the dropdown multiple times. 

Screenshots: 
http://goo.gl/1EojOm

**Comment by klhall1987** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;s1xlPXjh&#x2F;74-newsletter-action-spinner-no-longer-present"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Newsletter action spinner no longer present</a>

**Comment by kstover** [comment]
Fixed in a recent version.
