### ISSUE TITLE
Localize datepicker

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1771]
Datepicker only loads with english translations, regardless of WP language settings.

**Comment by nimus** [comment]
Kyle was already on it with NF 2.x right..?
http://kylebjohnson.me/jquery-ui-datepicker-localization-in-ninja-forms/
https://github.com/kjohnson/ninja-forms-datepicker-localize

**Comment by kstover** [comment]
@nimus We changed the datepicker plugin in version 3.0, and we haven't gotten it localised quite yet.

**Comment by kstover** [comment]
The datepicker localisation can be done in JS: http://developer.ninjaforms.com/codex/datepicker/
