### ISSUE TITLE
Conditional Logic has two "Select Option" options where it has to be one "Select" and one "Deselect"

### ISSUE THREAD

**Issue by bubencode** [wpninjas/ninja-forms#1780]
When adding a new condition using 'Conditional Logic' 
in "Do" and "If the Condition Is Not Met" sections
when a "Radio List" is selected as an object of action 
there are both "Select Option" options

while there should be:
'Select Option'
'Deselect Option'

**Comment by kstover** [comment]
I've moved this over to the Conditional Logic private repo. Thanks for the report!
