### ISSUE TITLE
If no default selection is set for a check-box list, after the conversion, all of the check-box are checked.

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#1782]
An issue with the conversion where if no selections are set as the default on a check-box list, after the upgrade, all check-boxes are checked. The fix is to select and deselect the boxes (http://goo.gl/pFDO3f) then re-save the form.

Replication steps.
Create a form in 2.9.x with a check-box list
Make sure that no options are set to be selected
Convert to 3.0
View the form and all of the options will be selected event though none are selected in the form builder

**Comment by kstover** [comment]
Can't replicate with the current version.
