### ISSUE TITLE
Calculations with list fields don't seem to properly pass calc values

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1784]
These display properly on the front end of the form, but trying to process the form or pass to PayPal extension causes an error

**Comment by wpnzach** [comment]
I cannot get much more detail here as the calc merge tag is not available in success message or admin email to see what the value is set at during processing.

**Comment by jmcelhaney** [comment]
Here is another case where this is happening. https://wpninjas.desk.com/web/agent/case/22789

**Comment by kstover** [comment]
@kjohnson should be able to confirm what is happening in the PHP. It seems like it would be easy to check for a calc value, and if it doesn't exist, use the list option value.

**Comment by wpnzach** [comment]
Calc merge tags are not available in hidden fields, either, but if I copy/paste them they do use the calc value in the submission.

**Comment by jameslaws** [comment]
We dealing with this in a more recent issue with more details.
