### ISSUE TITLE
Remove "Slug" option from screen options in Submissions page

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1786]
![image](https://cloud.githubusercontent.com/assets/7498743/18488296/c0b1a632-79c6-11e6-93ab-1b444062ee8a.png)

**Comment by tw2113** [comment]
This was attempted in subs-cpt.php line 863 but that class appears to be deprecated since.

Something like the following would work, but I'm not sure where best to put it for preferred location.
```
function ninja_forms_remove_sub_slugdiv() {
    remove_meta_box( 'slugdiv', 'nf_sub', 'normal' );
}
add_action( 'admin_menu', 'ninja_forms_remove_sub_slugdiv' );
```

**Comment by kstover** [comment]
Does not show in the current version for me. Closing. If this re-appears, we can re-open.
