### ISSUE TITLE
The Insert Merge Tag list is not showing in the Email Action body only in FireFox

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#1794]
The Insert Merge Tag list is not showing in the Email Action body only in FireFox
### Environment

Ninja Forms Version:     3.0.5
WP Version:              4.6.1
PHP Version:             7.0.8

**Comment by kjohnson** [comment]
Wonder if this is a z-index issue in Firefox? The jBox content might be hidden.

@jmcelhaney does the same issue exist with help text?

**Comment by jmcelhaney** [comment]
@kjohnson Yes, this issue happens with Help Text and Description also.
