### ISSUE TITLE
Quote Request Form template - missing right edit sidebar 

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#1807]
Hi

I am looking at the Quote Request Form template. 
Some of the fields do not open the right edit sidebar panel.
Such as the field below. Just click through them and you should see others that also do not open up such as: What services may we assist... , How urgent is this project and State. 

![screen shot 2016-09-15 at 17 26 33](https://cloud.githubusercontent.com/assets/5323259/18555891/c444f0de-7b69-11e6-9d1c-99a98b7ce01d.png)

Btw
I would be puzzled if this is not an error. As clicking any field in a form should open the edit field for the field on the right.

Btw2
I also check Event Registration form and there are also some fields there that do not open a sidebar panel on the right.

**Comment by jameslaws** [comment]
That's a known bug. The data is there, but you have probably  scrolled down in one drawer and then switched fields. Try scrolling up in the drawer and see if the settings show up.

**Comment by paaljoachim** [comment]
Seeing the full screen form.
Then clicking "What services my we assist you with?" has no reaction. Does not open any sidebar on the right. The same goes for the others.
Good to hear it is already a known bug.

**Comment by jameslaws** [comment]
I can't reproduce what you are describing. The known bug is simply not jumping back to the top of the drawer when you switch field contexts. I don't see what you are describing.

**Comment by paaljoachim** [comment]
Here James.

https://youtu.be/CPWTOCwP8Mo

Example of an error message:

![screen shot 2016-09-15 at 18 17 28](https://cloud.githubusercontent.com/assets/5323259/18557803/b64e7a3e-7b70-11e6-8458-9da0085a4709.png)


load-scripts.php?c=1&load[]=hoverIntent,common,admin-bar,svg-painter,heartbeat,wp-auth-check,unders…:251 Uncaught ReferenceError: getColumns is not defined

(anonymous function)	@	(program):6
c	@	load-scripts.php?c=1&load[]=hoverIntent,common,admin-bar,svg-painter,heartbeat,wp-auth-check,unders…:251
Marionette.Renderer.render	@	main.js:13
_renderTemplate	@	backbone.marionette.min.js?ver=4.6.1:20
render	@	backbone.marionette.min.js?ver=4.6.1:20
render	@	backbone.marionette.min.js?ver=4.6.1:21
renderChildView	@	backbone.marionette.min.js?ver=4.6.1:20
_addChildView	@	backbone.marionette.min.js?ver=4.6.1:20
addChild	@	backbone.marionette.min.js?ver=4.6.1:20
(anonymous function)	@	backbone.marionette.min.js?ver=4.6.1:20
(anonymous function)	@	load-scripts.php?c=1&load[]=hoverIntent,common,admin-bar,svg-painter,heartbeat,wp-auth-check,unders…:251
m.each.m.forEach	@	load-scripts.php?c=1&load[]=hoverIntent,common,admin-bar,svg-painter,heartbeat,wp-auth-check,unders…:251
showCollection	@	backbone.marionette.min.js?ver=4.6.1:20
_renderChildren	@	backbone.marionette.min.js?ver=4.6.1:20
_renderChildren	@	backbone.marionette.min.js?ver=4.6.1:21
render	@	backbone.marionette.min.js?ver=4.6.1:20
renderChildView	@	backbone.marionette.min.js?ver=4.6.1:20
_addChildView	@	backbone.marionette.min.js?ver=4.6.1:20
addChild	@	backbone.marionette.min.js?ver=4.6.1:20
(anonymous function)	@	backbone.marionette.min.js?ver=4.6.1:20
(anonymous function)	@	load-scripts.php?c=1&load[]=hoverIntent,common,admin-bar,svg-painter,heartbeat,wp-auth-check,unders…:251
m.each.m.forEach	@	load-scripts.php?c=1&load[]=hoverIntent,common,admin-bar,svg-painter,heartbeat,wp-auth-check,unders…:251
showCollection	@	backbone.marionette.min.js?ver=4.6.1:20
_renderChildren	@	backbone.marionette.min.js?ver=4.6.1:20
render	@	backbone.marionette.min.js?ver=4.6.1:20
show	@	backbone.marionette.min.js?ver=4.6.1:20
onRender	@	itemSettingGroup.js:21
(anonymous function)	@	backbone.marionette.min.js?ver=4.6.1:20
triggerMethod	@	backbone.marionette.min.js?ver=4.6.1:20
render	@	backbone.marionette.min.js?ver=4.6.1:20
render	@	backbone.marionette.min.js?ver=4.6.1:21
renderChildView	@	backbone.marionette.min.js?ver=4.6.1:20
_addChildView	@	backbone.marionette.min.js?ver=4.6.1:20
addChild	@	backbone.marionette.min.js?ver=4.6.1:20
(anonymous function)	@	backbone.marionette.min.js?ver=4.6.1:20
(anonymous function)	@	load-scripts.php?c=1&load[]=hoverIntent,common,admin-bar,svg-painter,heartbeat,wp-auth-check,unders…:251
m.each.m.forEach	@	load-scripts.php?c=1&load[]=hoverIntent,common,admin-bar,svg-painter,heartbeat,wp-auth-check,unders…:251
showCollection	@	backbone.marionette.min.js?ver=4.6.1:20
_renderChildren	@	backbone.marionette.min.js?ver=4.6.1:20
render	@	backbone.marionette.min.js?ver=4.6.1:20
show	@	backbone.marionette.min.js?ver=4.6.1:20
onRender	@	editSettings.js:21
(anonymous function)	@	backbone.marionette.min.js?ver=4.6.1:20
triggerMethod	@	backbone.marionette.min.js?ver=4.6.1:20
render	@	backbone.marionette.min.js?ver=4.6.1:20
render	@	backbone.marionette.min.js?ver=4.6.1:21
show	@	backbone.marionette.min.js?ver=4.6.1:20
loadContent	@	drawer.js:39
u._callHandler	@	backbone.radio.min.js?ver=4.6.1:2
request	@	backbone.radio.min.js?ver=4.6.1:2
openDrawer	@	drawer.js:145
u._callHandler	@	backbone.radio.min.js?ver=4.6.1:2
request	@	backbone.radio.min.js?ver=4.6.1:2
clickEdit	@	itemControls.js:32
_	@	load-scripts.php?c=1&load[]=hoverIntent,common,admin-bar,svg-painter,heartbeat,wp-auth-check,unders…:254
m	@	load-scripts.php?c=1&load[]=hoverIntent,common,admin-bar,svg-painter,heartbeat,wp-auth-check,unders…:254
f	@	load-scripts.php?c=1&load[]=hoverIntent,common,admin-bar,svg-painter,heartbeat,wp-auth-check,unders…:254
u.trigger	@	load-scripts.php?c=1&load[]=hoverIntent,common,admin-bar,svg-painter,heartbeat,wp-auth-check,unders…:254
maybeClickEdit	@	fieldItem.js:91
dispatch	@	load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=4.6.1:3
r.handle	@	load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=4.6.1:3

**Comment by jameslaws** [comment]
Can you post you system status from the Get Help menu?

**Comment by paaljoachim** [comment]
System report

### Environment ###

Home URL:                http://test1.dev
Site URL:                http://test1.dev
Ninja Forms Version:     3.0
WP Version:              4.6.1
WP Multisite Enabled:    No
Web Server Info:         Apache/2.4.12 (Unix) OpenSSL/1.0.1m PHP/5.5.24 mod_perl/2.0.8-dev Perl/v5.16.3
PHP Version:             5.5.24
MySQL Version:           5.6.24
PHP Locale:              negative_sign:
WP Memory Limit:         40
WP Debug Mode:           No
WP Language:             Default
WP Max Upload Size:      512 MB
PHP Post Max Size:       512
Max Input Nesting Level: 64
PHP Time Limit:          600
PHP Max Input Vars:      5000
SUHOSIN Installed:       No
Server IP Address:       127.0.0.1
Host Name:               localhost
SMTP:                    localhost
smtp_port:               25
Default Timezone:        

### Plugins ###

Installed Plugins:       Black Studio TinyMCE Widget by Black Studio version 2.2.11
                         Caldera Forms by CalderaWP version 1.4.2
                         LifterLMS by Mark Nelson
                         Thomas Patrick Levy
                         codeBOX LLC version 3.0.0-beta.6
                         Ninja Forms by The WP Ninjas version 3.0

**Comment by jameslaws** [comment]
You are using an outdated version of Ninja Forms. Please update to 3.0.5 and try it again.

**Comment by paaljoachim** [comment]
Man I apologize for such a simple error. I overlooked the fact that I was using an older version of Ninja Forms. Sorry about that.

**Comment by jameslaws** [comment]
No apology needed. I do this too. :)
