### ISSUE TITLE
Better click detection (builder assumes drag if mouse moves at all)

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1813]
Is there a way we can set that if the movement is less than a few pixels that it's a click event and not a drag event?  Right now, 3.0 can appear buggy when fields aren't added on click due to even the most minute mouse movement.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.

**Comment by wpnzach** [comment]
reopening

**Comment by kstover** [comment]
I'm closing this because we are working on a complete builder re-write that will most likely use a different drag and drop library.
