### ISSUE TITLE
Post Merge Tags do not populate in action settings

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#1814]
Merge Tags for Post data (ie Post ID, Post Title, etc ) are not populating in action settings during processing.

**Comment by kjohnson** [comment]
Probably need to pass the Post data along with the submission data, as processing does not happen within the context of the Post.

**Comment by kjohnson** [comment]
Additional report by [Adriano Godoy](https://wpninjas.kustomerapp.com/app/customers/583c34e81e42781100b38886/event/583c34e8af481d1100271a4c).

**Comment by klhall1987** [comment]
Additional Report by [Anne-Claire](https://wpninjas.kustomerapp.com/app/customers/583f07e939f60d1100a83aca/event/583f07e99da1321000ec5668)

**Comment by o1y** [comment]
+1

**Comment by kstover** [comment]
Closing because we are currently refactoring merge tags.
