### ISSUE TITLE
Integrate With The WP REST API

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#1817]
Since we now require WP version 4.4, we can create custom API endpoints Integrating with the REST API could:
- Let us use Backbone collections' and models' native URL setting for population, which would remove the need to localise large amounts of data and templates.
- Saving form data could be improved by updating model data when the drawer is closed.
- Eventually be used by third-party APIs to consume NF Data.

To get started, we could create a REST endpoint without modifying how forms currently work.
- [ ] Form endpoint that returns settings, actions, and fields as JSON

Once this is done, we could update how we display forms without modifying anything else.

In order to update the builder to use endpoints, we'd need:
- [ ] Form endpoint that updates form settings
- [ ] Actions endpoint that returns action collection JSON
- [ ] Action endpoint that updates an action model
- [ ] Fields endpoint that returns field collection JSON
- [ ] Field endpoint that updates a field model

We'd also need to think about how we cache form previews.

Eventually, we would want to add endpoints for submissions, so that third-party apps could consume the NF data.
- [ ] Submission endpoint that returns submissions JSON
- [ ] Submission endpoint that updates a submission

**Comment by kstover** [comment]
Closed in favour of a custom REST implementation, since hosts can disable the WP REST API altogether.

**Comment by drewcovi** [comment]
@kstover is this currently dead or will the custom implementation somehow integrate into the default Wordpress API? It seems if a host is blocking the REST API that's something that wouldn't reflect poorly on Ninja Forms.

**Comment by pbredenberg** [comment]
I'm using WordPress as a back end for a JS client app, and it would be great if Ninja Forms could act as a middleman to receive and process form submissions via the API.

**Comment by TylerBarnes** [comment]
I'm doing the same as @pbredenberg. I came here looking to see if I could ditch gravity forms for ninja forms but I guess not.
