### ISSUE TITLE
Conversion of Multiple Email address in an Email Action adds an apostrophe

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#1819]
Conversion of Multiple Email address in an Email Action adds an apostrophe which causes the Emails not to be sent out in 3.0

Ninja Forms Version:    3.0.5

Replication Steps:
Create an Email action in 2.9.x with two or more emails in the To: field
convert to 3.0
check the email action of the converted form and the emails will be separated by an apostrophe instead of a comma

**Comment by klhall1987** [comment]
Changing to new milestone v3.0.10.

**Comment by kstover** [comment]
Should be working properly in the current version.
