### ISSUE TITLE
Don't enable submit button when other inputs are invalid

### ISSUE THREAD

**Issue by binarykitchen** [wpninjas/ninja-forms#1825]
Currently ninja-forms v3.x enables the submit button when visible errors are cleared. But the problem is that inputs are only validated on-blur events. This poses this problematic scenario:
1. You enter a random required form input further down first
2. Submit button becomes enabled
3. You click on submit button
4. Validation runs and shows other form input errors

This can lead to poor usability. Most modern sites do it the other way around. Should be:
1. You enter a random required form input further down first
2. Run internal validation and leave submit button disabled but dont show any errors
3. Fill out all remaining form inputs
4. Submit button becomes enabled

**Comment by binarykitchen** [comment]
any news on this one @kstover?

**Comment by kstover** [comment]
Is this an issue with version 3.1.2?

**Comment by Much2tall** [comment]
Issue has been resolved in current version (3.2.1)

**Comment by binarykitchen** [comment]
nice, well done guys :)
