### ISSUE TITLE
Recaptcha not applying CSS classes

### ISSUE THREAD

**Issue by DustinWStout** [wpninjas/ninja-forms#1829]
I've added two CSS classes to the Recaptcha field for the form on this page: https://warfareplugins.com/contact-us/

Classes: one-half first

For some reason, those classes are not being output. Classes are showing up on all other form wrappers (hence why the Submit button looks misaligned).

**Comment by kstover** [comment]
Hey @DustinWStout, is this still an issue in the current version of Ninja Forms?

**Comment by klhall1987** [comment]
Confirmed that this is still a bug.
