### ISSUE TITLE
Merge tags do not update when field data changes

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1830]
If user a merge tag for a field in an email, action, or calculation, then RENAME that field, the merge tag remains WITH THE OLD NAME in the list of merge tags even if the field is deleted from the builder and the form published.  This old name persists even if the form builder is reloaded.

If user a merge tag for a field in an email, action, or calculation, then DELETE that field, the merge tag remains in the list even is the form is published.  

If I rename a field, the KEY for the field changes but it does not update any uses of that merge tag in the builder, meaning that any uses of the merge tag for that field break.

**Comment by jameslaws** [comment]
https://db.tt/t5eOaLGT

This is a bit of a pain. :(

**Comment by jameslaws** [comment]
If you don't publish and reload the builder, label names aren't updated.

**Comment by kjohnson** [comment]
New user report: https://wpninjas.kustomerapp.com/app/customers/581f9f019b361e1100fdc708/event/582245661a2c3410002b1ca3

**Comment by jameslaws** [comment]
Is this still an issue?

**Comment by kstover** [comment]
Closing because we are currently refactoring merge tags.
