### ISSUE TITLE
Uninstall hook cleanup

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#1834]
2.9.x Tables
- [x] `nf_objectmeta`
- [x] `nf_objects`
- [x] `nf_relationships`
- [x] `ninja_forms_fav_fields`
- [x] `ninja_forms_fields`

Options
- [x] `ninja_forms_settings`
- [x] `ninja_forms_load_deprecated`
- [x] `ninja_forms_allow_tracking`
- [x] `ninja_forms_do_not_allow_tracking`

**Comment by klhall1987** [comment]
Changing to new milestone v3.0.10.

**Comment by kstover** [comment]
Closing in favour of a newer issue about uninstall deletion.
