### ISSUE TITLE
Empty or missing action settings return a string

### ISSUE THREAD

**Issue by ramiabraham** [wpninjas/ninja-forms#1836]
If a field is left as empty, or even if it's _not present in a form_, querying for its value will return a string containing the field ID, prepended with the string `field`. Example: 
- 1. Given the field ID `example_field_id`:

`fieldexample_field_id`
- 2. Using the field within action settings:

``` php
$this->_settings[ 'example_field_id' ] = array(
                'name'  => 'example_field_id',
                'type'  => 'field-select',
                'label' => __( 'Example Field', 'td' ),
                'width' => 'full',
                'group' => 'primary',
                'use_merge_tags' => true,
                'field_types'    => array(
                    'email'
                )
            );
```
- 3. Calling the field via:

``` php
$action_settings[ 'example_field_id' ];
```
- 4. To replicate, echo or log the action setting anywhere in the `process()` method of the action when it's either missing from the form, or an empty input.

**Comment by kstover** [comment]
Closing because I can't seem to replicate. If this is still an issue, we can re-open and investigate.
