### ISSUE TITLE
Date field doesn't keep format from the builder. 

### ISSUE THREAD

**Issue by devinbalram** [wpninjas/ninja-forms#1844]
https://wpninjas.desk.com/web/agent/case/23214

Create a date field on your form -> Set the format of the date field in anything other than MM/DD/YYYY & publish -> Enter the date -> In the submissions & submission email, it's being shown as MM/DD/YYYY.

Have tested locally & confirmed the behavior. 

https://goo.gl/tW9j9m
### Environment

Home URL:                http://robinphotoco.com
Site URL:                http://robinphotoco.com
Ninja Forms Version:     3.0.5
WP Version:              4.6.1
WP Multisite Enabled:    No
Web Server Info:         Apache
PHP Version:             5.5.36
MySQL Version:           5.5.51
PHP Locale:              negative_sign:
WP Memory Limit:         40
WP Debug Mode:           No
WP Language:             Default
WP Max Upload Size:      1 GB
PHP Post Max Size:       1,024
Max Input Nesting Level: 64
PHP Time Limit:          300
PHP Max Input Vars:      1000
SUHOSIN Installed:       No
Server IP Address:       149.47.153.242
Host Name:               crystal.asoshared.com
SMTP:                    localhost
smtp_port:               25
Default Timezone:        
### Plugins

Installed Plugins:  Ninja Forms - Conditional Logic by The WP Ninjas version 3.0.4
                              Ninja Forms - Constant Contact by The WP Ninjas version 3.0.1
                              Ninja Forms - Multi-Part Forms by The WP Ninjas version 3.0.4
                              Ninja Forms - File Uploads by The WP Ninjas version 3.0.2
                              Ninja Forms by The WP Ninjas version 3.0.5
                              WP Maintenance Mode by Designmodo version 2.0.8

**Comment by klhall1987** [comment]
Changing to new milestone v3.0.10.

**Comment by klhall1987** [comment]
Changing to new milestone v3.0.10.

**Comment by kstover** [comment]
Seems to be working in the current version. If this comes back up, we can re-open.
