### ISSUE TITLE
Support conditionals in note editor for email messages

### ISSUE THREAD

**Issue by binarykitchen** [wpninjas/ninja-forms#1845]
That's cool you can insert fields in the note editor for email messages. Currently I have something like this:

```
<p>Yay, thanks! We received your videomail and will respond pretty soon!</p>
<p>What you wrote:</p>
<pre>{field:message}</pre>
<p><a href="{field:videomail}">Link to your videomail</a></p>
```

But the problem is that the message field is optional and might be blank. Would something like this be possible:

```
<p>Yay, thanks! We received your videomail and will respond pretty soon!</p>
{if:field:message}
<p>What you wrote:</p>
<pre>{field:message}</pre>
{end}
<p><a href="{field:videomail}">Link to your videomail</a></p>
```

?

**Comment by kjohnson** [comment]
The merge tag system is not a full implementation of templating, but rather a more simple find/replace for field values, etc.

Also, this sort of logic is probably better handled with the Conditional Logic UI as opposed to duplicating efforts with the merge tag system.

**Comment by binarykitchen** [comment]
ok, thanks @kjohnson 

can you point me to an example of the Conditional Logic UI how the above can be solved there?

**Comment by kstover** [comment]
This is something that we can discuss internally, but I'm not sure that we will be implementing. As we have further discussion, we can re-open.
