### ISSUE TITLE
Third-party NF3 add-ons showing on licensing tab

### ISSUE THREAD

**Issue by ramiabraham** [wpninjas/ninja-forms#1856]
Ninja Forms 3+ requires add-ons to provide misc strings/ints that define the add-on. 

This is defined in the initializing constants, in the main add-on plugin class.

In our case:

``` php
/**
 * Constants for Ninja Forms 3.
 *
 * @since  1.1
 * @package affiliatewp-afnf
 */
const VERSION = '1.1';
const SLUG    = 'affiliatewp-afnf';
const NAME    = 'AffiliateWP - Affiliate Forms for Ninja Forms';
const AUTHOR  = 'AffiliateWP';
```

Totally fine there. But NF 3 then treats the add-on as if it were an official NF add-on, showing it on the NF licensing tab:

![lic](https://cldup.com/YOcg7_NlxZ.png)

I think this could cause confusion by customers of either product. 

Worth noting is that this doesn't cause any apparent loss of functionality within the add-on.

**Comment by ramiabraham** [comment]
We're starting to get (AffiliateWP) customers that are confused by this setting. Has your team seen any similar confusion with customers yet?

Thanks

**Comment by pippinsplugins** [comment]
Any chance this can be addressed please? It's still causing problems for us, especially as it appears that it does more than just register the license tab: it breaks our updater too.

This should _not_ be required for external add-ons.

**Comment by jameslaws** [comment]
@kstover and @kjohnson Can you guys speak to this and what's happening here from our perspective?

**Comment by ramiabraham** [comment]
We now have a workaround in for this, but it involves temporarily unsetting some NF3 data just prior to any updates occurring in AffiliateWP, then restoring NF3 extension updater functionality. It works, but that's definitely not a great solution.

We would much prefer to help get this resolved in NF core; would you guys be cool with a PR for this?

I think the affected elements would be:

- Making use of the NF3 licensing methods/properties _optional_ for all NF3+ add-ons
- Removing methods which prevent NF3+ extensions from being updated by processes not part of the NF3 extension updater class.

Thanks

**Comment by ramiabraham** [comment]
In checking the above-noted workaround, I removed the method in our main instance which defines the add-on strings for an NF3 add-on. I was expecting it to cause the add-on to not appear in NF as it has, but now it appears defining these properties _isn't_ required. Looks like we missed an update which removed that requirement, is that accurate?

**Comment by kstover** [comment]
I think that there may be some confusion here. I'm sorry for not responding to this issue sooner; it flew under my radar.

This wasn't ever a requirement. You should be able to just remove the call the the licensing class. You're seeing it in the licenses tab because there is a call to the license class somewhere in your code.

If you generated this with the Kozo plugin generator, it includes a licensing hookup by default. You just need remove the "setup_licenses" calls in the constructor.

**Comment by kstover** [comment]
All the "setup_license" method does is hook into the licensing class; they don't affect anything else.
