### ISSUE TITLE
NF 3 add-ons cannot hook on plugins_loaded, ninja_forms_loaded, or nf_admin_init

### ISSUE THREAD

**Issue by ramiabraham** [wpninjas/ninja-forms#1862]
In Ninja Forms 2.x, as well as many comparable extendable plugins (WC, EDD, etc), extensions/add-ons could use `plugins_loaded` as a dependable hook on which to load their third-party files, and use plugin hooks from other plugins.

Ninja Forms 3.0+ does define uses a `ninja_forms_loaded` action on line 355 of `ninja-forms.php`. 

However, as of Ninja Forms 3.0.6, hooking on this action doesn't load any of the third-party extension/add-on functionality.

In our case, we're hooking onto the following:

Filters:

``` php
ninja_forms_register_fields
ninja_forms_field_type_sections
ninja_forms_register_actions
ninja_forms_merge_tags_system
```

Actions:

`ninja_forms_enqueue_scripts`

With our main plugin instance firing at `plugins_loaded`, `99`.

---

What we've tried so far:
- A variety of `plugins_loaded` priorities
- Core WP hooks, such as `admin_init`
- Other NF 3 hooks, such as `nf_admin_init` and `nf_init`

**Comment by kjohnson** [comment]
I'll look into it, hopefully tonight.

**Comment by ramiabraham** [comment]
You're a machine @kjohnson

**Comment by kjohnson** [comment]
@ramiabraham I'm not seeing any issues with our add-ons. Do you have a repo or gist that I can take a look at?

**Comment by pippinsplugins** [comment]
@kjohnson https://github.com/AffiliateWP/affiliatewp-affiliate-forms-ninja-forms/issues/65#issuecomment-250338685

**Comment by ramiabraham** [comment]
Thanks @pippinsplugins. @kjohnson to use an official NF add-on as an example, in the NF User Registration add-on, the instantiation function below is called without a hook:

(https://github.com/wpninjas/ninja-forms-user-registration/blob/master/ninja-forms-user-registration.php#L164):

```php
function NF_UserRegistration()
    {
        return NF_UserRegistration::instance();
    }

    NF_UserRegistration();
```

What many plugins do in lieu of this, is to hook that function to `plugins_loaded`. This ensures that all plugin have loaded, and prevents possible issues if a dependency is deactivated.

If this instantiation function is hooked to `plugins_loaded` as well (or `ninja_forms_loaded`, or `nf_admin_init`), it will no longer function.*

*Although I've confirmed that in the past, it seems the current versions of NF3 and NF User Registration are incompatible out of the box; the NF User Registration actions don't appear to show up presently with `NF 3.0.6`.

**Comment by kjohnson** [comment]
@ramiabraham The user registration repo is not a published plugin, so that is something that will still need to be revisited.

I have it on my schedule today to look into AffiliateWP/affiliatewp-affiliate-forms-ninja-forms#65

**Comment by ramiabraham** [comment]
Thanks!

**Comment by kstover** [comment]
If this is still an issue, please re-open. We're trying to wrangle our GitHub issues, and this one isn't clear to me.
