### ISSUE TITLE
Star rating help text displaying wrong rating. 

### ISSUE THREAD

**Issue by devinbalram** [wpninjas/ninja-forms#1874]
https://wpninjas.desk.com/web/agent/case/23881

Add a star rating to the form -> Publish form -> Preview the form -> Hover over each star -> The ratings show backwards i.e. the first star when hovered over, shows "5", the second star "4," and so forth. 

Replicated locally on Ninja Forms 3.0.6

**Comment by kstover** [comment]
Should be fixed in the current version.
