### ISSUE TITLE
Duplicate on any field in builder creates two copies instead of one

### ISSUE THREAD

**Issue by bubencode** [wpninjas/ninja-forms#1875]
Using of 'Duplicate' function on any field in the form builder results in creation of two new instances of this field, instead of just one copy as it should be. Deleting of one of this extra fields leads to deletion of both duplicates.

**Comment by kstover** [comment]
Hey @bubencode. Are you using any add-ons?

**Comment by bubencode** [comment]
Hi @kstover, thanks for responding. Yes I am using Conditional Logic, Layout & Styles, Multi-Part Forms and PayPal Express.
I mentioned this bug in a support request last week too, and Zach @wpnzach replied the following (quote):
"The bug in the builder with adding two fields appears related to a recent Layout and Styles change in how new fields are added to the form builder. The bug is not present with Layout and Styles deactivated. We’re aware and are working on a fix..."
I tried deactivating the Layout & Styles on my site and yes, it eliminated the bug, confirming Zach's hypothesis. So I am looking forward to the Layout & Styles next update release.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
