### ISSUE TITLE
Rename "select" field to "dropdown"

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#1878]
The use facing name of the select field is not what a common user might be looking for. Instead this should be called a dropdown as that is the common application.

**Comment by klhall1987** [comment]
Changing to new milestone v3.0.10.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
