### ISSUE TITLE
Repeatable Fields

### ISSUE THREAD

**Issue by BFTrick** [wpninjas/ninja-forms#188]
It would be great to either have repeatable fields or repeatable groups of fields. I can see individual fields being much easier to implement.

**Comment by scotcrop** [comment]
@kstover @jameslaws is this something being considered for the new version (3) of Ninja Forms?

**Comment by kstover** [comment]
It's definitely on our radar, but it won't be a 3.0 feature.

Perhaps a 3.1 or 3.2. Our core changes will make this much easier to implement.

**Comment by scotcrop** [comment]
@kstover glad to hear it. Testing 3.0 Alpha 2 out now and its looking good.

**Comment by kjohnson** [comment]
Dependent on #40

**Comment by zagreusinoz** [comment]
Sorry to come in on an older thread but I can't find any other information about this.   Has this been implemented or is it on the roadmap?

**Comment by SamirJoza** [comment]
Years have past since the thread was originally posted and yet, no mentioning wether or not this will be implemented. It would be great addition

**Comment by ericwindham** [comment]
Hi @SamirJoza and @zagreusinoz 

It is still on the roadmap. We have had conversations about it just this week, actually. Still don't have a timetable, but my best guess is we at least get started on the implementation by end of year.

We are currently shoring up some things that will enable to do this and some other exciting things soon. 

I know 'end of year' is a wide net. We want to start on it as soon as possible. But, there are a few things we need to finish up before starting on this.

Eric Windham

**Comment by matt-sanders** [comment]
@ericwindham just wondering if this is still something that's in the near future or if we're looking more at a long term thing? It would be so awesome to have this, Ninja forms is great, but this is one of the few things that continually pushes me back to other plugins.

**Comment by matt-sanders** [comment]
Thanks for the update Eric, hopefully we can see this in the new year!

**Comment by illtrax** [comment]
@ericwindham Really need this feature! Please keep us updated. Thanks!

**Comment by christian-gwcm** [comment]
I can't see that this has been implemented. Is it still worked on? could really use this feature! Would pay for it as an add on...

**Comment by ericwindham** [comment]
@christian-gwcm It has not been implemented yet. We are currently working on a few things that will set us up for the implementation of repeatable fields. As soon as those things are done, repeatable fields is next. I don't have a timeline just yet. We would have liked to have already started on them, but things come up. But, it is on our immediate roadmap. It will be released as part of an existing add-on.

**Comment by colinporter** [comment]
Hi @ericwindham 

Any update on this? We really need this functionality so we can ditch other form plugins :)

**Comment by matt-sanders** [comment]
@ericwindham @kstover any update on this? Has been a few years now. If it's extra dev hands you need I could potentially help. We'd love this feature for the project I'm currently working on so could possibly pour some dev time to help with the implementation if necessary.

**Comment by jordanz18** [comment]
@kstover @ericwindham Any updates on this or any sample code to do this? I just purchased ninja forms but I may have to switch to formidable forms
