### ISSUE TITLE
In field masks, values shouldn't be translated as it breaks how they work.

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#1880]
Change the WordPress language to something other than english and notice that the custom mask value is being translated which means the js can't reveal the custom text box.

For reference: https://wpninjas.desk.com/web/agent/case/23800

**Comment by Oxonium** [comment]
Hey !

Any update on this ?

**Comment by klhall1987** [comment]
Hi @Oxonium,

Currently we haven't had a chance to look into this issue. I have moved it to a new milestone and we will try to look into it soon. We will let you know as soon as we have an update.

**Comment by Oxonium** [comment]
Hi again @klhall1987 !

I hate to push for it but we are at v 3.0.11 and the bug is still here. I have to use input masks for a website soon to be release...

Thanks !

**Comment by dimic00** [comment]
Grrr got the same problem :(
Any news on this? Hope it will fix soon, it is a major problem on the project I am working on.
Thanks !

**Comment by Axel-Charpentier** [comment]
Hello,

This problem blocking me on one of my projects, when will it be resolved ?!

Thanks.

**Comment by Oxonium** [comment]
Well, seeing theses updates I'm not the only one with this problem...

Could you please give us an update ? Cheers !

**Comment by Oxonium** [comment]
Just saw the bug fix in 3.0.14, thanks guys !

**Comment by dimic00** [comment]
F*ck yeah, thanks! It will be very helpful 👍

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
