### ISSUE TITLE
Form Preview displays pagination

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#1882]
> When previewing a form, it appears to use the template for the “home” (front) page and so displays any pagination (from wp_link_pages()) as well as comments on that page. This is confusing as the pagination and comments are not really part of the form preview.
## 

Reported By: Mike Glendinning
Reference: https://wpninjas.desk.com/web/agent/case/23807

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
