### ISSUE TITLE
Product fields in all forms shortcode should show quantity

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#1884]
The product field shows price in the all fields shortcode rather than quantity. If it's using the inline quantity, it should use that number instead.

**Comment by klhall1987** [comment]
Changing to new milestone v3.0.10.

**Comment by jameslaws** [comment]
I think we need to work on this as a part of our pricing fields sprint. Depening on the settings there may need to be different values saved/displayed.

2 / $250.00
2 @ $250.00
$500.00
$500 (2 @ $250.00)
etc.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
