### ISSUE TITLE
In submission bulk actions the export action is duplicated.  

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1885]
In submission bulk actions the export action is duplicated.

**Comment by klhall1987** [comment]
Changing to new milestone v3.0.10.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
