### ISSUE TITLE
number_format should respect WordPress locale decimal and thousands separators

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#1886]
Anywhere that we call number_format, we should pass the extra variables to set the decimal and thousands separators.

**Comment by kstover** [comment]
http://php.net/manual/en/function.number-format.php

**Comment by klhall1987** [comment]
Changing to new milestone v3.0.10.

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/5832e42dca58701100504380/event/58b4311753052f11001898bc

**Comment by wssmichael** [comment]
Has this been implemented with the new update?

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
