### ISSUE TITLE
Star review field hover tips/tool tips inverted

### ISSUE THREAD

**Issue by Quay3** [wpninjas/ninja-forms#1887]
To reproduce:
1) Add a Star Review Field
2) Hover over first star, tool tip shows "5"; hover over second star, tool tip shows "4", etc

These appear to be inverted. Expected behavior would seem to be that the tool tip corresponds to the star you're hovering over. For example, when you hover over the first star, the tool tip would show "1".

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
