### ISSUE TITLE
Required fields fail on "0" value, should only fall on null

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1890]
Currently, "0" causes all fields to fail if they are required.  This includes single line text, number, and paragraph text.

0 should be considered a valid input for these fields, but they should still fail if they contain NO data.

**Comment by tw2113** [comment]
Hactoberfesting, thus I'm looking over bugs here :)

This is one of those frustrations of PHP and false-y values. String numeral zero equates to false. Would need to either be is_null() checks or so, if not strict checking, aka ===

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
