### ISSUE TITLE
Need better error handling on upgrade page

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#1891]
When the upgrade process returns a 500 error, or a failed response, we should be able to recognize the empty response and alert the user that an error occurred.

This should also better help the support team to assist customers.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
