### ISSUE TITLE
Fix hardcoded table reference

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#1894]
> I just noticed you left a hardcoded table prefix in the file Render.php, line 53.
> ninja-forms/includes/Display/Render.php
> Can you change this to get the prefix from the $wpdb object instead?
## 

Reported By: Felix Stein
Reference: https://wpninjas.desk.com/web/agent/case/23978

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
