### ISSUE TITLE
CSV trouble with multi-select and checkbox list

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#1895]
> The CSV that exports with form submission is breaking data from multi-select and checkbox list fields into individual pieces rather than a collection of data points assigned to that field. This results in the CSV data no longer lining up properly beyond where the multi-select or checkbox list fields appear in the form.

--
Reported By: https://wpninjas.desk.com/web/agent/case/21424
Reference: Brandon Andrusic

**Comment by klhall1987** [comment]
fixed by https://github.com/wpninjas/ninja-forms/pull/1896 which was merged and released in v3.0.8.
