### ISSUE TITLE
Using conditional logic addon glitch.

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#1897]
I am testing the conditional logic addon 3.0.3 and am finding it glitchy (two forms that did not come up correctly). Scratch that I updated to version 3.0.5 and had to create new forms as the old forms still showed glitches from the earlier version. 
1. Form
   I made a form based on http://spirituellfilm.no/pamelding-til-film/ (as I could not find the toogle I used a select drop down instead).
   The basics of the form is such:
   First name
   Last name
   Select
   Select
   Select
   Text paragraph
   First name
   Last name
   Submit

![screen shot 2016-10-02 at 08 06 17](https://cloud.githubusercontent.com/assets/5323259/19020446/2357e792-8877-11e6-8114-777ac5feb6b5.png)

Previewing it the order of the fields were switched. The conditionals logic plugin is activated but I am still not using it in the form.

![screen shot 2016-10-02 at 08 07 07](https://cloud.githubusercontent.com/assets/5323259/19020454/446b4dd4-8877-11e6-937a-fb71aef2fdd3.png)
(The form is longer then the screenshot seen.)

I exported the form to my DropBox: https://www.dropbox.com/s/kxboqgh9zly70yi/nf_form_10-02-2016.nff?dl=0

I am using Desktop Server with a local development site on Chrome.

ps
Let me know what you need testing. I am trying to create a tutorial using Conditional Logic but because of the glitches going on will have to wait.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
