### ISSUE TITLE
Missing Brazilian Portuguese Translation Strings

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#1900]
These were sent in by a user:

I'm using Ninja forms and on the Plugin Settings &gt; Labels it's not translated for Brazilian Portuguese, so I just translated it. Bellow are the fields translated like they're shown on Labels tab (1st to last):
Required fields label: Campos marcados com \* são obrigatórios
Symbol...: *
Error message...: Por favor, certifique-se de que todos os campos foram preenchidos.
Required Field: Este é um campo obrigatório.
Anti-Spam...: Por favor, responda a pergunta anti-spam corretamente.
Honeypot...: Por favor, deixe o campo spam em branco.
Timer Error: Por favor, aguarde alguns instantes para enviar o formulário.
Javascript Error: Você não pode enviar o formulário sem que o Javascript esteja habilitado.
Valid email: Por favor, informe um endereço de email válido.
Processing: Processando
Password...: As senhas fornecidas não são iguais.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
