### ISSUE TITLE
Calc variable names are not being tracked 

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1902]
When a calc variable name is changed that variables name is not change across the form builder. 

Replication steps:
1. Create a new form add an html field. 
2. Go to settings and add a calc variable. 
3. Go to the builder and add that calc variable to the html field.
4. Go to the settings domain and change the name of the calc variable. 
5. Go to the build and check the html field. You'll see that the name of the calc variable has not changed.

**Comment by jameslaws** [comment]
Is this something we can even fix?

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
