### ISSUE TITLE
Product fields with value in the thousands improperly render.

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#1904]
This notice is thrown: Notice: A non well formed numeric value encountered in /Users/james/Documents/dev/WordPress/wp-content/plugins/local-three/includes/Display/Render.php on line 339

And the value is not display correctly.

1,000.00 turns to 1.00
10,00.00 turns to 10.00
100,000.00 turns to 100.00
1,000,000.00 turns back to $1.00

**Comment by klhall1987** [comment]
Moving this issue to 3.0.10 milestone.
