### ISSUE TITLE
Front-end not updating newly-added fields

### ISSUE THREAD

**Issue by ramiabraham** [wpninjas/ninja-forms#1906]
I may have stumbled onto a notable issue, in which forms don't get updated on the front-end in NF3 when new fields/actions are added to an existing, previously-published form.

---

Replication steps:
- Create a form, add some fields, publish form
- Add form to a published post/page
- View published form on the post/page while logged in, confirm all fields are present
- View published form on the post/page while logged _out_ (or, in a different browser), confirm all fields are present
- Return to NF admin form editor and add more fields to the form, then publish form again
- View published form on the post/page while logged in, confirm all _new_ fields are present
- View published form on the post/page while logged _out_ (or, in a different browser), newly-added fields are missing.

---

So far I've ruled out:
- client-side caching
- transients

**Comment by klhall1987** [comment]
Moving this issue to 3.0.10 milestone.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
