### ISSUE TITLE
Custom merge tags not working when registered via third-party

### ISSUE THREAD

**Issue by ramiabraham** [wpninjas/ninja-forms#1910]
In a prior version of NF3, we could define custom merge tags in one of the merge tag sections, such as `User` or `System`.

The callback string provided was a method within the add-on class, such as `array($this, 'the_method')`. In NF `3.0.6` (possibly in earlier versions too, have only checked 3.0.6 so far), this no longer functions, and instead causes the associated event in which the merge tag is used to silently fail, or the merge tag returns an empty string.

---

To replicate, within the class of any third-party code:

``` php

add_filter( 'ninja_forms_merge_tags_system', array( $this, 'register_merge_tag') );

public function register_merge_tag( $merge_tags ) {
            $url = 'affwp.dev/farts';

            $merge_tags[ 'custom_merge_tag' ] = array(
                'id'       => 'custom_merge_tag',
                'tag'      => '{system:custom_merge_tag}',
                'label'    => __( 'Custom Merge Tag', 'custom' ),
                'callback' => array( $this, 'get_some_url' )
            );

            return $merge_tags;
        }

    public function get_some_url() {

            $url = admin_url();
            return $url;
        }

```

---

In our case, the usage is as a url value for the NF _Redirect_ action:

![ALT_TEXT](https://cldup.com/Ni51W6E8aH.png)

**Comment by Divan4ik** [comment]
I just join to find out when it will work

**Comment by kjohnson** [comment]
New docs for creating custom merge tags: http://developer.ninjaforms.com/codex/merge-tags/

**Comment by ramiabraham** [comment]
Noice, thanks @kbjohnson90

**Comment by bahcivan** [comment]
Hi, can someone explain me exactly how i create a custom merge tag with the username

Database table: wp_users, Column: user_login

I tried to make it with the Docs ([http://developer.ninjaforms.com/codex/merge-tags/](http://developer.ninjaforms.com/codex/merge-tags/)) but it doesn't work. I don't understand in which files i must make the changes...

**Comment by mrinx** [comment]
I got the example from the docs working by hooking to the `nf_init` as opposed to the `ninja_forms_loaded`, though I assume the `nf_init` is not the best action to hook to.

**Comment by TonyC5** [comment]
@mrinx - Thank you for your tip.  I also was able to get the example working by hooking `nf_init` (hooking `ninja_forms_loaded` did not work as you indicated).
