### ISSUE TITLE
CSV Field Order does not match form

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#1914]
>  Is there a way to assign the order of the fields and corresponding columns? They are not exporting with the order in which the fields are placed on the actual form.
## 

Reported by: Jason Gloria
Reference: https://wpninjas.desk.com/web/agent/case/24205

**Comment by niekvdl** [comment]
I have the same problem, but it seems there is no solution? Thanks, Niek

**Comment by jameslaws** [comment]
This has been reported again. I spoke with @kjohnson and he said he will make sure it's patched in 3.0.15.

**Comment by kstover** [comment]
This was fixed in 3.0.17.

**Comment by nikhresna** [comment]
Hi,

I happen to encounter this issue in v3.0.29

When I view submission in admin, the order are correct:
```
	#	Nama depan	Nama belakang	Tempat/tanggal lahir	No. KTP	Date
```

also when I exported the form, it had correct order
```
"formContentData": "nama_depan_1488298093815","nama_belakang_1488298198058","tempat_tanggal_lahir_1488298216200","no_ktp_1488298285005","alamat_1488298302550","pekerjaan_1488298328758","no_hp_1488298392233","email_1488298404525","paket_1488298473095","periode_1488298509072","nama_bank_1488298581474","no_rekening_1488298680795","nama_rekening_1488298724883","submit_1488298158554"]
```

but order got random when I exported all submissions
```
"#","Date Submitted","Periode","Paket","Nama bank","No. rekening","Nama rekening","Email","No. HP","Tempat/tanggal lahir","Nama belakang","Nama depan","No. KTP","Alamat","Pekerjaan"
```


Any idea?

**Comment by nikhresna** [comment]
I noticed `Submissions` is a post type,
exporting XLM of `Submissions` also returned correct order

I can provide all the export files if necessary
