### ISSUE TITLE
FORCE_SSL_ADMIN is causing forms to crash for logged-in users

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#1915]
If a site has FORCE_SSL_ADMIN set to true in their wp-config, submitting a form while logged-in (from a non-preview) crashes submission.

**Comment by klhall1987** [comment]
The user who let us know about this issue has given us some more information please see the ticket below. 

https://wpninjas.desk.com/web/agent/case/23803

**Comment by klhall1987** [comment]
User sent us a code snippet that might help resolve this issue. You can find the code snippet at in the gist below. 

https://gist.github.com/klhall1987/02e23b3d92947a825e146702329ca851

He did add that, "this change will likely be needed on any other Ajax requests that you make from the front-end. I think everything should be OK within the admin tool as that will either be completely HTTP or completely HTTPS. Also, the error handling for the “parseJSON” call (just logging “Parse Error”) isn’t very robust as this leaves the page in an indeterminate state. I suspect it would be better to log and display the error and reset the form as in the Ajax error handler."

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
