### ISSUE TITLE
Saved/favorited "Select" fields cannot be used in the builder

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1916]
fieldItem.js:68 Uncaught TypeError: Cannot read property 'get' of undefined

This error happens when trying to add a "Select" saved field into the builder.

When added, a glitched saved field with no controls appears in the form with the error above.  

Reproduction steps:
1. Add a "Select" field
2. Make it a "Saved Field" (you can make changes or leave settings as default values)
3. Add the field to the form by dragging it into the builder (note: click to add does not work at all)
4. Only the select field adds to form, sans icons/styling/ability to open configuration drawer.  JavaScript error appears on page.

NOTE:  With LAyout and Styles/MPF activated, the above steps happen but all other fields are visually removed from the form builder as well.  The video below demonstrates this behavior ONLY in vanilla Ninja Forms.

https://goo.gl/YUWzr8

**Comment by dud3sweet** [comment]
Having  issues with select fields not saving properly and sometimes breaking the builder after being reloaded even on the demo site for version three. Rolling back until fixed.

**Comment by wpnzach** [comment]
Another user encountered this issue.  Also caused this error on the front end: 
![preview-chat-screen shot 2017-01-18 at 2 02 27 pm](https://cloud.githubusercontent.com/assets/7498743/22078696/e9e9a35a-dd86-11e6-9a93-fccc14d3e1f0.png)
