### ISSUE TITLE
Submission Edit Screen Sort Order

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#1918]
On the submission edit screen (for the Custom Post Type), the fields appear out of order when using add-ons, like Layout & Styles.
## 
### Layout & Styles

| Builder | Submission Header |
| --- | --- |
| ![screenshot 2016-10-05 15 17 04](https://cloud.githubusercontent.com/assets/10858303/19127924/14ed80be-8b0f-11e6-8c90-2adc47d4befc.png) | ![screenshot 2016-10-05 15 16 56](https://cloud.githubusercontent.com/assets/10858303/19127927/1a21036c-8b0f-11e6-8095-10a0b75d494c.png) |

**Comment by kjohnson** [comment]
The issue appears to be related to the `formContentData`, or rather how field order is modified in a layout.

**Comment by kstover** [comment]
This also affects exported submissions. Ultimately, the builder would need to be modified to store an "overall" order. However, for the time being, we could update the field order using the formContentData at submission export or edit.
