### ISSUE TITLE
Conditional Fields: Cannot Submit When Required Field is Hidden

### ISSUE THREAD

**Issue by thinkcodenyc** [wpninjas/ninja-forms#1931]
When a select dropdown field is required, but hidden due to conditions, the form cannot be submitted. 

Additionally, when a required field is revealed due to conditions (i.e. it was not visible on initial page load), it renders with a validation error already displaying. 

Running Conditional Fields 3.0.4 and Ninja Forms 3.0.7

**Comment by jkjohan** [comment]
Any solution to this?
I have the same problem.
Running Conditional Logic 3.0.10 and Ninja Forms 3.0.19

**Comment by kstover** [comment]
This should be fixed in the latest version of Conditional Logic and Ninja Forms. If you still have this issue, please create a support ticket at ninjaforms.com.
