### ISSUE TITLE
Display Inconsistency in Backend With Placeholder / Default Value Fields

### ISSUE THREAD

**Issue by thinkcodenyc** [wpninjas/ninja-forms#1932]
On the Ninja Forms edit form page, under **Advanced**, most fields have "Placeholder" listed before "Default Value" but some others have it in the opposite order. 

Specifically noticed the First Name and Email fields have "Placeholder" listed second, but might be present on others. Phone, and single-line text input fields have "Placeholder" listed first.

<img width="862" alt="screen shot 2016-10-09 at 3 03 53 pm" src="https://cloud.githubusercontent.com/assets/10250301/19222918/9b48f9a2-8e31-11e6-88d6-b9152aeb6b32.png">
<img width="858" alt="screen shot 2016-10-09 at 3 00 26 pm" src="https://cloud.githubusercontent.com/assets/10250301/19222905/6db7e30e-8e31-11e6-9ec2-1cefa742f1d0.png">
<img width="854" alt="screen shot 2016-10-09 at 3 00 31 pm" src="https://cloud.githubusercontent.com/assets/10250301/19222906/6dc336aa-8e31-11e6-86ed-3390cc243737.png">

**Comment by JacobDB** [comment]
Yep, I've noticed this too. I think "Placeholder" should be the bottom field; if that's agreeable, I believe the following will need updating:

- Single Line Text
- Address
- City
- Phone
- Zip
- Product
- Shipping
- Number
- Anti-Spam

This is an easy fix, just swapping some array keys. @thinkcodenyc , do you think you'd be able to submit a pull request for this?

**Comment by JacobDB** [comment]
@thinkcodenyc Actually I just took care of it 😄 . Submitted a pull request, hopefully it gets accepted!
