### ISSUE TITLE
Checkbox Lists & Select Fields: Selected value(s) not being saved properly.

### ISSUE THREAD

**Issue by thinkcodenyc** [wpninjas/ninja-forms#1934]
With regards to select fields, after testing them exhaustively, I've only been able to get values that are single words (e.g. `Photographers`) to be saved (when the form is submitted in the frontend), or to wrap anything with a space or symbol (e.g. a hyphen) in single quotes in the backend's edit field page `''`. When wrapping values with standard quotes `""`, the field values disappear after clicking to another field. See screenshot below (this has been the only way I've been able to get the form to submit with the user's selection saved):

<img width="835" alt="screen shot 2016-10-10 at 3 21 03 pm" src="https://cloud.githubusercontent.com/assets/10250301/19248297/2cbfcdf4-8efd-11e6-8006-dd755d2d1bd8.png">

With regards to Checkbox Lists, neither of the above methods seem to work. Regardless of the field's option values, no user selections are saved to the database.

**Comment by dud3sweet** [comment]
Having similar issues with select fields not saving properly and sometimes breaking the builder after being reloaded even on the demo site for version three. Rolling back until fixed.

**Comment by kstover** [comment]
@dud3sweet @thinkcodenyc 

Is this still an issue in the current version of Ninja Forms?

I can't replicate locally.
