### ISSUE TITLE
Weird UI js/data issues

### ISSUE THREAD

**Issue by farinspace** [wpninjas/ninja-forms#1935]
Feel free to rename the title not sure how to classify this issue ..

We've started to use Ninja Forms for client installations, our most recent install uses nf3 (v3.0.8). But the UI seems to be a bit buggy. I've used it in Safari as well as Firefox (local install and WPEngine install) and I get the same behavior.

I create a simple form, both from the default "contact us" form and from scratch, after saving or after update, certain fields aren't recognized, the screen looks like the attached screenshot. The fields cant be read and display "false", clicking to edit the field yields a message: Field type "" not found."

<img width="1181" alt="screen shot 2016-10-11 at 4 02 31 pm" src="https://cloud.githubusercontent.com/assets/94205/19291975/83c2667c-8fcd-11e6-9550-93e230ec1dfa.png">

There is definitely some weirdness going on, which is quite troubling.

**EDIT:**

I tried uninstalling, I check "remove all data" before uninstall. I then reinstalled, but all my form data was still available (all fields were "false" as pictured in screenshot)

Tested using Chrome, similar behavior, I add a field and publish, exit, and reenter the form and the field comes up as "false".

Uninstalled plugin .. went into DB and deleted all nf3, nf and ninja_forms tables .. reinstalled, went into the default "contact me" form, saw an old field I added and double submit field (weird).

Renaming fields and changing field values seem not to work either, it always reverts back to the old values when i exit and reenter the form.

**Comment by kjohnson** [comment]
@farinspace I have a fix that we are testing. Would you be able to test the fix on a customer's staging site?

**Comment by farinspace** [comment]
I have a local install with similar behavior which I can test on .. unfortunately I won't be able to test until later this evening.
