### ISSUE TITLE
Update data model on form submission

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1937]
Lots of users are writing JS to interact with their forms (such as filling in fields) and we're getting a fair number of users complaining that data is not saved in the submission.  On form submission, can we update the data model with whatever is currently held in each field to prevent them from needing to know backbone/marionette to do otherwise very simple JS tasks?

**Comment by wpnzach** [comment]
Thie behavior seems to be problematic with browser autocomplete as well.  Based on the total volume of requests we've had from users wanting a better solution for this, and the added knowledge that now at least Safari's autocomplete is also impacted, I'm escalating this to a bug.

**Comment by kstover** [comment]
Users who use jQuery.val() should not have this problem. I'm going to close this because it should be taken care of by a recent monkey-patch for jQuery.val() function if it's a Ninja Forms element.
