### ISSUE TITLE
Required checkbox throw "field is required" error even with the checkbox selected when using jQuery v3

### ISSUE THREAD

**Issue by ettoredn** [wpninjas/ninja-forms#1943]
Steps to reproduce in v3.0.9:
1. Create a form with a required checkbox
2. Try to submit the form.

**Comment by jameslaws** [comment]
I just tried this locally and I can't reproduce.

**Comment by ettoredn** [comment]
Try using jQuery v3 (either updating it manually or using jQuery Updater). That's what makes it throw the validation error.

**Comment by jameslaws** [comment]
I'm not sure about all that, but we only support the version that ships with the most recent version of WordPress. That is the only one that should be used as far too many plugin expect it.

**Comment by kstover** [comment]
Make sure that you are firing a .change() event on the element. Just changing the checked or unchecked state won't update the data model behind the form.

**Comment by ettoredn** [comment]
Checking/unchecking the checkbox by clicking it works as expected. The validation error is thrown when the form is submitted by clicking the submit button.
On Oct 13, 2016 03:32, Kevin Stover <notifications@github.com> wrote:Make sure that you are firing a .change() event on the element. Just changing the checked or unchecked state won't update the data model behind the form.

**Comment by mgallardo** [comment]
Same error here 👎  cannot use the form with this bug :-(

**Comment by followfung** [comment]
I've just run into this bug as well (I was running 1.12.4). As @jameslaws has mentioned, downgrading to the version of jQuery that ships with WordPress fixed it.

**Comment by danielsepp** [comment]
Still an issue.
WP 4.7 comes with 1.12.4 so no downgrading.

**Comment by simonpeters** [comment]
Have the same issue with WP 4.7

**Comment by h-plus-arry** [comment]
Problem is maybe in the fieldCheckbox.js in the function beforeUpdateField
```javascript
		beforeUpdateField: function( el, model ) {
			var checked = jQuery( el ).attr( 'checked' );
```
**var checked** will remain in its inital State in newer Versions of jQuery (because the attr() function does not take property values into account anymore )
so a possible fix would be to use prop() instead of attr()

```javascript
		beforeUpdateField: function( el, model ) {
			var checked = jQuery( el ).prop( 'checked' );
```
