### ISSUE TITLE
Submission Column screen options not being saved on a per form basis

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#1945]
When you save a forms submissions columns under screen options, they are saved a piece of user meta. The problem is when you save another forms submission display columns it overwrites the previous one. These need to be saved on a per form basis. This is also related to this issue: https://github.com/wpninjas/ninja-forms/issues/1899

Both of these things worked in 2.9.x and were not properly ported over for 3.0.

**Comment by kstover** [comment]
This was released in a previous version. This issue didn't get closed.
