### ISSUE TITLE
Date picker field z-index issue when used in popups/modals.

### ISSUE THREAD

**Issue by danieliser** [wpninjas/ninja-forms#1953]
The datepicker CSS appears to set the z-index much too low for use with popup plugins such as Popup Maker.

The default z-index of a popup is 1999999999 (https://github.com/PopupMaker/Popup-Maker/blob/master/assets/css/site.css#L58).

We do this simply to ensure its above everything else as it should be.

Not sure if the solution is to modify your datepicker styles to increase it above that or for use to add a specific CSS tweak on our end.

The reason I am not sure it should be on our end is most datepickers render the interface by appending it to the <body> and not inside the popup. Thus our changes would effect it globally as well, so may as well be in your end.

I don't see any apparent adverse effects to this change.

**Comment by jameslaws** [comment]
It seems like the easiest solution would be to insert a css rule in Popup Maker like:

.pika-single {
  z-index: 19999999999;
}

**Comment by danieliser** [comment]
jameslaws - Sounds good. At least with the issue on here your users can find an easy solution. I will get it added in the next update.
