### ISSUE TITLE
Check for duplicate field_keys

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#1959]
Due to previous publishing issues, duplicate field keys may have been created.

Add checks for duplicate keys:
- [x] Builder
- [ ] Display

Remove any duplicates and update form cache.

This is a temporary solution in response to a major bug and should later be removed and replaced with a refactored model/factory update.

**Comment by kstover** [comment]
Fixed by changing the key generation to a timestamp.
