### ISSUE TITLE
Can't export or download submission

### ISSUE THREAD

**Issue by webguy262** [wpninjas/ninja-forms#1980]
Version 3.0.6 and can't export or download submissions. We have two forms. One never budges from 0%, the other hangs at 50%. Recently moved site to an AWS ec2 using Bitnami WordPress. Sound like a memory issue? If so, any idea where / how to increase memory? Already upped it in php.ini.

**Comment by kjohnson** [comment]
@webguy262 it sounds like there might be a JS or PHP error. Can you submit a support ticket so that our team can take a look? http://ninjaforms.com/contact

**Comment by webguy262** [comment]
Filled out contact form. BTW, I have two forms: omne have only 17 subs, the other 28k. Yesterday, I could not even export the 17 records. It hung at 50%. Today I was able to get those. Exporting the 28k subs still appears to hang at 0% but I leave the page open for a while jik.
