### ISSUE TITLE
"No Error" WordPress error when clicking on Contact Us template

### ISSUE THREAD

**Issue by Quay3** [wpninjas/ninja-forms#1983]
login credentials for a site with this issue in ticket https://github.com/wpninjas/ninja-forms/issues/24548

Replication:
- click Add New Form
- click Contact Us template

Result is a white screen with a box at the top that reads simply: No Error

**Comment by corin12355** [comment]
This is happening with us as well.
Ninja Forms version 3.0.13, WordPress 4.6.1 Multisite

**Comment by PeJak93** [comment]
I have same problem.
I can't add any form. :/

**Comment by kjohnson** [comment]
We are still looking into this issue.

A reproducible pattern has not been yet been found.

**Comment by kjohnson** [comment]
@PeJak93 this should be limited to form templates. Forms can still be built form scratch.

**Comment by Assembly-Brent** [comment]
I had this issue also. Happened after updating wordpress and Ninija forms at the same time. The fix is to deactivate ninja forms, and reactivate it (and if you have the old ninja forms designer plugin, uninstall it)

**Comment by kstover** [comment]
This issue should be taken care of in the current version of Ninja Forms; there was an encoding issue with the form that was saved. If you are still having this issue, please feel free to re-open this issue with the collation type of your database tables.
