### ISSUE TITLE
Ninja Forms not Displaying in IE11

### ISSUE THREAD

**Issue by ion-storm** [wpninjas/ninja-forms#1987]
Ninja Forms 3.0.9 is not displaying in IE11, can you please advise if there is a known bug or setting for Internet Explorer to show the form?
Thanks

**Comment by Basilakis** [comment]
IE is not supported even from Microsoft, this here should be closed.

**Comment by kjohnson** [comment]
We are investigating some IE related issues. Specifically, some standard JS functions are not included with IE.

**Comment by roborourke** [comment]
IE11 is still pretty widely used. Would at least be good to get a list of the unsupported functions used so they can be polyfilled.
