### ISSUE TITLE
How can I delete NINJA FORM PLUGIN completely from wordpress. 

### ISSUE THREAD

**Issue by designandtravel** [wpninjas/ninja-forms#1988]
How can I delete NINJA FORM PLUGIN completely from wordpress. I have uninstalled it but few traces remain, which you can see on website. http://imgur.com/a/tYa8D

![as](https://cloud.githubusercontent.com/assets/22934110/19569119/262fc8dc-9712-11e6-8320-09c4060781a8.png)

**Comment by Basilakis** [comment]
Do you have any cache active?
That seems to be real strange issue, as it has the preview inside.
Can you flush your Permalinks and check if it will get solved?

**Comment by designandtravel** [comment]
Ninja Form Preview Page is gone now by removing its page from my page option of dashboard.
Now, issue left is home+present psge name is coming, as you can see in image, whereas home is clickable.

I checked my menu option - no extra menu is formed over there.
Also, check in Page option - no automatic HOME page is develop over there.

How to remove home (3rd menu look alike thing)?

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
