### ISSUE TITLE
font awesome css breaking label field

### ISSUE THREAD

**Issue by Quay3** [wpninjas/ninja-forms#1989]
Replication:

1) Place the font awesome css  < i class="fa fa-user" aria-hidden="true"></i > into the label space of a field (I added spaces here only so that the line of css won't disappear in the comment)

2) publish form

3) Open setting drawer of the field you altered in step 1. Inside the label space is "<i class=" while "Single Line Text" />" now appears below the label space.

**Comment by kstover** [comment]
This is a symptom of #2029. Closing this issue in favour of that one.
