### ISSUE TITLE
Add Custom Currency Symbol Setting

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1993]
We need to have a setting to allow users to set a custom currency symbol.

**Comment by klhall1987** [comment]
Requested again by [Gregory](https://wpninjas.kustomerapp.com/app/customers/5878ce392498d81000631580/event/5878ce39d6f7121100e68c84)

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
