### ISSUE TITLE
The Year selection in the Date field only shows 20 years

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#1994]
The Year selection in the Date field only shows 20 years (10 before and 10 after) with no scroll bar to select earlier of later years. You are able to select previous years by cycling through he months with the arrows, but the year selection makes it appear that there is only the ability to choose a range of 20 years.

Replications steps:
Add a date field to a form
View the form and click in the date field
Click on the Year and you will only see the options form 10 years before and 10 years after the current year.
### Environment

Home URL:                http://localhost/wordpress3
Site URL:                http://localhost/wordpress3
Ninja Forms Version:     3.0.11
WP Version:              4.6.1
WP Multisite Enabled:    No
Web Server Info:         Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/7.0.8 mod_ssl/2.2.29 OpenSSL/0.9.8zh DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0
PHP Version:             7.0.8
MySQL Version:           5.5.42
PHP Locale:              negative_sign:
WP Memory Limit:         40
WP Debug Mode:           Yes
WP Language:             Default
WP Max Upload Size:      32 MB
PHP Post Max Size:       32
Max Input Nesting Level: 64
PHP Time Limit:          30
PHP Max Input Vars:      1000
SUHOSIN Installed:       No
Server IP Address:       ::1
Host Name:               localhost
SMTP:                    localhost
smtp_port:               25
Default Timezone:        America/New_York
### Plugins

Installed Plugins:
Ninja Forms by The WP Ninjas version 3.0.11

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.

**Comment by jbostoen** [comment]
Getting lots of complaints over this. Only -10 and +10 years compared to selected date (= by default today) are shown.

Today, it shows 2008 - 2028. If you select 2008, it shows 1998 - 2018.

---

Now, if we start by defining the date range: start year = 1900 .
If you use the datepicker now, it shows year = 2018; and if you try to pick a year, it shows 1900-1910.

You could solve this by putting 1900-2018 - but I have quite a few forms where I'd just want it to be between 1900 and <current year>; without having to go over each form to check for these date fields ...
