### ISSUE TITLE
Filter 'ninja_forms_custom_columns' is missing submission ID

### ISSUE THREAD

**Issue by tobiasschutter** [wpninjas/ninja-forms#2003]
The `apply_filters( 'ninja_forms_custom_columns', $value, $field )` would be more useful if it  also contains the submission ID. Like so: `apply_filters( 'ninja_forms_custom_columns', $value, $field, $sub_id )`.

We are writing an integration with [Admin Columns](https://wordpress.org/plugins/codepress-admin-columns/) for Ninja Forms, but we need this third paramater "Submission ID" to be able to properly hook into to your column output.

I am hoping you guys can add this little change =) We'll make sure to do a pull request as well.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
