### ISSUE TITLE
Adding multiple merge tags causes buggy-seemign behavior

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2011]
When working in calculations or actions, adding a second merge tag always creates the tag at the beginning of the field instead of at the cursor location.  While it technically works, it feels very buggy/broken in practical use.

**Comment by jmcelhaney** [comment]
Also, you are unable to add multiple merge tags unless you click out of the merge tag list and re-open it.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
