### ISSUE TITLE
Field Re-Ordering on Publish

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#2017]
Multiple reports, but nothing confirmed or reproduced locally.

**Comment by kjohnson** [comment]
> I'm running WP 4.5.4 with Ninja Forms 3.0.11, which runs perfectly except for one thing I've encountered multiple times today: when I create a form from scratch (not choosing a template) and I publish it the FIRST the time, it doesn't save the right order of fields.
For example, I created a form:
- input name
- input name 2
- input e-mail
- input address
- input city
- submit

> Then I save, I go to the forms overview list, then I click on edit again and suddenly the order has changed. It is not completely reversed, it looks random. The submit-button I added when saving is at the bottom tho.

> 1. I click to add. Then I click the element to change the name and click
done, then I click to add another etc.
2. I'm adding them directly to the bottom of the list without reordering
before publishing. I added them directly in the right order.

-- 
Reported by: Jeroen Balk
Reference: https://wpninjas.desk.com/web/agent/case/25407

**Comment by dud3sweet** [comment]
`<iframe src="https://player.vimeo.com/video/189060294" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
<p><a href="https://vimeo.com/189060294">Ninja Forms Form Publish Bug</a> from <a href="https://vimeo.com/user24483610">Matrix LLC</a> on <a href="https://vimeo.com">Vimeo</a>.</p>`

**Comment by dud3sweet** [comment]
[This video](https://vimeo.com/189060294) shows the bug occurring with fields reordering, disappearing, and linking together after the form is published in the builder. The bug was reproduced on the demo site running version 3.0.10.

**Comment by jameslaws** [comment]
Can you reproduce on 3.0.11 as that's the current version and I can't reproduce that locally?

**Comment by dud3sweet** [comment]
Can you update the demo site to version 3.0.11? I can reproduce it on my own website where everything is up to date otherwise.

**Comment by dud3sweet** [comment]
[This video on my up to date website](https://vimeo.com/189077011#t=510s) shows me reproducing the bug. You can see the version 3.0.11 shown in my settings at the very beginning of the recording.

**Comment by dud3sweet** [comment]
[This video](https://vimeo.com/189833172) shows me reproducing the bug after updating to 3.0.12 on my website.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
