### ISSUE TITLE
Calculations not appearing under conditional logic in Emails & Actions tab

### ISSUE THREAD

**Issue by Quay3** [wpninjas/ninja-forms#2018]
To reproduce:

1) Create a calculation

2) Create an email action (or a success message or redirect action)

3) In the Conditional Logic options of the action, there is a "Calculations" header but the calculations themselves do not show up.

This was patched and is working properly under Advanced>Conditional Logic, but not under Emails & Actions.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
