### ISSUE TITLE
Really long submissions columns

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#2019]
Hey

Here is an example:

![screen shot 2016-10-26 at 22 24 21](https://cloud.githubusercontent.com/assets/5323259/19743856/51e292ee-9bcb-11e6-85c7-614f9fd2b7ca.png)

One field the Message field contains a lot of text. As I scroll down the page the message field for each take up a lot of space. It would be nice with a way to click the entry and have it show the full text. Or have a limited view to get an overview of many submissions at once.

**Comment by jameslaws** [comment]
There is a simple fix. Click on screen options and uncheck any fields that don't display well in a table format.

**Comment by paaljoachim** [comment]
Ok.

I just noticed a submissions bug I will post in another issue.

**Comment by wpnzach** [comment]
related to #1899
