### ISSUE TITLE
Conditionally Hidden Fields Displayed on Tab Focus

### ISSUE THREAD

**Issue by iansvo** [wpninjas/ninja-forms#2020]
**Problem**
Fields that have been added via Conditional Logic are toggled visible when tabbing from the previous field.

**Replication Steps**
1. See example URL: http://setzerandcochran.mycfmediasite.com/patient-forms/hipaa-consent/
2. Click into (focus) the Your Email Field
3. Press the Tab key
4. Observe two new fields that are visible, with validation warnings, that appear below the checkbox.

See screencast: http://www.screencast.com/t/GqbSAszCSup

**Comment by iansvo** [comment]
Its important to note that this only happens on tab. The issue doesn't occur if you just click to the next field.

**Comment by Basilakis** [comment]
Possible duplicate #2018

**Comment by iansvo** [comment]
I'm not really seeing how those two are related, as the issues appear to be about different issues.

#2018 refers to Email & Actions, this issue relates to form fields on the front-end.

**Comment by Basilakis** [comment]
From what I understand, the problem is the same coding related. :)

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
