### ISSUE TITLE
Empty submission when first submitting a form

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#2021]
Reproduction Steps:
1. Create a new form. In my case I created two forms. One with just a star rating and one with a single textbox.
2. Submit the form a few times in a row.
3. View submissions in the admin and note the empty submissions: https://db.tt/Pv0NDjUA

Ironically enough, these empty submissions have appropriate sequential numbers (#2001). The actual submissions all show zero.

**Comment by kjohnson** [comment]
Could not reproduce.

I think this is old data, which explains both the sequential numbers and the old submission date.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
