### ISSUE TITLE
Submissions bug

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#2025]
Hey

I opened a submission and saw this:

![screen shot 2016-10-28 at 16 41 59](https://cloud.githubusercontent.com/assets/5323259/19810393/90947d32-9d2d-11e6-9453-fe4ef469bc2c.png)

![screen shot 2016-10-28 at 16 42 11](https://cloud.githubusercontent.com/assets/5323259/19810399/99cec376-9d2d-11e6-9a20-992014b4d305.png)

 Warning: in_array() expects parameter 2 to be array, string given in /Users/joachim/Documents/Websites/easywebdesigntutorials.dev/wp-content/plugins/ninja-forms/includes/Fields/ListCheckbox.php on line 37
Call Stack
# Time    Memory  Function    Location

1   0.0032  412096  {main}( )   ../post.php:0
2   1.1036  89461136    include( '/Users/joachim/Documents/Websites/easywebdesigntutorials.dev/wp-admin/edit-form-advanced.php' )   ../post.php:173
3   1.3252  91132224    do_meta_boxes( )    ../edit-form-advanced.php:693
4   1.3263  91134304    call_user_func:{/Users/joachim/Documents/Websites/easywebdesigntutorials.dev/wp-admin/includes/template.php:1045} ( )   ../template.php:1045
5   1.3263  91134504    NF_Admin_CPT_Submission->fields_meta_box( ) ../template.php:1045
6   1.3354  91226640    Ninja_Forms::template( )    ../Submission.php:235
7   1.3356  91242864    include( '/Users/joachim/Documents/Websites/easywebdesigntutorials.dev/wp-content/plugins/ninja-forms/includes/Templates/admin-metabox-sub-fields.html.php' )   ../ninja-forms.php:583
8   1.3385  91248232    NF_Fields_ListCheckbox->admin_form_element( )   ../admin-metabox-sub-fields.html.php:23
9   1.3396  91255736    in_array ( )    ../ListCheckbox.php:37

Using Desktop Server
Chrome
Ninja Forms 3.0.11

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
