### ISSUE TITLE
Disabled Actions are still processing on submission

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#2026]
Email Actions are still sending on submission even when Disabled
Save data Action is still saving the data to the database on submission when the action is disabled.

Reproduction steps:
Create a form with a single line text and a submit
Create an email action and set it as disabled
Set the Save Submission Data to disabled
Submit the form and an email will be sent from the disabled Email Action and the submission will save to the database.

### Environment ###
Home URL:                http://localhost/wordpress3
Site URL:                http://localhost/wordpress3
Ninja Forms Version:     3.0.11
WP Version:              4.6.1
WP Multisite Enabled:    No
Web Server Info:         Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/7.0.8 mod_ssl/2.2.29 OpenSSL/0.9.8zh DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0
PHP Version:             7.0.8
MySQL Version:           5.5.42
PHP Locale:              negative_sign:
WP Memory Limit:         40
WP Debug Mode:           Yes
WP Language:             Default
WP Max Upload Size:      32 MB
PHP Post Max Size:       32
Max Input Nesting Level: 64
PHP Time Limit:          30
PHP Max Input Vars:      1000
SUHOSIN Installed:       No
Server IP Address:       ::1
Host Name:               localhost
SMTP:                    localhost
smtp_port:               25
Default Timezone:        America/New_York

### Plugins ###
Installed Plugins:       Ninja Forms by The WP Ninjas version 3.0.11

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/581292c8cffc051100889442/event/581292c80b0ff41100318245

**Comment by kjohnson** [comment]
Could not reproduce.

**Comment by jmcelhaney** [comment]
This only happens when Conditional Logic is active, so it has been moved to the Condtional Logic repo. https://github.com/wpninjas/ninja-forms-conditional-logic/issues/137
