### ISSUE TITLE
Set field model order explicitly to integer

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#2034]
Sometimes the server localises fields' "order" attribute as a string rather than an integer. The field model js should just use parseInt() to force an integer.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
