### ISSUE TITLE
Ninja Forms test values query string is not working

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2040]
When the Ninja Forms test values query string is used on a preview it's breaking my form and throwing the console error detailed in the image below. I have tried it on forms that have been published to pages as well, it's not breaking the form there but it does not populate the test values either. 

Screenshot: 
![screen shot 2016-11-03 at 9 38 14 am](https://cloud.githubusercontent.com/assets/9393977/19968287/52aa0b1e-a1aa-11e6-9aa9-775e1b91ba2d.png)

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
