### ISSUE TITLE
Number fields will not validate if step value other than 1 is used

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2042]
![image](https://cloud.githubusercontent.com/assets/7498743/19969609/9e1e26a2-a1af-11e6-9f30-7269aa0e860f.png)

See in the above image.

A step value of 0.01 is set, I cannot get the number field to validate.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
