### ISSUE TITLE
Page is not scrolled up upon submission

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#2043]
Long forms, when submitted, leave the success message out of view.

> My form takes some space, so user is expected to scroll down to "Submit" button. Submission works as expected, but unfortunately page is not scrolled up to where "Thanks for submission" message is.

Reference: https://wpninjas.desk.com/web/agent/case/24916
Reported by: Oleg Mezhov

**Comment by wpnzach** [comment]
related to #1860
