### ISSUE TITLE
Select list calc values cause calc merge tags to fail in actions

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#2044]
Reproduction steps:

1. Create a form with a select list.
1. Create a calculation based upon that select list
1. Add the merge tag for that calculation to your form's success message. {calc:variable_name}
1. Preview the form and submit.
1. The calc variable will be empty.

**Comment by jameslaws** [comment]
I can't reproduce this locally, but I have certainly seen that calcs have not been passed to actions for many, many users.

While making sure this works consistently, we also need to add the calc merge tags to the merging selector so it can more easily be used.

**Comment by kstover** [comment]
This was fixed in a recent update, but this issue wasn't closed.
