### ISSUE TITLE
Add A Session Manager

### ISSUE THREAD

**Issue by BFTrick** [wpninjas/ninja-forms#205]
For certain functionality we might need a session manager. Stuff like storing the [UTM tracking codes](http://blog.hubspot.com/marketing/what-are-utm-tracking-codes-ht), the users page history, perhaps fields from previous forms, etc.

You could use the global `$_SESSION` but that has issues on managed hosts. A couple of potential solutions here:

1. Eric Mann wrote [WP-Session-Manager](https://github.com/ericmann/wp-session-manager) which is a plugin but could be pulled into Ninja Forms. WooCommerce uses a modified version of Eric's implementation.
1. There's also a Session Manager [within EDD](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/41e1d84cf98a2e278f099db78c65464239e17b90/includes/class-edd-session.php).

Do you have any thoughts on this @pippinsplugins ? Is it better to go with one rather than the other?

**Comment by BFTrick** [comment]
I've had several requests over the last month to store data in the session. Would love to get this added to NF. :)

**Comment by kstover** [comment]
I've added this in the feature/wp-session branch. It is slated to go into version 2.9.17.
