### ISSUE TITLE
Duplicated form with conditional logic loses conditionals and breaks form display

### ISSUE THREAD

**Issue by tankadesign** [wpninjas/ninja-forms#2051]
I have a form which was originally converted from a 2.9 form. I have since replaced many of the fields because the conversion has weird issues. But some old fields probably remain. The form had some conditional logic (hide one field if another field has a certain value, nothing crazy). I then duplicated this form and began editing it. When I displayed the form on a page it didn't load. I check the Conditional Logic button on the Advanced tab and it wasn't clickable, until I clicking on another button first to open the editing panel. Then I could click on Conditional Logic. There were conditions set and clicking the Add Condition button wouldn't work.

Here's the JS error that's caused which I click on the Conditional Logic button the first time after the tab first loads.
![screenshot](https://cloud.githubusercontent.com/assets/3287994/19983644/2e45736c-a1e1-11e6-9758-994280cb59c4.jpg)

**Comment by kstover** [comment]
This should be fixed with the latest version of Conditional Logic. If it isn't, please create a support ticket on our site ninjaforms.com.
