### ISSUE TITLE
Submit button loses custom classes after submission

### ISSUE THREAD

**Issue by leecollings** [wpninjas/ninja-forms#2056]
I am adding custom classes to the submit button to work with Bootstrap, and they appear fine when the page is loaded:

    <input type="submit" name="_ninja_forms_field_37" class="ninja-forms-field  btn btn-primary btn-block" id="ninja_forms_field_37" value="Add me to the newsletter" rel="37">

But if I submit this form (even by not entering anything, so resulting in the error message as I have required fields), after submission is clicked, the button appears like this:

    <input type="submit" name="_ninja_forms_field_37" class=" " id="ninja_forms_field_37" value="Add me to the newsletter" rel="37">

(Note the classes have gone, and the button just appears in default styling).

No confirmation messages with Mailchimp addon
Also, there's no confirmation message shown when using a form with the Mailchimp add on. I would expect to see a success message after a form completion, or an error message if the user exists. But there's nothing. After the form is submitted, it just re-appears as a blank form as if the page has just re-loaded.

**Comment by kstover** [comment]
Hey @leecollings, could you open up a support ticket on our site: ninjaforms.com if this is still an issue?
