### ISSUE TITLE
Error message Mailchimp API invalid when saving NF settings

### ISSUE THREAD

**Issue by leecollings** [wpninjas/ninja-forms#2057]
Whenever I click 'Save' on the Settings page, I get a message saying:

The API key you have entered appears to be invalid. Please go back and re-enter it. Error message: You must provide a MailChimp API key

But my Mailchimp API key is correct. Also, If I go to the Add Ons page, i have a message saying 

MailChimp requires an update. You have version 3.0.1 installed. The current version is 3.0.3.

But there's no way to update the add-on... ?

**Comment by grappler** [comment]
@leecollings You need to download the update from your account.

**Comment by ryanaddams** [comment]
I'm having the same issue, and I have the latest version (3.0.3), and the Mailchimp API key is correct.

**Comment by kstover** [comment]
Hey @leecollings, @ryanaddams, could you open up a support ticket on our site: ninjaforms.com if this is still an issue?
