### ISSUE TITLE
Help Text not showing when mousing over the icon

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#2058]
Help Text not showing when mousing over the icon
Error in the console: Uncaught TypeError: jQuery(...).jBox is not a function(…)  coming from the file: /ninja-forms/assets/js/min/controllers/helpText.js

Replication steps:
Add a text-box field to the form
Add help text to the field
View the form on the front-end and you will see that the Help Text not showing when mousing over the icon

### Environment ###
Home URL:                http://localhost/wordpress3
Site URL:                http://localhost/wordpress3
Ninja Forms Version:     3.0.14
WP Version:              4.6.1
WP Multisite Enabled:    No
Web Server Info:         Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/7.0.8 mod_ssl/2.2.29 OpenSSL/0.9.8zh DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0
PHP Version:             7.0.8
MySQL Version:           5.5.42
PHP Locale:              negative_sign:
WP Memory Limit:         40M
WP Debug Mode:           Yes
WP Language:             Default
WP Max Upload Size:      32 MB
PHP Post Max Size:       32M
Max Input Nesting Level: 64
PHP Time Limit:          30
PHP Max Input Vars:      1000
SUHOSIN Installed:       No
Server IP Address:       ::1
Host Name:               localhost
SMTP:                    localhost
smtp_port:               25
Default Timezone:        America/New_York

### Plugins ###
Installed Plugins:       Ninja Forms by The WP Ninjas version 3.0.14

**Comment by Lynnsy57** [comment]
Similar problem on all forms where this was not an issue before I updated the plugin 1 day ago.

**Comment by jameslaws** [comment]
The full error I get is: TypeError: jQuery(this).jBox is not a function. (In 'jQuery(this).jBox("Tooltip",{theme:"TooltipBorder",content:jQuery(this).data("text")})', 'jQuery(this).jBox' is undefined)

@kjohnson Is this something might have been broken by your pass to check settings to determine what to enqueue?
