### ISSUE TITLE
Additional Field Data Not Considered in PHP

### ISSUE THREAD

**Issue by davekiss** [wpninjas/ninja-forms#2062]
I'm following [this procedure](http://developer.ninjaforms.com/codex/field-submission-data/) to add additional submission data to a field, and while it submits with the request okay, it is no longer getting picked up on the server.

My guess is that this behavior regressed with the introduction of https://github.com/wpninjas/ninja-forms/commit/70dbbb56c0b027aa8f67f3130df20f122e49969c#diff-7abec66a11d2ab1ee52c46078e68cb20

**Comment by kjohnson** [comment]
Seems to be resolved, at least with v3.0.15 (current release).
