### ISSUE TITLE
Conditionals + Email actions

### ISSUE THREAD

**Issue by tankadesign** [wpninjas/ninja-forms#2064]
Using latest versions (core: 3.0.14, conditionals: 3.0.8) of plugins with activated add-ons.
I have 2 email actions set that have different messages based on user input. A radio button field has **Yes** or **No** values. Each email action has a single conditional that is set to Process the action when the value is either **Yes** or **No** for the radio button field. Submitting the form produces no email.

![test](https://cloud.githubusercontent.com/assets/3287994/20023780/b4c5ae3e-a2b8-11e6-946d-0b65469b9344.jpg)

If I change the conditional to be negatives instead, **Don't Process** when the opposite is true, then I get both emails - so it just ignores the conditional altogether. If one is set to **Don't Process** I get the other email no matter what the conditional is set to.

**Don't Process** seems to be getting ignored no matter what, which I've never used before but was hoping it would solve the first problem.
![dontprocess](https://cloud.githubusercontent.com/assets/3287994/20023888/44e23230-a2b9-11e6-864a-9a749152a9c9.jpg)

Attached is a basic test form.
[nf_form_11_04_2016.nff.json.zip](https://github.com/wpninjas/ninja-forms/files/572731/nf_form_11_04_2016.nff.json.zip)

**Comment by kjohnson** [comment]
Fixed in Conditional Logic v3.0.9.
