### ISSUE TITLE
Font size accessibility

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#2065]
>  **SortSite Results**
> 
> Use relative rather than absolute units in CSS property values. - WCAG 2.0 AA 1.4.4<http://www.w3.org/TR/WCAG20/#visual-audio-contrast-scale>
Absolute units are CM, MM, IN, PC and PT. When used with fonts PX is also considered an absolute unit, because it isn't relative the user's preferred font size. Low-vision users, and a lot of people over 50, increase the browser default font size to make text easier to read. Absolute units ignore this user choice. Relative units like EM and percentages "stretch" according to the screen size and/or user's preferred font size, and work on a large range of devices.
>
> *…ninja-forms/assests/css/display-structure.css?ver=4.6.1* on lines: 63, 151, 304, 421, 494
>
> Simply changing these font sizes to em or rem would clear that up.

Reference: https://wpninjas.desk.com/web/agent/case/25591
Reported by: Eric Cox

**Comment by jameslaws** [comment]
Closed until we do a full accessibility audit.
