### ISSUE TITLE
Redirect page field shortcodes

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#2069]
Being that we have session issues with the field merge tags on redirect pages, there must be a better way to handle this need.

Two options come to mind:

1. Use query strings in the redirect action to map specific data to be accessible to the page.

2. Modify the redirect to post form data to the page.

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/58a6c80faf1a5011001e3979/event/58a6c80faf1a5011001e397b

**Comment by kjohnson** [comment]
@jmcelhaney for option 1, there is an existing solution for accessing URL Parameters (querystring values) with a shortcode: https://wordpress.org/plugins/url-params/

**Comment by kstover** [comment]
Moved to the internal feature request tracker.
