### ISSUE TITLE
File Uploads not working on 3.x

### ISSUE THREAD

**Issue by tankadesign** [wpninjas/ninja-forms#2072]
I've tested this on a new site under WP multisite and patently doesn't work. Files are uploaded to a tmp directory in the correct upload directory but are never processed. They don't appear in the File Uploads section of the admin and are never transferred out of the tmp directory. File Uploads used to work flawlessly on my setup with 2.x.

**Comment by rwmichel** [comment]
Experiencing this same issue too, as well as other major issues with File Uploads 3.x.  WPNinjas, please acknowledge that this issue is being addressed.

**Comment by jameslaws** [comment]
This should be working as of the latest Ninjas Forms release. We have no reports stating otherwise and works for me in my installs.

**Comment by tankadesign** [comment]
Any way to bug test on our side? Like a log we can look at? Saying it works for you is nice and all, but helps no one.

**Comment by jameslaws** [comment]
What version of Ninja Forms and File Uploads are you currently testing on?

**Comment by tankadesign** [comment]
Core: 3.0.14
FU: 3.0.4

**Comment by tankadesign** [comment]
Confirmed that this works fine with 2.9 after I used rollback.

**Comment by jameslaws** [comment]
There is likely your issue. Ninja Forms is on 3.0.15.
