### ISSUE TITLE
Calculations missing in 'Insert Merge Tag' menu for default value of Hidden Field

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2079]
1. Create form with hidden field and some other fields.
2. Create new calculation.
3. Try to update default value of hidden field using Insert Merge Tag menu in form editor.
4. Scroll down in the Insert Merge Tag menu - no Calculations are listed. When you type calculation merge tag manually as default value, calculation merge tag works as expected. HTML field has the same Insert Merge Tag menu, but it contains calculations in it.

**Comment by kstover** [comment]
Closing this for future discussion of where calculation merge tags should show up.
