### ISSUE TITLE
Date Fields and Default Values

### ISSUE THREAD

**Issue by Quay3** [wpninjas/ninja-forms#2080]
There is no Advanced option to set a default value for a date field. We've had a reader from the blog request it (trying to pass a value to it via querystring). I talked to Kyle and he told me to open an issue for it for future reference. So, here it is. Thanks Kyle!

**Comment by lucafabbri** [comment]
It is not clear whether you fixed or not

**Comment by mixter923** [comment]
I'd like to understand how/why this issue was closed without closure (resolution).  Will set default for date fields be available in future release?  Is it available in Premium version of nf?  Is there a work-around?  Thanks in advance for any response.
