### ISSUE TITLE
Calc variables are not sending data to payment gateways if the form cache has been deleted

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2084]
If a calculation variable merge tag is used to send dynamic payment information in a collect payment  action to a payment gateway. If form cache is deleted, then the collect payment action fails. 

Replication Steps(using stripe in this example):
1. Create a form.
2. Add a Email, Credit card, checkbox list, and submit button. 
3. Add calc values to the checkbox list field. 
4 .Go to advanced settings and make a calc value that adds the checkbox list field. 
5. Go to emails and actions tab.
6. Create a collect payment action select stripe. 
7. Set up the collect payment action to use the calculation variable you created. 
8. Publish the form. 
9. Delete the form cache.
10. Preview, fill out the form, submit the form and it will fail to send the data to the payment gateway.

**Comment by jameslaws** [comment]
Is this still an issue?

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
