### ISSUE TITLE
When a long form is submitted with a long success message the it does not go to the top

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#2089]
Steps to reproduce:
1. Create a long form
2. Hide the form on submission
3. Add the all fields to the success message
4. Fill out and submit form

The form submits and does all the basic expected stuff but does not move the page to the top of the success message. This makes it very confusing to users.

**Comment by decanero** [comment]
Workaround: I currently use the following workaround as an interim "patch" for the issue:

1. Place tag <a name="thank_you"></a> -tag at the beginning of the thank you page
2. Insert this script as the first line of your thank you page (text edit mode):

            <script type="text/javascript">
                  window.location.href = "#palaute"
             </script>

This works for me for time being (tested: iphone safari + desktop chrome)

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
