### ISSUE TITLE
Datepicker issues with iOS

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#2097]
> It has been reported to me that people using an iPad are unable to complete forms with a Date field. The field appears grey and they are unable to type anything in the field. I have also just checked with someone else. They get the same issue using an older ipad on IOS version 9.3.5

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
