### ISSUE TITLE
Is this an email address? on email fields

### ISSUE THREAD

**Issue by helgatheviking** [wpninjas/ninja-forms#210]
Was just setting up a form, and this seemed redundant. If you have selected an email field, it seems like you don't need the checkbox to determine if it is an email field. 

Similarly, I don't understand the "is this an email address" on the textbox fields. Why add a text field and set it to be an email when an email field is available? Or is that because the email is considered user info and the textbox "email" is not?

**Comment by kjohnson** [comment]
Email fields in v3 no longer require a 'validate as email' setting.
