### ISSUE TITLE
NinjaForms, Azoom Wordpress theme and modernizr

### ISSUE THREAD

**Issue by juanmatias** [wpninjas/ninja-forms#2101]
I'm using NinjaForms with Azoom theme on Wordpress. 
The problem is that Azoon needs and loads a modernizr version 2.6.2 with addTest function, but Ninja Forms loads hardcoded on file ninja-forms/assets/js/min/front-end-deps.js a hardcoded version of modernizr (3.3.1 without addThis function).
I commented out these lines in order to load my site without problem.

Issue:
1. Install Wordpress with Azoom theme
2. Install NinjaForms and create some form
3. Try to load form page and look into console, modernizr.addTest is not a function (but it is called by Azoom components)

While Azoom loads modernizr 2.6.2 if you add Modernizr object to watchlist it can be observed that the loaded modernizr is 3.3.1 and has no addTest function.

`/*!
 * modernizr v3.3.1
 */
/* Fix by JMdlCB 8 nov 2016
 * !function(e,t,n){function r(e,t){return typeof e===t}function o(){var e,t,n,o,i,s,u;for(var a in h)if(h.hasOwnProperty(a)){if(e=[],t=h[a],t.name&&(e.push(t.name.toLowerCase()),t.options&&t.options.aliases&&t.options.aliases.length))for(n=0;n<t.options.aliases.length;n++)e.push(t.options.aliases[n].toLowerCase());for(o=r(t.fn,"function")?t.fn():t.fn,i=0;i<e.length;i++)s=e[i],u=s.split("."),1===u.length?g[u[0]]=o:(!g[u[0]]||g[u[0]]instanceof Boolean||(g[u[0]]=new Boolean(g[u[0]])),g[u[0]][u[1]]=o),C.push((o?"":"no-")+u.join("-"))}}function i(){return"function"!=typeof t.createElement?t.createElement(arguments[0]):b?t.createElementNS.call(t,"http://www.w3.org/2000/svg",arguments[0]):t.createElement.apply(t,arguments)}function s(){var e=t.body;return e||(e=i(b?"svg":"body"),e.fake=!0),e}function u(e,n,r,o){var u,a,l,f,p="modernizr",d=i("div"),c=s();if(parseInt(r,10))for(;r--;)l=i("div"),l.id=o?o[r]:p+(r+1),d.appendChild(l);return u=i("style"),u.type="text/css",u.id="s"+p,(c.fake?c:d).appendChild(u),c.appendChild(d),u.styleSheet?u.styleSheet.cssText=e:u.appendChild(t.createTextNode(e)),d.id=p,c.fake&&(c.style.background="",c.style.overflow="hidden",f=_.style.overflow,_.style.overflow="hidden",_.appendChild(c)),a=n(d,e),c.fake?(c.parentNode.removeChild(c),_.style.overflow=f,_.offsetHeight):d.parentNode.removeChild(d),!!a}function a(e){return e.replace(/([a-z])-([a-z])/g,function(e,t,n){return t+n.toUpperCase()}).replace(/^-/,"")}function l(e,t){return function(){return e.apply(t,arguments)}}function f(e,t,n){var o;for(var i in e)if(e[i]in t)return n===!1?e[i]:(o=t[e[i]],r(o,"function")?l(o,n||t):o);return!1}function p(e,t){return!!~(""+e).indexOf(t)}function d(e){return e.replace(/([A-Z])/g,function(e,t){return"-"+t.toLowerCase()}).replace(/^ms-/,"-ms-")}function c(t,r){var o=t.length;if("CSS"in e&&"supports"in e.CSS){for(;o--;)if(e.CSS.supports(d(t[o]),r))return!0;return!1}if("CSSSupportsRule"in e){for(var i=[];o--;)i.push("("+d(t[o])+":"+r+")");return i=i.join(" or "),u("@supports ("+i+") { #modernizr { position: absolute; } }",function(e){return"absolute"==getComputedStyle(e,null).position})}return n}function m(e,t,o,s){function u(){f&&(delete N.style,delete N.modElem)}if(s=r(s,"undefined")?!1:s,!r(o,"undefined")){var l=c(e,o);if(!r(l,"undefined"))return l}for(var f,d,m,v,h,y=["modernizr","tspan","samp"];!N.style&&y.length;)f=!0,N.modElem=i(y.shift()),N.style=N.modElem.style;for(m=e.length,d=0;m>d;d++)if(v=e[d],h=N.style[v],p(v,"-")&&(v=a(v)),N.style[v]!==n){if(s||r(o,"undefined"))return u(),"pfx"==t?v:!0;try{N.style[v]=o}catch(g){}if(N.style[v]!=h)return u(),"pfx"==t?v:!0}return u(),!1}function v(e,t,n,o,i){var s=e.charAt(0).toUpperCase()+e.slice(1),u=(e+" "+z.join(s+" ")+s).split(" ");return r(t,"string")||r(t,"undefined")?m(u,t,o,i):(u=(e+" "+O.join(s+" ")+s).split(" "),f(u,t,n))}var h=[],y={_version:"3.3.1",_config:{classPrefix:"",enableClasses:!1,enableJSClass:!1,usePrefixes:!1},_q:[],on:function(e,t){var n=this;setTimeout(function(){t(n[e])},0)},addTest:function(e,t,n){h.push({name:e,fn:t,options:n})},addAsyncTest:function(e){h.push({name:null,fn:e})}},g=function(){};g.prototype=y,g=new g;var C=[],_=t.documentElement,w=y._config.usePrefixes?" -webkit- -moz- -o- -ms- ".split(" "):["",""];y._prefixes=w;var b="svg"===_.nodeName.toLowerCase(),x=i("input"),S="search tel url email datetime date month week time datetime-local number range color".split(" "),E={};g.inputtypes=function(e){for(var r,o,i,s=e.length,u="1)",a=0;s>a;a++)x.setAttribute("type",r=e[a]),i="text"!==x.type&&"style"in x,i&&(x.value=u,x.style.cssText="position:absolute;visibility:hidden;",/^range$/.test(r)&&x.style.WebkitAppearance!==n?(_.appendChild(x),o=t.defaultView,i=o.getComputedStyle&&"textfield"!==o.getComputedStyle(x,null).WebkitAppearance&&0!==x.offsetHeight,_.removeChild(x)):/^(search|tel)$/.test(r)||(i=/^(url|email)$/.test(r)?x.checkValidity&&x.checkValidity()===!1:x.value!=u)),E[e[a]]=!!i;return E}(S);var T=y.testStyles=u;g.addTest("touchevents",function(){var n;if("ontouchstart"in e||e.DocumentTouch&&t instanceof DocumentTouch)n=!0;else{var r=["@media (",w.join("touch-enabled),("),"heartz",")","{#modernizr{top:9px;position:absolute}}"].join("");T(r,function(e){n=9===e.offsetTop})}return n});var A=function(){function e(e,t){var o;return e?(t&&"string"!=typeof t||(t=i(t||"div")),e="on"+e,o=e in t,!o&&r&&(t.setAttribute||(t=i("div")),t.setAttribute(e,""),o="function"==typeof t[e],t[e]!==n&&(t[e]=n),t.removeAttribute(e)),o):!1}var r=!("onblur"in t.documentElement);return e}();y.hasEvent=A;var k="Moz O ms Webkit",O=y._config.usePrefixes?k.toLowerCase().split(" "):[];y._domPrefixes=O;var z=y._config.usePrefixes?k.split(" "):[];y._cssomPrefixes=z;var P=function(t){var r,o=w.length,i=e.CSSRule;if("undefined"==typeof i)return n;if(!t)return!1;if(t=t.replace(/^@/,""),r=t.replace(/-/g,"_").toUpperCase()+"_RULE",r in i)return"@"+t;for(var s=0;o>s;s++){var u=w[s],a=u.toUpperCase()+"_"+r;if(a in i)return"@-"+u.toLowerCase()+"-"+t}return!1};y.atRule=P;var L={elem:i("modernizr")};g._q.push(function(){delete L.elem});var N={style:L.elem.style};g._q.unshift(function(){delete N.style}),y.testAllProps=v;var R=y.prefixed=function(e,t,n){return 0===e.indexOf("@")?P(e):(-1!=e.indexOf("-")&&(e=a(e)),t?v(e,t,n):v(e,"pfx"))};g.addTest("forcetouch",function(){return A(R("mouseforcewillbegin",e,!1),e)?MouseEvent.WEBKIT_FORCE_AT_MOUSE_DOWN&&MouseEvent.WEBKIT_FORCE_AT_FORCE_MOUSE_DOWN:!1}),o(),delete y.addTest,delete y.addAsyncTest;for(var U=0;U<g._q.length;U++)g._q[U]();e.Modernizr=g}(window,document);
 * 
 * */ `

This way it works without any issue.
Maybe Ninja Forms should test if modernizr is already loaded before load it.

Thanks

**Comment by shaylash** [comment]
Hi,

Just to let you know that I have the same problem with Modernizr.mq not a function on pages where ninja form is present. 


Thanks for your great work!!!

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
