### ISSUE TITLE
Cannot upgrade ninja forms after rollback

### ISSUE THREAD

**Issue by wolfman66** [wpninjas/ninja-forms#2102]
I installed a theme that came with Ninja Forms. After issues with version 3.0.1.5 I tried rolling back. The theme was never built with the previous version 2.9X.
Now I cannot upgrade to version 3.
My install shows that v 3.0.1.5 is installed but the interface and tools are v2.9 ones.
I have cleared all caches in wordpress and uninstalled with option to remove data which obviously does not work.
Any suggestions?

**Comment by kjohnson** [comment]
@wolfman66 when you say that you cannot upgrade, are you not able to get tot he upgrade page, or are is the upgrade page breaking?

**Comment by wolfman66** [comment]
I can get to the upgrade page, but the upgrade does not work when clicking
the "upgrade button"


Regards
Adam Wolfson
*_______________*


*Adam Wolfson (Principal) *


*MPRE (Master Practitioner In Real Estate), PGDFP (Postgraduate Diploma In
Financial Planning) (NQF 7)**208 Darrenwood Heights, Edgeworth Lane,
Darrenwood, 2194. *

*O: +27 87 550 1705 ; F: +27 866 227 944. C: +27 79 048
6085.**www.allrealty.co.za
<http://www.allrealty.co.za>*
<https://www.privyseal.com/za/adam-ezra-wolfson/eaab-estate-agent/1c>

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.

**Comment by deeannalynn** [comment]
I am having this very same issue. I rolledback to 2.9 and now I can't get back to the new 3.1 version, the UI is stuck in 2.9 even though I updated the plugin, deactivated it, deleted, reinstalled... nothing is working.
I need serious help!

**Comment by jameslaws** [comment]
Support is handled at https://ninjaforms.com/contact/

Our team will be happy to assist you there.
