### ISSUE TITLE
Field Wrap Styles not Applying

### ISSUE THREAD

**Issue by iansvo** [wpninjas/ninja-forms#2103]
I noticed that the wrap styles do not appear to be working, when using the Layout & Styles add-on.

I originally noticed this when I was adding Advanced CSS properties that didn't seem to be having an effect and thought I'd double check to be sure.

I tested this by trying to add an orange background to the field wrap. In previous versions, this would've added an orange block behind the element in question or whatever, but this is not happening. I tested this on multiple form fields, all with the same result. I was able to replicate this on both live pages and the preview form page.

NOTE: I tested this with the default 2016 theme and the issue still persists. 

**Replication Steps**

1. Open a form
2. Go to the "wrap styles" for a given element
3. Attempt to apply CSS changes to that element
4. View the live form.

Ninja Forms Version:	3.0.15
Layout & Styles Version: 3.0.11
WP Version:	4.6.1

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
