### ISSUE TITLE
Show media upload button is not displaying on the front end. 

### ISSUE THREAD

**Issue by JoshRiser** [wpninjas/ninja-forms#2106]
I am using THREE and added a Paragraph Text field with Show Rich Text Editor checked on. When visiting the page I get this error.

```
Notice: JavaScript is required for this content.

Fatal error: Call to undefined method NF_Display_Render::form_uses_textarea_media() in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/ninja-forms/includes/Display/Render.php on line 530
```

I'm not sure what the method code is supposed to be so I have no way of using the Rich Text Editor on this field.

Any help?

**Comment by klhall1987** [comment]
Hey @JoshRiser,

We are going to start looking into this issue. I want to let you know I am renaming the issue so it's easier for us to find when looking for it.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
