### ISSUE TITLE
reimplement `ninja_forms_display_field` in Render.php

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#2107]
The filter was accidentally removed during a larger sweep of the Render.php file.

See wpninjas/ninja-forms-vimeo-uploader#10

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.

**Comment by davekiss** [comment]
@jameslaws @kjohnson I've confirmed today that this is still an existing bug, can this be reopened?

**Comment by jameslaws** [comment]
@davekiss Neither @kjohnson nor I are on this project any more, I'll ping @wpnzach to have a look at it.
