### ISSUE TITLE
Add filter for custom form restrictions

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#2109]
Currently, restrictions like `Submission Limit` or `Require Logged In` are hard coded into the render function. This does not allow for custom restriction settings in be added to a form via a plugin.

----

> We use a custom-developed plugin with previous versions that added additional restrictions to forms, namely adding a start and end date for the form to be enabled. I've added the fields to the Restriction section of the forms using 'ninja_forms_from_restriction_settings' filter, but can't seem to locate a means of preventing the form from displaying. Previously, we were setting 'sub_limit_reached' to 'true' and supplying a custom message. Now that that setting is deprecated, I'm having a hard time finding a way to replicate the earlier behavior.
> 
> Jer Brand per [customer submitted ticket](https://wpninjas.kustomerapp.com/app/customers/582b58a64e522a10002c4622/event/582b58a64e522a10002c4624)

This request, specifically, is achievable with [Show/Hide Content Shortcode](https://wordpress.org/plugins/shortcodes-to-show-or-hide-content/) plugins, but other forms of custom restrictions would need this filter.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
