### ISSUE TITLE
Lets gather and have a dugnad!

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#211]
Ok developers. From my impression many of you are busy elsewhere working on paid projects. 3.0 needs a good strong push forward.

Do please have an open developer chat at a time most of you can attend and open for others as well to take part. Similar to the WP core developers are on IRC encouraging each other to work on trac tickets. Ninja Forms developers need something to encourage this strong push forward.

Btw if I am totally off and you guys are close to finishing 3.0 - awesome! But if not then it seems something needs to be done to get this into hyperdrive mode.

Ps Dugnad is a Norwegian expression meaning coming together to work on a project.

**Comment by kstover** [comment]
First, thank you for your enthusiasm, Paal! We have actually been able to get quite a few of the things on the list done. We've changed our approach to releases, and I think it's going much better than before. :)

**Comment by paaljoachim** [comment]
It is great to follow along and contribute with ideas...:)
