### ISSUE TITLE
Add support for South African Rand (currency)

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#2112]
User request via the WordPress Support Forums

> Is it possible to change currency to South African Rand (R)?

----

Reference: https://wordpress.org/support/topic/chance-currency-to-south-african-rand/

**Comment by jmcelhaney** [comment]
https://github.com/wpninjas/ninja-forms/issues/2160

**Comment by Much2tall** [comment]
Appears to be unsupported by PayPal?

https://www.paypal-community.com/t5/Sending-and-receiving-money/SOUTH-AFRICA-RAND-ZAR/td-p/788178
