### ISSUE TITLE
Ampersands in list field option values are causing field to show empty in submission  

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2116]
If an ampersand(&) is used in a list field option value, then it's causing the field to show as empty in the submission.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
