### ISSUE TITLE
Add "disable input" setting for Date Field

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#2117]
> I'd like to be able to disable input. What i want is that the user can only select the from the calendar drop down and not be able to type in to the field.

Requested by [Tracy Hughes](https://wpninjas.kustomerapp.com/app/customers/582b73f2a7c35210002ea126/event/582b73f24e522a10002c53cf)

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
