### ISSUE TITLE
Unable to sort Forms by Date Created

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#2118]
Unable to sort Forms by Date Created. An error occurs when this is attempted:
Notice: Undefined index: updated in /wp-content/plugins/ninja-forms/includes/Admin/AllFormsTable.php on line 168

### Environment ###
Home URL:                http://localhost/wordpress3
Site URL:                http://localhost/wordpress3
Ninja Forms Version:     3.0.15
WP Version:              4.6.1
WP Multisite Enabled:    No
Web Server Info:         Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/7.0.8 mod_ssl/2.2.29 OpenSSL/0.9.8zh DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0
PHP Version:             7.0.8
MySQL Version:           5.5.42
PHP Locale:              negative_sign:
WP Memory Limit:         40M
WP Debug Mode:           Yes
WP Language:             Default
WP Max Upload Size:      32 MB
PHP Post Max Size:       32M
Max Input Nesting Level: 64
PHP Time Limit:          30
PHP Max Input Vars:      1000
SUHOSIN Installed:       No
Server IP Address:       ::1
Host Name:               localhost
SMTP:                    localhost
smtp_port:               25
Default Timezone:        America/New_York

### Plugins ###
Installed Plugins:       Ninja Forms by The WP Ninjas version 3.0.15

**Comment by isleshocky77** [comment]
Currently referencing a field which does not exist. The `updated` below should be `created`.

```php
# /plugins/ninja-forms/includes/Admin/AllFormsTable.php:101
            'date'  => array( __( 'updated', 'ninja-forms' ), TRUE ),
```

**Comment by isleshocky77** [comment]
@jmcelhaney Was your install showing valid dates under "Date Created"? Surprised due to #2061
