### ISSUE TITLE
Bundle Modernizr to avoid conflicts

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#2123]
> It looks from the traces as if you’re using a bundler (RequireJS, Webpack, etc.) to create a main.js; my apologies if that’s not the case.
> 
> If so, then it’s possible to either wrap the version of Modernizr that you’re using in a CommonJS or AMD wrapper or to use the bundler's non-AMD bundling option to pack that into your main.js. Once that’s the case, then it can be required just as any other module as a non browser globals anonymous import, and then you’re insulated from something else on the page loading an incompatible Modernizr version ahead of you.
> 
> Additionally, if you’re depending on Modernizr’s adding detect classes to the body, then it’s possible to use their custom build option to use your own prefix, again, so that you’re insulated against someone else stepping on you, though that tends to be a nonissue in practice.
> 
> We use Modernizr in our own product, and we’ve in the past been impacted by such things as Chrome plugins using their own version of Modernizr. Bundling it as require’d dependency eliminates things like that.
> 
> Unfortunately, Modernizr doesn’t have a noConflict feature as, for example, jQuery does, so we’ve found setting it up as a standard import to be a reliable solution.
>  
> Allan Bazinet

**Comment by kstover** [comment]
We aren't really able to bundle or require this for our use-case, as it's really a summernote dependancy. Unless you're using the RTE on the front-end, you don't need it.

The first step towards a solution would be to only enqueue Modernizr if you are using summernote on the front-end.
