### ISSUE TITLE
`ninja_forms_render_default_value` filter not called on custom forms.

### ISSUE THREAD

**Issue by gelform** [wpninjas/ninja-forms#2132]
I'm trying to pre-populate fields using the `ninja_forms_render_default_value`filter. Fields are pre-populated correctly on the default "Contact Me" form, but not on custom forms.

Steps to reproduce the issue:
1. Add the sample code from http://developer.ninjaforms.com/codex/pre-populating-fields-on-display/
 to `functions.php`:
```
add_filter( 'ninja_forms_render_default_value', 'my_change_nf_default_value', 10, 3 );
function my_change_nf_default_value( $default_value, $field_type, $field_settings ) {
	if( 'textbox' == $field_type ){
		$default_value = 'foo';
	}
	return $default_value;
}
```

2. Preview the default "Contact Me" form.
3. The "Name" single line form field contains "foo" as it should.
4. Add a custom form with a single line form field
5. Preview the custom form.
6. The single line form field is not pre-populated with "foo".

This behavior is the same whether previewing forms, or viewing them embedded in pages.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
