### ISSUE TITLE
Reports of users not being able to update add-ons 

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2135]
I've had a few reports of users not being able to update their add-ons. I've came across the issues a few times now. Usually deactivating and reactivating the license keys resolves the issue. However,  on the users site I've linked to below. I cant get the license to activate after deactivating. I have a report from another user with the same issue. 

Link to Customers Ticket: 
https://wpninjas.kustomerapp.com/app/customers/5808f62f3565c21000f50676/event/582b94a11b567212001fbdd9

**Comment by klhall1987** [comment]
Another ticket that may be affected by this bug: 
https://wpninjas.kustomerapp.com/app/customers/581acca37c6a3e110021e06e/event/5830d2d1da2b7d1100245a7e

**Comment by wpnzach** [comment]
This is not a Ninja Forms bug, I'm going to resolve this.  This is a bug in EDD which has plagued us for a long time and has no discernable cause.
