### ISSUE TITLE
"Use Quantity" setting set to "on/true/enabled" on form edit

### ISSUE THREAD

**Issue by shinerweb** [wpninjas/ninja-forms#2137]
Version 3.0.16 and 3.0.15

When you have a form containing field type(s) of "product" and you set the "Use Quantity" setting to off, when you subsequently edit that form at a later date, on loading, all fields of type "product" will have their "Use Quantity" setting set to "on/true/enabled" regardless of it's previous state. 

Workaround is simple enough in that you just have to make sure to go through any "product" fields and set the "Use Quantity" setting to your desired value prior to your last edit/change/save. 

I've attached a PDF with some screen captures and how to reproduce the problem.

[ninja-forms-QuantityBug1.pdf](https://github.com/wpninjas/ninja-forms/files/606975/ninja-forms-QuantityBug1.pdf)

**Comment by shinerweb** [comment]
Got bit by this one again the other day...  what have I done wrong in that no one has looked as this yet ?
Sorry n00b here :(

**Comment by kjohnson** [comment]
Got another report from a custom ticket.

Confirmed locally and bumping priority.

**Comment by kjohnson** [comment]
Bumping priority again.
