### ISSUE TITLE
Other form's submit buttons disable on field error.

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#2139]
When a field error is added on one form, the submit buttons on other forms are disabled.

The submit button controller does not check the field model's form ID.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
