### ISSUE TITLE
jQuery/Javascript Drag and Drop Fields

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#214]
For the next version, we want to be able to let users drag and drop new fields into their fields list, rather than just clicking to add fields. We also want to add the ability to drag and drop / reorder field rows.

At the moment, we need to find someone who is great at jQuery and JS to take this part of the build over completely. If you're interested in doing this, please let me know asap.

**Comment by kjohnson** [comment]
Psssh. jQuery. :P
