### ISSUE TITLE
Double confirm for form/field deletion

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2141]
Edit and delete are right next to each other on "All Forms" page.  A misclick on "Delete" instantly destroys all form/field data.

**Comment by wpnzach** [comment]
@kstover Can we get this in the next release?  It's way too easy to lose everything in a single click. @echadwilliams just hit us up on Twitter and was a victim to this.

**Comment by kjohnson** [comment]
Another, similar, report came through the support system.

We need to either consider a confirmation, or eventually a "soft delete" system.
