### ISSUE TITLE
Wrap success messages in a more form specific wrap for better styling

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#2144]
Currently we have a div with the class .nf-response-msg that is output at all times. The success message is placed in this. 

When outputting the actual success message we need to also wrap it in a div that is more descriptive. Maybe even also add a class name option to the action so different success messages could be styled differently.

**Comment by Much2tall** [comment]
Success Message also needs to be display:none until the Form has actually been submitted.
Otherwise, styling the margin/padding affects the page.
