### ISSUE TITLE
Allow running actions manually

### ISSUE THREAD

**Issue by sebet** [wpninjas/ninja-forms#2147]
I'm trying to use Ninja Forms on a custom form which has multiple steps. I'm only using Ninja Forms on the first step. After the first step I'm taking control over the output but I would also need to take control over the actions so they run only when the user goes through all the steps.

Currently, I can clear the actions through a filter so they don't run but there's not way to manually run actions afterwards.

I've tried to extend your `NF_AJAX_Controllers_Submission->process()` method but you keep changing it's code and methods so it's not feasible.

If you could provide a way to manually process the actions considering existing form data passed through a parameter it would be great since I could run the actions at any given time.

**Comment by kjohnson** [comment]
@sebet this is something that we are looking into, and already have an issue form. However, I cannot provide a timeline for this feature.

**Comment by sebet** [comment]
@kjohnson, thanks for the reply. Can you please reference the issue so I can track it?
