### ISSUE TITLE
Add South African Rand to currency options

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#2160]

**Comment by skoop** [comment]
isn't that already in there? https://github.com/wpninjas/ninja-forms/blob/develop/includes/Config/CurrencySymbol.php#L164

**Comment by klhall1987** [comment]
I have received another request for this feature. [Ray](https://wpninjas.kustomerapp.com/app/customers/589f13e760730f110006e4e2/event/58a22cad263ef711001b6c62)

**Comment by Quay3** [comment]
I've received another request for this feature as well. It's a blocker for being able to use Ninja Forms if not able to use in their local currency.

https://wpninjas.kustomerapp.com/app/customers/58c283c1e0a3041000b3bd58/event/58c283c2e0a3041000b3bd5a

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/58c3f6fee0a3041000b88735/event/58c687168eea771100a4ee91
