### ISSUE TITLE
Add a URL field type

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#2162]
We do not currently have an html5 url field type.

**Comment by X-Raym** [comment]
@jameslaws Thanks for reporting !
Yes, just a simple http / https kind of text field

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.

**Comment by X-Raym** [comment]
@jameslaws Ok, I understand, but how initial bug or feature request writer will be able to update, discuss or get news about their ticket ?

**Comment by jameslaws** [comment]
Bugs are handled here still. Feature requests are business decisions and when implemented it would be explained in the changelogs and newsletters.
