### ISSUE TITLE
Merge tags not selectable in single-line text fields

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2163]
When editing forms, clicking on merge fields in the embedded drop-down in single line text fields doesn't do anything. Have tested in Firefox, Safari and Chrome with same results. Merge tags populate fine in paragraph/rich editor fields, and copy-pasting those into single-line fields produces the expected results in the form, emails and submission data.

**Comment by kjohnson** [comment]
Could not reproduce locally.
