### ISSUE TITLE
HTML merge tags do not work in email actions

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2164]
HTML merge tags are non-functional: Adding an HTML field merge tag into an email only produes the tag, not the content. Other merge tags work fine.

**Comment by klhall1987** [comment]
Also reported by [Gabriel](https://wpninjas.kustomerapp.com/app/customers/584f52de4fc9031100598425/event/58519b064fc90311005aa203).

**Comment by kjohnson** [comment]
I don't think that the HTML field was intended to be supported by merge tags, if I remember correctly.

This is something that we should discuss, to either support HTML field merge tags or remove them from the list.

**Comment by klhall1987** [comment]
Also reported by [Adam](https://wpninjas.kustomerapp.com/app/customers/58c9cf84ab5832110087d635/event/58c9cf846857e311002dbd54)

**Comment by Quay3** [comment]
Also reported here: https://wpninjas.kustomerapp.com/app/customers/58d8d01e34c7f111000ad3e5/event/58d8d01e705fd4100063ad7d

The HTML field can be selected from the merge tag list but does not work as expected.
