### ISSUE TITLE
File Upload throws JS Error

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#2181]
**Introduced in 3.0.17**
TypeError: e.get is not a function. (In 'e.get("formID")', 'e.get' is undefined)  maybeDisable — submitButton.js:35

**Reproduction:**
1. Add a File Upload Field
2. View the form on the front-end and try to upload a file
3. See console

**Comment by kstover** [comment]
Closed in File Uploads repo.

**Comment by EmilyRandall** [comment]
This error is still occurring.  Is there an ETA for when it will be fixed?

**Comment by austenlennon** [comment]
Complete mess... my site has been screwed by this too TypeError: e.get is not a function. (In 'e.get("formID")', 'e.get' is undefined)

**Comment by dynamicJake** [comment]
Still no fix on this?
