### ISSUE TITLE
Notice being printed when it obviously shouldn't

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#2187]
Full disclosure: I wasn't able to reproduce this locally.

This notice is being printed if you visit a non-existing page on the front-end: Notice: Trying to get property of non-object in /wp-content/plugins/ninja-forms/includes/Admin/Metaboxes/AppendAForm.php
wp-content/plugins/ninja-forms/includes/Admin/Metaboxes/AppendAForm.php on line 19

**Comment by breadadams** [comment]
![image](https://cloud.githubusercontent.com/assets/5795227/21588427/d8758c3a-d0e6-11e6-856c-79ff815fb169.png)

I'm seeing that, from this:

```php
echo apply_filters('the_content', get_the_excerpt($p));
```

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.

**Comment by disinfor** [comment]
Also seeing the same issue:
`echo apply_filters( 'the_content', get_post_field( 'post_content', $id ) );`

![screen shot 2017-06-07 at 12 48 35 am](https://user-images.githubusercontent.com/10200724/26863956-3070989a-4b1b-11e7-8d1f-ac8cc4f33be3.png)
