### ISSUE TITLE
E-mail messages being duplicated / sent multiple times

### ISSUE THREAD

**Issue by Chris1777** [wpninjas/ninja-forms#2191]
Hi there

I've spotted an error in which the same e-mail is being sent multiple times. A month ago i experienced a customer sending the same e-mail 4 times, however since this was a lone case i just thought that he might had sent the same e-mail or had connection issues or something like that (or might have been fixed in newer versions).

However, now i've experienced it again today, and the same e-mail was sent 8 times in a row, immediately after each other. You can see an image of the submissions here: http://imgur.com/2Ow50QS

**Comment by Chris1777** [comment]
In additon to above, the numbers of the submissions are completely wrong/scrambled as can be seen here:
http://imgur.com/a/HPvrI

**Comment by kstover** [comment]
Hey @Chris1777, Sorry for the super-delayed response. If this is still an issue, please open a support ticket on our site: ninjaforms.com.
