### ISSUE TITLE
{post:title} and {post:url} are not working for Email Notifications

### ISSUE THREAD

**Issue by mikehwagz** [wpninjas/ninja-forms#2192]
I currently have one form that is used across multiple pages of a site. I set up email notifications and, in order to know from which page the form was submitted, I added `{post:title}` into the email subject and then `{post:url}` to the body of the email. I've tested this across multiple pages and posts and the email notifications come back without the expected post information.

Does anyone have any insight on this bug?

**Comment by aut0poietic** [comment]
Confirming this bug when used with `Ninja_Forms()->display( $form_id )` directly in a theme's php files. 

Looking for the source of the issue or a workaround...

**Comment by nikonratm** [comment]
Same problem when trying to use "do_shortcode"

Any ideas??

**Comment by nikonratm** [comment]
Cheap work-around is to create a hidden field(s) and set the default values to be {post:title} or whichever post fields you want to use. These can then be included in email actions, etc.

But yea, should be fixed.

**Comment by aut0poietic** [comment]
That didn't work for us -- kept setting the the URL to the `nf_sub` instead of the URL to the post in the email. 

I ended up creating a hidden field, assigning it a unique class name, then polling for form load and setting the value to `document.location.href`.

Nothing I'm terribly proud of, but it got the job done.

**Comment by o1y** [comment]
I think #1814 describes the reason for the problem. The post related merge tags require a Post context. The Post object in this case  is `null`.

**Comment by klhall1987** [comment]
We have a user who reported they need to use this functionality [Roman](https://wpninjas.kustomerapp.com/app/customers/58a723183b4e101100c400da/event/58a723183b4e101100c400dc)

**Comment by klhall1987** [comment]
I tested all the post merge tags and none of them seem to be working.

**Comment by Much2tall** [comment]
Got another report of this

**Comment by kstover** [comment]
Closing because we are currently refactoring merge tags.
