### ISSUE TITLE
Hidden fields have a height (auto) 

### ISSUE THREAD

**Issue by ricemann** [wpninjas/ninja-forms#2193]
If you create a custom field with own template - <nf-field></nf-field> have a height of 5 px / 23 px. Hidden fields are hidden and shouldn't have a height. It is imposible to change this with jQuery. Or CSS to my knowledge

**Comment by kstover** [comment]
Hey @ricemann, Sorry for the super-delayed response. If this is still an issue, please open a support ticket on our site: ninjaforms.com.
