### ISSUE TITLE
Add Fliter to Translate the Datepicker

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2204]
We currently do not have a filter or a way to translate the date picker. We have quite a few users asking for this feature. 

reported by [Daniel](https://wpninjas.kustomerapp.com/app/customers/58496e509a1cc31100dbdbe4/event/58496e509a1cc31100dbdbe6)

**Comment by kstover** [comment]
This can be done using JS.

This radio message: nfRadio.channel( 'pikaday' ).trigger( 'init', dateObject, view.model ); is fired whenever a date picker is inited on the front-end. You can then update the dateObject however you'd like.

**Comment by hatsumatsu** [comment]
@kstover Could you elaborate on how to use the date picker's API to localize the UI?

**Comment by hatsumatsu** [comment]
This fix causes rows with three equal-width columns to be narrower than a row with two equal-width columns.
