### ISSUE TITLE
Deactivating fields

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#2208]
From a user:

"I think you should be able to toggle on/off or active/inactive (whatever
you want to call it) any field. Take for example a list of products and you
just don't want it on the form, or a question that you don't need at the
moment, but want back at some point. I don't feel you should have to delete
it and all it's possible additional functions if you plan to use it again."

This is an interesting proposition, but the consequences would need to be really thought through.

**Comment by dud3sweet** [comment]
.field_element {
visibility: hidden;
}

**Comment by kjohnson** [comment]
@dud3sweet that would be the easiest approach form a custom code perspective.

**Comment by kstover** [comment]
Moving "Enhancements" and "Feature Requests" to a custom Trello board.
