### ISSUE TITLE
Add-on updates are not showing in 2.9.x 

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2223]
Add-on updates do not seem to be showing in the 2.9.x code base. When an update is ready to be applied WordPress adds the notification, but none of add-ons will show they need to be updated and the add-ons will not show up on the WordPress Update screen. 

Replication Steps(starting in 2.9.x): 
1. Download Conditional Logic. 
2. Roll back to the v3.0.8 tag using git. 
3. Input license key for conditional logic. 
4. Go to the Dashboard->Update and use the check again button. 
5. You should see that you have an update, but nothing will show up on the page.

**Comment by kstover** [comment]
Closed in 3.0.20.
