### ISSUE TITLE
Duplicated forms do not retain proper field order

### ISSUE THREAD

**Issue by Quay3** [wpninjas/ninja-forms#2236]
When duplicating a form with multiple fields, the duplicates do not retain the order of fields from the original; i.e. the field order changes from duplicate to duplicate. 

First reported here: https://wpninjas.kustomerapp.com/app/customers/583867da4bcc3c1100baefc2/event/585826bff06ae310000496f8

**Comment by kjohnson** [comment]
The forms appear to be rendering fields in the order that they are localized, and not honoring the order property.

**Comment by Quay3** [comment]
Also reported here with import/export:

https://wpninjas.kustomerapp.com/app/customers/584d78eff2a29e1000c8eca2/event/584d78ef68654f1100d4cb7b

**Comment by rlagarde** [comment]
Hi,
I reported the first issue : duplicate order

If I export and import a form (.nff), order is also lost on my website. 
<img width="300" alt="capture d ecran 2016-12-23 a 12 32 39" src="https://cloud.githubusercontent.com/assets/24719323/21453091/2b157bcc-c90c-11e6-8072-24e8f6969da7.png">

BUT if i import this very same .nff on NF demo website (https://three.ninjaforms.com), field order is preserved and I can edit, save and even duplicate my imported copy with correct order.
<img width="300" alt="capture d ecran 2016-12-23 a 12 32 15" src="https://cloud.githubusercontent.com/assets/24719323/21453101/44be036e-c90c-11e6-80f9-ae3dbd2c84c2.png">
Encoding is broken though.

Rémi
_WP 4.7 - Locale FR_Fr - NF 3.0.20_

**Comment by rlagarde** [comment]
After some investigations, I found out that exported/imported forms are displayed in following order : 
1,10,100,101,...,109,11,110,111,...
instead of 
1,2,3,...,10,11,...,99,100,101,...
I think this is because strcmp is used to sort fields by order property.
I don't know wich files call this sort functions but it should first cast field('order') to integer and then sort it, using something like this:
`return ($order_a < $order_b) ? -1 : (($order_a > $order_b) ? 1 : 0);`

**Comment by kjohnson** [comment]
Ah, there might be a sort order issue with strings vs integers.

**Comment by rlagarde** [comment]
That's what I wanted to point out. 
This is a blocking issue for us as we have to duplicate and edit a 150 fields form each week.
What file is called to display a form (and sort it) in the builder ?

**Comment by rlagarde** [comment]
I'm glad to see priority bump on this.
I saw a note on readme.txt on 3.0.23 about duplicated form bug but field order is still wrong for me.

**Comment by kjohnson** [comment]
@rlagarde I am looking back into this issue now. Should have this fixed soon.

Testing Note: A string vs integer sorting issue will require a test form of more than 10 fields, so as the recreate the string comparison issue.

**Comment by kjohnson** [comment]
```php
return $a - $b;
```

**Comment by rlagarde** [comment]
@kjohnson 
Hi, this is not working for me.
When you edit a long form (more than 10 fields) order is messed up.
This is because form data is preloaded as a json encode.
I got this working today and will post a PR

**Comment by kjohnson** [comment]
It looks like the issue is that the order setting is being stored as a string at the time of duplication.

So, we could:

1. Force order to save as an integer (in PHP)
1. Force ordering to cast as integer (in JS)

**Comment by rlagarde** [comment]
@kjohnson 

I think you won't be able to save as an integer unless you change database model.
field order is being stored in wp_nf3_field_meta table

<img width="932" alt="screencap" src="https://cloud.githubusercontent.com/assets/24719323/22184413/23a689bc-e0d1-11e6-8c9d-0718d566a1f8.png">

a field order position is the **value** (string) when **key** is "order" (string)
> CREATE TABLE `wp_nf3_field_meta` (
>   `id` int(11) NOT NULL AUTO_INCREMENT,
>   `parent_id` int(11) NOT NULL,
>   **`key` longtext** COLLATE utf8mb4_unicode_ci NOT NULL,
>   **`value` longtext** COLLATE utf8mb4_unicode_ci,
>   UNIQUE KEY `id` (`id`)
> ) ENGINE=MyISAM AUTO_INCREMENT=58136 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
