### ISSUE TITLE
Glitch with submit button in Firefox

### ISSUE THREAD

**Issue by a00andos** [wpninjas/ninja-forms#2238]
I sometimes experience a small glitch when pressing the submit button in Firefox (50.1.0). 

This can be seen in the default Contact form that comes with the latest Ninja Forms 3 installation. Try clicking the submit button **with all fields empty**. Usually the button doesn't trigger at first click, but instead move a pixel or two down... If clicked it again it usually trigger as expected, and show errors for the required fields that are left empty.

**Comment by kstover** [comment]
Hey @a00andos, Sorry for the super-delayed response. If this is still an issue, please open a support ticket on our site: ninjaforms.com.
