### ISSUE TITLE
Character encoding issue after update to 3.0.20

### ISSUE THREAD

**Issue by eikeland** [wpninjas/ninja-forms#2239]
After updating to 3.0.20 all my forms which had norwegian characters like æ,ø,å shows up as scrambled on the backend and front end.
For example the char "Ø" shows as "Ã¸".

I had to manually change all text on all my forms, the text works fine after inputting it again with norwegian chars. so the problem is somewhere in the update conversion.

**Comment by eikeland** [comment]
I was able to recreate the issue.
The problem occurs when converting forms from 2.9 to 3.0

**Comment by SmashBrando** [comment]
I too have this issue. Single and double quotes along with some $nbsp; change to either an â or a large version of this.

**Comment by SmashBrando** [comment]
So I may have resolved the issue from a process standpoint. 

1 - Rollback to 2.9 under settings.
2 - Download and manually replace the ninjaforms plugin with version 3.0.5 - https://github.com/wpninjas/ninja-forms/releases/tag/3.0.5
3 - Upgrade forms (this one will be slower but be patient)
4 - Check your forms. In my case the character encoding was fixed. I do also have some layout scrambling but I can deal with that.
5 - Update ninjaforms to whatever the latest is at the time.

*wasted about 10 hours doing different things to remedy this.

**Comment by kstover** [comment]
Hey guys, Sorry for the super-delayed response. If this is still an issue, please open a support ticket on our site: ninjaforms.com.
