### ISSUE TITLE
Error message in console, but everything works.

### ISSUE THREAD

**Issue by eikeland** [wpninjas/ninja-forms#2240]
My browser console is filled with errors concerning the file front-end-deps.js on line 64 column 3795. But everything works ok on the frontend in version 3.0.20.

`Error: Undefined symbol field_
Stack trace:
u@http://eikeland.local/sim/sim-web/wp-content/plugins/ninja-forms/assets/js/min/front-end-deps.js?ver=3.0.20:64:3795
anonymous/<.eval@http://eikeland.local/sim/sim-web/wp-content/plugins/ninja-forms/assets/js/min/front-end-deps.js?ver=3.0.20 line 63 > Function:1:356
n/<.string@http://eikeland.local/sim/sim-web/wp-content/plugins/ninja-forms/assets/js/min/front-end-deps.js?ver=3.0.20:64:14426
compile@http://eikeland.local/sim/sim-web/wp-content/plugins/ninja-forms/assets/js/min/front-end-deps.js?ver=3.0.20 line 50 > Function:20:14
t<.setupCalc@http://eikeland.local/sim/sim-web/wp-content/plugins/ninja-forms/assets/js/min/front-end.js?ver=3.0.20:2:5934
t<.registerCalcs/<@http://eikeland.local/sim/sim-web/wp-content/plugins/ninja-forms/assets/js/min/front-end.js?ver=3.0.20:2:5226
m.forEach@http://eikeland.local/sim/sim-web/wp-includes/js/underscore.min.js?ver=1.8.3:5:2350
t<.registerCalcs@http://eikeland.local/sim/sim-web/wp-content/plugins/ninja-forms/assets/js/min/front-end.js?ver=3.0.20:2:5173
_@http://eikeland.local/sim/sim-web/wp-includes/js/backbone.min.js?ver=1.2.3:1:3909
m@http://eikeland.local/sim/sim-web/wp-includes/js/backbone.min.js?ver=1.2.3:1:3712
f@http://eikeland.local/sim/sim-web/wp-includes/js/backbone.min.js?ver=1.2.3:1:1565
u.trigger@http://eikeland.local/sim/sim-web/wp-includes/js/backbone.min.js?ver=1.2.3:1:3592
i<.initialize@http://eikeland.local/sim/sim-web/wp-content/plugins/ninja-forms/assets/js/min/front-end.js?ver=3.0.20:1:6990
e.Model@http://eikeland.local/sim/sim-web/wp-includes/js/backbone.min.js?ver=1.2.3:1:4450
q/n@http://eikeland.local/sim/sim-web/wp-includes/js/backbone.min.js?ver=1.2.3:1:22929
._prepareModel@http://eikeland.local/sim/sim-web/wp-includes/js/backbone.min.js?ver=1.2.3:1:12982
.set@http://eikeland.local/sim/sim-web/wp-includes/js/backbone.min.js?ver=1.2.3:1:10100
.add@http://eikeland.local/sim/sim-web/wp-includes/js/backbone.min.js?ver=1.2.3:1:9162
.reset@http://eikeland.local/sim/sim-web/wp-includes/js/backbone.min.js?ver=1.2.3:1:11031
e.Collection@http://eikeland.local/sim/sim-web/wp-includes/js/backbone.min.js?ver=1.2.3:1:8645
q/n@http://eikeland.local/sim/sim-web/wp-includes/js/backbone.min.js?ver=1.2.3:1:22929
r<.initialize@http://eikeland.local/sim/sim-web/wp-content/plugins/ninja-forms/assets/js/min/front-end.js?ver=3.0.20:1:8218
s.Object@http://eikeland.local/sim/sim-web/wp-content/plugins/ninja-forms/assets/js/min/front-end-deps.js?ver=3.0.20:20:10927
q/n@http://eikeland.local/sim/sim-web/wp-includes/js/backbone.min.js?ver=1.2.3:1:22929
O<.initialize@http://eikeland.local/sim/sim-web/wp-content/plugins/ninja-forms/assets/js/min/front-end.js?ver=3.0.20:2:31027
s.Object@http://eikeland.local/sim/sim-web/wp-content/plugins/ninja-forms/assets/js/min/front-end-deps.js?ver=3.0.20:20:10927
q/n@http://eikeland.local/sim/sim-web/wp-includes/js/backbone.min.js?ver=1.2.3:1:22929
a<.initialize@http://eikeland.local/sim/sim-web/wp-content/plugins/ninja-forms/assets/js/min/front-end.js?ver=3.0.20:3:3319
s.Object@http://eikeland.local/sim/sim-web/wp-content/plugins/ninja-forms/assets/js/min/front-end-deps.js?ver=3.0.20:20:10927
s.Application<.constructor@http://eikeland.local/sim/sim-web/wp-content/plugins/ninja-forms/assets/js/min/front-end-deps.js?ver=3.0.20:21:6781
q/n@http://eikeland.local/sim/sim-web/wp-includes/js/backbone.min.js?ver=1.2.3:1:22929
@http://eikeland.local/sim/sim-web/wp-content/plugins/ninja-forms/assets/js/min/front-end.js?ver=3.0.20:3:4684
u@http://eikeland.local/sim/sim-web/wp-content/plugins/ninja-forms/assets/js/min/front-end.js?ver=3.0.20:1:2207
h/<@http://eikeland.local/sim/sim-web/wp-content/plugins/ninja-forms/assets/js/min/front-end.js?ver=3.0.20:1:2584`

**Comment by kjohnson** [comment]
@eikeland can you provide more detail on where you are seeing this? I'm not seeing anything similar when I spot check.

**Comment by eikeland** [comment]
It was on all pages where ninja forms where included, but after converting forms to the new version, its gone.
