### ISSUE TITLE
Model get_setting returning default incorrectly

### ISSUE THREAD

**Issue by polevaultweb** [wpninjas/ninja-forms#2248]
If you have a setting where the value could be `"0"`, the `get_setting()` method of the `NF_Abstracts_Model` will incorrectly return the default value, instead of the actual value.

This is because the evaluation of `$return` here is very loose, so it evaluates `0` to false.
https://github.com/wpninjas/ninja-forms/blob/master/includes/Abstracts/Model.php#L209

**Comment by kjohnson** [comment]
@polevaultweb can you submit a PR?

**Comment by kstover** [comment]
@polevaultweb If this is still an issue, please re-open this issue.
