### ISSUE TITLE
Form lists view

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#226]
Hey

In the Forms view:
- Adding a how many times the form has been visited.
- Adding a number of submissions (and being able to click the number to enter submissions list).

Template function could perhaps be moved to another location.

**Comment by kstover** [comment]
This could be done easily if we moved the list table over to the WP_List class. That would standardize how our tables look across the board.

**Comment by jameslaws** [comment]
Closed as irrelevant due to 3.0 and this being merged into a new UI in a future version.
