### ISSUE TITLE
Required Checkbox List throwing Validation Errors Even When Checked

### ISSUE THREAD

**Issue by thinkcodenyc** [wpninjas/ninja-forms#2262]
<img width="346" alt="screen shot 2016-12-29 at 3 52 47 pm" src="https://cloud.githubusercontent.com/assets/10250301/21554650/667b324c-cddf-11e6-89a5-903e00ed8353.png">

Running NF 3.0.20, required checkbox lists are throwing an error as though there is no input, when you try to check a box.

**Comment by kjohnson** [comment]
@thinkcodenyc make sure that the options have corresponding values.

![screenshot 2016-12-29 23 16 02](https://cloud.githubusercontent.com/assets/10858303/21559591/12701a8a-ce1d-11e6-8480-2fbcaee94d1e.png)

**Comment by thinkcodenyc** [comment]
There are values assigned: 

<img width="1024" alt="screen shot 2016-12-29 at 11 23 25 pm" src="https://cloud.githubusercontent.com/assets/10250301/21559639/e14d4012-ce1d-11e6-8c49-548958e7db9d.png">

**Comment by kjohnson** [comment]
@thinkcodenyc I'm nor able to reproduce this locally. Are you seeing it on a new form, or is it specific to a form?

**Comment by thinkcodenyc** [comment]
This was due to a duplicate inclusion of jQuery. Bug-free once removed.
