### ISSUE TITLE
Merge Tag Picker not appending ":calc" to end of tag in calculations on existing inputs

### ISSUE THREAD

**Issue by karpadiem** [wpninjas/ninja-forms#2275]
The Merge Tag Picker (is that what its called?) seems to be omitting ":calc" from the end of tags when working in calculations. However, it works as expected when the input is new (and the form has not been saved/reloaded).

**Steps to reproduce:**

1. Create a new form.
2. Insert a select box
3. add values to each option
4. to go calculations and create a new calculation
5. Open the Merge Tag picker and click on the input you just created. It should create a tag that looks like this: "{field:listselect_1483478569895:calc}" **This is the expected behavior**.
6. Save the form. Close and return to the editor. 
7. Return to calculations.
8. Select the same field in the Merge Tag Picker. It should create a tag that looks like this "{field:listselect_1483478569895}". Notice the missing ":calc" at the end of the tag.
9. Save the form. Close and return to the editor.
10. Repeat steps 2 - 5. You will see it once again includes the ":calc" at the end of the tag.

Missing "calc" at the end of the tag is not an issue for calculations on the javascript side, but it seems that the PHP backend requires it (is this new? i feel like this worked before).

**Comment by jameslaws** [comment]
We either need to get this to consistently add the :calc or (better yet) Calc to process knowing the context they are being used in and not requiring an additional :calc attribute.

**Comment by kstover** [comment]
This is being addressed in our Calculation re-factor scheduled for 3.1 release in April.
