### ISSUE TITLE
"Add form to this page" vs. "Append a Ninja Form"

### ISSUE THREAD

**Issue by SDavisMedia** [wpninjas/ninja-forms#228]
Up until today, I had only ever used Ninja Forms on a live site for a single contact form. I would just append the form to a page and be done.

Today I created a new form from scratch that I wanted to also append to a page. In the creation of the form, I came across the "Add form to this page" option and since my page was already created, I selected it. Great.

I went on to create the rest of the form and finish up with the page content. Before publishing, I noticed that the "Append a Ninja Form" option had nothing selected and I naturally selected my new form. I totally forgot about the previous setting I had already done.

Two forms showed up on the page. And of course, that was my fault. But considering appending a form to a page automatically adds it to the bottom, and it appears that the adding a form to the page setting does the same exact thing, I can't help by wonder why they aren't the same setting that update the same option in the database.

Thoughts on this?

**Comment by kjohnson** [comment]
The "Add form to this page" setting has been deprecated as of v3.
