### ISSUE TITLE
text wrapping on long radio list labels

### ISSUE THREAD

**Issue by Quay3** [wpninjas/ninja-forms#2282]
When a very long label is used in an option of a radio list, the text moves down below the radio button, potentially making it unclear that the text is associated with that radio button.

Replication:
1) Make a form with a radio list field
2) In any option in that radio list field, assign a label that is very long (full sentence length plus, didn't count individual characters)
3) View the form in preview mode- text will have dropped down below the radio button.

This was initially reported in the following ticket: 
https://wpninjas.kustomerapp.com/app/customers/586d0c46634e6610006f10dd/event/586d0c46264fb41100e07762

**Comment by klhall1987** [comment]
I think this might be more than just radio list labels. I was able to replicate the same issue using a checkbox label. I had another [Nazim](https://wpninjas.kustomerapp.com/app/customers/5876deb1f013d51100f17f20/event/58ad8822af1a50110025be8c) report this issue as well.

**Comment by Quay3** [comment]
Another report of this issue here: https://wpninjas.kustomerapp.com/app/customers/58d183ef34c7f11100ff9393/event/58d9703ccace8d1000a1ed60

**Comment by Quay3** [comment]
Another support request on this this morning.

**Comment by kstover** [comment]
Closed as a duplicate.
