### ISSUE TITLE
{submission:sequence} merge tag not storing any data in the database

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#2294]
{submission:sequence} merge tag not storing any data in the database

replication steps:
create a form with a hidden field
set the default valuse of the hidden field to {submission:sequence}
save and view the form and make a submission
view the submission and no data will have been saved in the hidden field

### Environment ###
Home URL:                http://localhost/wordpress3
Site URL:                http://localhost/wordpress3
Ninja Forms Version:     3.0.20
WP Version:              4.7
WP Multisite Enabled:    No
Web Server Info:         Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/7.0.8 mod_ssl/2.2.29 OpenSSL/0.9.8zh DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0
PHP Version:             7.0.8
MySQL Version:           5.5.42
PHP Locale:              negative_sign:
WP Memory Limit:         40M
WP Debug Mode:           Yes
WP Language:             Default
WP Max Upload Size:      32 MB
PHP Post Max Size:       32M
Max Input Nesting Level: 64
PHP Time Limit:          30
PHP Max Input Vars:      1000
SUHOSIN Installed:       No
Server IP Address:       ::1
Host Name:               localhost
SMTP:                    localhost
smtp_port:               25
Default Timezone:        America/New_York

### Plugins ###
Installed Plugins:       Ninja Forms by The WP Ninjas version 3.0.20

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/584877bc52749d1000a40db7/event/586eabde634e6610006fd4f1

**Comment by francobrotto** [comment]
same issue here, any solution?

**Comment by klhall1987** [comment]
[Isabel](https://wpninjas.kustomerapp.com/app/customers/58b09cb953052f1100119a61/event/58c8628f2221ee1100e55246) is have this issue too.

**Comment by klhall1987** [comment]
https://wpninjas.kustomerapp.com/app/customers/580e80957c98031100738a65/event/58f7c1a78813631100296fa9

**Comment by kjohnson** [comment]
The `{submission:sequence}` merge tag isn't populated until AFTER the "Store Submission" action is processed.

This means that it is unavailable for field default values or any actions that modify the data before the submission is stored.

What we probably need to do is remove this merge tag form the Field context all together.

As for Actions, we could possible restrict this based on the Class' Timing Property ("Late" only).

**Comment by kjohnson** [comment]
PR merged. Closing issue.
