### ISSUE TITLE
Recaptcha not showing up

### ISSUE THREAD

**Issue by zietbukuel** [wpninjas/ninja-forms#2305]
After configuring the keys I added the field and it's just not showing up.

I get the following error message in the console:

`ReCAPTCHA couldn't find user-provided function: ninja_forms_grecaptcha_explicit_render`

**Comment by kstover** [comment]
Hey @zietbukuel, Sorry for the super-delayed response. This should be taken care of in the latest version of Ninja Forms. If this is still an issue, please open a support ticket on our site: ninjaforms.com.
