### ISSUE TITLE
Paragraph/RTE Setting Formatting

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2310]
1) Emails that are sent to the user and the admin lose their hard returns.
Here is what it looks like before the upgrade:
https://www.dropbox.com/s/tv1wh58rnjly4ei/ninja-forms-screenshot-02-2017-01-13_15-05-49.png?dl=0
Here is what it looks like after the upgrade:
https://www.dropbox.com/s/qs7fho6b336lhc6/ninja-forms-screenshot-01-2017-01-13_15-02-39.png?dl=0

From @aaronwiener

**Comment by klhall1987** [comment]
I was able to replicate the issue locally using this form. 

[59077d029310581000ef999c-SureSyncProTrialRequest---01-05-2017- (1).nff.zip](https://github.com/wpninjas/ninja-forms/files/971063/59077d029310581000ef999c-SureSyncProTrialRequest---01-05-2017-.1.nff.zip)

**Comment by klhall1987** [comment]
Field settings that use an RTE also appear to lose their formatting upon conversion(like description or help text).
