### ISSUE TITLE
list fields output as a serialized array in submission exports

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2314]
Multi-Select fields are being output as serialized arrays in submission exports. I've added a screen shot of what I'm seeing below. 

Screenshot: 
![screen shot 2017-01-16 at 4 39 15 pm](https://cloud.githubusercontent.com/assets/9393977/21999886/557d1990-dc0a-11e6-8499-405023db7325.png)

Replication Steps: 
1. Create a new form.
2. Add Multi-Select field and submit button. 
3. Publish, preview, and submit. 
4. Export form, you should see the multi-select field as a serialized array.

**Comment by wpnzach** [comment]
This happens in checkbox lists as well

**Comment by kstover** [comment]
Closed in this PR: https://github.com/wpninjas/ninja-forms/pull/2350
