### ISSUE TITLE
New TLD Email Validation

### ISSUE THREAD

**Issue by wipetom** [wpninjas/ninja-forms#2315]
Hy Guys,

in Version 3.0.24 (Ninja Forms) i have an issue with the validation by submitting an email-form:
It seems that the .TLD ".hosting" is not permitted. I haven't tested other TLDs.

Regards
Thomas, CSE

**Comment by kjohnson** [comment]
@wipetom this appears to be an issue with the WordPress provided `is_email()` function. We are looking into an fix.

**Comment by jameslaws** [comment]
We have another user who has asked about this,

**Comment by jameslaws** [comment]
Another user just asked about this.

**Comment by Quay3** [comment]
related: https://github.com/wpninjas/ninja-forms/issues/2429

**Comment by kjohnson** [comment]
@wipetom I submitted a PR #2599. Can you take a look and test it out?
