### ISSUE TITLE
Support merge tags in HTML editor

### ISSUE THREAD

**Issue by binarykitchen** [wpninjas/ninja-forms#2322]
When I add a merge tag in the HTML editor, it does not seem to get rendered properly.

For example

```
<p>You can view it anytime at:<br/><a href="{field:videomail}">{field:videomail}</a></p>
```

Will be displayed as

```
You can view it anytime at:
{field:videomail}
```

which is wrong ...

**Comment by kjohnson** [comment]
@binarykitchen is this the case for other field merge tags?

Also, try publishing the form and see if that works.

**Comment by binarykitchen** [comment]
@kjohnson yes, also happens for other field merge tags and also when published.

Probably a serious bug?

**Comment by dorey1981** [comment]
Perhaps check the file /includes/MergeTags/Fields.php

On line 68,69,70 the array field $field['key'] is used which does not exist. Changing this to $field['settings']['key'] appears to resolve the issue.

eg; 

change:

`
        if( isset( $field[ 'key' ] ) ) {
            $callback = 'field_' . $field['key'];
            $this->add( $callback, $field['key'], '{field:' . $field['key'] . '}', $value );
        }
`

to:

`
        if( isset( $field['settings']['key'] ) ) {
            $callback = 'field_' . $field['settings']['key'];
            $this->add( $callback, $field['settings']['key'], '{field:' . $field['settings']['key'] . '}', $value );
        }
`

**Comment by jameslaws** [comment]
@binarykitchen Are you taking about within the html editor of the HTML FIELD or with in an Action like a Success message?

**Comment by binarykitchen** [comment]
@jameslaws within an action!

**Comment by binarykitchen** [comment]
@dorey1981 nope, your suggested code change doesn't solve this :(

**Comment by jameslaws** [comment]
@binarykitchen I just tried this in a success message with the all_fields and single merge tags and I can't reproduce any issues like you are describing.

**Comment by binarykitchen** [comment]
okay - i tested all over again and reckon, this only happens when using my new videomail plugin which is still under development. i have emailed to you both @jameslaws and @dorey1981 the zipped plugin along with the nff export of that form.

have a look and see the bug yourself. hope this helps to reproduce?

**Comment by kstover** [comment]
Hey @binarykitchen, Sorry for the super-delayed response. If this is still an issue, please hop into our developer slack for more discussion.

**Comment by binarykitchen** [comment]
yes, this is still a problem. i cannot use merge tags when using HTML emails.
