### ISSUE TITLE
BCC bug during conversion

### ISSUE THREAD

**Issue by binarykitchen** [wpninjas/ninja-forms#2333]
When converting from 2.9 to 3.0 it looks like the field for multiple BCCs doesn't get converted correctly.

Before it was like 
one@more.com, two@more.com, three@more.com

After conversion it was
one@more.com`two@more.com`three@more.com

**Comment by wpnzach** [comment]
What version of Ninja Forms are you updating from/to?  Can you give us a copy off your System Status?  Screenshots of the behavior and form exports from 2.9 would also be very helpful.

**Comment by binarykitchen** [comment]
I am afraid, I don't have such a screenshot as the conversion already has been done. During the conversion there were no errors. Next to all forms there were green ticks, all seemed to go smooth.

The conversions ran on latest Ninja Form v3.0.24

**Comment by kstover** [comment]
Hey @Chris1777, Sorry for the super-delayed response. If this is still an issue, please open a support ticket on our site: ninjaforms.com.
