### ISSUE TITLE
Order of fields gets lost during conversion

### ISSUE THREAD

**Issue by binarykitchen** [wpninjas/ninja-forms#2334]
From 2.9 to 3.x the order of fields in a form is not correct anymore. Rather like randomized. Order should be kept.

**Comment by wpnzach** [comment]
What version of Ninja Forms are you updating from/to?  Can you give us a copy off your System Status?  Screenshots of the behavior and form exports from 2.9 would also be very helpful.

**Comment by binarykitchen** [comment]
I am afraid, I don't have such a screenshot as the conversion already has been done. During the conversion there were no errors. Next to all forms there were green ticks, all seemed to go smooth.

The conversions ran on latest Ninja Form v3.0.24

**Comment by kstover** [comment]
Hey @binarykitchen , Sorry for the super-delayed response. If this is still an issue, please open a support ticket on our site: ninjaforms.com.
