### ISSUE TITLE
Duplicating form does not reset sequential number

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2336]
Tested in 3.0.24 

Duplicating form does not reset sequential number

**Comment by kjohnson** [comment]
Another report of this issue by [Anthony](https://wpninjas.kustomerapp.com/app/customers/5931bf578c759b00101cc5b4/event/5930cb20478904001279f708).

Adding this bug to the next development sprint.

**Comment by klhall1987** [comment]
Could not replicate the issue in the current version. I had @wpnzach test as well. I'm going to close this issue, if it arises again we will fix it then.
