### ISSUE TITLE
Checkbox list empty when submitted.

### ISSUE THREAD

**Issue by jhondelbaguio** [wpninjas/ninja-forms#2345]
I created a form with 3 fields, 1 Single Line text, Country and Checkbox List. After i submitted the form. the 2 fields working well but the Checkbox list doesn't save the values i checked unless i assigned the choices as 'checked as default'. I'm using Ninja Forms Version : 3.0.24

![selection_023](https://cloud.githubusercontent.com/assets/13846656/22199210/ec6847a0-e194-11e6-9c2f-1df74c211fa1.png)

**Comment by kabitakis** [comment]
I'm having the same issue. Are there any updates on this one?

**Comment by jhondelbaguio** [comment]
No closure for this, i reverted back to the previous version.
