### ISSUE TITLE
Calculations are not saved with the submission

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#2346]
If you create a set of calculations, none of the results are saved anywhere with the submission. This makes the calcs almost useless when not used in conjunction with a Payment Gateway.

**Comment by klhall1987** [comment]
[Greg](https://wpninjas.kustomerapp.com/app/customers/58a38e1d4b70bd1100867994/event/58a38e1d4b70bd1100867997)is also having this issue.

**Comment by Much2tall** [comment]
Will be taken care of in the calc changes for version 3.1.
