### ISSUE TITLE
no changelog updates?

### ISSUE THREAD

**Issue by RobertShippey** [wpninjas/ninja-forms#2364]
There have been a few updates to the plugin recently where the changelog hasn't been updated to list what has changed. The most recent example being the latest version 3.0.25, and the last update to the changelog lists 3.0.24. 

It's always good to know what's changed to make sure things stay compatible, etc. 

Edit: To clarify, I'm referring to the changelog here https://wordpress.org/plugins/ninja-forms/changelog/

**Comment by kstover** [comment]
Hey @RobertShippey. I have no clue why WordPress.org hasn't picked up on the changelog, but if you download the plugin or browse it on trac here: https://plugins.trac.wordpress.org/browser/ninja-forms/trunk/readme.txt you'll see the changelog and update notice.
