### ISSUE TITLE
Field data not exporting

### ISSUE THREAD

**Issue by Much2tall** [wpninjas/ninja-forms#2366]
assumption is that db tables with non-standard prefixes are causing the export to fail

reproduce:
create wp install, rename db tables to non-standard prefixes, create a form, submit data, export the record.

**Comment by timarney** [comment]
I also having a similar issue.

In my case the data values do not come back properly

"#","Date Submitted","Name","Location","Email","Telephone"
"6150","01/28/2017"
"6149","01/28/2017"
"6148","01/28/2017"


I tracked the issue down to Submission.php

The export method
public static function export( $form_id, array $sub_ids = array(), $return = FALSE )

The deprecated export 

i.e. 

DEPRECATED - Individual value filters are inefficient.

Works - I force the export to use this in my case.

The "OPTIMIZED" export is not working properly

**Comment by raykimsey** [comment]
Same problem here. I updated Submission.php with the prefix to access non-standard named table #2368 but still did not solve the issue with the export to csv as referenced above.

I tried updating my Submission.php with the change to the line:

SELECT id FROM {$wpdb->prefix}_nf3_fields

This still does not solve the problem for me. Replacing the following code with previous code with the previous allows me to export properly.  Thanks for your help... also see other comments in #2368

$field_values = $wpdb->get_col( "
SELECT IFNULL( meta_value, '' )
FROM ". $wpdb->postmeta . " as postmeta
RIGHT JOIN (
SELECT id FROM {$wpdb->prefix}_nf3_fields
WHERE id IN ( " . implode( ',', $fields_order_by ) . " )
ORDER BY FIELD( id, " . implode( ',', $fields_order_by ) . " )
) as fields
ON postmeta.meta_key LIKE CONCAT( '%', fields.id, '%' )
AND postmeta.post_id = " . $sub->get_id() );

**Comment by kstover** [comment]
Hey,

I'm working on this now. The problem is two fold:

1) The SQL needs to use a $fields_order_by_id variable in the RIGHT JOIN statement.
2) We need the database prefix from $wpdb.

**Comment by kstover** [comment]
I've back-tracked this a bit.

With a recent change to how we cache form data during the php request cycle, we can revert to our older method of exporting submissions, which should mean that everything exports properly.

**Comment by timarney** [comment]
@kstover I updated to 3.0.26 and tried the export 

I'm now getting 

"#","Date Submitted","Name","Location","Email","Telephone"
"6259","01/30/2017","","","",""
"6258","01/30/2017","","","",""

Note: The data does exist for those entries.

**Comment by raykimsey** [comment]
Same here. Updated to 3.0.26 and get same as timarney.
