### ISSUE TITLE
Improve Product Fields

### ISSUE THREAD

**Issue by Much2tall** [wpninjas/ninja-forms#2370]
- [x] Add Donation Field
- [x] Add Tax Field
- [x] Add Product Options Field
- [x] Update Total Field logic
- [ ] Visually connect Product Fields with their Quantity and Product Options Fields in the Builder

**Comment by klhall1987** [comment]
Could we get this issue fixed in this update as well.
https://github.com/wpninjas/ninja-forms/issues/2527

**Comment by Much2tall** [comment]
Other related issues:
- [ ] https://github.com/wpninjas/ninja-forms/issues/2441
- [ ] https://github.com/wpninjas/ninja-forms/issues/2546

**Comment by kstover** [comment]
Closing in favour of a new refactor of Product fields.
