### ISSUE TITLE
Actions - Odd behavior...caching of some sort

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2374]
I've worked with many users where actions for certain behaviors were not working.  This includes E-mail, MailChimp, PayPal and more.  In many of these cases, making a new action where every single option matches exactly the non-working action, the new action works.

It seems something in the actions can get out of sync with whatever data is displayed in the actions editor vs whatever data is actually processing in the action.  Using this for reference and to gather more data in the future.

**Comment by kjohnson** [comment]
@wpnzach ran across something similar with @Much2tall where there was a bad condition. Any overlap here?

**Comment by kstover** [comment]
I think that this *should* be fixed with an update to core that let's actions remove fields from settings if the field is removed from the form. I'm going to close. We can re-open if necessary in the future.
