### ISSUE TITLE
Warn user if "FROM" address is anything other than @domain.tld

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2375]
If anything is in the FROM field other than @domain.tld, including use of a merge tag, notify user that the email action may not work properly and send them to email troubleshooting documentation.

**Comment by jameslaws** [comment]
This actually needs to throw a warning when certain known issues with the FROM address occur.

- FROM address is not the domain that the site is on.
- FROM address is a merge tag from the form.
- FROM address is not a valid email address.

This should not block the saving of the drawer, but throw a warning a link to a document that better explains the complexity of the FROM address.

**Comment by kjohnson** [comment]
@jameslaws I added a wrapper class of `nf-warning`, for styling purposes.

**Comment by kstover** [comment]
@kjohnson @wpnzach Can I get an update on this?

**Comment by kjohnson** [comment]
Looks like the above comments were addressed in the PR.
PR is merged.
Closing.
