### ISSUE TITLE
Builder breaks with Chinese characters

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2377]
switch your site to Chinese then, create a new form, add a field, and change the label text to some Chinese characters and the builder will stop working. I didn't see any PHP Errors or JS errors in the console.

**Comment by klhall1987** [comment]
Another asked this be addresse: [John](https://wpninjas.kustomerapp.com/app/customers/58a1a43160730f110008e141/event/58a1a43160730f110008e143)

**Comment by kjohnson** [comment]
Issue appears to be moot. May have been related to #2552 .
