### ISSUE TITLE
CSV export does not update progress

### ISSUE THREAD

**Issue by timarney** [wpninjas/ninja-forms#2381]
Visual output remains at 0% for the entire export process.

Using 3.0.26 also existed in 3.0.25 ... not sure about before that as I'm a new user.

![screen shot 2017-01-30 at 7 13 02 pm](https://cloud.githubusercontent.com/assets/62242/22447652/af67a71e-e721-11e6-9e96-51591d4ed753.png)

**Comment by kjohnson** [comment]
@timarney are you seeing any JS errors in the console?

**Comment by timarney** [comment]
@kjohnson the only error in the console is

The missing progress bar image - https://github.com/wpninjas/ninja-forms/pull/2380
http://pickering2024.com/wp-content/plugins/ninja-forms/assets/images/pbar-ani.gif 

No errors coming back from the requests.

**Comment by kjohnson** [comment]
We will probably need to look at the site specifically.

Can you submit a support request with temporary admin credentials?

**Comment by timarney** [comment]
Will do - just giving my client a heads up first than I'll take care of that.

**Comment by timarney** [comment]
@kjohnson 

Opened a support request.  I did notice the 'progress js' file / asset is linking to the deprecated folder.
