### ISSUE TITLE
All Fields Merge Tags showing less and less information (and some fields still out of order)

### ISSUE THREAD

**Issue by karpadiem** [wpninjas/ninja-forms#2389]
Thankfully the latest update addresses the field order issue when using the "All Fields" merge tag. After playing around with it I realized that I needed to edit each Multi-Part section in order to take advantage of the fix.

After going through and doing this I noticed that my submission emails were returning less and less info in the "All Fields" merge tag.

The first email this morning had 27 fields in it (actually, thats still way less than the amount of fields in my form). The last email of my tests had 20. I thought at first that they were fields that were left empty, but then first and last names dropped out of the table, but are shown in the email where those fields are directly called.

Also, some random fields are still showing at the top of the table when they should be at the bottom.

I don't know if this helps, but my rollbar.com tracker is also giving me this error on every submit.

> E_WARNING: array_merge(): Argument #2 is not an array
1
File "/home/nativeedge/nativeedgelandscape.com/wp-content/plugins/ninja-forms/includes/AJAX/Controllers/Submission.php" line 152 in array_merge

I'd be happy to forward the emails to a private address.

**Comment by kjohnson** [comment]
@karpadiem we have a release coming up that should address this. There has been a lot of tinkering to get the ordering right with different combinations of add-ons.
