### ISSUE TITLE
Special characters are not being encoded correctly on form import

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2401]
Some characters are being changed to symbols when the form is imported. Here are some characters I have found. 

řčžý

Replication Steps:
1. Create a new form.
2. Add a textbox.
3. Change the label to řčžý.
4. Export the form. 
5. Import the form and view it and you'll see the characters are being changed to symbols.

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/58c270c7e0a3041000b3809d/event/58d51cae34c7f111000550ab

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/5912f729b04d10110060a4d4/event/5912f729b04d10110060a4d9

**Comment by kjohnson** [comment]
This issue is not yet resolved.

**Comment by kjohnson** [comment]
The issue appears to be located in the stored form cache.
The associated field_meta row contains the correct string, while the form cache stored in the options table is incorrect.
