### ISSUE TITLE
Every 10 rows, CSV exports re-add headers

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2404]
Every 10 rows, CSV exports re-add headers

`"#","Date Submitted","Name","Email","Message"
"76","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"75","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"74","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"73","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"72","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"71","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"70","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"69","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"68","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"67","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"#","Date Submitted","Name","Email","Message"
"66","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"65","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"64","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"63","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"62","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"61","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"60","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"59","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"58","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"57","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"#","Date Submitted","Name","Email","Message"
"56","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"55","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"54","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"53","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"52","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"51","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"50","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"49","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"48","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"47","02/06/2017","dghdfhjdghad","dfgdfgh@sdfg.com","hsrtygd68iurftyi"
"#","Date Submitted","Name","Email","Message"`

**Comment by Much2tall** [comment]
Is this still an issue?
