### ISSUE TITLE
Redirect with params on ninja_forms_after_submission hook

### ISSUE THREAD

**Issue by imarem** [wpninjas/ninja-forms#2412]
Hi I'am trying to redirect to a page with ninja_forms_after_submission hook adding the params of form.
If I use a redirect to a URL with query string values (using merge tags) is too unsecure way.

this is my code:

function action_ninja_forms_after_submission( $this_data ) { 
	wp_redirect( add_query_arg( 'key', value, 'url_to_page' ) );exit;
}; 
// add the action
add_action( 'ninja_forms_after_submission', 'action_ninja_forms_after_submission'); 

And doesn't work.

Is there any way you can do this management? Please Help!!

**Comment by joeboyscout04** [comment]
Well, I'm facing this question as well...How can I do a redirect after processing a form (from php) since I am making a web request after form submits and need data from the response on the redirected page.

**Comment by UVLabs** [comment]
Was able to accomplish this with the filter "ninja_forms_run_action_settings":

```
add_filter( 'ninja_forms_run_action_settings', 'nf_filter_redirect_url', 10, 4  );

function nf_filter_redirect_url( $action_settings, $form_id, $action_id, $form_settings ) {
  
  if( $form_id !== <id> ){
  return $action_settings;
  }

  // more conditions can be added as needed
  // doc: https://developer.ninjaforms.com/codex/submission-processing-hooks/ 

  $my_variable = 'something';

  $action_settings['redirect_url'] = $action_settings['redirect_url'] . "&awb=" . $my_variable;

  return $action_settings;

}
```
