### ISSUE TITLE
ListCheckbox warning when submitting form without checked elements in list

### ISSUE THREAD

**Issue by ivan-demchenkov** [wpninjas/ninja-forms#2414]
Got this warning when submitted form without checking any element in ListCheckbox:
Warning: Invalid argument supplied for foreach() in /var/www/wp-content/plugins/ninja-forms/includes/Fields/ListCheckbox.php on line 36

**Comment by ivan-demchenkov** [comment]
This error in administrative interface when watching submitted data. Also in administrative interface in grid in listcheckbox column get notice: Notice: Array to string conversion in /var/www/wp-content/plugins/ninja-forms/includes/Admin/CPT/Submission.php on line 189
Array

**Comment by kstover** [comment]
Hey @ivan-demchenkov , Sorry for the super-delayed response. If this is still an issue, please open a support ticket on our site: ninjaforms.com.
