### ISSUE TITLE
Ninja Forms merge vars on REST API routes? - Notice: Undefined offset: 0 in \ninja-forms\includes\Helper.php on line 203

### ISSUE THREAD

**Issue by Pebblo** [wpninjas/ninja-forms#2418]
Hi guys,

Should Ninja Forms be trying to pull values from the query string on all REST routes?

I'm on of the support team for Event Espresso and noticed a conflict when one of our add-ons attempts to use our REST endpoints with Ninja Forms active locally so did a little digging.

It looks like the `WPN_Helper::get_query_string()` is running on all routes pulling in any values from the query string. However the function assumes that all values that are within an array will be numerically indexed and attempts to use `$value[ 0 ]` which if not set throws:

`Notice: Undefined offset: 0 in \ninja-forms\includes\Helper.php on line 203`

You can view an example of this on any site using NF using this route:

`/wp-json/wp/v2/posts?foo[bar]=baz`

**Comment by kstover** [comment]
Hi @pebblo. I'll dig into this over the weekend. We actually met at the Manchester WP meet up once. :) You were nice enough to give me a lift back to Liverpool.

**Comment by Pebblo** [comment]
Yeah I remember, followed the sat nav and ended up going the long way home, got their in the end though :)

Thanks for looking into it, really like the new UI btw!
