### ISSUE TITLE
Edit asterisk symbol in NF3?

### ISSUE THREAD

**Issue by jezthomp** [wpninjas/ninja-forms#2421]
You used to be able to edit the asterisk symbol in Ninja Forms, now you cannot in Ninja Forms 3?

I’d like to change the asterisk to something like (required).

Is this possible?

**Comment by kjohnson** [comment]
@jezthomp we have a filter for the string: https://ninjaforms.com/docs/edit-translate-fields-marked-required/

**Comment by jezthomp** [comment]
Is it possible for an example of just changing the asterisk, rather than the wording at the top. I’m after changing the one that appears in the label?
