### ISSUE TITLE
Email which is used to receive submitted forms is disclosed in submit response

### ISSUE THREAD

**Issue by ivan-demchenkov** [wpninjas/ninja-forms#2422]
After submit form to admin-ajax.php, it returns response, that contains json where is email in: 
data -> actions -> email -> to.
![email](https://cloud.githubusercontent.com/assets/7835992/22886424/d89471ec-f20e-11e6-9914-56d5c5643fd5.png)

**Comment by kjohnson** [comment]
We could add a permissions check before returning this data, which is intended for troubleshooting purposes.

@kstover @jameslaws thoughts?

**Comment by kstover** [comment]
I don't think that the settings for the action should be returned unless the user is logged-in as an admin.
