### ISSUE TITLE
Working Example Of Custom Fields in v3

### ISSUE THREAD

**Issue by cupcakedream** [wpninjas/ninja-forms#2424]
I was hoping to develop a shipping calculator extension for Ninja Forms. The UI is great, I love that it's popular and appears to be well built. After searching for an hour or two, I haven't been able to find a working example of how to add a custom field in Ninja Forms 3. I dug thru the issues here, looked at the quick start guide and docs for v3, the documentation for v2, which are still linked on the main site, and have come up with nothing. I'm running v3.0.027. What's up with the lack of documentation? I assumed this basic stuff would be available for developers, and I'm a little concerned about putting my time into an extension.

Thanks,
Mike

**Comment by kstover** [comment]
Hey @Chris1777, Sorry for the super-delayed response. Your best bet would be to join our developer Slack at developer.ninjaforms.com/slack. We have done a poor job of managing issues here on GitHub.
