### ISSUE TITLE
Email action giving invalid value for the "to" setting error when using merge tag for email field

### ISSUE THREAD

**Issue by Quay3** [wpninjas/ninja-forms#2426]
Reproduction steps:

1) Create a form with an Email field and a Submit button.
2) Create an email action and place the merge tag for the Email field into the To setting.
3) Submit form with an email address entered into the Email field.

Form gives the following error and does not submit: 

"Your email action "Admin Email" has an invalid value for the "to" setting. Please check this setting and try again."

@kstover Yes, the field keys do match.

User that initially reported this issue states that the issue is not present in version 3.0.19. I replicated on 3.0.27.

**Comment by RonWillemse** [comment]
Thnx @Quay3 to open this issue, I'm the one that reported this issue to you. I'm not sure if versions between 3.0.19 and 3.0.27 also have this problem.

I really hope that there will be a fix for this, because I like to keep my plugins updated with the latest versions.

**Comment by RonWillemse** [comment]
I updated and tested to 3.0.30 and everything is working perfectly now. SO this issue can be closed.
