### ISSUE TITLE
Conditional Logic not functioning properly on Save Submission action

### ISSUE THREAD

**Issue by Quay3** [wpninjas/ninja-forms#2428]
Reproduction steps:

1) Create a form with a Single Line Text field.
2) Set conditional statement on the Save Submission action to process only if Single Line Text is equal to Dog (or whatever). 
3) Submit form with text other than Dog entered into the Single Line Text field. Save Submission fires and submission is available under Forms>Submissions.

**Comment by kstover** [comment]
@Quay3 This needs to be moved over to the Conditional Logic repo. If you could do so, that'd be awesome.
