### ISSUE TITLE
Some TLD's not allowed in email field on front end

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2429]
As an example, admin@custommaintenance.solutions will fail to validate in-line validation in the email fields.

**Comment by wpnzach** [comment]
After more testing by a user and myself, this appears to be anything larger than a 6 character TLD

**Comment by Quay3** [comment]
User reporting that .brussels is not validating in the email field wither. Confirmed locally.

**Comment by Quay3** [comment]
related: https://github.com/wpninjas/ninja-forms/issues/2315

**Comment by kjohnson** [comment]
Closing in favor of #2315.
