### ISSUE TITLE
Default Collect Action to sandbox mode intelligently

### ISSUE THREAD

**Issue by polevaultweb** [wpninjas/ninja-forms#2432]
Eg. If PayPal is selected, but there are no live creds, only sandbox, turn on sandbox for the action automatically. This is a UX nice to have, but I spent 5 mins wondering why my form didn't redirect to paypal, as I hadn't turned on the action sandbox setting, as it was hidden away in advanced group.

**Comment by kstover** [comment]
This issue should be added to the PayPal repo rather than Ninja Forms core.
