### ISSUE TITLE
Collect action redirect processes fields again.

### ISSUE THREAD

**Issue by polevaultweb** [wpninjas/ninja-forms#2433]
To recreate

1. Create form with file upload field
2. Set the FU field to save to media (this forces a fatal error)
3. Add PayPal plugin with sandbox creds
4. Add Collect Payment action in sandbox mode with total.
5. Submit form, pay in PP.
6. Form processes the FU upload once before the redirection to PP and once after.
7. The tmp FU is deleted on the second process and causes an error.

https://wpninjas.kustomerapp.com/app/customers/58421aaf24f5391100db1656/event/58a369714b70bd110086336f

**Comment by polevaultweb** [comment]
@kjohnson any joy with this?

**Comment by kjohnson** [comment]
@polevaultweb Ah, ok. Now I remember talking about this one... on it!
