### ISSUE TITLE
reCaptcha does not work with CF7 enabled

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2438]
We're seeing this a LOT because CF7 is preinstalled on so many sites, as well as recommended by so many themes.  It's definitely worth looking into to avoid the support volume (I see about three a week, I thought there was already an issue for this)

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/58bdbb365b34651000297357/event/58bdbb3718c9f511001d9ce5

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/5831b813ca58701100502281/event/58cbebd55087371000e61a7d

**Comment by Much2tall** [comment]
Downgrading bug level, as we're now throwing a notice about this to users.

**Comment by kstover** [comment]
Closing until we hear back from CF7.
