### ISSUE TITLE
Emails fail when a CC or BCC is entered

### ISSUE THREAD

**Issue by Quay3** [wpninjas/ninja-forms#2439]
Tested this out in my local with just Ninja Forms & Mailgun installed (everything is up to date). Test emails go through fine until a CC or BCC address is entered. WIth the CC or BCC entered the email is not delivered. 

Reproduction steps:

1) In a clean install with Ninja Forms and Mailgun, configure an email action and send. Delivery is successful. 
2) Add an email address to the CC or BCC setting under Advanced. No delivery.

Additional notes:

This doesn't appear to be limited to email routed through Mailgun. The user initially reporting this issue is using Flywheel managed WordPress hosting. He did follow up with them and they're not reporting any issue on their end.

**Comment by klhall1987** [comment]
Mailgun does not accept CC or BCC with a Sandbox account.

I disabled Mailgun Quay's machine and I was unable to replicate the issue. I'm going to close this issue, since I can't replicate the issue locally on my machine on his without Mailgun.

**Comment by ricemann** [comment]
I am not convinced - I can verify that this doesn't work in Ninja forms 3.2.4. And I am using standard smtp @siteground. So you don't have to test with mailgun that isn't able to send to bcc anyway : )

I think you should open this issue again.
