### ISSUE TITLE
Hidden characters showing after upgrade/conversion

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#2449]
When a `v2.9.x` form is converted to a `v3+` form, hidden characters are converted to a visible format after being processed by `utf8_decode`.

**Comment by Much2tall** [comment]
Might have already been resolved.
Needs testing.

**Comment by Much2tall** [comment]
Appears to have been addressed here https://github.com/wpninjas/ninja-forms/pull/2884
