### ISSUE TITLE
Improving Calcs

### ISSUE THREAD

**Issue by Much2tall** [wpninjas/ninja-forms#2451]
- [x] Context for Merge Tags - ":calc" on list fields or pulls value (fix context so that it always pulls 'calc' if it exists, then value if calc is unset)
- [x] Rounding setting to calculations (add option of round to x amount of decimal points beneath calc label in builder)
- [x] Save calculations as extra value and show them on submission editing screen and export with submissions
- [x] Remove math.min.js and math.min.js.map and replace its function calls with vanilla js
- [x] Calculations should be available in all merge tags contexts within emails and actions
- [x] Apply padding to calculation content box to avoid overlapping with the merge tag icon
- [x] Calculation content box needs to have key tracking for merge tags it contains

**Comment by Much2tall** [comment]
Related Issues:
 - [x] https://github.com/wpninjas/ninja-forms/issues/2346

**Comment by Much2tall** [comment]
Still need to update license to reflect removal of math.min and replacement with math-expression-evaluator.min

https://github.com/redhivesoftware/math-expression-evaluator/blob/master/LICENSE

**Comment by jmcelhaney** [comment]
When a decimal amount is set to more than 3 places, a comma is added after the decimal point. https://goo.gl/KFQg3d

**Comment by Much2tall** [comment]
Corrected the issue.
