### ISSUE TITLE
Select field data is not being included in submission data

### ISSUE THREAD

**Issue by Quay3** [wpninjas/ninja-forms#2462]
Steps to Reproduce:

1) Create a form with a Select field

2) Submit the form and check the submissions entry for that form. The select field column is present, but the option selected in the field is not.

**Comment by Quay3** [comment]
Looked into this further after a report from another user [https://wpninjas.kustomerapp.com/app/customers/58b1567053052f110012ecd8/event/58b1567153052f110012ecda]

Radio List fields and checkbox lists are not being saved in submission data either when following the described reproduction steps. Checkbox lists are further displaying an error in the submission when you click on "Edit":
![checkbox list error](https://cloud.githubusercontent.com/assets/13201356/23333355/17ef4a36-fb58-11e6-8ca2-c75238d71366.PNG)

**Comment by Quay3** [comment]
To clarify, this is on 3.0.29

**Comment by rtoddhoward** [comment]
Now that this has been identified as a Major Bug, is there a plan to get it resolved?  When is the next release? Can we get a patch released asap? I have forms collecting information that now do not work, and I need to know if I should wait for a fix, or find another soultion.

**Comment by kjohnson** [comment]
@rtoddhoward we have identified the issue and are preparing a release/update.

**Comment by Quay3** [comment]
We have another ticket mentioning this. 

https://wpninjas.kustomerapp.com/app/customers/58e82ab87202f411007dc7fe/event/58e82ab8570c0b1100e5f7e4

**Comment by jameslaws** [comment]
This was patched and released in version 3.0.30 on February 28th.
