### ISSUE TITLE
Importing a form clears out PayPal API credentials

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2464]
User, myself, and @jmcelhaney were able to reproduce this out of the box.  @klhall1987 was not.

Reproduction steps are:

Have PayPal API credentials entered and saved.
Export a form. (credentials will still be present).
Import the same forms.
Credentials will be cleared.

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/58ae3c35684a1011009f2ef6/event/59093ad64ab23c1000163e5a

**Comment by jmcelhaney** [comment]
This is also an issue with Stripe's API keys exhibiting the same behavior.
https://wpninjas.kustomerapp.com/app/customers/58dbdddc8f7a6910002ba835/event/592728d4749f4000101b8120
