### ISSUE TITLE
2.9-Converted checkboxes don't show properly in all fields shortcode

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2468]
Checkboxes converted from 2.9 set a value of "zero" in the "Checked Calculation Value" as well as the "Unchecked Calculation Value" of the "Advanced" field settings.  These values seem to override the "Checked" and "Unchecked" values instead of just applying to calculations, breaking the fields on conversion until the "0" values are removed from the Advanced settings.

**Comment by kjohnson** [comment]
Not a conversion issue, except that the v2.9.x defaults of `0` (zero) - which are `` (empty) in THREE - introduce this already existing issue.
