### ISSUE TITLE
Add missing support for merge tags in actions

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#2480]
Currently some merge tags do not support actions, because the correct data is not accessible from within `admin-ajax`. This data should be submitted along with the form data, so that the merge tag can be properly populated.

- [x] Post Merge Tags
- [x] User Merge Tags
- [x] System Merge Tags
- - [x] System IP (Need to verify it is the user's IP)

**Comment by wpnzach** [comment]
Calculation merge tags are currently not working in actions.  Is this related, @kjohnson ?

**Comment by kjohnson** [comment]
@wpnzach calcs are working for me, but they aren't listed in the UI, see #2478.
