### ISSUE TITLE
Date Field does not respect Year Range advanced setting

### ISSUE THREAD

**Issue by Quay3** [wpninjas/ninja-forms#2484]
Reproduction steps:

1) Add a Date field to a form
2) In the Year Range option under Advanced Settings of that Date field, set Start Year to 2017 and End Year to 2018.
3) On the front end with this form, you can still select dates that are outside of the indicated Year Range.

**Comment by dbeja** [comment]
Year Range according to datepicker lib used (Pikaday) is only used for the list of years that show up when you click over the "Month Year" to select directly a different year, it doesn't limit the dates selected.

What could be done would be to setup 1st January of Start Year as _mindate_ and 31st December of End Year as _maxdate_.

Should I submit a pull request with this change?
