### ISSUE TITLE
Even when RIGHT of checkbox is selected, "Single checkbox" displays long labels ABOVE the checkbox.

### ISSUE THREAD

**Issue by RobbyButler** [wpninjas/ninja-forms#2489]
Here is my setting for the single checkbox with a long label:
![image](https://cloud.githubusercontent.com/assets/1231332/23482361/b2608994-fe83-11e6-9a36-ed51d93f4e8c.png)

On my Chrome browser [Version 56.0.2924.87 (64-bit)] it renders this way:
![image](https://cloud.githubusercontent.com/assets/1231332/23482473/0faddbc4-fe84-11e6-97ed-f8c661124441.png)

I can "fix" this problem in my current Chrome browser by manually inserting <code>"&lt;br&gt;"</code> in my label:
![image](https://cloud.githubusercontent.com/assets/1231332/23482957/caa651a8-fe85-11e6-9c87-65eb58209015.png)

However this does not carry over to my old Safari [Version 5.1.10 (6534.59.10)] on an older Mac, and thus I'm not confident it will render properly on other systems:
![image](https://cloud.githubusercontent.com/assets/1231332/23482297/5d431e04-fe83-11e6-969b-647e123125e7.png)

**Comment by kstover** [comment]
@jameslaws Any ideas on this issue?
