### ISSUE TITLE
Submissions are NOT deleted with form, though the Deletion Warning says they are.

### ISSUE THREAD

**Issue by RobbyButler** [wpninjas/ninja-forms#2490]
This throws off the accurate WP count of submissions, causing people like me to contact support. :)

Support told me the submission counts will be disappearing from the listing of submissions to avoid causing concern.

I suggest it would be better (and probably easier to program) to follow through on the warning and DELETE submissions along with the form.

It might also be helpful to offer a way to delete phantom submissions (from Forms deleted prior to fixing this issue) in order to correct the submission counts on existing installations.

**Comment by kstover** [comment]
I think that this would need a step processor, as several thousand submissions could be present.

**Comment by kjohnson** [comment]
If we handle the deleting with SQL, we may not need any step processing.
