### ISSUE TITLE
Submissions text copy is being off in CMS -. Cut down string if it is longer than 140 characters

### ISSUE THREAD

**Issue by devrahul** [wpninjas/ninja-forms#2493]
Hi 
i was working on ninja form and i had noticed that ninja form have inbuilt feature in CMS  User submission text are not displaying if it is longer than 140 characters` .

Current Output behavior 
---------------------------- 
Submission text copy is being cuff off and currently it is not showing longer than 140 characters

Expected Output behavior 
---------------------------- 
Need to display full submission text in CMS

Our Investigation in Code base : below Function is restricting  to string if it is longer than 140 characters` 

```
function nf_field_text_sub_table_value( $field_id, $user_value ) {
	// Cut down our string if it is longer than 140 characters.
	$max_len = apply_filters( 'nf_sub_table_user_value_max_len', 140, $field_id );
	if ( strlen( $user_value ) > 140 )
		$user_value = substr( $user_value, 0, 140 );
	echo nl2br( $user_value );
}
```

Can anyone  help us overriding this feature if possible to implement into a plugin or theme.

**Comment by kstover** [comment]
@devrahul It appears that you're referencing something in the deprecated codebase. Have you had this issue in the 3.0 UI?
