### ISSUE TITLE
Front End Posting

### ISSUE THREAD

**Issue by austenlennon** [wpninjas/ninja-forms#2498]
I have the latest version. I uninstalled and rerun stalled but still not working.... Even though it is active and licensed... it is not showing active....  
![screen shot 33](https://cloud.githubusercontent.com/assets/23722967/23579338/507f612a-00e3-11e7-82a6-cfc27b572769.png)

**Comment by kstover** [comment]
@austenlennon Can you create a support ticket at ninjaforms.com? That's a much better place to get product-specific support.
