### ISSUE TITLE
Form Processing Error (when logged in)

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#2502]
When logged in, submitting a form may get "stuck" on processing.

Looking at the developer console, there is an error with the form trying to "reset" the recaptcha even when recaptcha is not present on the form.

**Comment by noahsch** [comment]
Any ETA on when this bug may be fixed? I may need to rebuild the forms using another method if it's going to take a while (weeks).

Thanks!

**Comment by kstover** [comment]
@noahsch This should have been taken care of in a recent update. Not sure why the ticket wasn't closed.

**Comment by Wp1stop** [comment]
Hi Guys. Having this issue with the latest release.

Is there a fix for this ?

**Comment by feyazbeck** [comment]
I am having the same issue as well! I have the latest greatest releases!
