### ISSUE TITLE
Character count counts words instead of characters in text areas

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2515]
Character count counts words instead of characters in text areas

**Comment by jmcelhaney** [comment]
https://github.com/wpninjas/ninja-forms/issues/2515

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/59ef7ecdb6bc240001527f1c/event/59ef405f9008ae0001090967

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/5a730a10c461980001864d11/event/5a730a10cffeeb0001f04871
