### ISSUE TITLE
Translation Error

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2518]
From a user: "Btw, I just noticed a misspelling on the first page when I want to
create a new form. in the Swedish version of the guide (under "Begin
with a template" in English maybe?) you have a template for "Contact us"
which is translated to "Kontakata oss" which should be "Kontakta oss"."

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
