### ISSUE TITLE
add datetime and random value for renaming conventions for File Upload

### ISSUE THREAD

**Issue by websbio** [wpninjas/ninja-forms#2537]
We would like to have %datetime% (yyyy-mm-dd-hh-ii-ss) and %random% (a random 6 digit value) as options for renaming conventions for File Upload. This would ensure that we do not have file name issues for files with the same name. This is particularly important when integrating with third parties (for example WebMerge).

**Comment by kstover** [comment]
I've moved this over to the File Uploads private repository.
