### ISSUE TITLE
RTL-friendly all fields merge tag

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2542]
Data on left, label on right.

**Comment by kjohnson** [comment]
Looks like this is more of an Email Action specific issue.
The success message output for the Fields Table merge tag is accounted for by the theme.

@wpnzach can you confirm?

**Comment by kjohnson** [comment]
Looks like we can add some inline CSS to the `<table>` markup to be compatible for emails.

---

https://github.com/woocommerce/woocommerce/pull/5945
