### ISSUE TITLE
Apostrophes causing data loss in single line text fields

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2543]
In a single line text field, entering an apostrophe will cause it to be removed on form submission, along with any remaining text on the line.

**Comment by wpnzach** [comment]
This appears to impact storage of data, but not display in submissions or in actions.

**Comment by kstover** [comment]
It looks like this only affects editing the submission. The column view and export both show it with the full value.

**Comment by wpnzach** [comment]
@kstover this is a dupe of #2443, which I have upgraded.
