### ISSUE TITLE
Cache files should be removed from repository

### ISSUE THREAD

**Issue by FlyingDR** [wpninjas/ninja-forms#2545]
There is currently cache files for Ruby SASS compiler available in repository ([1](https://github.com/wpninjas/ninja-forms/tree/master/assets/scss/admin/.sass-cache), [2](https://github.com/wpninjas/ninja-forms/tree/master/assets/scss/front-end/.sass-cache)). They can be safely removed and need to be put into `.gitignore`

**Comment by kstover** [comment]
@FlyingDR Can you provide a PR for the update of the .gitignore?

**Comment by FlyingDR** [comment]
@kstover sorry for late response, I've prepared pull request for this issue
