### ISSUE TITLE
Add Date Updated column in Forms table

### ISSUE THREAD

**Issue by binarykitchen** [wpninjas/ninja-forms#2547]
Currently you can list the forms only by Form Title and Date Created. When you have lots of Forms, it is painful to browse to the form you want to edit when you cannot sort them by Date Updated.

Would be great for usability when you can see the recently changed forms on top of that table.

**Comment by isleshocky77** [comment]
A column for forms is already in present named `updated_at`; however, in my version of ninja-forms it is currently all `NULL`. I would assume that this error would have to be fixed before displaying it on the forms list page. 

I would expect the `created_at` date to be fixed (#2061) as well or before an `updated_at` date were included.

**Comment by kstover** [comment]
The new dashboard should address this with a filter and the ability to sort. If this is still an issue, feel free to re-open this issue.
