### ISSUE TITLE
Long list items float to the next line leaving a blank line between text and the element

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2548]
If a list item has a long label the text will float to the next line leaving a blank line between the element and the text.

**Comment by klhall1987** [comment]
This is still a bug.

**Comment by klhall1987** [comment]
https://wpninjas.kustomerapp.com/app/customers/5876deb1f013d51100f17f20/event/5a23431381f7c60001475f03

**Comment by jameslaws** [comment]
Should these really be assigned to me anymore? I feel like the dev team knows CSS we’ll enough to handle it.

**Comment by jmcelhaney** [comment]
.nf-field-container .checkbox-wrap{
flex-wrap:nowrap;
}

**Comment by Much2tall** [comment]
Closing issue in favor of discussion at https://github.com/wpninjas/ninja-forms/issues/3246
