### ISSUE TITLE
Foreign characters for Labels cause Field Keys to generate improperly

### ISSUE THREAD

**Issue by Much2tall** [wpninjas/ninja-forms#2552]
(Japanese characters are the known offender)

Steps to replicate:
- Create a new Form
- Add a new Field
- Change its Label to all Japanese characters
- Publish the Form
The added Field will be missing from the preview.
If you go back into the Builder and check the Field Key for that Field, it will be only numbers, with no text or underscore.

**Comment by Much2tall** [comment]
**Workaround:** You can manually change the Field Keys under the Administration section by editing the Field. In order to correct the issue, simply add a random string of English characters, followed by an underscore character "_" before the randomly generated number already provided.

**Comment by kjohnson** [comment]
The field rendering issue appears to be moot.

However, it would be best if we provided some sort of identifying string to the field key, where as a number only field key in no way identifies the field.

Bumping down to a minor bug as this is no longer breaking functionality (per team discussion).

**Comment by wpnzach** [comment]
Moved priority back to high as this is a breaking issue again.  As an example, make a new form and set 한국 as the field label.  Field key will be just a string of numbers, and the nf-row div will not contain any data for this field when previewed.

**Comment by unipheas** [comment]
I'm having the same issue but with Chinese. The workaround listed up top worked for now. I prepended "zh_" on every element and they are now displaying.

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/59f15bfbc3332400017652e2/event/59f15c9ad644c9000195d630

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/5a48f1a662dbd10001fb702e/event/5a48f1a67c042c0001515533

**Comment by jmcelhaney** [comment]
https://github.com/wpninjas/ninja-forms/issues/3014

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/5a6eefac5a7873000187cda3/event/5a8fd417f610f50001e5d26a

**Comment by kjohnson** [comment]
@wpninjas/developers the HTML field does not currently have an "Administration" settings section. This means that the work-around does not work for the HTML field.

**Comment by kjohnson** [comment]
https://wpninjas.kustomerapp.com/app/customers/5add8303b6994473719acc29/event/5add830443e37c3d6dfcaab3

**Comment by AlmogBaku** [comment]
What's going on with that?
It makes the usage a nightmare...

**Comment by AlmogBaku** [comment]
I can verify that the fix on develop work
