### ISSUE TITLE
'0' zero values cause problems. Lots of problems

### ISSUE THREAD

**Issue by lukeswitz** [wpninjas/ninja-forms#2559]
**-Issue affects the post submission, csv and any post nf_sub values in the db. None are collected or assigned to custom field meta** 
The table is completely messed up by zero values. Killing my entire company data entry, severely concerned about this. 
![screen shot 2017-03-23 at 5 59 19 pm](https://cloud.githubusercontent.com/assets/10099969/24275096/a3a00aa8-0ff2-11e7-873e-20a0483e0bf7.png) and lots and lots more which cause negative values in the totals.

**Comment by lukeswitz** [comment]
![screen shot 2017-03-23 at 6 02 12 pm](https://cloud.githubusercontent.com/assets/10099969/24275130/dd19ee8e-0ff2-11e7-8f45-7efbb0b640c4.png)

**Comment by kstover** [comment]
HI @lukeswitz Can you give me some more detail about your form setup? Is this related strictly to calculations? I'm afraid we need more data to help figure out what's going on.

**Comment by kstover** [comment]
Hey @lukeswitz , Sorry for the super-delayed response. If this is still an issue, please open a support ticket on our site: ninjaforms.com.

**Comment by lukeswitz** [comment]
Seemed to be a transient option from migration in the calculations table. Did a complete rebuild and fixed other problems as well. Cheers.

**Comment by lukeswitz** [comment]
Line of code in the frontend-min.js was culprit. Count also broken for localized decimals.
