### ISSUE TITLE
Message input do not show up in the side panel (drawer)

### ISSUE THREAD

**Issue by jlambe** [wpninjas/ninja-forms#2568]
**Step:**
1. Install ninja-forms  3.0.31 & activate.
2. Edit default contact form
3. Edit the "Success message" property

**Issue:**

The `message` input in order to customize the success message do not show up. Same when trying to edit the email notification `Email message` property, nothing. View below a screenshot.

![ninja_forms](https://cloud.githubusercontent.com/assets/1917490/24321775/30457a84-1155-11e7-843c-7b741eb48cc8.png)

**Comment by kstover** [comment]
Hey @jlambe , Sorry for the super-delayed response. If this is still an issue, please open a support ticket on our site: ninjaforms.com.
