### ISSUE TITLE
Importing forms doesn't escape apostrophes

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2573]
It isn’t escaping apostrophes in text added in an HTML layout field. e.g. In the text `Tell us what you're interested in.` that gets added to the import data as-is, and it’ll cause an error when importing unless you edit the json and escape the apostrophe in “you’re”.

**Comment by kjohnson** [comment]
@wpnzach could not reproduce.

I created a form with an HTML field, containing `Tell us what you're interested in.` which imported as expected.

Here is a copy of the export:
https://gist.github.com/kjohnson/2c4835761d781c92aa83c68b37b9c1c2

Further, JSON uses Double Quotation Marks (`"`), so a Single Quotation Mark shouldn't be an issue.

Anyway, if you can reproduce this, let me know and I'll take another look.

**Comment by wpnzach** [comment]
can confirm, appears to no longer be an issue
