### ISSUE TITLE
Apostrophes don't encode properly in email FROM NAME/ADDRESS

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2574]
From user: 

The name of my website is "Kenn Nesbitt's Poetry4kids.com" but in
email notifications and confirmation emails, the "From" address appears
as "Kenn Nesbitt`&#039;s` Poetry4kids.com." I'm able to change the
reply-to, but not the from address, so I can't change this without
changing the name of my website.

**Comment by kjohnson** [comment]
@wpnzach unable to reproduce:

```
Return-Path: <mailcatcher@flywheel.local>
Date: Thu, 15 Jun 2017 18:17:16 +0000
From: Kyle's Support <kyle@wpninjas.com>
To: kyle@wpninjas.com
Message-ID: <e954eac7081ff245f52f943faa20771d@support.dev>
Subject: Test
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
X-PHP-Originating-Script: 1000:class-phpmailer.php
X-Mailer: PHPMailer 5.2.22 (https://github.com/PHPMailer/PHPMailer)

<p>This is a test.</p>
```

**Comment by wpnzach** [comment]
can confirm, appears to no longer be an issue
