### ISSUE TITLE
Anti Spam field failure can cause resubmission of fields

### ISSUE THREAD

**Issue by polevaultweb** [wpninjas/ninja-forms#2575]
This creates errors (potential fatals) when a File Upload field is present. The file upload is processed on submission, but the user gets bounced back to the form if the anti spam field fails to validate. The next submission will cause:

```
PHP Warning:  rename(/Applications/MAMP/htdocs/nfthree/wp-content/uploads/ninja-forms/tmp/nftmp-8ygaE-screen-shot-2017-03-24-at-11.43.44.png,/Applications/MAMP/htdocs/nfthree/wp-content/uploads/ninja-forms/8/screen-shot-2017-03-24-at-11.43.44-1.png): No such file or directory in /Applications/MAMP/htdocs/ninjaforms/wp-content/plugins/ninja-forms-uploads/includes/fields/upload.php on line 125
```

And will only be caught when this PR is merged https://github.com/wpninjas/ninja-forms-uploads/pull/204

**Comment by polevaultweb** [comment]
Should fields like anti spam be processed first so failures are caught up front, or maybe all fields should be validated before all fields are processed?

**Comment by kstover** [comment]
We're working on new flow for processing. @polevaultweb This is definitely on our radar. I'm doing to close this issue to help remove noise in the GitHub repo.
