### ISSUE TITLE
JSON Parse Error

### ISSUE THREAD

**Issue by sepson** [wpninjas/ninja-forms#2582]
`Undefined index: tag in /wp-content/plugins/ninja-forms/includes/Abstracts/MergeTags.php on line 48`

That fixed it for me (MergeTags.php on line 48)
`if( array_key_exists('tag', $merge_tag) && ! in_array( $merge_tag[ 'tag' ], $matches[0] ) ) continue;`

**Comment by sepson** [comment]
Btw I have the same issue with ninja-forms-style
`/wp-content/plugins/ninja-forms-styles/layouts/ninja-forms-layouts.php`

That fixed it for me (ninja-forms-layouts.php on line 202):
```
if(array_key_exists($field_key, $fields_by_key) ) {
    $field = $fields_by_key[ $field_key ];
    $field_id = ( is_object( $field ) ) ? $field->get_id() : $field[ 'id' ];
    $new_order[ $field_id ] = $field;
}
```

**Comment by jonnymaceachern** [comment]
Also had this issue and this resolved it.

**Comment by kstover** [comment]
The undefined index issue should be taken care of in the latest version.

Sorry for missing this issue until just now.

If it still presents itself, please feel free to re-open this ticket.
