### ISSUE TITLE
Missing User Id in submission screen throws notice

### ISSUE THREAD

**Issue by polevaultweb** [wpninjas/ninja-forms#2583]
From https://wpninjas.kustomerapp.com/app/customers/5858325fe837f411008bf6df/event/58dbfb9a8f7a6910002beb22

One other issue I just noticed. One of the fields grabs the user ID if logged in. In the admin panel I see the following error in the Submission Info meta box if the user ID field is empty:
Notice: Trying to get property of non-object in /var/www/vhosts/nuumobile.noeticinc.com/httpdocs/add-nuu/plugins/ninja-forms/includes/Admin/CPT/Submission.php on line 294

**Comment by kstover** [comment]
This has been closed in a recent PR. The name "Anonymous" is used if no user ID is found.
