### ISSUE TITLE
 Cannot add additional Images in an HTML field when using multiple HTML fields

### ISSUE THREAD

**Issue by Quay3** [wpninjas/ninja-forms#2585]
Reproduction steps:

1) Create a new form containing 2 HTML fields. 
2) Open the first HTML field, add an image.
3) Open the second HTML field, add an image. The image will not add. This also occurs if you attempt to add a second image to the first HTML field.

Note: Tested this with one HTML field. You can add a second image to the field fine when there is only 1 total HTML field. It appears to be something about having multiple HTML fields.

**Comment by wpnzach** [comment]
Two fields are not necessary here.

This can also happen in a single field.  No more media can be added after closing the drawer, or changing contexts to another field if one exists.
