### ISSUE TITLE
Forms with Hide Successfully Completed Form Setting Turned Off Duplicates Submissions

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2587]
If the hide Successfully Completed Form setting is turned off then submissions will be multiplicatively duplicated. So for instance if you submit the for twice with out refreshing the page the second submission will show up two times, if your submit the form 3 times then the submission will show up three times in the submissions. 

Replication Steps: 
1. Create a form. 
2. Turn off the hide Successfully Completed Form setting in Advanced settings->Restriction. 
3. Preview and submit the form a few times and view the submissions.

**Comment by wpnzach** [comment]
This customer is impacted if we can send them a fix once resolved: https://wpninjas.kustomerapp.com/app/customers/5888f2d5e66d1c1000b2cc52/event/58ded39f33a6f71100ba8f72

**Comment by rdbsf** [comment]
im experiencing the exact same thing as described in the bug.
tested on on Version 3.0.31 and Version 3.0.34

**Comment by guitman444** [comment]
I am having this issue now. One submission results in many entries. Tried creating new form, same thing. Tried turning off "Hide Successfully Completed Form", did not help.
