### ISSUE TITLE
i18n: A confirmation email was sent to xxxxxx@yyy.zz

### ISSUE THREAD

**Issue by martin8032** [wpninjas/ninja-forms#2590]
The string "A confirmation email was sent to xxxxxx@yyy.zz" (which is displayed after sending a form) is not translatable through the language pack.

**Comment by kjohnson** [comment]
@martin8032 this is an Email form action setting, which is set by the site owner.

See: https://ninjaforms.com/docs/email/

**Comment by martin8032** [comment]
Correct. Sorry for that.
