### ISSUE TITLE
i18n: Forms

### ISSUE THREAD

**Issue by martin8032** [wpninjas/ninja-forms#2591]
The string "Forms" (which is the title of the according backend screen) is not translatable through the language pack.

**Comment by kjohnson** [comment]
Ah, I see. Good catch.

For Reference:
![nftranslationformstitle201704041250](https://cloud.githubusercontent.com/assets/10858303/24668523/32fccc68-1935-11e7-82a0-50878ec7e4dc.png)

**Comment by kjohnson** [comment]
With the move to the new Dashboard feature, the "Forms" screen is no longer in use.
