### ISSUE TITLE
i18n: Submissions

### ISSUE THREAD

**Issue by martin8032** [wpninjas/ninja-forms#2592]
The string "Submissions" (which is the title of the according backend screen) is not translatable through the language pack.

**Comment by kjohnson** [comment]
Related to #2591.

For Reference:
![nftranslationsubmissionstitle201704041252](https://cloud.githubusercontent.com/assets/10858303/24668583/6f446b68-1935-11e7-8e30-003ba1a97ed2.png)

**Comment by dbeja** [comment]
This page is using the Core template from Wordpress to get the page title and in WP Core you have this:

```
<h1 class="wp-heading-inline"><?php
echo esc_html( $post_type_object->labels->name );
?></h1>

```

which means this page title is read from the custom post type labels and they are correctly setup with translation functions:

```
$labels = array(
            'name' => _x( 'Submissions', 'Post Type General Name', 'ninja_forms' ),

```

Could it be because the pot files are not updated?

**Comment by kjohnson** [comment]
Taking another look, the issue seems to be that the wrong text domain is being used.

It should be `ninja-forms`, not `ninja_forms`.

I'll update the textdomain, but the translations would also need to be updated.
