### ISSUE TITLE
Recaptcha WRAPPER CLASS

### ISSUE THREAD

**Issue by tiagosumita** [wpninjas/ninja-forms#2593]
Hi, what is a Recaptcha WRAPPER CLASS and what is the value that I should put there to make this work? Thank you

**Comment by kjohnson** [comment]
@tiagosumita there is a field setting called `Wrapper Class` that can be used to add a CSS class/selector to the output of the reCAPTCHA field.

This is not necessary for reCAPTCHA to work.

Instead, be sure to add you reCAPTCHA keys in the plugin settings.
See `Forms -> Settings -> reCAPTCHA`.
