### ISSUE TITLE
Honeypot Field Processing

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2601]
Honeypot fields do not appear to be loaded on the front end of the site. I see references to the field in the source but nothing in the pages HTML. I've had a user complain their site was hit by bots because our honeypot didn't protect their site.

**Comment by kjohnson** [comment]
@klhall1987 I'm seeing the Honeypot field in my example form.

Also, keep in mind that the Honeypot is not perfect and a site can still be targeted.

**Comment by kjohnson** [comment]
We need to review the Honeypot Field process to make sure that everything works.
