### ISSUE TITLE
Separators in Calculation Outputs

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#2602]
> My question is: Is there any way to add comma separators in long numbers for ease of visual digestion? Eg. to display 10,000,000 instead of 10000000 in a calculation output.

**Comment by Much2tall** [comment]
Absolutely possible. However, we need to consider locale context for this, as in some sections of the world (mostly EU), it would read as 10.000.000 instead.

**Comment by kjohnson** [comment]
@Much2tall of course.

**Comment by kstover** [comment]
@Much2tall What's the status of this with the Calc re-work?

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
