### ISSUE TITLE
Merge Tag UI Wrap Up Issues

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#2613]
There are several issues with the new UI that need to be addressed in order for me to continue styling and to be ready for release. They are listed below.

## Organization
- [x] We need to deprecate the old all_fields and add a new version. (See the scope doc for details)
- [x] The two new all fields merge tags should be under Forms tab and not Fields.
- [x] We need an "Other" tab for misc merge tags instead of creating top level tabs for every tag. i.e. Query Strings, Reset Password, etc.

## User Interface
- [x] Merge tag button doesn't open the new merge tag UI
- [x] No active state being applied to the tabs when selected
- [x] When using the merge tag button to open the UI inside a Rich Text Editor, an opening { isn't inserted, which means that when you select a merge tag, nothing is inserted.
- [x] When the user presses the escape key with the merge tag UI open, it should only close the merge tag ui and prevent the event from bubbling up and closing the drawer.
- [x] Clicking outside the modal should close the merge tag UI. (This is a simple param to pass to jBox when you init the modal.)
- [x] Closing the merge tag ui without inserting anything should remove any orphaned { brackets. Seen when using escape to close the ui.
- [x] The Merge Tag UI doesn't work with option repeaters.

## User Experience
- [x] When merge tag button clicked, cursor focus should be on the search box
- [x] Hide tabs with no content. i.e. No calcs, no calcs tab.
- [x] When searching, either in the setting or the search box, enter key should insert top result.
- [x] Remove console.logs before shipping.
- [x] When initiating merge tags UI on an RTE it appears that all scrolling breaks.
- [x] Post, User, etc. merge tags still don't work within actions.

## Browser Compatibility
- [x] Disable browser autocomplete when using merge tags
- [x] Scrolling of tabs and tags does not work in Safari (maybe others)
- [x] Overlay does not span entire builder in Safari (maybe others)

That's just on first glance so lets start with these.

**Comment by jameslaws** [comment]
@kjohnson Talk to me today so I can explain how I would like to reorganize the the merge tags in the new UI.

**Comment by kjohnson** [comment]
@jameslaws can you test the overlay spanning in Safari?

I made some updates.

**Comment by jameslaws** [comment]
@kjohnson What is the timeline on the above remaining issues so I can fully get in and get the look and feel right?

**Comment by kstover** [comment]
I unchecked the "When searching, either the setting or search box, enter key should insert top result" because using the enter key while inside the field element works, but pressing enter while inside the search box **does not** insert the top result.

**Comment by kjohnson** [comment]
@kstover @jameslaws fixed everything on the list (new fields table tags are in another branch).

**Comment by jameslaws** [comment]
@kbjohnson90 I'm not seeing the organization improvements in the Merge Tag UI. i.e. The other tab with things like query string or calculations hidden when no calc exist. Was that pushed somewhere else?

**Comment by jameslaws** [comment]
I also still can't scroll the list of field merge tags when there are more than fits in the box.

**Comment by jameslaws** [comment]
@kjohnson You have the first merge tag in the list styled differently. My understanding is that is so users will know that if they hist enter during an auto filter that is the item that will be entered.

The issue is that if I click through tabs, the first one is always highlighted and clicking enter doesn't enter it. I propose that either....

Clicking enter should always enter the first item in the list 

or

That we only highlight the first item when in a filter/search context.

**Comment by kstover** [comment]
I'd go for the latter, although I'm not sure how'd you'd "click" enter unless you're using an on-screen keyboard. ;)

**Comment by kstover** [comment]
I have merged the Merge-Tag-UI branch into develop, so all work should be done in develop.

**Comment by kjohnson** [comment]
@jameslaws @kstover Post and User merge tags seem to be working for me.

Make sure that the form is on a post, for post tags, and that the user profile is filled, for user tags.

**Comment by kjohnson** [comment]
@jameslaws @kstover fixed the bug with scrolling.

**Comment by kjohnson** [comment]
Looks like that is the last item on the list.

**Comment by kjohnson** [comment]
@kstover @klhall1987 @jmcelhaney can ya'll re-test Merge Tags with Options Repeaters?
