### ISSUE TITLE
Custom Theme Issues

### ISSUE THREAD

**Issue by wloske** [wpninjas/ninja-forms#2621]
Hi there,

we have a custom theme setup in which we store the output of Ninja-Forms in a variable and put it out later. `NinjaForms()->display($id)` is what we use and we catch it with  Now we get all setup and options -  I think - and the blinking grey circle but no form and an error message

```
front-end-deps.js:20
Uncaught constructor
message:"An "el" #nf-form-2-cont .nf-form-layout must exist in DOM"
name: "Error"
stack: ... 
```
The content I get into the DOM is (The comments are mine to find what out is in the form):
```
 <!--[FORM -->
<noscript class="ninja-forms-noscript-message">
    Notice: JavaScript is required for this content.</noscript>
<div id="nf-form-2-cont" class="nf-form-cont">
    <div class="nf-loading-spinner"></div>
</div>
<script>
    var formDisplay = 1;

    /* Maybe initialize nfForms object */
    var nfForms = nfForms || [];

    /* Build Form Data */
    var form = [];
    form.id = '2';
    form.settings = { ... filled with what seems to be correct ... }];

    /* Add Form Data to nfForms object */
    nfForms.push( form );
</script>
<!--[FORM -->
```

I assume I am missing some prerequisites or some Javascript code which finally renders the form. Do I need to put some containers into my DOM to "catch" the form parts?

Aside: Is there no HTML output available anymore? Only Javascript and "false" forms without actions? Is there a best practice available somewhere how to do things outside the loop?

Thanks in advance

**Comment by kstover** [comment]
Hey @wloske, I think the best way to get this taken care of would be to visit our Slack group for developers: developer.ninjaforms.com/slack. Join us there and we can get this answered for you. Ping @kjohnson when you get there.
