### ISSUE TITLE
Anti-spam doesn't allow for answer correction

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2623]
Reproduction steps:

Create a form with default contact form template.

Preview form.

Answer anti-spam incorrectly and try to submit (you will not be allowed).

Correct your anti-spam answer and try to submit (you will still not be allowed).

**Comment by zaewin** [comment]
Confirming this bug on the latest update of NF (3.1.2). An incorrectly answered anti-spam questions locks the form.

**Comment by kstover** [comment]
Just tested locally, and it should be working in the latest version of Ninja Forms.
