### ISSUE TITLE
Render Options filter not used in admin submission view

### ISSUE THREAD

**Issue by JPBetley** [wpninjas/ninja-forms#2640]
When using the `ninja_forms_render_options` filter, it is possible to programmatically provide an array of options that should be available for selection in a List field. When displaying a form like this, the List field correctly has the options provided by the `ninja_forms_render_options` filter. However, those options are unavailable in the admin view of a submission.

Steps to reproduce:

1. Create a form using a dropdown list field
2. Add a filter to your `functions.php` file to hook into the `ninja_forms_render_options` filter
3. Open the form on a page, select an option, and submit it
4. Open the newly created submission for the form
5. See that the dropdown has no value, and none of the options set in your `ninja_forms_render_options` filter

After attempting to track down the issue, I found the function that builds the form element as it is displayed in the submission view. https://github.com/wpninjas/ninja-forms/blob/master/includes/Abstracts/List.php#L36

Applying the filters here provides the same list options in the submissions view that are available in the front end rendering.

**Comment by JPBetley** [comment]
Closed by #2641

**Comment by Twansparant** [comment]
This hasn't solved this issue for me?
I can see in the submit `response.data` that the field has the correct value, but it doesn't show up in the submission field?

**Comment by luukScheur** [comment]
This also didn't solve it for me, perhaps the filter is incorrect but I guess it should work fine like this:
in functions.php:
```
add_filter('ninja_forms_render_options', 'list_default_value', 10, 2);
function list_default_value($options, $settings)
{
	global $post;
	if ($settings['id'] == 26) {
		$args = array(
			'post_type' => 'product',
		);
		$query = new WP_Query($args);
		if ($query->have_posts()) {
			$options = array();
			while ($query->have_posts()) {
				$query->the_post();
				$options[] = array(
						'label' =>  get_the_title(),
						'value' =>  get_the_title(),
						'calc'  =>  null,
						'selected' => 0
				);
			}
		}
		wp_reset_postdata();
	}
	return $options;
}
```
The field itself has no default options set and they are all dynamically inserted with this filter. The options show at the frontend but at the backend we won't see any options. As well as the overview as the submission detail.

In my opinion this issue is still open. Looking forward to a fix

**Comment by dionadk** [comment]
is this issue resolved? I am not able to see the select options on the submission table.

**Comment by HectorLector** [comment]
I have the same problem with 'ninja_forms_render_options'. In the frontend the options are displayed correctly but in the admin submission panel I cannot see the options.
If I use a multi selection item I even get the following error message:

Warning: Invalid argument supplied for foreach() in /users/sleeper/www/wordpress/wp-content/plugins/ninja-forms/includes/Fields/ListMultiSelect.php on line 36

Any Ideas?
