### ISSUE TITLE
Populating form field with Javascript

### ISSUE THREAD

**Issue by splurtcake** [wpninjas/ninja-forms#2644]
Hello,

I'm trying to populate a form field with a value from javascript.

For example
`$('#some-ninja-field').attr('value', 'whatever')`

This visually updates the field's value on the front end, however when posting the form the value is not sent.

I have tried triggering other events (such as keyup, keydown, focus & blur) as I know the plugin is built with Backbone so figured it might listen to keyboard events to bind to internal models, however none of these make any difference.

Has anyone else tackled this?

Cheers,
Josh

**Comment by kstover** [comment]
Hi @splurtcake, you can use .val() instead of .attr() and it should update the value properly for you.

**Comment by jschrab-lc** [comment]
One more thing @splurtcake - you may very well need to trigger a 'change' event. This is what I finally realized I had to do to set a hidden field.
http://developer.ninjaforms.com/codex/changing-field-values/
```javascript
var fieldID = 197;
var newValue = 'compactpro';

jQuery( '#nf-field-' + fieldID ).val( newValue ).trigger( 'change' );
```
 Also, I was unable to successfully use VanillaJS methods of triggering a 'change' event and had to go down the jQuery path. Still, Ninja Forms requires jQuery so you can count on it being there.

**Comment by Tyg-g** [comment]
I'd like to understand why the vanillaJS `.dispatchEvent(new Event("change"))` does not work. It seems to me illogical as it should be the same thing.

**Comment by UVLabs** [comment]
@Tyg-g I'm wondering the same thing, i tried doing it in VanillaJS like you but it didn't work...jQuery worked
