### ISSUE TITLE
reCaptcha - Submitting form without validating locks the user from submitting.

### ISSUE THREAD

**Issue by MongolianMisfit** [wpninjas/ninja-forms#2648]
As the title suggests, submitting without validating reCaptcha locks the form with an error, rendering the user unable to submit the form. 

The only solution in this case is a complete reload of the page, and resubmission whilst appropriately validating reCaptcha.

**Comment by patricedefago** [comment]
Hello,

Same bug for me.

It's not good for conversion.

Thanks to correct this.

Have a good day☀️🍀😀

**Comment by kstover** [comment]
I cannot reproduce this on the current version of Ninja Forms. If this is still an issue, please feel free to re-open this issue.

**Comment by klhall1987** [comment]
@kstover Here are the replication steps: 

1. Create a new form with a checkbox, recaptcha field and submit button.
2. Preview the form. 
3. Click the submit button. 
4. Validate the Recaptcha Field and try to resubmit the form.

**Comment by roborourke** [comment]
@kstover same here, if you fill out all fields except recaptcha and submit it locks the form for resubmission.

Additionally the error message doesn't show, it appears that `id` isn't passed when generating the field's error div.
