### ISSUE TITLE
New Dashboard Wrap-up

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#2651]
These are some of the issues I've ran across while doing some initial testing of the feature-dashboard branch.

## MUST
- [x] Move "Dashboard" link to the top of the submenu, removing the "Forms" link.
- [x] We shouldn't have to fetch new forms when moving between the form list and "Add New" or between tabs. The only way we add a new form is through this menu, so we don't need to check for new data when going between tabs. We already have that data as a collection from initial load.
- [x] The confirmation modal should darken the rest of the screen. Clicking outside the modal should cancel.
- [x] Need the ability to sort forms by Title or Created Date
- [x] Only show "more" link if more than 10 forms are found.
- [x] Delete and Duplicate links should use the pointer cursor.
- [x] Add "Blank" as an option in the "Add New" widget.
- [x] When on the "Add New" widget, the search box placeholder should read: "Search Templates."
- [x] Duplicating gives me a form with an ID of 0.
- [x] When you delete a form, the zebra striping for the form list doesn't update.
- [x] When you're on the "Forms" or "Dashboard" page, the menu item doesn't get an active class, so you don't get a visual telling you that's where you are.
- [x] Need some kind of indicator that duplication is happening. Maybe open a modal with a spinner and some text? I'm open to ideas, but without that kind of feedback, the user doesn't know anything is happening. This will lead to users clicking duplicate multiple times.
- [x] Forms, Apps, Membership needs an active class to show which one is current selected.
- [ ] When jBox modals are opened, the page jumps to the top.

## SHOULD
- [ ] Show a form count with the Forms Table (which should be updated by the filter).
- [x] Sort by form title and date created.
- [x] Localize Dashboard Menu items so that they can be translated via php.

**Comment by kjohnson** [comment]
@kstover @jameslaws All MUSTs completed. Ready for styles.

**Comment by jameslaws** [comment]
@kjohnson I added a new must for a missing class. As I keep working through the styling I will add more to the list.
