### ISSUE TITLE
Changing Font Color in Ninja Form

### ISSUE THREAD

**Issue by CherishYou2** [wpninjas/ninja-forms#2665]
Please help! I am very much a beginner at designing my website on wordpress. Because my main font is white it seems you cannot fill out the form in black. For some reason you can input a message but nothing else? If you want to have a look https://cherishyou.co.uk/enquire/
https://cherishyou.co.uk/register/

**Comment by Much2tall** [comment]
@CherishYou2 We have an add-on for applying styling to your Forms. Unless you're planning on implementing a custom solution, we recommend using it to resolve issues such as this one.

https://ninjaforms.com/extensions/layout-styles/
