### ISSUE TITLE
Minimum amount of characters for text/textarea input fields

### ISSUE THREAD

**Issue by UVLabs** [wpninjas/ninja-forms#2674]
This was requested already and closed: https://github.com/wpninjas/ninja-forms/issues/624 it's been several months and nothing seems to have changed, I think this is one of those features which are actually a must for a forms plugin...would be great if this could be added so we could ensure users don't submit text fields which don't have a minimum amount of characters and then have to email them telling them "can you give us a longer......"

**Comment by kjohnson** [comment]
This feature is not currently scheduled in the development cycle, but is something that we are considering.

What is your use case for a minimum input length? I can add the use case to the feature request for consideration.

**Comment by UVLabs** [comment]
@kjohnson I have a form where I ask users to fill out a description of their business in other to get them listed on my site.

In the description form I have a message saying please try entering as much info as possible but usually they just send 1 line for text example:

"We xxxxx and are xxxxx come check us out!" I then have to email them asking them to please send something longer. It's a real time killer and could be avoided if there was a minimum amount of characters available option. 

I'm not sure how hard this might be accomplished but since you already have a function for the maximum amount of characters can't you turn it around for a minimum amount of characters? It might be more useful to users than you actually think, especially when forms have fields asking users questions

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.
