### ISSUE TITLE
why do you reset fields upon submit?

### ISSUE THREAD

**Issue by binarykitchen** [wpninjas/ninja-forms#2675]
in a plugin i am developing i can see that the `init:model` event is triggered after the form has been submitted which does not make sense to me.

after some debugging i found the cause in coreSubmitResponse.js at the code snippet below.

```js
actionSubmit: function( response ) {
  var formModel = nfRadio.channel( 'app' ).request( 'get:form', response.data.form_id );
  
                    ...

  if ( 1 == response.data.settings.clear_complete ) {
    // this here triggers the `init:model` and is breaking my plugin
    formModel.get( 'fields' ).reset( formModel.get( 'loadedFields' ) );
  }

  ...
}
```

can somebody explain me the reason behind this and confirm whether it's a bug or not? cc @kjohnson

**Comment by kstover** [comment]
Clearing the fields after a successful submission is a per-form setting. This isn't a bug; it's the way that the form is setup.

You could listen to the formModel's fieldCollection's reset event or something similar if you needed.

**Comment by binarykitchen** [comment]
@kstover oh i see - can you point me to a working example how i can listen to the reset event inside a field controller?

it is something like `this.listenTo(Backbone.Radio.channel('videomail'), 'reset', this.onReset)`?

**Comment by binarykitchen** [comment]
ping?

**Comment by binarykitchen** [comment]
@kjohnson any clues how I should hook this in the videomail plugin?

**Comment by binarykitchen** [comment]
hellooo??

**Comment by kstover** [comment]
@binarykitchen Backbone has a "reset" event that runs whenever a collection is reset. I'm going to close this issue in favour of our developer slack. That's a much better place to ask these kinds of questions. developer.ninjaforms.com/slack.

**Comment by lonix1** [comment]
@binarykitchen I have the exact same problem. Did you learn how to prevent clearing the form on submission?

Any shareable code would be appreciated!
