### ISSUE TITLE
Submit button does not re-enable once validation issues are fixed

### ISSUE THREAD

**Issue by alijaza** [wpninjas/ninja-forms#2684]
I have reproduced this in two ways:

* create a simple for with just a single antispam field and a submit button. Enter the wrong input and submit. Then correct the input and try to submit again. Submit button is disabled.

* Second way is similar but slightly different. I have a field with custom field validation logic. If I enter the wrong input and an error is shown, I cannot submit again even if I correct the input.

Version 3.0.34.1, WP 4.7.4

**Comment by jmcelhaney** [comment]
@kjohnson I was able to replicate the issue with the Anti-spam field.

**Comment by tan-ahmed** [comment]
I too was able to replicate this issue!
