### ISSUE TITLE
Question: which function in the NF_Abstracts_Field class influences the exporting of a CSV?

### ISSUE THREAD

**Issue by binarykitchen** [wpninjas/ninja-forms#2685]
I have the infamous "Array to string conversion" error here when exporting a submission to CSV.

This is because one of the fields is an array which requires special treatment. What function inside the NF_Abstracts_Field class should I override to have it return a string instead of an array for field X before exporting?

**Comment by Much2tall** [comment]
@binarykitchen Is this a list of some type?
If so, you might want to check into how includes/Abstracts/List.php is handling things.

For quicker responses, you might also want to join our slack group: http://developer.ninjaforms.com/slack/

**Comment by binarykitchen** [comment]
@Much2tall not sure how to respond since i am a newbie here, trying to develop a ninja form plugin. i also could give you access to the private repo instead?

regarding `includes/Abstracts/List.php`, which one of those functions does impact the exporting to CSV? which one should i override?

here a concrete example
https://github.com/wpninjas/ninja-forms-videomail/blob/develop/src/php/fields/videomail.php#L77

you see i am extracting a value (the url) from an array and use that to display a table cell in a custom column:

```
  public function custom_columns ($value, $field) {
    if ($this->_name != $field->get_setting('type')) return $value;
    if (empty($value)) return __('No Video Recorded');
    // ok, value is a videomail
    return '<a href="' . $value['url'] . '">' . __('View Online', 'ninja-forms-videomail') . '</a>';
  }
```

how can i do something similar for CSV export?

**Comment by kstover** [comment]
As @Much2tall suggested, could you join our slack group and ask these questions there? GitHub isn't a great place to ask these kinds of questions. I'm going to close this issue and point you there.
