### ISSUE TITLE
{submission:sequence} is 0 every time when submitting the form as a guest.

### ISSUE THREAD

**Issue by ilamp** [wpninjas/ninja-forms#2709]
{submission:sequence} return 0 in the email when submitting forms as a guest. It works fine as logged in users.

**Comment by ilamp** [comment]
I was able to narrow it down to object caching in W3 Total Cache.

**Comment by kjohnson** [comment]
If W3 Total Cache is caching the submission object, then you would either need to whitelist the forms page or require users to log in.

We will also look into ways to bypass these settings on form submission.
