### ISSUE TITLE
Large form getting stuck while submit

### ISSUE THREAD

**Issue by sbyy** [wpninjas/ninja-forms#2718]
Hi,
I'm facing a problem with Ninja form. I have a very large form with about 30 fields, while user click submit, the submit button will suck in processing, and will take about 2-5 minutes on a blank page, and redirect back to the empty form. Non of the actions (like successful message, redirect and email will be send), but when I check the submission, the form got submitted and all the data were saved. The form just looks like not successfully submit but actually submitted.
I test my other short form, they all works fine, all the actions after submit are working, only all of my large form getting stuck like this. And when I delete half of the fields of the large form, the form works fine again. I use those large form for 3 years without any problem, this problem just happen in these 2 days. Can anyone help me? Thanks!

**Comment by kjohnson** [comment]
Hello @sbyy,

This sounds like something that the support team needs to look into.
Can you submit a ticket at https://ninjaforms.com/contact ?

We will likely need temporary admin credentials so that we can take a look at the form.

**Comment by Herickpalazzin** [comment]
I have the same problem
if someone knows how to solve let me know in the email suporte@adeso.org.br
