### ISSUE TITLE
PHP Warning on Submission

### ISSUE THREAD

**Issue by Much2tall** [wpninjas/ninja-forms#2720]
PHP Warning: preg_match_all() expects parameter 2 to be string, array given in /nas/content/live/fr2000/wp-content/plugins/ninja-forms/includes/MergeTags/WP.php on line 48

**Comment by isleshocky77** [comment]
It appears this has been filed under #2600 as well.

**Comment by isleshocky77** [comment]
I've added a PR for this issue. Just a note, I know you have this as a minor bug; but this was actually causing my forms not to submit as the warnings were making nginx exceed a set limit. I'll have to look into that further.
