### ISSUE TITLE
The 2.9.x version of Save User Progress is allowing users to upgrade to 3.0

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2721]
If a user is on the 2.9.x code base with Save User Progress installed, it will allow them to upgrade to 3.0. Ninja Forms will run through the conversion routine and then deactivate the plugin once it gets finished with conversion.

**Comment by kstover** [comment]
This shouldn't be happening with the newest version of core. If you can recreate this with versions >= 3.1.2, please re-open this issue.
