### ISSUE TITLE
[Bug] Special chars converted to hex numbers in labels

### ISSUE THREAD

**Issue by binarykitchen** [wpninjas/ninja-forms#2738]
This is weird. Each time I click on the configure button of a single input and abort it, the label changes from i.E. `Parent's Last Name` to `Parent&#x27;s Last Name`

But when I click on configure again, then it is `Parent's Last Name` again. Looks like encoding does not work properly when listing the inputs in the form builder. Using latest version here.

Here a snapshot my client sent me and complained about that:

<img width="386" alt="screen shot 2017-05-12 at 8 08 33 am" src="https://cloud.githubusercontent.com/assets/177641/26021272/788b436e-37de-11e7-931a-9556f8d3bad0.png">

cc @kjohnson

**Comment by Much2tall** [comment]
@binarykitchen &#x27; is a code reference to the apostrophe character: '
( can also be referenced by &apos; )
Does the reference appear improperly to users who are filling out the Form?

**Comment by Much2tall** [comment]
Had to edit my original post because the browser read both of those codes as the ' character when I completed them.

**Comment by binarykitchen** [comment]
Can't answer that because I cannot reproduce anymore. Closing for now. Will reopen if it happens again.
