### ISSUE TITLE
[Bug] Broken styles in form editor

### ISSUE THREAD

**Issue by binarykitchen** [wpninjas/ninja-forms#2739]
That screenshot says it all:

![selection_008](https://cloud.githubusercontent.com/assets/177641/26021365/bc0a8b76-37df-11e7-9a9c-2761be47f8bf.png)

Wasn't like that before ... how to investigate?

**Comment by jameslaws** [comment]
That's is due to a plugin that is causing a conflict by adding styles or something to pages that it shouldn't. Mainly our admin. 

My guess is it clears up if you deactivate plugins.

**Comment by binarykitchen** [comment]
Ugh, I dont want to deactivate plugins since the site is in production and has heavy traffic. Is there no other way to investigate @jameslaws ?

**Comment by binarykitchen** [comment]
I wouldn't mind to give you temporary access for easier investigations ...

**Comment by jameslaws** [comment]
Not really. That's the main and clearest way to track down plugin and theme behaving badly. Probably good idea to always have a staging version of your sites so you have a safe place for testing. 

If you post your plugin list it might be possible for me to give you a hint as to the one likely to be the culprit. Not definite, but possible. 

You can try and inspect element and see what kind of stuff might be there that looks out of place, but since file are usually combined in the admin, that may not yield great results.

**Comment by binarykitchen** [comment]
ok, here a list of the plugins we are using:
Contact Form 7
Custom Facebook Feed
GetResponse Integration Plugin
Hands on Travel Registration
Instagram Feed
LayerSlider WP
Ninja Forms
Ninja Forms - Conditional Logic
Ninja Forms - Email Confirm
Ninja Forms - File Uploads
Ninja Forms - Layout & Styles
Ninja Forms - Multi-Part Forms
Ninja Forms - Stripe	
Ninja Forms - Zapier
Theme Blvd Responsive Google Maps
User Switching
WP Maintenance Mode
WP-FB-AutoConnect
WPide

Find anything suspicious?

**Comment by binarykitchen** [comment]
and here all the CSS files which are loaded:

![selection_011](https://cloud.githubusercontent.com/assets/177641/26021478/46db2e70-37e2-11e7-9e22-4e65513074e8.png)

**Comment by jameslaws** [comment]
It's the WPide plugin.

**Comment by binarykitchen** [comment]
@jameslaws huh, how do you know?

**Comment by jameslaws** [comment]
I recognize the name of the plugin as one that causes the issue in your screenshot.

**Comment by binarykitchen** [comment]
@jameslaws then this must be really a "bad" plugin! its description says

"WordPress code editor with auto completion of both WordPress and PHP functions with reference, syntax highlighting, line numbers, tabbed editing, automatic backup."

how the heck can a code editor mess with the styles of a ninja form editor? does not make sense to me ...

**Comment by jameslaws** [comment]
Sigh, because it enqueues and altars pages outside of the scope of what it does.

I'm trying to help, but if you don't believe me, there is nothing else I can do. It's an easy confirm. Just deactivate it. It's not front-end facing so it won't impact the site for your visitors.

**Comment by binarykitchen** [comment]
@jameslaws oh you get me wrong, you do a great help and i would hug you right now :) indeed, disabling that stupid plugin does the trick! thanks!

**Comment by jameslaws** [comment]
🤘🏻

**Comment by geigel** [comment]
I'm also having the same display issue with a production site with large traffic. Does Ninja Forms publish a list of plugins that conflict with the plugin so I can whittle down the possible culprits?

Here's the list of plugins we're using:

Beaver Builder Booster
Beaver Builder Plugin (Lite Version)
Breadcrumb NavXT
Child Theme Configurator
Classic Editor
Contact Widgets
Countdown Pro Wpdevart
Elementor
Fudge Lite Core
GDPR Cookie Consent
Google XML Sitemaps
Insert Headers and Footers
Ivory Search
MetaSlider
NextGEN Gallery
Ninja Forms
Ninja Mail
Really Simple SSL
String Locator
Timetable and Event Schedule
UpdraftPlus - Backup/Restore
WooCommerce
WordPress Importer
WP101 Video Tutorials
Yoast SEO

Thanks in advance for any insight and help the community can provide.

AG3
