### ISSUE TITLE
Confirm Delete dialog when deleting form has no actionable buttons

### ISSUE THREAD

**Issue by CSWebSolutions** [wpninjas/ninja-forms#2744]
Hi,
I am attempting to delete a form but when I select to delete, the "Confirm Delete" dialog does not contain any actionable buttons, just the text to "Delete" or "Cancel". I have tried this on latest Chrome and Firefox browsers.

Please advise.

![ninjaforms_delete_dialog_issue](https://cloud.githubusercontent.com/assets/28730149/26104165/7b4d031e-3a34-11e7-822c-ce7a9afeb272.jpg)

**Comment by kstover** [comment]
This should be taken care of in the latest version. If you try it out and it doesn't work, please feel free to re-open this ticket.
