### ISSUE TITLE
Ninja form gets stuck when I make a tiny update and hit the Publish button

### ISSUE THREAD

**Issue by manna06** [wpninjas/ninja-forms#2748]
Hi,

I don't have programming experience. When I make any change to a Ninja Form and hit the Publish button it keeps hanging. I've followed their advice to disable all other plugins and to set my default wordpress theme to twentyseventeen but it still hangs.

Please help asap. This problem has made me sad since it's been ongoing for 3 weeks now and users can't submit forms either on my website.

![image](https://cloud.githubusercontent.com/assets/28766771/26177789/34a8a97c-3b29-11e7-8e36-da67b75088be.png)

**Comment by manna06** [comment]
Not sure if this helps...
I right-clicked on the hanging Publish button and clicked on Inspect and saw a lot of code.

<script type="text/javascript">
	document.body.className = document.body.className.replace('no-js','js');
</script>

**Comment by kjohnson** [comment]
@manna06 This request should be directed to the [Support Team](https://ninjaforms.com/contact), as GitHub issues are for development and confirmed bug reports. Also, this issue log is not monitored for per-site support requests.
