### ISSUE TITLE
Submissions date range not showing correct data

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2749]
When a date is selected in the submissions date range selector, the submissions from the end date do not show, the submissions stop on the day before.

**Comment by klhall1987** [comment]
This is still an issue.

**Comment by tommimi** [comment]
any news? This a very annoying bug for me. (paying user of a couple of extensions)

**Comment by klhall1987** [comment]
Hey @tommimi, 

Currently we have not had a chance to work on this issue.

**Comment by kjohnson** [comment]
@tommimi we have an open pull request, which will still need to be reviewed.

It may or may not be included in the next release, but please feel free to checkout the branch and test it locally.

**Comment by tommimi** [comment]
Tried. Still broken. No entry found using filter.
