### ISSUE TITLE
Possible Reuse of Deleted Form ID (Duplicating form is using fields from previously deleted form)

### ISSUE THREAD

**Issue by karpadiem** [wpninjas/ninja-forms#2750]
I have three forms:

Contact: 6
Feedback: 8
Questionnaire: 9

At some point a few months ago I created a test form called "calc test" to test some calculations. I have no idea what its form number was. When I was done with it, I deleted it.

Today I duplicated the questionnaire (9) to test some possible changes. The duplication window came up and hung around for a while (its a big form, I'm used to waiting around for it). Eventually it disappeared. I was expecting the new form to be on the list but it was not. Refreshing the page added "Questionnaire - Copy" to the list as expected.

The new copy has an id of "10". And, when I click edit, instead of seeing the fields that should of been copied from the questionnaire, I'm seeing the fields from my old "calc test" form. It seems like it might of properly copied over the actions though.

I've duplicated form 9 again (resulting in form 11) and it all worked as expected.

My Theory:
My previous "Calc Test" form had an ID of 10. 
Deleting the "Calc Test" form did not properly delete all the fields etc.
NinjaForms mistakenly reissued the ID of 10. 
The duplication process encountered errors when it found data already existing for form 10.

**Comment by kstover** [comment]
Was this all in version 3?

Did you delete it with the "Delete" link or through MySQL?

**Comment by karpadiem** [comment]
@kstover Yes, it was all in V3. I deleted it using the delete link.

One other possible contributing factor is that I occasionally use WP-Optimize to clean up my database. One of the things it does is "remove deleted posts and pages from trash". I don't know if that would of possibly deleted some reference left by ninjaforms after the "delete" link.

Is the delete link expected to remove fields from the database when a form is deleted?

**Comment by kstover** [comment]
@karpadiem Yup, the delete link SHOULD remove all fields associated with a form.

I have had this issue before when running several versions of Ninja Forms on my test site, but usually that involves having lots of 2.9.x installs and forms as well.

**Comment by kstover** [comment]
@karpadiem I think I know what's going on here. It's related to an issue with form caches not being removed when a form is deleted. Once that is fixed, this should be taken care of. Going to close this issue.
