### ISSUE TITLE
Where did confirmation page/review page go?

### ISSUE THREAD

**Issue by bowenac** [wpninjas/ninja-forms#2755]
Using Multi Part forms, and apparently based on a lot of videos I have watched, as well as documentation, it seems like confirmation pages no longer exist?

Video showing it, really old.
https://vimeo.com/69214495

Check your work section here
https://ninjaforms.com/multi-part-forms-must-see-features/

I'm trying to implement my own with jQuery but each time next or previos is clicked, the whole part is removed so those fields are no longer in the dom so I can't access them via jQuery.

**Comment by kjohnson** [comment]
As per our conversation in Slack, the "Review Page" feature of the Multi-Part Forms add-on has been removed.
