### ISSUE TITLE
Debug mode for ninjaforms?

### ISSUE THREAD

**Issue by JasonBee** [wpninjas/ninja-forms#2768]
Hello all - I am looking for a debug option in NinjaForms. I've enabled debugging on the WP site, but the forms don't generate errors i need to see, so no useful info.

**I'd like to trace the NinjaForms logic** to debug some triggers that are not firing as expected, but I simply can't find out how to do this. 

I apologize in advance if I'm missing anything obvious.

**Comment by kjohnson** [comment]
@JasonBee we suggest enabling [WP_DEBUG](https://codex.wordpress.org/WP_DEBUG), also don't forget to enable WP_DEBUG_DISPLAY.

If you aren't finding the answer, the you should reach out to the support team directly.

https://ninjaforms.com/contact

**Comment by leecollings** [comment]
I think this should be re-opened and added as a feature request.

I completely agree with this, a debug mode should be put into the main component plugin to switch on or off, that will not fire an email, but output a simple(or full) parameter output of the form that's going to be sent.
