### ISSUE TITLE
The Fatal Error happened in starting plug-in 

### ISSUE THREAD

**Issue by kfengc27** [wpninjas/ninja-forms#2769]
Fatal error: Uncaught Error: Call to undefined function utf8_decode() in /var/www/html/wp-content/plugins/ninja-forms/includes/Helper.php:44 Stack trace: #0 [internal function]: WPN_Helper::utf8_decode('Contact Me') #1 /var/www/html/wp-content/plugins/ninja-forms/includes/Helper.php(42): array_map(Array, Array) #2 [internal function]: WPN_Helper::utf8_decode(Array) #3 /var/www/html/wp-content/plugins/ninja-forms/includes/Helper.php(42): array_map(Array, Array) #4 /var/www/html/wp-content/plugins/ninja-forms/includes/Abstracts/ModelFactory.php(132): WPN_Helper::utf8_decode(Array) #5 /var/www/html/wp-content/plugins/ninja-forms/ninja-forms.php(664): NF_Abstracts_ModelFactory->import_form('{"settings":{"t...') #6 /var/www/html/wp-includes/class-wp-hook.php(298): Ninja_Forms->activation('') #7 /var/www/html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #8 /var/www/html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #9 /var/www/html/wp-admin/plugins.php(166): do_action('activate_ninja-...') #10 in /var/www/html/wp-content/plugins/ninja-forms/includes/Helper.php on line 44

**Comment by kjohnson** [comment]
@kfengc27 `utf8_decode()` has been a PHP function since PHP 4.

We do have a [wrapper for the function](https://github.com/wpninjas/ninja-forms/blob/master/includes/Helper.php#L40), but that is available in the plugin.

Can you contact support and provide a system status for your site?

https://ninjaforms.com/contact
