### ISSUE TITLE
Calling wp_enqueue_script with wp-api as a dependency breaks ninja forms

### ISSUE THREAD

**Issue by DylanSimowitz** [wpninjas/ninja-forms#2770]
When I call wp-api as a dependency of my script, it breaks ninja forms.
```
wp_enqueue_script('sage/main.js', asset_path('scripts/main.js'), array('jquery', 'wp-api'), null, true);
```
These are the errors from the console.
```
formData.js:9 Uncaught ReferenceError: Marionette is not defined
    at formData.js:9
    at u (almond.js:314)
    at d (almond.js:180)
    at u (almond.js:305)
    at d (almond.js:180)
    at u (almond.js:305)
    at almond.js:388

front-end-deps.js?ver=3.1.2:20 Uncaught TypeError: Cannot read property 'vent' of undefined
    at front-end-deps.js?ver=3.1.2:20
    at arrayEach (lodash.js:537)
    at Function.forEach (lodash.js:9359)
    at front-end-deps.js?ver=3.1.2:20
    at arrayEach (lodash.js:537)
    at Function.forEach (lodash.js:9359)
    at i._proxyMethods (front-end-deps.js?ver=3.1.2:20)
    at new i (front-end-deps.js?ver=3.1.2:20)
    at front-end-deps.js?ver=3.1.2:20
    at front-end-deps.js?ver=3.1.2:20
```
Simply removing wp-api as a dependency for my script fixes these errors and the form loads, but my script really does depend on wp-api so this isn't an acceptable solution.

WordPress Version: 4.7.5

**Comment by kjohnson** [comment]
@DylanSimowitz

I wasn't able to reproduce this issue locally.

Is there something else that may be incompatible?

WordPress: 4.8
Ninja Forms: 3.1.4 (`master`, `develop`)

```php
<?php if ( ! defined( 'ABSPATH' ) ) exit;

/*
 * Plugin Name: _
 */

add_action( 'wp_enqueue_scripts', function() {
    wp_enqueue_script('_', plugin_dir_url( __FILE__ ) . 'script.js', array( 'jquery', 'wp-api' ), null, true);
});
```
_.php`

```js
console.log( 'HERE' );

```
`script.js`

**Comment by DylanSimowitz** [comment]
@kjohnson I'm building a theme and not a plugin if that makes any difference. If that doesn't matter, I'm using [bedrock](https://github.com/roots/bedrock) which changes the default plugin path among other things. This is fine as long as WP_PLUGIN_DIR or an equivalent is used in the plugin.

**Comment by DylanSimowitz** [comment]
The issue was an incompatibility with lodash. Switched to underscore and all is well.
