### ISSUE TITLE
Fields not showing up in the merge tag list until the form is reloaded. 

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2780]
Any new field that is create does not show up in the merge tag field list until the form is reloaded. 

Replication Steps: 
1. on a new form add a first name field. 
2. Go to the emails and actions tab and open the email action. 
3. Open the merge tag menu and you will see that the field doesn't exist.

**Comment by kjohnson** [comment]
Regression introduced by #2776.

**Comment by kjohnson** [comment]
Open PR (#2781) needs to be updated to cover calcs.
