### ISSUE TITLE
Unable to delete a Ninja form

### ISSUE THREAD

**Issue by RashmiRagupalV** [wpninjas/ninja-forms#2782]
Hello,

I created some test Ninja forms while I was working on Ninja forms; now i want to delete them. 
When I click on the icon next to Date Created to delete a form, nothing happens, the form still stays there. As a result, I just have some unused forms.

Please advice.

**Comment by kstover** [comment]
Could you submit a pull request on our site? This repo is for tracking issues that are known bugs with reproduction steps.

**Comment by kstover** [comment]
https://ninjaforms.com/contact/
