### ISSUE TITLE
No end of issues whilst previewing forms

### ISSUE THREAD

**Issue by thomasfw** [wpninjas/ninja-forms#2788]
We've decided to implement Ninja Forms and were surprised to see a number of issues right away after installing the plugin and doing some testing.

---

### The preview functionality messes with other post loops

When in NF preview mode, post loops that are running on the same page (e.g. a loop in a sidebar widget or on the page footer) are completely wrecked. Amongst other issues, it looks like the excerpt within the loop is replaced with the Ninja Forms markup and loading spinner.

```html
<!-- This is where my excerpt is being output within widget's loop -->
<small class="timid"><noscript class="ninja-forms-noscript-message">
    Notice: JavaScript is required for this content.</noscript><div id="nf-form-1-cont" class="nf-form-cont">

    <div class="nf-loading-spinner"></div>

</div>
</small>
```

In both screenshots below I disabled javascript so you can see the duplicated output more easily (sidebar on the right, post content on the left)...

**Form Preview**
First item in the sidebar loop has it's content/excerpt overridden:

<img width="1207" alt="screen shot 2017-06-12 at 15 19 37" src="https://user-images.githubusercontent.com/7723105/27038358-a8270d9a-4f82-11e7-9a52-ab0b56b00d70.png">

**Published post containing form shortcode**
This is how it's meant to display (taken from a post containing a published gravity form which causes no issues):

<img width="1217" alt="screen shot 2017-06-12 at 15 26 42" src="https://user-images.githubusercontent.com/7723105/27038704-a4d7b4a4-4f83-11e7-81b6-d961a398d877.png">

---

### Clicking 'Preview Form' right after opening the form builder results in database error and multiple PHP warnings on preview page: 

Example preview url: http://mysite.dev/?nf_preview_form=tmp-1497272504

<img width="1091" alt="screen shot 2017-06-12 at 14 16 15" src="https://user-images.githubusercontent.com/7723105/27041591-51035ac8-4f8c-11e7-901c-1e822b2991d4.png">

---

### Issues when using the global $post variable in themes

An example: We're checking whether or not to display a slider in our theme's header.php by checking the current `$post`'s meta data...

```php
// Check for post slider
global $post;
$slider = is_object($post) ? get_post_meta( $post->ID, '_post_slider_shortcode', true ) : false;
```

When in form preview mode, the home page's `$post` metadata is still picked up, so we're getting the home page slider above all our form previews as a result. 

I'm not keen on the idea of conditionally checking for `isset($_GET['nf_preview_form'])` everywhere we're using the global `$post` to combat the issue above. But consider adding an `nf_is_preview()` function that we can use in our templates like we would the WP `is_preview()` function.

---

For the time being we'll probably add some conditionals to remove the footer, sidebar, header and nav from our template when `nf_preview_form` GET param is set, in order to display the form on it's own. But it seems like a very hacky and intrusive way to get the preview working without any issues.

Thanks

**Comment by thomasfw** [comment]
Looks like most of this stems from the `NF_Display_Preview` class overriding everything, e.g:

```php
// Form is attempting to load in place of the sidebar post excerpt
 add_filter('get_the_excerpt', array( $this, 'the_content' ) );
``` 

```php
// This is why i'm only seeing 1 post in other loops
add_action( 'pre_get_posts', array( $this, 'pre_get_posts' ) );
``` 

..seems a bit clumsy

**Comment by kstover** [comment]
We are currently working on improving how we handle form previews. It can be a bit tricky to show an accurate preview for all our users in every possible theme setup in the WordPress ecosystem.

For the specifics of what we're doing, @kjohnson would need to respond, as he's the dev working on that particular feature.

**Comment by kjohnson** [comment]
@thomasfw the Preview Page does overwrite everything. The issue that this tries to solve is that different themes display content in different ways.

The preview system hooks into `the_content` and tries to find a place to display the form.

While this may be overreaching, this approach has yielded that largest coverage of theme support, thus far.

We are certainly looking to improve the system, but have other priorities placed on us as a development team.

If you would like to suggest a different approach, then a Pull Request is always welcome.

**Comment by thomasfw** [comment]
Just looking at the cause of the database error I mentioned above. Are you guys aware that you're directly injecting url parameters into the sql query?


```php
$subs = $wpdb->get_results( "SELECT post_id FROM " . $wpdb->postmeta . " WHERE `meta_key` = '_form_id' AND `meta_value` = $form_id" );
```
https://github.com/wpninjas/ninja-forms/blob/master/includes/Display/Render.php#L91

**Comment by jameslaws** [comment]
Can you clarify what you are referring too. The line you shared doesn't write to the database, it simply queries the database and then counts the number of rows returned.

**Comment by kstover** [comment]
@jameslaws I think it could still theoretically be used to add some malevolent SQL stuff. A simple solution would be to run $form_id through an absint() at the beginning of that function and the localise preview function.

**Comment by kstover** [comment]
Patched in develop here: https://github.com/wpninjas/ninja-forms/commit/d41d2d3c65b3587fd172dc4a165ec9f6dc0a36f1

**Comment by kjohnson** [comment]
Closing this because the SQL Injection issue was resolved and the preview system is being updated.
