### ISSUE TITLE
Query string merge tags should not populate if query string not present.

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2790]
To reproduce, add a query string merge tag to a field.

When query string is present, that value will be in the field.  When query string isn't present, the merge tag gets displayed on the form and saved in submissions, causing very broken feeling behavior and leading to user complaints.

![593ef2d394653f1200673cee](https://user-images.githubusercontent.com/7498743/27097130-44a61634-5041-11e7-947d-86cfff37cbfc.png)

![593ef2d394653f1200673ced](https://user-images.githubusercontent.com/7498743/27097135-4664da28-5041-11e7-8b39-0584b4b5edfc.png)

**Comment by kjohnson** [comment]
Only seems to be an issue for `published` forms, as opposed to `previews`.
