### ISSUE TITLE
Post tags unavailable in e-mail merge?

### ISSUE THREAD

**Issue by tleen** [wpninjas/ninja-forms#2799]
Setup is WordPress 4.8, NF v3.1.4.

I am unable to see the post merge tags in an email action. I can get the tags from the form no problem, but post:title, post metas any of that are a no go. I end up seeing the merge tags in the resultant received e-mail:
> This is a contact request for {wp:post_title}

Form data comes through no problem.

I am generating the form through the ninja_forms_display_form() function within a post context. Post related data goes into the form without issue. It doesn't seem present when the e-mail is being created via the ajax call.

It seems like this issue is related to #2192 and #1814 , which are closed because things were being refactored. Is this a known issue or am I the only one with this problem? Was this refactor already accomplished? 

The current workaround would be to echo post data in a hidden field, but I do have some meta information I would rather not have exposed in this manner. This could totally be user error too, I may be missing something?

**Comment by kstover** [comment]
I can't reproduce this locally using the [ninja_form] shortcode on the post, so my guess is that it is related to the use of the display function.

If you test with the shortcode on a post, does that come through properly?

@tleen

**Comment by tleen** [comment]
In this situation I won't be able use the shortcode in the post so I invoke it in the page template directly. I did try it via the do_shortcode function and the results were the same. I will try it as part of the post content and see what happens.

**Comment by tleen** [comment]
I tried the shortcode in the post content with the same result. Still no merging of post tags in the email.

**Comment by tleen** [comment]
I setup a clean WP install to mess around with this issue. Its WP 4.8 and the master branch of the NF plugin. The only other plugin is Advanced Custom Fields (Pro) 5.5.14. (I have a hunch it may be involved.) Posts have a meta field via ACF called "post-extra-title". Form is shortcoded into the Hello World starter post. Form is being submitted via admin-ajax.

I am using a copy of the default contact form with the confirmation email step removed.

It seems to occur when a post meta field is used, the post information is no longer merged in:

**Only post data**

When my email looks like this: 

```text
Post title: {wp:post_title} 

Post url: {wp:post_url}

Site url: {wp:site_url}

{field:message}

- {field:name} ( {field:email} )
```

My result is:

```text
Post title: Hello world! 

Post url: http://ninjaforms.wordpress.thomasleen.com/2017/06/16/hello-world/

Site url: http://ninjaforms.wordpress.thomasleen.com

This is a test of the post information merging in NF.

- Thomas Testerman ( tom@testaddress.org )
```

**Only meta data **

When the email looks like this:

```test
Post extra title: {post_meta:post-extra-title}

{field:message}

- {field:name} ( {field:email} )
```
The result is:

```text
Post extra title: This is the extra post meta title

This is a test of the post information merging in NF.


- Thomas Testerman ( tom@testaddress.org )
```

**Both post and meta data**

See what happens when I have the email with both post fields and meta fields:

```text
Post title: {wp:post_title} 

Post url: {wp:post_url}

Site url: {wp:site_url}

Post extra title: {post_meta:post-extra-title}

{field:message}

- {field:name} ( {field:email} )
```

_We lose the wp merge information in the resultant email._

```text
Post title: {wp:post_title} 

Post url: {wp:post_url}

Site url: {wp:site_url}

Post extra title: This is the extra post meta title

This is a test of the post information merging in NF.


- Thomas Testerman ( tom@testaddress.org )
```

Order of the merge tags does not seem to matter either:

```text
Post extra title: {post_meta:post-extra-title}

Post title: {wp:post_title} 

Post url: {wp:post_url}

Site url: {wp:site_url}

{field:message}

- {field:name} ( {field:email} )
```

```text
Post extra title: This is the extra post meta title

Post title: {wp:post_title} 

Post url: {wp:post_url}

Site url: {wp:site_url}

This is a test of the post information merging in NF.


- Thomas Testerman ( tom@testaddress.org )
```

Any guesses as to what is causing this? @kstover perhaps try mixing in a meta field to see if you can reproduce?
