### ISSUE TITLE
Unreliable $form_data passed to the ninja_forms_submission_actions filter callback

### ISSUE THREAD

**Issue by brbreen01** [wpninjas/ninja-forms#2805]
The $form_data passed into the ninja_forms_submission_actions filter callback function is not reliable. The 'value' attributes (at least) are sometimes correct, sometimes in the wrong fields and sometimes missing! The $actions data however seems fine.

**Comment by kstover** [comment]
I'm going to ping @kjohnson so that he can respond here.

**Comment by kjohnson** [comment]
@brbreen01 it looks like the doc's weren't updated.

That filter has 3 parameters: `$actions`, `$form_cache`, `$form_data`.

It sounds like you need the 3rd parameter, which is the `$form_data` that you are looking for.
