### ISSUE TITLE
Export, Import problem with unicode text

### ISSUE THREAD

**Issue by devlifeX** [wpninjas/ninja-forms#2814]
Hey
Recently i install `ninja forms 3.1.4`, and i found issue in unicode text, in my case i used 
persian text `تماس با ما` for my field label, and after export and import my text was weird! like this `ØªÙØ§Ø³ Ø¨Ø§ ÙØ§`
please fix this issue.
php ver: `5.6.30`
ninja forms ver: `3.1.4`
wordpress ver: `4.6.6`

**Comment by Much2tall** [comment]
Related to https://github.com/wpninjas/ninja-forms/issues/2717
