### ISSUE TITLE
The Star Rating field is not being caught by the required field validation

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#2815]
The Star Rating field is not being caught by the required field validation in Ninja Forms 3.1.4

**Comment by vogography** [comment]
And the problem is that when people send a form without making a star rating now the submissions say that the question was rated with 4 stars so the results of surveys are not true.

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/59e5582686980e00017e7603/event/59e5582686980e00017e7607

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/59de534c3edcd5000182f264/event/59de8c440d582a00017e0dbf

**Comment by misterfifi1** [comment]
Hi, 

We are facing the same issue, how can we fix it?

Regards,

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/5a588637dcbb120001b85953/event/5a588637b573fd00012e6df9

**Comment by vogography** [comment]
Hi jmcelhaney: I cannot open the link above? Is there any solution for the still existing problem?

**Comment by jmcelhaney** [comment]
https://github.com/wpninjas/ninja-forms/issues/3000
