### ISSUE TITLE
Mailchimp - Warning: curl_setopt(): cannot represent a stream of type MEMORY as a STDIO FILE*

### ISSUE THREAD

**Issue by leecollings** [wpninjas/ninja-forms#2823]
This error has been in this plugin running on PHP 7.1.1 for several releases, and I believe I have commented on it in the past.

> Warning: curl_setopt(): cannot represent a stream of type MEMORY as a STDIO FILE* in C:\wamp64\www\bellavou\wp-content\plugins\ninja-forms-mail-chimp\includes\Libraries\Mailchimp.php on line 207

I had fixed this in the previous version by replacing line 206 from this:
`$curl_buffer = fopen('php://memory', 'w+');`
to this:
`$curl_buffer = fopen('php://temp', 'w+');`

This should be applied for future updates to fix this issue!

**Comment by kjohnson** [comment]
@leecollings looks like we have that reported in the Mailchimp Add-on repo, which is private.

I'll put that on next week's bug fix sprint.

Closing in favor of https://github.com/wpninjas/ninja-forms-mail-chimp/issues/53.
