### ISSUE TITLE
Feature Request: Multi-Select Rows

### ISSUE THREAD

**Issue by MongolianMisfit** [wpninjas/ninja-forms#2824]
In 2.9, for multi-select, there was an option to choose how many rows would show within the multi-select.
At this time there is no option to adjust the number of fields displayed without adjusting the element itself.

This is a customer request based off of ticket: https://wpninjas.kustomerapp.com/app/customers/5949a0a366c5e2001145d698/event/5949a0a3e544760012c02c56

**Comment by Much2tall** [comment]
@kstover I thought we moved feature requests out of GitHub?

**Comment by kjohnson** [comment]
Sounds like we need to re-implement the `multi_size` setting, so that it is also compatible with v2.9.x.
