### ISSUE TITLE
AJAX undefined index 'tag' - error reporting/JSON issue

### ISSUE THREAD

**Issue by maxxwv** [wpninjas/ninja-forms#2827]
If error_reporting is turned on when a form is submitted, the server throws an undefined index notice for 'tag' in Abstracts/MergeTags.php, which throws off the JSON return and apparently breaks the form process notification. Emails still send just fine, but the user is not notified of that and the form appears to be stuck on 'processing'.

**Comment by kjohnson** [comment]
@maxxwv can you provide the error message? This will tell us where, specifically, we need to make changes.

**Comment by maxxwv** [comment]
The line in question is 45 in includes/Abstracts/MergeTags.php. It's an easy change -

`if( ! in_array( $merge_tag[ 'tag' ], $matches[0] ) ) continue;`
to
`if( ! isset( $merge_tag[ 'tag' ] ) || ! in_array( $merge_tag[ 'tag' ], $matches[0] ) ) continue;`
seems to fix the issue.

**Comment by maxxwv** [comment]
@kjohnson Sorry - put that comment there then got busy enough to forget to come back and give the actual error message as requested.

`<br />
<b>Notice</b>:  Undefined index: tag in <b>/server/path/to/wordpress/wp-content/plugins/ninja-forms/includes/Abstracts/MergeTags.php</b> on line <b>45</b><br />
<br />`

Step to reproduce:

- Activate plugin
- Ensure the WP_DEBUG and WP_DISPLAY_DEBUG constants are true
- Submit form

Obviously the error appears in the Network tab of developer's tools. Please note that the returned JSON after the error messages indicates a successful form submission.

**Comment by kjohnson** [comment]
@maxxwv thanks for the PR!

**Comment by maxxwv** [comment]
@kjohnson my pleasure - thanks for merging!
