### ISSUE TITLE
Request for an Image Submit Button

### ISSUE THREAD

**Issue by MongolianMisfit** [wpninjas/ninja-forms#2828]
Based on a support ticket, a user references a 1.0 feature they wishe to implement, one that is not present in 3.0. 
(Original URL of the feature from 2012: http://wpninjas.com/image-ninja-forms-submit-button/)

**Comment by kstover** [comment]
@MongolianMisfit Can you be more specific? When you create an issue here, everything needed to address that issue should be present in the issue. Developers shouldn't need to visit another page to view details.

**Comment by kstover** [comment]
Closing because this is really a documentation issue.
