### ISSUE TITLE
Radio/checkbox list fields have a line break between the label and the element

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2832]
Radio/checkbox list fields have something causing them to appear like they have a line break between the element and list element.

**Comment by kjohnson** [comment]
This seems to be theme specific.

For example, Twenty Seventeen sets all labels to `display:block`.

This is not the case in Twenty Sixteen or Twenty Fifteen.

**Comment by kjohnson** [comment]
This can be resolved by enabling "Opinionated Styles".

Ninja Forms -> Settings -> Advanced -> Opinionated Styles.
