### ISSUE TITLE
NINJA Forms Hanging, Processing Empty

### ISSUE THREAD

**Issue by marcusipp** [wpninjas/ninja-forms#2834]
Since I need forms up I've had to take the Ninja forms down and replace with simple form so I don't lose customers. After clicking submit, going to a blank white pageSome users reported the Submit/Processing just hanging there. All form submissions that came in from the unsubmitted forms were blank in submissions. Any one else reporting issue and find fix?

**Comment by kjohnson** [comment]
@marcusipp When (if) this happens, the issue is usually specific to the site. More often than not it is a plugin/theme compatibility issue.

I would suggest contacting the support team so that they can assist you with your site specifically.
https://ninjaforms.com/contact

**Comment by marcusipp** [comment]
Thank you for your feedback but that actually was not the case at all. Had
the forms installed on several sites and the same thing is happening
everywhere. It turned out that recaptcha has been changed and or updated
and was the cause of the issue. They have since done some update again to
recaptura and the forms
