### ISSUE TITLE
Array to string conversion error when exporting submisssion

### ISSUE THREAD

**Issue by binarykitchen** [wpninjas/ninja-forms#2835]
```
<b>Notice</b>:  Array to string conversion in <b>/home/michael-heuberger/code/infernal.darkness.com/public/wp-content/plugins/ninja-forms/includes/Database/Models/Submission.php</b> on line <b>347</b><br />
```

Happens when I am trying to export a submission from my new videomail-client plugin. Initially reported in https://github.com/wpninjas/ninja-forms-videomail/issues/35 and attached is the broken CVS file.

**Comment by kjohnson** [comment]
Closing in favor of wpninjas/ninja-forms-videomail#35.
