### ISSUE TITLE
On error, form redraws without default values

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2839]
If a field in a form is prepopulated with a default value, when that form is submitted and an error encountered (such as a missed required field), the default value is not present in the field on the redraw.

**Comment by Much2tall** [comment]
@wpnzach
I'm unable to reproduce this. Were any add-ons involved?
Multi-part maybe?

**Comment by Much2tall** [comment]
Appears to be working. Closing issue unless it reappears.
