### ISSUE TITLE
Deleted fields aren't being tracked in action settings

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2840]
Fields used in action settings are showing up as the field merge tag after they are deleted. For example if in User Management you set a Password field as the Password Field setting, then delete the password field, then the password will be set to {field:password} when the action is processed. 

Replication Steps(Using the user management example): 
1. Create a form using the Update Profile template.
2. Delete the password field. 
3. add a dump/die statement to include the Key and Value on like 200 in user_management/includes/actions/UpdateProfile.php. 
4. Fill out the form and view the AJAX request that is sent.

**Comment by jameslaws** [comment]
I'm assuming this has a major impact on an action where a field had been deleted.

**Comment by klhall1987** [comment]
Yes, I let Zach and Kevin know about the issue. I'll talk with @kjohnson about this tomorrow morning.
