### ISSUE TITLE
Actions and filters do not work after Paypal submission

### ISSUE THREAD

**Issue by ioneill** [wpninjas/ninja-forms#2853]
After successfully completing a Paypal transaction, filters and actions do not work. 

I tested the following actions and filters: 

ninja_forms_run_action_settings
ninja_forms_checkout_success
ninja_forms_paypal_express_checkout_success
ninja_forms_checkout_failure
ninja_forms_paypal_express_checkout_failure
ninja_forms_action_email_message
ninja_forms_after_submission

To test: 
* create new form
* add a PayPal Collect Payment (sandbox)
* add an email action
* add a filter (for example):

```php
add_filter( 'ninja_forms_action_email_message', 'sos_ninja_forms_action_email_message', 10, 3);

function sos_ninja_forms_action_email_message ($message, $data, $action_settings){
    $message = "test";
    return $message;
}
```
* Submit the form, and the email will send with the email text as defined in the form builder
* Deactivate the PayPal action, submit the form again, and the email text will be "test"

The same behaviour is seen in all the functions above. 

### Environment ###

Ninja Forms Version:     3.1.6
WP Version:              4.8
WP Multisite Enabled:    No
Web Server Info:         Apache/2.2.22 (Debian)
TLS Version:             1.2
PHP Version:             5.6.30-1~dotdeb+7.1
MySQL Version:           5.6.29
PHP Locale:              negative_sign:
WP Memory Limit:         40M
WP Debug Mode:           No
WP Language:             Default
WP Max Upload Size:      200 MB
PHP Post Max Size:       200M
Max Input Nesting Level: 64
PHP Time Limit:          10800
PHP Max Input Vars:      5000
SUHOSIN Installed:       No
Server IP Address:       192.168.131.111
Host Name:               192.168.131.111
SMTP:                    localhost
smtp_port:               25
Default Timezone:        

### Plugins ###

Installed Plugins:       Ninja Forms - PayPal Express by The WP Ninjas version 3.0.5
                         Ninja Forms by The WP Ninjas version 3.1.6

**Comment by Much2tall** [comment]
@ioneill 

We're aware of this behavior.

The Payment Gateway Action in conjunction with PayPal freezes Form submission and redirects the user to PayPal for payment. The submission then continues when the user returns, using the payload from before the processing of the payment.

**Comment by ripegooseberry** [comment]
So basically no emails are sent (Email actions do nothing) when a Paypal action is used?
That is a SERIOUS limitation.

**Comment by wpnzach** [comment]
@ripegooseberry Email actions do fire if the payment is completed.  If the payment has not been completed, they do not fire.
