### ISSUE TITLE
Email Error not being properly captured

### ISSUE THREAD

**Issue by Much2tall** [wpninjas/ninja-forms#2854]
Your email action "Admin Email" has an invalid value for the "to" setting. Please check this setting and try again.
Your email action "Admin Email" has an invalid value for the "to" setting. Please check this setting and try again.
Your email action "Admin Email" has an invalid value for the "to" setting. Please check this setting and try again.

Steps to reproduce:
- Create a New Form
- Add an Email Field and a Submit Button
- Modify the Email Action to use the Email Field for the "to" address
- Enter an invalid email, such as ,,,@,,,@.com

The error message is thrown, even to non-authenticated users, and the Form cannot be submitted, even after the Email Address has been corrected.

**Comment by kstover** [comment]
Closed in: https://github.com/wpninjas/ninja-forms/pull/2859
