### ISSUE TITLE
Add new field types

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#286]
Here are some but please add other if I'm missing any.
- [ ] Range
- [ ] Color Picker
- [ ] Date / Time
- [ ] Toggle?

As well we need to update our current fields for html5 capabilities like placeholder and defined types.
- [ ] color
- [x] date
- [ ] datetime
- [ ] datetime-local
- [x] email
- [ ] month
- [x] number
- [ ] range
- [ ] search
- [x] tel
- [ ] time
- [ ] url
- [ ] week

Anything I'm missing, concerns, etc.

**Comment by kstover** [comment]
I think that this is something we can do much easier once 3.0 is released.
