### ISSUE TITLE
Issue in JS main.js

### ISSUE THREAD

**Issue by Sankalp1998** [wpninjas/ninja-forms#2863]
Hello,
I am using updated version of Ninja Form and i am facing some issue while using ninja form.
In console it's giving me this error:-  https://gyazo.com/f136aeafbfc0aff44a99af224f00259d
and my form is looking like:- https://gyazo.com/6381eab0ffddbd2194bfb3082343ed2c
Please try to figure out the issue ASAP so i can fix this on my website too.
Thanks

**Comment by Much2tall** [comment]
@Sankalp1998 

Could you provide more information?
If possible, could you post a copy of your System Status? (Ninja Forms->Get Help->Get System Report)

Also, could you provide a link to the page where this Form exists?

**Comment by Much2tall** [comment]
@Sankalp1998 
Closing this issue due to lack of information. If you'd like to reach out to our support team (https://ninjaforms.com/contact/), I'm sure they would be happy to help you.
