### ISSUE TITLE
'Form not found' in large forms

### ISSUE THREAD

**Issue by myhappyidea** [wpninjas/ninja-forms#2866]
Hi,
I am working on a specially long and complex form for one of my clients, and we have reached a moment where we cannot add any more questions / options as it does not save or publish. If i erase a few and save it does save/publish, but if I add a few more, it does apparently save/publish but actuallly its just ignoring us and does not do so.
When this happens we get a "form not found" error on the console log. 
We are kind of baffled because we tried to upload the same form to another server and it let us upload a few more questions but eventually the same thing happened. 
Could this be a php configuration or some sort of memory issue?
I think I have may seen a 'similar' post here but it was closed as they just told the OP to contact NF (I did but got no answer and my client is driving crazy).
Thanks in advance!
Ana

**Comment by Much2tall** [comment]
@myhappyidea 
Without seeing the Form for myself, it sounds like the size of it has exceeded the parameters that your server has set for php processing. We have, in rare cases, also seen issues where that data has reached a size too large for sql. In either case, the best approach to fixing this is to contact our support staff.
All tickets are generally touched within 24 hours, unless submitted over the weekend.

**Comment by myhappyidea** [comment]
Hi, can you give us a hint about which parameters could help us? We increased everything we could, I have no problem in upgrading to a super-server but I would really like to know if this is the cause.
I did submit a ticket yesterday and got no answers, so I was navigating and found this and thought about giving a shot here.
Thanks!

**Comment by Much2tall** [comment]
The best things to check first would be WP Memory Limit and PHP Max Input Vars.
If both of those are already fairly large, it's possible you've encountered the SQL size issue, but we would need to look at the site to be sure.

**Comment by Much2tall** [comment]
Closing conversation in favor of responses via our internal ticket system.
