### ISSUE TITLE
Merge Tags for deleted fields still present as an option after field deletion

### ISSUE THREAD

**Issue by Quay3** [wpninjas/ninja-forms#2867]
Reproduction steps:

1. Add a field to a form. Save form. Delete Field.
2. Add a field of the same type to the form. Save.
3. Open a list of merge tags anywhere in the form. The deleted field remains.

Technically you could skip step 2 to reproduce, but included here to demonstrate the confusion this would cause users. Specific example: User trying to populate To field of an email action. Multiple email field merge tags present due to previously deleted email fields.

**Comment by Much2tall** [comment]
Know issue, but I'll reference it anyway, since it's currently being worked on.

**Comment by kjohnson** [comment]
This seems to be an issue with the Merge Tag Collection.

Specifically, unpublished fields are being removed from the collection when deleted, but published fields are not.

**Comment by kjohnson** [comment]
The Merge Tag Collection is corrected when the Builder is reloaded.

**Comment by kjohnson** [comment]
Theory: 
> The field is created with a `tempID`. When the form is published the field is updated with the new `ID`, but the merge tag reference is not.
