### ISSUE TITLE
Developers/agencies need a way to remove ads for clients

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2879]
From an agency member:

I've recently noticed that the dashboard has some tabs on top (Forms, Extensions and Membership). I have always hidden these from my clients as this is what I would offer them, at our rates, which include support etc... I used to hide the menus using Menu Editor Pro.
Now I can totally understand how this might be good for business, but is there a way to keep designers/developers in mind? I see from the community groups that there are many who take the path of getting the client to buy the plugins/add-ons and another group who manage everything for their clients. I'm from the second group and it's not something I would advertise to my clients.
I'm only hoping you'd take this into consideration, as I would really prefer giving access to my clients to edit and create new forms.

**Comment by kstover** [comment]
Add a filter for removing the add-ons page, banner ads, and the Apps and Integration tab.
