### ISSUE TITLE
RTE Merge Tag Selector loses cursor location when adding merge tags

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#2883]
When inserting merge tags into an RTE with multiple lines, the cursor position jumps around in the RTE. ~~which eventually breaks inserting new merge tags.~~

Edit: Broken merge tags were caused by Capitalization, see #2740.

---

https://db.tt/x0yeOEpNXm

Not sure if this is exclusive to calk merge tags or not. The video above does a good job detailing the issues. Related to https://wpninjas.kustomerapp.com/app/customers/591496a2e041380010cbffaf/event/591496a2e041380010cbffb4

**Comment by kjohnson** [comment]
The cursor placement issue in the RTE seems to be limited to the use of the Merge Tag Button, which moves focus to the Merge Tag Box filter.

Inserting a merge tag by opening a `{` maintains context.

**Comment by kjohnson** [comment]
Further, opening a `{` and then clicking into the filter does not re-create the issue.

**Comment by kjohnson** [comment]
@wpnzach Are you still seeing this with the current `develop` branch?

I'm not seeing it any more; may have been resolved with #2740.

**Comment by wpnzach** [comment]
Yes I still see this behavior in the current develop branch.  I tested in an email action RTE.

**Comment by kjohnson** [comment]
@wpnzach can you do an updated video of the reproduction steps? There might be specific situations that I am not coming across.

**Comment by wpnzach** [comment]
https://goo.gl/U1LbRq
