### ISSUE TITLE
Submissions limit per user or unique field (such as email address)

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2911]
This is very often requested and is more useful to most requesters than an overall submissions limit for the form.

**Comment by mikedamoiseau** [comment]
This code does not take into account submissions that have been sent to the trash. 
The SQL query should also check the `post_status` of the post in the table `$wpdb->prefix . 'posts'` (value of the field should be `publish`).
Or am I missing something here?
