### ISSUE TITLE
Descriptions appear beside single checkbox fields instead of below

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2925]
![image](https://user-images.githubusercontent.com/7498743/28689086-57ba1194-72e2-11e7-8ca6-2b2df2b97aaa.png)
 Help text icon also seems oddly positioned.  Description text should span entire field length

**Comment by Much2tall** [comment]
@wpnzach 
I'm unable to reproduce this locally.
Can you list plugins/theme that were active to see this?

**Comment by wpnzach** [comment]
It's out of the box.  I assigned to James because we worked on it a bit
yesterday

**Comment by wpnzach** [comment]
Also appears strangely when other label positions chosen, all might need some small tweaks

**Comment by wpnzach** [comment]
Another use has complained about this issue

**Comment by wpnzach** [comment]
@jameslaws this needs looked at before conversion as it makes a big difference coming from 2.9
