### ISSUE TITLE
Add a 'currency' option for the Input Mask Restriction setting.

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#2927]
This mask should default to the currency set by the:
1) Form
1) Plugin

**Comment by Much2tall** [comment]
Need to get Locale settings for Calculations worked out before completing this, as there are potential settings that may be defined by that this can use. (To avoid redundancy.)

**Comment by kstover** [comment]
Closing this in favour of https://github.com/wpninjas/ninja-forms/issues/2954. Per our discussion at the dev meeting earlier, the locale portions of the mask can be updated once locales are done; it isn't a blocker for adding the currency mask.
