### ISSUE TITLE
Create the ability to display the total submissions on the front-end of the site via merge tag

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#2951]
Create the ability to display the total submissions on the front-end of the site via shortcode

**Comment by kjohnson** [comment]
@jmcelhaney @kstover what is the context of the feature request?

The original request said `shortcode`, but the updated title says `merge tag`.

Is this needed within the form (ie `merge tag`), or outside the form (ie `shortcode`) ?

**Comment by jmcelhaney** [comment]
To clarify: Create the ability to display the total amount of submissions that the form has made on the front-end of the site via an shortcode
