### ISSUE TITLE
Currency field mask doesn't exist in 3.0 - CONVERSION ISSUE

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2954]
In 2.9, if a field has a currency mask, this doesn't convert to 3.0 and causes this issue on the front end: 
![image](https://user-images.githubusercontent.com/7498743/28892583-77feb374-779c-11e7-825b-5688ffd8c4df.png)

For reference, the above is the 3.0 output of a field converted from 2.9 with a currency input mask 
and a default value of 500

**Comment by wpnzach** [comment]
duplicate of #2927

**Comment by klhall1987** [comment]
I have marked this issue as a high priority. We will come back and fix this bug after @Much2tall is done creating local settings https://github.com/wpninjas/ninja-forms/issues/2950. This will allow us to fully fix the issue instead of just putting a bandaide on the problem.

**Comment by kjohnson** [comment]
PR merged. Closing.
