### ISSUE TITLE
"Confirm" field to ensure two fields match

### ISSUE THREAD

**Issue by MongolianMisfit** [wpninjas/ninja-forms#2959]
Needed for users who want to double confirm email addresses. @kjohnson believes the code is already there and just needs extended to a "Confirm" field that can match any other field.

**Comment by Much2tall** [comment]
I think the code may already exist, yeah. The question is how we want to apply it.

**Comment by kjohnson** [comment]
I created a "Email Confirm" field, which is based on the "Password Confirm" field.
See https://github.com/kjohnson/ninja-form-email-confirm

It should be easy enough to create a generic "Confirm" field.

**Comment by Naima-Awan** [comment]
> I created a "Email Confirm" field, which is based on the "Password Confirm" field.
> See https://github.com/kjohnson/ninja-form-email-confirm
> 
> It should be easy enough to create a generic "Confirm" field.

where to add this code please tell me ??? please
