### ISSUE TITLE
Make Confirm Password Field fail gracefully. 

### ISSUE THREAD

**Issue by amdrew** [wpninjas/ninja-forms#2964]
While troubleshooting a customer's site I found that a form with a `Confirm Password` field generates the following JS error and causes the form to not show:

`TypeError: t is undefined`

WP 4.8.1
Ninja Forms 3.1.9

Replicated on customer's site, 2 local sites and 1 live site. To replicate:

1. Create new WordPress site
1. Activate Ninja Forms
1. Add blank form
1. Add `Password Confirm` field
1. Publish form (submit button is optional)
1. Preview form or add to page and preview

<img width="977" alt="screenshot 2017-08-05 20 03 51" src="https://user-images.githubusercontent.com/52581/28994072-39aeb46e-7a19-11e7-9c27-fa21cabe2a9b.png">

<img width="1426" alt="screenshot 2017-08-05 20 01 57" src="https://user-images.githubusercontent.com/52581/28994053-f829c024-7a18-11e7-9d9b-ea838147d852.png">

You can see the issue on this test site:
http://ninja-forms.sumobi.com/test/

**Comment by klhall1987** [comment]
Hey @amdrew, 

The Confirm Password field needs a password field to be mapped to, so that it has something to confirm. But you're right we need to better handle this error. I'm going to change the name of this issue to better reflect the issue. 

Thanks, 

Kenny
WP Ninjas, LLC

**Comment by amdrew** [comment]
@klhall1987 I did use a password field in combination with the password confirm field, I just simplified the example above for easier replication of the issue. 

I've updated the test site now with both fields (by clicking the password field which auto-adds the confirm) field. Same error:

<img width="756" alt="screenshot 2017-08-08 10 20 51" src="https://user-images.githubusercontent.com/52581/29048128-4557efa4-7c23-11e7-88d9-0082a5c43c79.png">
