### ISSUE TITLE
Add custom user meta merge tag

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2968]
We have had a user request a custom meta merge tag, similar to the{wp:user_first_name}.

**Comment by jameslaws** [comment]
This already exists: https://db.tt/ySsH9GlIaA

**Comment by jameslaws** [comment]
After a quick convo with @klhall1987 he clarified that this would be for customer "user" meta.

**Comment by websbio** [comment]
Any update on this? We receive many user complaints as they have to fill in their information each time they submit a form.

**Comment by jameslaws** [comment]
No movement on this. Once a month we go over feature requests we receive and determine which ones we want to pursue. 

Then it has to fit into one of our current development focuses. If it doesn't it sits as an issue until it does fit into a started development focus.

**Comment by kstover** [comment]
Should follow the convention of the post meta mergetag: {user_meta:YOUR_META_KEY}
