### ISSUE TITLE
Optimize the merge tag queries only run when needed

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2970]
We had a users who reported queries running when they were not needed. The here is the data they sent us:

SELECT meta_key, meta_value
FROM wp_postmeta
WHERE post_id = 0
NF_MergeTags_WP->setup_post_meta()
1 call
NF_MergeTags_Deprecated->setup_post_meta()
1 call

I spoke with Kyle he said it looks like the queries are running on every page/post.

**Comment by kjohnson** [comment]
This isn't a conversion issue.
