### ISSUE TITLE
Email "to" fields including TO, BCC, CC with multiple merge tags need logic to know when to truncate trailing commas

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2974]
It's a not-uncommon use case (two this week) where users might want multiple email addresses in the TO, CC, or BCC fields in the email actions.  The issue is that if merge tags are used for these, but the form is submit without one of these email addresses, the form will fail to submit because of the improper formatting of those fields.

An example use case might be a form registering several people at once for an event.  They should be able to have an email action with multiple recipients, maybe up to four....but if only two are registered instead the merge tags in the CC of an email action might be blank, causing the form submission to fail.

**Comment by kjohnson** [comment]
PR merged. Closing issue.
