### ISSUE TITLE
Feature Request: Timepicker Element

### ISSUE THREAD

**Issue by MongolianMisfit** [wpninjas/ninja-forms#2991]
User request for a timepicker element in 3.0
-with the option of 12 or 24 hour formats
-with hour and minute inputs or the option to round to the hour

**Comment by Much2tall** [comment]
So, a Time Field?
Or maybe an expansion of the Date Field?

**Comment by MongolianMisfit** [comment]
The recent ticket requesting this was referencing an expanded date field. However, I time field would suffice. Of course how this is implemented, may warrant dev discussion.

**Comment by kstover** [comment]
I think that this would fit within our planned "Advanced Date" add-on.

**Comment by webbr** [comment]
Is there any news about that request? 
Would be great as enhancement of the datepicker.
