### ISSUE TITLE
Merge tag selector unusable at bottom of field/action settings

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2996]
See screenshot from user here: https://www.dropbox.com/s/samg5f0be06a1xe/2017-08-05.png?dl=0

Once the selector opens the page cannot be scrolled.  Even if you scroll down in the drawer, part of the selector will still be obscured.

**Comment by kjohnson** [comment]
The `#merge-tag-box` element exists outside of the drawer, so that it maintains persistence outside of the drawer instance. However, being physically outside of the drawer prevents the drawer from inheriting the scrolling event.
