### ISSUE TITLE
Redirect to new window?

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#3003]
Seems like an easy thing to add...some users want to open a new window but still keep their own users on their site after form submission.  Would allow success message and redirect at the same time.  Thoughts?

**Comment by Much2tall** [comment]
I'm a bit hesitant to introduce anything that includes a "popup" window into the product, but I can see where something like this might be useful.

**Comment by kstover** [comment]
Modern browsers would interpret anything that we try to open in a new window as a pop-up and will block them as such.
