### ISSUE TITLE
Merge Tags Not working 

### ISSUE THREAD

**Issue by run7even** [wpninjas/ninja-forms#3005]
Hi, 

I have created a form using ninja forms, my favorite form builder ever. In 2.0, adding fields was no problem. However in 3.0, I am unable to create a "Confirm Your Details" page on my form because the merge tags are displayed on the front end. 

Basically, I create a multipart form. Add final part, add some merge tags like {all_fields_table}, fill out my form, and I just see the merge tag shortcuts, not the data they represent. 

You can access the form here: https://neueautoscheibe.de/termin-vereinbaren/

They do show up in emails, just not on the website.

**Comment by Much2tall** [comment]
@run7even 

This repository is for the resolution of confirmed code errors. It is not a support channel.
In order to have your issue resolved, please submit a ticket to our support team at https://ninjaforms.com/contact/

-KR

**Comment by run7even** [comment]
i have , no response 

On 25. Aug 2017, at 15:48, KR Moorhouse <notifications@github.com> wrote:

Closed #3005.
