### ISSUE TITLE
The Number Field is allowing non-numeric characters to be entered into it

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#3006]
The Number Field is allowing non-numeric characters to be entered into it:

From the user (which I was able to confirm locally)
-Using Safari, you can type all non-integer characters in the Quantity fields.
-Using Firefox, you can type all non-integer characters in the Quantity fields.
-Using Chrome, the following non-integer characters can be entered: e (lower case 'e'), E (upper case 'E'), + (plus sign), . (period)

**Comment by kjohnson** [comment]
According to the spec, `E` and `e` are accepted values as they are used in floating point numbers.
