### ISSUE TITLE
Submissions Page conflict with Yoast SEO plugin

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#3007]
It looks like Yoast SEO is modifying the post query without checking what page it's on.  As a result, our Submissions page no longer respects the form ID and breaks the output when trying to view Ninja Forms submissions.  @kstover has asked that we look at the Yoast code: https://github.com/Yoast/wordpress-seo and find out where it breaks so we can notify their team

**Comment by kjohnson** [comment]
Related to Yoast/wordpress-seo#7750.

**Comment by kjohnson** [comment]
I believe that I tracked down the breaking commit.

yoast/wordpress-seo@26a19fa 
![screenshot-2017-8-23 submissions issue3007 wordpress 1](https://user-images.githubusercontent.com/10858303/29629823-27cb0606-8808-11e7-9d6a-d6aa4f03a212.png)

Previous Commit: yoast/wordpress-seo@cb94368
![screenshot-2017-8-23 submissions issue3007 wordpress 2](https://user-images.githubusercontent.com/10858303/29629824-27ccf0ba-8808-11e7-90b9-ef78081afc0f.png)

Yoast/wordpress-seo#7750

**Comment by moorscode** [comment]
Yoast SEO (& Premium) 5.3.3 has been released, which has patched this problem.
