### ISSUE TITLE
Twenty Seventeen Checkbox/Radio Lists

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#3008]
![image](https://user-images.githubusercontent.com/7498743/29675766-23c8395e-88c4-11e7-9bbd-9c6d5d80f7ee.png)
Elements and labels do not appear on the same line

**Comment by wpnzach** [comment]
related to #2925

**Comment by Much2tall** [comment]
Opinionated Styles correct this when enabled.
Does that still make it a bug?

**Comment by klhall1987** [comment]
Duplicate issue, https://github.com/wpninjas/ninja-forms/issues/2832
