### ISSUE TITLE
PHP Fatal error: Uncaught MailChimp_Error: MCThrift\\Login\\UnknownLoginAccount: No LoginAccount exists

### ISSUE THREAD

**Issue by janhenkes** [wpninjas/ninja-forms#3011]
I am receiving the following error which results in 500 errors showing on our website:

```
PHP Fatal error: Uncaught Mailchimp_Error: MCThrift\\Login\\UnknownLoginAccount: No LoginAccount exists with user_id=xxxx and login_id=xxxx in wp-content/plugins/ninja-forms-mail-chimp/includes/Libraries/Mailchimp.php:253, referer: http://m.facebook.com/
Stack trace:, referer: http://m.facebook.com/
#0 wp-content/plugins/ninja-forms-mail-chimp/includes/Libraries/Mailchimp.php(228): Mailchimp->castError(Array), referer: http://m.facebook.com/
#1 httpdocs/wp-content/plugins/ninja-forms-mail-chimp/ninja-forms-mail-chimp.php(177): Mailchimp->call('lists/list', '{"apikey":"xxxx...'), referer: http://m.facebook.com/
#2 wp-content/plugins/ninja-forms-mail-chimp/includes/Actions/MailChimp.php(119): NF_MailChimp->get_lists(), referer: http://m.facebook.com/
#3 wp-content/plugins/ninja-forms/includes/Abstracts/ActionNewsletter.php(104): NF_MailChimp_Actions_MailChimp->get_lists(), referer: http://m.facebook.com/
#4 wp-content/plugins/ninja-forms/incl in wp-content/plugins/ninja-forms-mail-chimp/includes/Libraries/Mailchimp.php on line 253, referer: http://m.facebook.com/
```

I hope you guys can help me out!

**Comment by klhall1987** [comment]
Hey Janekes, 

This issue is going to need some troubleshooting. Please submit a ticket to our support team(https://ninjaforms.com/contact/) and they will help you start tracking down this issue. I'm going to close this issue, as this repo is meant for troubleshooting issues with Ninja Forms Core.

Thanks, 

Kenny
WP Ninjas LLC

**Comment by janhenkes** [comment]
Bedankt voor uw bericht, van 31 augustus t/m 4 september ben ik afwezig. Bij urgente zaken kunt u contact opnemen met mijn collega's via 070 820 05 72 of door een mail te sturen naar helpdesk@jannesmannes.nl.


Met vriendelijke groet,
Jan Henkes

**Comment by janhenkes** [comment]
Bedankt voor uw bericht, van 31 augustus t/m 4 september ben ik afwezig. Bij urgente zaken kunt u contact opnemen met mijn collega's via 070 820 05 72 of door een mail te sturen naar helpdesk@jannesmannes.nl.


Met vriendelijke groet,
Jan Henkes
