### ISSUE TITLE
Exclusions from Date Field

### ISSUE THREAD

**Issue by Much2tall** [wpninjas/ninja-forms#3016]
Ability to exclude specified dates or days of the week from the possible selections in a Date Field.

**Comment by iowawesleyan** [comment]
On Ninja Form's date picker field, I need the ability to exclude dates or days of the week

**Comment by kstover** [comment]
We have an add-on planned to allow you to do more advanced things with dates out of the box; this can be done currently with custom code.

**Comment by iowawesleyan** [comment]
Can you help me with the custom code?
