### ISSUE TITLE
Default Value Merge Tag Conversion

### ISSUE THREAD

**Issue by Much2tall** [wpninjas/ninja-forms#3018]
Need to do a dive of what Merge Tags aren't being properly updated during conversion from 2.9 to 3.

Known issues:
- [x] Querystring
- [x] Wordpress settings (wp:post_url, etc.)

**Comment by kjohnson** [comment]
v2.9.x Form Export: ["Default Value Conversion Test Form"](https://github.com/wpninjas/ninja-forms/files/1271215/DefaultValueConversionTestForm.zip)
