### ISSUE TITLE
Issue when deleting fields

### ISSUE THREAD

**Issue by anastasis92** [wpninjas/ninja-forms#3027]
When I delete a field from the form and click the publish button an infinite loop occurs. After I refresh the browser the field is not deleted.

**Comment by Much2tall** [comment]
@anastasis92 

We're unable to reproduce this locally, and as this repository is for known, existing issues, please contact our support team for further diagnosis of the problem. (https://ninjaforms.com/contact/)

Our support staff would be happy to help walk you through resolving your problem.
