### ISSUE TITLE
Feature/Add-on Request: Front-end Viewing for Users to See Their Own Submissions

### ISSUE THREAD

**Issue by MongolianMisfit** [wpninjas/ninja-forms#3039]
> "It would be great if we could have a way to give our users a front-end solution for viewing their own submissions. A list of all forms submitted with the response formatted nicely (perhaps the possibility to create a view option for forms similar to how forms are built)."

Original ticket:
https://wpninjas.kustomerapp.com/app/customers/58b09cb953052f1100119a61/event/59b12504cf16160011a4142d

**Comment by Much2tall** [comment]
This might be a duplication of concept for "Views".

@kjohnson @kstover

**Comment by kstover** [comment]
This would be covered by our planned "Views" extension, as @Much2tall stated above.

**Comment by Orrefors** [comment]
@kstover Hi, when is this extension planned to be available?
