### ISSUE TITLE
Display bug on single checkbox

### ISSUE THREAD

**Issue by jameswinston58** [wpninjas/ninja-forms#3059]
I've tested this on multiple installs and have had the same results in Chrome and Firefox. (I have not checked IE).

The label and checkbox element only take up a small amount of a given area when using left of right label alignment.

Example:
![screen shot 2017-09-11 at 2 33 51 pm](https://user-images.githubusercontent.com/31865158/30294190-e07d2730-9701-11e7-8d5d-a6a9b3d5407e.png)

**Comment by jameslaws** [comment]
This is fixed in a release later this week.
