### ISSUE TITLE
Required Fields that have not been focused do not get caught as required

### ISSUE THREAD

**Issue by Much2tall** [wpninjas/ninja-forms#3069]
Any required field that has been conditionally shown (part or individual field) is not being treated as "required" for Form Submission to take place.

**Comment by jmcelhaney** [comment]
It appears that is is for any field that has not had focus.
To replicate:
Create a form with fields that are required.
Submit the form without filling out or giving focus to any fields and submit.
The form will submit without any required field errors.

**Comment by kjohnson** [comment]
PR in Layout & Styles in merged. Closing issue.
