### ISSUE TITLE
Giving a hint - Switching from From Settings to Field Settings.

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#307]
I open the Add New form. Look at the Form Settings and do nothing and click the Field Settings. I am not able to move on before adding a form title. There is not hint of this though. 

It would be good if the focus skiftet toward the Form title box having the cursor blink in it giving the hint to the user that one needs to give the form a name/title. Or some other hint of needing to give the form a title and save it before moving on to Field Settings. I would also probably give the title box some more space as it feels a bit crammed between the top tabs and the From Email Settings area. Perhaps add some text above the form title box.

**Comment by kstover** [comment]
Version 2.9 should take care of this problem.
