### ISSUE TITLE
Checkbox field ignoring custom values set in the field. 

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#3076]
Checkbox field ignoring custom values set in the field. 

To replicate:
Create a form with a single checkbox
Go under the Advanced settings of the field and set values
Submit the form then check the submissions and the custom value that is set is not recorded

**Comment by kjohnson** [comment]
Another report from Ken Prayogo (ken.prayogo) via the Developer Slack.

> "When editing an existing form submission, no multi-select field displays any of the selected values, so all the checkboxes are unchecked even though the user submitting did select some options."

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/599318652725970010399648/event/59c8df249cccaf00122e7f9a

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/59c233273a331600117929f7/event/59c233273a331600117929f9

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/5821adb805b06a1100148b36/event/59ddd368db61f20001bd2b37

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/59f318dbc4f5d30001fe6109/event/59f318dbc4f5d30001fe610f
