### ISSUE TITLE
Add option to import submissions via the export CSV

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#308]
Many users are asking for an easy way to copy submissions from one site to another with the same forms (3 this weekend alone).  It would be beneficial to have the option to "Import Submissions" the way we export them.

**Comment by bradleysa** [comment]
@wpnzach thanks for creating this ticket. @kstover is correct about my use case. I thought there would be an option to export the form submissions, and then important them at a different domain. There is currently an option to export form submissions into a .csv, but there is not an option to important submissions from a .csv. 

I am not using ninja forms as a CRM, but I am using it as a database.

Does anyone have any suggestions, or know of any options, for importing submissions?

**Comment by ChrisAynesworth** [comment]
Importing submissions into a form via .csv would be amazing! I currently have to export 500+ form submissions into ninja. Would love to hear that there is an easier way to do it than by hand somehow...

**Comment by j4jes** [comment]
I have just exported my submissions to CSV and noticed they are in ascending order with newest on top. I have 100+ old entries from a previous system that I have added to the CSV document in ascending order, trying my best to keep the same format fields and columns. I guess I assumed there was an import submissions, seems logical if there is a download submissions. Now I'm stuck possibly having to enter these 100 entries manually !!

**Comment by mbacon40** [comment]
This is something that would really be a useful tool. We do not use Ninja Forms as a CRM, but save them there as a backup that needs to be referenced from time to time. We have run into situations where we have done some work on a staging version of a site and were ready to push live but then realized that we would wipe out our form submissions in the process. It would be incredible if we could just have the ability to import these forms.

**Comment by Helyanti** [comment]
> This is something that would really be a useful tool. We do not use Ninja Forms as a CRM, but save them there as a backup that needs to be referenced from time to time. We have run into situations where we have done some work on a staging version of a site and were ready to push live but then realized that we would wipe out our form submissions in the process. It would be incredible if we could just have the ability to import these forms.

I have the same problem too like @mbacon40. When I was pushing update form staging to live website just realized that the forms in live got overwritten with those in staging. Luckily I had enable Admin Email Notification so I can still refer to the data there. 

Is there any way to skip the data from being overwritten when pushing update to live website? Or the only option is to export prior to updating the site?

**Comment by JoseAMijaresRS** [comment]
I would benefit too form this request.
i migrated a website to another host and the contacts where not imported. I need a way to join the old submission with the new submissions amd keep all of them in one place.
