### ISSUE TITLE
Hidden Field Template doesn't use type hidden

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#3085]
The field template for the Hidden Field Type does not use type `hidden`, but rather hard codes the inline style `display:none`. This can cause conflicts with themes/plugins/custom css in which the hidden fields are shown.

**Comment by phrichards** [comment]
I'll work on this one. But I'm going to wait till after Oct. 1 to submit the PR for Hacktoberfest, hope that's cool.

**Comment by acekyd** [comment]
If this is not yet done, can I pick this up @kjohnson
