### ISSUE TITLE
Form doesn't load - infinite loader

### ISSUE THREAD

**Issue by dimic00** [wpninjas/ninja-forms#3100]
Hi,

I build a form in the back-office, I published it and pasted the shortcode into my page and put my page alive.
When I go to my page, the form doesn't load, I only saw the loader again, again and again.

No error in the JS console.
I tried to create a new form, with new fields, nothing change. I disabled my JS scripts, nothing change. I disabled all plugins (except Ninja Forms), nothing change. I also desactivated and deleted my Ninja Forms plugin, and installed it again, but yeah, you know, nothing change. So I am a bit disarm...

Wordpress version : 4.8.2
Ninja Forms version : 3.2.1

If you have an idea !

Thanks

**Comment by Much2tall** [comment]
@dimic00 We're unable to reproduce this error.
As this repository is a location for confirmed issues with the product, not a support channel, please contact our support team at https://ninjaforms.com/contact/ and they should be able to help you work through your issue.
