### ISSUE TITLE
Getting error on the front-end when rending form: Error: The input type "number" is not supported by autoNumeric

### ISSUE THREAD

**Issue by qodo** [wpninjas/ninja-forms#3108]
```
Error: The input type "number" is not supported by autoNumeric
https://www.mysite.org/wp-content/plugins/ninja-forms/assets/js/min/front-end--autonumeric.min.js?ver=3.2.1
Line 9
```

- **What actions are you taking?**
Trying to load a form created with Ninja Forms

- **What had happened was...** 
Form fails to load completely.
```
Error: The input type "number" is not supported by autoNumeric
https://www.mysite.org/wp-content/plugins/ninja-forms/assets/js/min/front-end--autonumeric.min.js?ver=3.2.1
Line 9
```

Using Firefox 55 in Windows 10.
Also on Chrome for windows

**Comment by wpnzach** [comment]
@qodo can you submit a support request here: https://ninjaforms.com/contact/

This isn't something we can reproduce so I need to close this issue, but our support team should be able to help you get sorted.
