### ISSUE TITLE
Forms can be submitted with blank required fields

### ISSUE THREAD

**Issue by SippieCup** [wpninjas/ninja-forms#3109]
- **What actions are you taking?**

  - Open a ninjaform that has a required field, hit submit, and it'll go through

- **What are you expecting to occur?**
  - Expected validation errors
- **What is occurring instead?**
  - the form is submitted with required fields being blank.

**Comment by kjohnson** [comment]
@SippieCup this should be resolved in the latest release of Layout & Styles.

There was an issue where L&S was overriding the validation method for the formContentData.
