### ISSUE TITLE
Country list - default sort

### ISSUE THREAD

**Issue by jbostoen** [wpninjas/ninja-forms#3117]
When adding a **country** field, the sort seems to be based on the value. 
In Dutch, "Belarus" is "Wit-Rusland"; yet it suddenly appears between countries with B.

**Comment by isaactorresmichel** [comment]
Added a PR to fix this problem.

**Comment by jbostoen** [comment]
Just purchased Ninja Forms. :)

Glad to see the issue on the front end was resolved so quickly. Minor detail: back end still seemed to be sorted on value?
