### ISSUE TITLE
Field blocks or importing form into form

### ISSUE THREAD

**Issue by jbostoen** [wpninjas/ninja-forms#3118]
Unless I'm mistaken, it's not possible yet to create field blocks in the UI?

Case: I have to create lots of different Ninja forms where there's a block with first name, last name, email, phone number, street, zip code, country (and for some defaults are provided).

Another "easy" work-around would be the option to include an existing form (where predefined blocks, actions would be added at the bottom of existing fields, actions).

My current work-around is that I've created a form with those things and copy that one to start from.

**Comment by Much2tall** [comment]
@jbostoen 
You are correct. It is not currently possible to create Field blocks or import a Form into another Form.

Field blocks are something that's on our radar, but it's still an abstract concept. Importing Forms into other Forms probably won't happen.

Out of curiosity, would the ability to save your Form as a Custom Template (which would appear in the **Add New** menu) resolve your issue?

**Comment by jbostoen** [comment]
Thanks for your answer.

It would be easier if that could be done in a straight-forward way. 

For the moment, I just made my template as a form instead and then copy it all the time. For our other users, it's something they'll need to know.

**Comment by Much2tall** [comment]
Sounds good.

Closing this issue in favor of discussion here: https://github.com/wpninjas/ninja-forms/issues/3135
