### ISSUE TITLE
Submission sequence number not incrementing on duplicated form

### ISSUE THREAD

**Issue by marian37** [wpninjas/ninja-forms#3136]
Few days ago I realized, that each submission in my forms, that were **duplicated** from a template form, has **sequence number 1** - it **does not increment**.

When I quickly looked at source codes, it looks like it is caused by the changes in method **duplicate()** from class **NF_Database_Models_Form**. It is also connected with how **get_next_sub_seq()** method in the same class works.

**Comment by Much2tall** [comment]
Good catch!

I can locally confirm this behavior.

**Comment by klhall1987** [comment]
https://wpninjas.kustomerapp.com/app/customers/59e88391efef9e000167e411/event/59e6140686980e0001842e29

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/59de385b3485330001a83176/event/59f34fbac4f5d300010276b2

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/59f72f08242e060001a6b6da/event/59f72f08242e060001a6b6de

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/589b6fdb2f7cef10007aa2c7/event/59f872e8b1fc9600019910e1

**Comment by Quay3** [comment]
https://wpninjas.kustomerapp.com/app/customers/59fb2645a2dc1700017b3904/event/59fb2645272cb70001bb8359

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/59fbb6df7ba5470001b36c19/event/59fbb6df211dcc0001dae79f
