### ISSUE TITLE
How to display a custom action result in the success message

### ISSUE THREAD

**Issue by TonyC5** [wpninjas/ninja-forms#3142]
Using Ninja Forms 3.2.1 with WordPress 4.8.2, I have created a custom action (WP Hook) that submits the form data to an external database (not the WordPress database).  After recording the form data in the external database, the custom action generates a unique tracking number that I would like to provide to the user in the form's success message.  I have successfully implemented a success message with my own merge tag, but I don't know how to pass the tracking number from the custom action to the success message.  So far, I have only been able to configure a static value in the merge tag to display in the success message.  I have not figured out how to dynamically update the merge tag with the unique transaction ID from the custom action.

Am I correct in attempting to use a merge tag to display the transaction ID in the success message?  If so, how do I pass a value from the custom action to the merge tag?  If a merge tag is not the correct way to do this, what is the correct way to pass and display a value from my custom action to the success message?

**Comment by TonyC5** [comment]
It might help if I explain my specific use case for Ninja Forms:  For the issue explained above, I am attempting to use Ninja Forms to submit helpdesk requests.  The user completes the helpdesk ticket form and clicks Submit.  The form's custom action (a WP Hook) records the form data in an external database and generates a unique ticket number.  I would like to display this unique ticket number in the success message like this: "Your helpdesk ticket number is X," where X is the unique ticket number generated in the custom action.  I assume that the Ninja Forms Success Message supports this "dynamic" display capability and I have attempted to implement this with a merge tag, but I have not figure out how to create a custom merge tag that captures the unique ticket number produced by my custom action.  So far, I have only figured out how to use the merge tag to display a static value that is predefined in my custom merge tag class.

**Comment by TonyC5** [comment]
Thanks to some help in a Ninja Forms Slack discussion, I looked at the `ninja_forms_run_action_settings` action processing filter.  In order to use Ninja Forms to submit helpdesk tickets and to report the unique ticket number in the Success Message, I removed my WP Hook Action (so that my form has only one action: the Success Message Action) and moved my custom callback code (previously called by the WP Hook Action) into a custom `ninja_forms_run_action_settings` filter.  The custom filter parses `$action_settings['email_message']` to get the form field values, submits the form field values to an external helpdesk database and adds the resulting helpdesk ticket number to `$action_settings['success_msg']` before returning `$action_settings.`  

Admittedly, I'm a NInja Forms newbie, so I'm really hoping there's  a better way to do this.  For now it seems to me that Ninja Forms needs an easy way for a custom callback called by WP Hook to dynamically update the Success Message.

**Comment by Much2tall** [comment]
@TonyC5 
Closing issue as this repository is a place for known bugs in the software, not development questions.
We'll be happy to continue discussing things with you in our developer slack channel.

**Comment by TonyC5** [comment]
I understand why you closed this.  Could you please convert this into a feature request for making it easier to display real-time-generated success messages based on the result of a WP Hook action?  The current implementation makes it extremely difficult to perform a custom Action (via WP Hook callback) and communicate the results of this action to the Success Message action.  My simple use case is a form to submit a help desk ticket, where the success message includes a unique ticket number for each submission.  The ticket number is generated in the WP Hook callback.
