### ISSUE TITLE
ninja_forms_processing_callback key is different from documentation

### ISSUE THREAD

**Issue by TonyC5** [wpninjas/ninja-forms#3143]
Using Ninja Forms 3.2.1 and WordPress 4.8.2, I created a custom function `my_ninja_forms_processing_callback` to be used in `add_action( 'my_ninja_forms_processing', 'my_ninja_forms_processing_callback' );`  Ninja Forms documentation stated that to get the form ID in my custom callback function, I needed to use the `id` key as follows

`function my_ninja_forms_processing_callback( $form_data ) {
    $form_id       = $form_data[ 'id' ];
...
}
`

I have found that the key `id` is not correct.  The correct key that works for me in my custom call back is `form_id` used as follows:

`function my_ninja_forms_processing_callback( $form_data ) {
    $form_id       = $form_data[ 'form_id' ];
...
}
`

**Comment by Much2tall** [comment]
Closing this in favor of discussion at https://github.com/wpninjas/ninja-forms/issues/3051 .
The issue does still need to be addressed, but it's not the only problem with the documentation.
A more broad approach will be necessary.
