### ISSUE TITLE
Where does submission data get saved?

### ISSUE THREAD

**Issue by weareselect** [wpninjas/ninja-forms#3150]
Hello, 

I'm trying to find out where the data is being saved from my forms. We are trying to create a search function to "search" the data but I cannot find the tables nor make any sense of it. 

I have the following in the DB

wp_nf3_actions | 
wp_nf3_action_meta
wp_nf3_fields
wp_nf3_field_meta
wp_nf3_forms
wp_nf3_form_meta
wp_nf3_objects
wp_nf3_object_meta
wp_nf3_relationships

Any advice would be greatly appreciated

**Comment by Much2tall** [comment]
@weareselect 
Submissions themselves are stored in a WordPress Custom Post Type.
You can find them in the `wp_posts` and `wp_postmeta` tables under the post type of 'nf_sub'.

Closing issue, as this repo is for the tracking of known bugs in the software.

For further dev questions, you can reach us at developer.ninjaforms.com/slack.
