### ISSUE TITLE
Cannot define styles for custom element classes

### ISSUE THREAD

**Issue by TonyC5** [wpninjas/ninja-forms#3153]
- **What actions are you taking?**
  - I assigned custom container and custom element classes to my Ninja Form fields so that I can create CSS to modify the field styles.   I am referencing the custom container and custom element classes in CSS to modify the container and element styles.  I’m running WordPress 4.8.2, Ninja Forms 3.2.2, PHP 5.6.31.

- **What are you expecting to occur?**
  - I expect to be able to modify the style of my field containers and the style of my field elements by referencing their respective custom classes in CSS.

- **What is occurring instead?**
  - I am able to modify the style of my field containers using the custom container class, but I cannot modify the style of my field elements using the custom element class. In order to modify the style of the elements, I am having to use the Ninja Forms assigned element ID (e.g. #nf-field-54).

**Comment by Much2tall** [comment]
@TonyC5 
Could you link us to the page where you're trying to achieve this result?
We would like to take a look at your style rules to see where the breakdown is.

**Comment by TonyC5** [comment]
https://www.alottajava.com/request_reissue

**Comment by Much2tall** [comment]
Classnames: reissue-gift-card-id-container and reissue-gift-card-auth-code-container?

I can affect both of these via CSS on the page by inserting it with browser dev tools.

I can also add a class to my local installation and affect it via CSS on the page.

Please confirm that your CSS file was getting properly output to the page and you didn't have any other CSS rules overwriting the ones you were trying to display.

If you experience further issues with it, please reach out to our support team at (ninjaforms.com/contact). They're better equipped to troubleshoot issues. This repository is for tracking known bugs in the codebase.

**Comment by TonyC5** [comment]
@Much2tall - As I indicated in my problem statement, the container classnames work.

The element class names do not work.

**Comment by TonyC5** [comment]
@Much2tall - Here are examples of what works and what doesn't work.

This works:

`#nf-field-52 {
  width: 7em !important;
}`

This does not work:

`.reissue-gift-card-id-element {
  width: 7em !important;
}`

**Comment by TonyC5** [comment]
@Much2tall I have confirmed that checkbox input styles cannot be referenced (in CSS) by their custom classes.  Not sure, but this may be a CSS limitation and not a Ninja Forms limitation.

For example;

This works:

`input[id=nf-field-76] {
  transform: scale(1.5);
}`

This does not work:

`input[class=my-checkbox-element] {
  transform: scale(1.5);
}`
