### ISSUE TITLE
Datepicker format not using default format from the Ninja Forms Date setting on load.

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#3172]
Datepicker format not using default value from the Ninja Forms Date setting on load. You have to change the option to another choice and then back to default for it to use the default format.

Steps to reproduce:
1. Add a datepicker field and view the form
2. The format will include the time despite what is set under Ninja Forms  > Settings > Date Format 
3. Change the date format then change it back to default and view the form.
4. The date format will be correct.

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/59fbd697211dcc0001dc6924/event/5a0118d673bb2d0001874565

**Comment by dtomasch** [comment]
I'm also having this same problem. Is there a fix?

**Comment by jmcelhaney** [comment]
https://github.com/wpninjas/ninja-forms/issues/3163

**Comment by mtderse** [comment]
I am having this same issue.
![image](https://user-images.githubusercontent.com/17810707/36548323-fec828ec-17bd-11e8-8c20-fb10ebc0b7dd.png)
