### ISSUE TITLE
Single Line Texts Fields with the currency mask and marked as required throw 'field required' errors even if the field is filled in

### ISSUE THREAD

**Issue by ericwindham** [wpninjas/ninja-forms#3173]
- **What actions are you taking?**
Create a single line text field, mark it required, and set the mask as 'currency'
  The form will not submit, throws 'missing required field' errors even though the field has a valid value
- **What are you expecting to occur?**
  The form should submit if the field has a valid value

**Comment by jmcelhaney** [comment]
Related to this issue: https://github.com/wpninjas/ninja-forms/issues/3115
