### ISSUE TITLE
Form is inserting in to multiple (odd) places. Only the first instance loads. (not Preview).

### ISSUE THREAD

**Issue by EkDor** [wpninjas/ninja-forms#3176]
My forms are inserting into multiple(and frankly odd) places in my website. I am not using Form Preview.

I can see 6 instances of it attempting load. Shown in screenshot bellow zoomed out and turned Java-Script off to make it more effective to view. Link to example page also bellow. Using NinjaForms v3.2.3

![screen shot](https://user-images.githubusercontent.com/8142101/32142611-b7d9696a-bcea-11e7-8bf0-0ad4e27d7a04.jpg)

http://www.parklandsart.com/development/

**Most of the things I have tried.**
- Load the page in different browsers. (logged out)
- Logged in and out.
- Brand new form using template. Only changed it's name.
- Only default templates used with the page I have appended the form to.
- Turned all but the primary NinjaForms plugin off.
- Googled
- Looked for similarities between the inserted sites.
- Looked for error message in Inspector, none came up.

Is there a way to specifically specify where the form is to be inserted, instead of leaving it to the plugins best guess? I would alway opt for that any way.

Cheers, Brook

**Comment by EkDor** [comment]
bump

**Comment by EkDor** [comment]
Could some one address this. At least acknowledge my issue somehow. Any ideas I can follow? I have a deadline. If this can't be resolved I will end up having to do a last minute switch to some non NinjaForms  plugin. And I'll have to ask for my money back for all the plugins I just renewed.

**Comment by Much2tall** [comment]
@EkDor 
This repository is for known issues with the codebase.
We are not able to reproduce your problem on our local machines.

In order to get this resolved quickly, we recommend you reach out to our support team at ninjaforms.com/contact.

**Comment by EkDor** [comment]
Well that's unprofessional.
