### ISSUE TITLE
Search in Submissions is not working in WP 4.8.3

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#3182]
The Search in Submissions table is not working since updating to WordPress 4.8.3

https://github.com/wpninjas/ninja-forms/blob/a8659baf2eff79852ad9b9d4b23be382748e129c/includes/Admin/Menus/Submissions.php#L208

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/59a7398852423e0010dd9be2/event/59f99030b1fc960001a89a4a

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/58ee5ff0570c0b1100032105/event/59f9da9bb1fc960001ac07f6

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/59fa1420268a35000194b19b/event/59fa1420268a35000194b19e

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/58b6c25a53052f110021077a/event/59fb1696272cb70001ba981d

**Comment by sevensix** [comment]
this is "low priority". For us it is important/essential to search! We have to edit the entries in the backend for specific entries, so we have to search them. How should we find an enrie when we have couple of hundred entries? This is absolutly prioirty high for us. When will ninja forms working again?

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/59cecec28f18290001c89afe/event/59fb5d8d5c7114000159ee4f

**Comment by MongolianMisfit** [comment]
https://wpninjas.kustomerapp.com/app/customers/58404a3939f60d1100a880ea/event/59fb525c5c7114000158cd39

**Comment by jmcelhaney** [comment]
This is also an issue in the 2.9.x codebase.

**Comment by klhall1987** [comment]
I've added this to my list of items to work on tomorrow morning.

**Comment by magiabinaria** [comment]
the last update of Ninja Forms did not fixed this error.

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/589ce3c12b74d711009a9888/event/5a12c0ad4cc29b00012ea796

**Comment by mvander3** [comment]
+1, this seems to be affecting me, as well. A fix or even a workaround would be much appreciated!

**Comment by exelWeb** [comment]
Fixed it by changing in
ninja-forms/deprecated/classes/subs-cpt.php:

-				$pieces['where'] = str_replace("((({$wpdb->posts}.post_title LIKE '%", "( {$query} (({$wpdb->posts}.post_title LIKE '%", $pieces['where']);
 
 +				$pieces['where'] = str_replace("((({$wpdb->posts}.post_title LIKE '", "( {$query} (({$wpdb->posts}.post_title LIKE '", $pieces['where']);

**Comment by haydenkshaw** [comment]
Why did you close this Much2tall? Ninja Forms hasn't pushed out an update to fix this yet

**Comment by wpnzach** [comment]
@haydenkshaw it's closed because the fix is merged and will be in the next update.  If you'd like to test it, please try the development branch.

**Comment by haydenkshaw** [comment]
Ah ok, excellent. Good to know. I'll post another comment when this update's released as I don't think I'm the only one waiting for this.

**Comment by haydenkshaw** [comment]
3.2.5's been released. As was said previously, this update [fixes the issue](https://github.com/wpninjas/ninja-forms/blob/3.2.5/readme.txt#L118). Bump @jmcelhaney @sevensix @MongolianMisfit @mvander3 @exelWeb to make sure you're aware.

**Comment by LDDConsulting** [comment]
The issue has not been fixed, I have updated to latest version

**Comment by mvander3** [comment]
It's definitely working for me. Thanks!
