### ISSUE TITLE
[Feature Request] Add Help Text to HTML Fields

### ISSUE THREAD

**Issue by TonyC5** [wpninjas/ninja-forms#3187]
- **What actions are you taking?**
  - I created a multi-column form and used an HTML field to create a single heading for the columns.  I would like to have a single pop-up help text for the columns.
- **What are you expecting to occur?**
  - I expected an HTML field to have the same Help Text and Description options (Display options) as other Ninja Forms fields, so that I can add Help Text to the HTML field.  This Help Text for the HTML field would be the Help Text for the multi-column input. 
- **What is occurring instead?**
  - HTML field does not have the same Help Text and Description options (Display options) as other fields.

**Comment by TonyC5** [comment]
I was able to mimic the Help Text behavior by include the following in my HTML field:

<span class="ninja-forms-req-symbol">*</span>
<span class="fa fa-info-circle nf-help" data-text="help text"></span>

**Comment by Much2tall** [comment]
As the HTML Field is intended to display all information itself and allows for a large variety of code input options, these features were not tied to it to prevent them from becoming cumbersome and confusing to both the administrator and the end users.
