### ISSUE TITLE
Custom meta Tags display merge tag if user is not logged in. 

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#3192]
If a custom meta tag is used in a field as a place holder and a user is logged out then the merge tag for that piece of custom meta is displayed in the field.

**Comment by jmcelhaney** [comment]
https://github.com/wpninjas/ninja-forms/issues/3201

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/5936ab9d6ec6a6001108fba3/event/5a09b6309575c20001744e64

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/586a35b8ac42cf10007bb66d/event/5a64ddfcf3fbb8000184de34

**Comment by jmcelhaney** [comment]
This is also an issue with querystring merge tags. If there is not a querystring, the merge tag itself gets saved.
https://wpninjas.kustomerapp.com/app/customers/5a543c2ab573fd0001f65e93/event/5a5434122596b70001ac840b
