### ISSUE TITLE
Conditional Fields: Cannot Submit When Required Field is Hidden (again)

### ISSUE THREAD

**Issue by toddnagel** [wpninjas/ninja-forms#3195]
So, an old ticket on this was closed, I just updated my conditional logic function into our dev site and it broke, now everything hidden required, is now unable to allow the form to submit because they are required, it worked fine an hour ago before the update..

Before the update, all hidden required items were not required, now they are required even when hidden..

Any help?

**Comment by Much2tall** [comment]
@toddnagel 
We're not able to reproduce this wholesale. However, we did see an error that if a required field gained browser focus without being filled in and then was hidden, it did not remove the error that prevents submission.

Is this the behavior you're seeing?

**Comment by toddnagel** [comment]
howdy, actually, we went ahead and updated the ninja form to the version 3,
and ended up with the styles plugin not working, but the validation went
back to working once we did this..

then, we had an error on login on our live site which was not using ninja
stuff, and it looks like were heading towards a php upgrade, and possible
more ram..but it appears the php version was not cutting it for wordpress
anymore..

so it could have been something that simple, it was the styles plugin that
got upset, so not sure why the updated plugins made the validation stop
working, but I am glad to be off the backwards compatibility mode..

will let you know if this comes up again, but for now, for us, the
validation issues have been solved!

Todd

Todd Nagel
818 482 3177
