### ISSUE TITLE
JavaScript event on validation error.

### ISSUE THREAD

**Issue by burhandodhy** [wpninjas/ninja-forms#3208]
I'm looking to integrate a Google Analytics events tracking, I need to run the Analytics script only when the form has some validation error. 

Is there any event through which it can be done?

**Comment by Much2tall** [comment]
Closing this issue, as this repository is for known bugs in the software.

@burhandodhy 
You can take a look at our developer documentation here: http://developer.ninjaforms.com/codex/
Or, if you want to talk with other devs, you can probably get an answer from someone in our developer slack here: http://developer.ninjaforms.com/slack
