### ISSUE TITLE
.fa-info-circle image is garbled

### ISSUE THREAD

**Issue by TonyC5** [wpninjas/ninja-forms#3215]
- **What actions are you taking?**
  - I'm adding help text to my fields.  When the help text is specified, the .fa-info-circle appears in the field label so that the user can hover over the .fa-info-circle for help.
- **What are you expecting to occur?**
  - I'm expecting the white "i" in the black circle to be recognizable as a common "info" symbol.
- **What is occurring instead?**
  - The .fa-info-circles in all of my forms are garbled.  The "i" in the black circle is illegible, so the symbol is not recognizable.

This can be fixed by adding the following custom CSS:

.fa-info-circle:before {
  display: none !important;
}

It looks like the following css in ninja-forms/assets/css/font-awesome.min.css is unnecessary/incorrect:

.fa-info-circle:before {
  content:"\f05a"
}

**Comment by Much2tall** [comment]
@TonyC5 I'm unable to reproduce this locally.

Can you confirm that you are experiencing this behavior with all other plugins disabled and on a default WordPress Theme, such as Twenty Sixteen?

**Comment by TonyC5** [comment]
@Much2tall This issue that I reported is caused by my theme (Fruitful Theme).  I installed Ninja Forms on a clean WordPress 4.9.1 installation with Theme Twenty-Seventeen and did not observe any issues with the .fa-info-circles.  I installed and activated the Fruitful Theme and the problem appeared immediately with no other changes.

**Comment by TonyC5** [comment]
@Much2tall Just out of curiosity, why does Ninja Forms styling define 
.fa-info-circle:before { content:"\f05a" } in ninja-forms/assets/css/font-awesome.min.css.  This seems like an unnecessary styling.
