### ISSUE TITLE
PDF Form Submission plugin activation conflict with WooCommerce PDF Invoices plugin

### ISSUE THREAD

**Issue by Curtisbrownlee** [wpninjas/ninja-forms#3231]
- **What actions are you taking?**
  - What had happened was... 
A client who already had WooCommerce PDF Invoices activated attempted to activate the Ninja Forms PDF Submission
- **What are you expecting to occur?**
  - What I was expecting to happen was...
Both plugins to be active
- **What is occurring instead?**
  - What *actually* happened was...
--When attempting to activate the Ninja Form PDF plugin, the following fatal error occured:
Fatal error : Can not redeclare class HTML5_Data in /home/edovelcozl/animo-hotel/wp-content/plugins/ninja-forms-pdf-submissions/lib/dompdf/lib/html5lib/Data.php on line 6
--After deactivating the WooCommerce plugin, activating the Ninja Forms' one, and trying to turn the original WooCommerce plugin back on, the following fatal error occurred:
Fatal error : Can not redeclare class HTML5_Parser in /home/edovelcozl/animo-hotel/wp-content/plugins/WooThemes_WooCommerce_PDF_Invoices_v3_2_1/lib/dompdf/lib/html5lib/Parser.php on line 11

**Comment by Much2tall** [comment]
Relocated to https://github.com/wpninjas/ninja-forms-pdf-submissions/issues/42
