### ISSUE TITLE
Urgent... Kindly Help...

### ISSUE THREAD

**Issue by AshutoshSwain** [wpninjas/ninja-forms#3241]
Problem I'm trying to solve: User1 goes to site and submits a form. User2 goes to site and submits a form . User3 goes to site and uses a search form . Once the User3 hits submit, they will see results (if any) on the same page - maybe under the search form, but I don't know as of yet.

What I've done: I have created a form using ninja forms. The form has a few fields on it. The form will be used by anybody to submit information. That part is working. I don't think the fact that I used ninja forms is particularly important here as the data being submitted is just going into the WP database.

What I want to do: Create another form that will be used as a search form that will search the data submitted with the other form and then display the results. The search form will be very short. It will have two dropdowns and a search button.

I've looked around but can't find anything on my level of understanding to accomplish what I'm trying to do. I'd like to do it the correct wordpress way. I don't know where to start to even get going. I think I need to create a page that will have the search form on it but I don't know where the code to power the search form needs to go. I've seen discussions talking about putting functions into functions.php etc but I just really don't know where to start. Also, this sounds like a task for AJAX, and I don't know where to put any of that code either. I tried putting some php code wrapped in tags on the 'page' that created to hold the search form but that didn't echo out anything, instead it printed out the code etc. So, I assume that putting AJAX or javascript on that page won't work either.

Any help is appreciated.

**Comment by wpnzach** [comment]
Github issues are for reporting bugs or feature requests for the software, we are not able to offer custom development assistance here.
