### ISSUE TITLE
Not saving all of the fields when saving data to ninja forms

### ISSUE THREAD

**Issue by Drax74** [wpninjas/ninja-forms#3253]
I am sending data to Ninja forms from remote backend built with `laravel/php`:

        $url = $this->postUrl . '/wp-admin/admin-ajax.php';
        $client = new Client();
        $response = $client->request('POST', $url, [
            'form_params' => [
                'security' => $this->getNonce(),
                'action' => 'nf_ajax_submit',
                'formData' => $request->formData,
            ]
        ]);

The `formData` looks like this:

    {
      "id":"1",
      "fields":[
           {"id":"1","value":"My Name"},
           {"id": "2","value":"myemail@email.com"},
           {"id":"3","value":"some message"}
       ]
    }

Where `id` is an id of that `ninja form` in WP in my case `Contact form`, and each object in the fields array represents a field in the form. Id of that object is an id of that field.In my case id 1 is an id of name field, and id 2 is an id of email field, while id 3 is an id of message field. The data is being saved normally to `message` and `email` field as you can see on the image below, but not to the `name` field.

[![enter image description here][2]][2]

On checking the WP DB postmeta table I could see that fields are being saved as:

    post_id  |  meta_key   |   meta_value
    
      341           field_2        myemail@email.com
      341           field_3        some message
      341           field_   

So, the problem is that the `name` field is being saved as only `field_` with no value, why is there a problem when the other fields are being saved as they should?
I have also tried with sending the data with key value pairs like this:

    {
     "id":"1",
     "fields":[
               {"key":"name","value":"My Name"},
               {"key": "email","value":"myemail@email.com"},         
               {"key":"message","value":"some message"}
     ]
    }

But, then the `message` field is not being save. I have even tried the combination of having id for `message` field and `key` for `name` field, but then email field was not being saved. 

  [1]: https://github.com/wpninjas/ninja-forms/blob/master/assets/js/front-end/controllers/submit.js
  [2]: https://i.stack.imgur.com/KprAG.png

**Comment by Much2tall** [comment]
@Drax74 
I can't reproduce this behavior locally.
My first guess is that your database has some missing data in it, and that's preventing it from saving submissions properly. The current methodology of submission relies on a cache of form data, which you're bypassing by not using a normal submission process. This means that the data is being pulled straight from your nf3_fields table in the database, and I would venture a guess that one of the records is missing from that data, causing the disconnect.

Normally, I would tell you to contact our support team to work this out. However, as this is a custom implementation, you're operating outside their scope of operations.

Unfortunately, the above is pretty much the only guidance I can offer you.
