### ISSUE TITLE
PHP Warnings on Plugin Activation

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#3256]
- **What actions are you taking?**
  - I activated Ninja Forms locally.
- **What are you expecting to occur?**
  - I expected Ninja Forms to activate without errors or warnings -- seeing a clean `plugins.php` admin screen.
- **What is occurring instead?**
  - I saw multiple PHP Warnings.
---

- `Warning: fopen(https://ninjaforms.com/): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden in /home/vagrant/code/WordPress/wp-content/plugins/ninja-forms/includes/Helper.php on line 277`
- `Warning: stream_get_meta_data() expects parameter 1 to be resource, boolean given in /home/vagrant/code/WordPress/wp-content/plugins/ninja-forms/includes/Helper.php on line 277`
- `Warning: Cannot modify header information - headers already sent by (output started at /home/vagrant/code/WordPress/wp-content/plugins/ninja-forms/includes/Helper.php:277) in /home/vagrant/code/WordPress/wp-admin/includes/misc.php on line 1114`
- `Warning: Cannot modify header information - headers already sent by (output started at /home/vagrant/code/WordPress/wp-content/plugins/ninja-forms/includes/Helper.php:277) in /home/vagrant/code/WordPress/wp-includes/option.php on line 919`
- `Warning: Cannot modify header information - headers already sent by (output started at /home/vagrant/code/WordPress/wp-content/plugins/ninja-forms/includes/Helper.php:277) in /home/vagrant/code/WordPress/wp-includes/option.php on line 920`

**Comment by Much2tall** [comment]
Appears to be resolved in the latest version of develop.
