### ISSUE TITLE
(vimeo-uploader) video dropzone error

### ISSUE THREAD

**Issue by moosalim** [wpninjas/ninja-forms#3274]
- **What actions are you taking?**
  - What had happened was when clicking on submit button without selecting video file or drooping it to dropzone, error will show asking for the video file. then we cannot add any file, we have to refresh the page. This matter will be worse when using mobile phone browser.
- **What are you expecting to occur?**
  - What I was expecting to happen was to allow us to select the file or drop it to the dropzone without refreshing the page.
- **What is occurring instead?**
  - What *actually* happened was not being able to drop file to the dropzone if missed at the first attempt to click   ##submit

**Comment by Much2tall** [comment]
@moosalim I've moved this issue to our Vimeo Uploader repo, where the project dev can better find and manage it.

**Comment by moosalim** [comment]
Thanks
can you please send me the link of where you moved it, so that I can follow
