### ISSUE TITLE
Ninja Forms Submissions CSV are Blank

### ISSUE THREAD

**Issue by xaif** [wpninjas/ninja-forms#3279]
- **What actions are you taking?**
  - I was filling the form... 
- **What are you expecting to occur?**
  - Get the submission in the CSV format
- **What is occurring instead?**
  - The submissions are coming blank

**Comment by Much2tall** [comment]
@xaif 
I am unable to confirm this behavior locally.
Please reach out to our support team at ninjaforms.com/contact

Closing issue as this repository is for confirmed problems with the software.
