### ISSUE TITLE
HTML tags showing in Custom Mask tooltip

### ISSUE THREAD

**Issue by Curtisbrownlee** [wpninjas/ninja-forms#3280]
- **What actions are you taking?**
  - What had happened was... 
Add a Single Line Text field to the form, change the Input Mask to Custom, and click the tooltip speech bubble in the Custom Mask label.
- **What are you expecting to occur?**
  - What I was expecting to happen was...
List the options available for a custom mask
- **What is occurring instead?**
  - What *actually* happened was...
The tooltip text had HTML tags displaying instead of creating the unordered list:
https://goo.gl/G3niFB

**Comment by Much2tall** [comment]
Problem originated in 3.2.8, apparently as a result of VIP updates.
We probably html_escaped something that we shouldn't have.
