### ISSUE TITLE
Blank space being added to Descriptions and Help Text

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#3294]
Blank space being added to Descriptions and Help Text

Replication steps:
Create a form with a Single Line Text field
Open up the Display settings for the field
There will be blank space added to the Help Text and Display options

**Comment by jmcelhaney** [comment]
This issue is the cause, but should be fixed by https://github.com/wpninjas/ninja-forms/pull/3299

**Comment by ericwindham** [comment]
Yeah, my bad. I did search for jBox and missed this issue. I'll close it when the Pull Request is merged.
