### ISSUE TITLE
jBox is undefined

### ISSUE THREAD

**Issue by ericwindham** [wpninjas/ninja-forms#3298]
We are getting 'jQuery.jBox is undefined' in several places. It happens when the help text has html tags in it but no actual text. The backend is smart enough to NOT load the jBox code, but the frontend only checks is the help_text string is empty, not that it doesn't have actual text.

To reproduce, create any field and just add a new line/return in the help text field.

**Comment by jmcelhaney** [comment]
https://github.com/wpninjas/ninja-forms/issues/3294
