### ISSUE TITLE
Default Ninja Forms Styling

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#33]
Right now Ninja Forms comes with almost know styling out of the box. Anyone who has styled forms before know there is no way to account for every theme and possible preference. This is the main reason we've not included much styling at all up till now.

I still don't want to include a lot bit would love to know if anyone has any suggestions for what some defaults ought to be?

**Comment by kjohnson** [comment]
Ninja Forms THREE now includes base structural styles with (optional) opinionated styles.
