### ISSUE TITLE
Ajax load ninja forms?

### ISSUE THREAD

**Issue by hartey11** [wpninjas/ninja-forms#3307]
- **What actions are you taking?**
I'm trying to display ninja forms on a site that uses AJAX to load in pages.

  - What had happened was... 
Works fine on load, but not set up to load scripts and initialise when page is loaded via AJAX

- **What are you expecting to occur?**
Same as if the page was loaded normally

- **What is occurring instead?**
nothing loads

Hi,

We are using https://github.com/luruke/barba.js to create page transitions and load the new page via AJAX.

Is there anyway to get ninja forms to work in such a setup?

**Comment by Much2tall** [comment]
@hartey11 
Using only the out of the box product, the answer is no.
We're aware that loading our forms on a page via AJAX is an issue, but it's not something that we can fix easily or quickly.
It might be possible to "force" the form to load by faking a browser page load, but there's no guarantee there, and implementation would be clunky.

This is something we plan to fix at some point, it's just not on the immediate horizon.
