### ISSUE TITLE
Excessive queries, particularly on front page

### ISSUE THREAD

**Issue by chrisgherbert** [wpninjas/ninja-forms#3317]
- **What actions are you taking?**

Viewing the front page of a site, which does not have an associated post (using `front-page.php`).  It also does not contain a Ninja Forms form.

- **What are you expecting to occur?**

Few or no queries associated with Ninja Forms to appear in Query Monitor's output.

- **What is occurring instead?**

Hundreds of duplicate queries being made:
    
![screen shot 2018-01-26 at 1 49 04 pm](https://user-images.githubusercontent.com/2541849/35455930-d3b79d4e-02a1-11e8-92e7-4e102278393c.png)

In this case I think the "Potential Troublemakers" may be a red herring.

**Comment by Much2tall** [comment]
@chrisgherbert 
Closing this issue in favor of further discussion here: https://github.com/wpninjas/ninja-forms/issues/3324
