### ISSUE TITLE
Possible issue with new checkbox settings breaking submission data on updated forms. 

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#3318]
If a user updates to the newest version from a version that was out before the new checkbox settings were added. Then it's possible that the new checkbox settings maybe breaking the submission data. When the submissions are exported. I've seen this on two customers tickets, but I have not been able to replicate fully locally. 

https://wpninjas.kustomerapp.com/app/customers/5a6a304c4b7e4d0001218bc2/event/5a66c029f3fbb80001a12391

**Comment by jmcelhaney** [comment]
I had and issue with Checked and Unchecked not showing in the Submission exports with this user: https://wpninjas.kustomerapp.com/app/customers/586f6f26ea3856110044deff/event/5a81565b970b8c000178d922
A republished the form and the Submissions showed Checked and Unchecked
