### ISSUE TITLE
[Feature Request] Add document viewer to forms

### ISSUE THREAD

**Issue by TonyC5** [wpninjas/ninja-forms#3348]
- **What actions are you taking?**
  - I would like to show a document in a scrollable/expandable/collapsible frame within a form, so that the website visitor can review the document without leaving the form.  The use case I have in mind for this is that the form displays terms and conditions that need to be accepted before submitting the form.  By default, the terms and conditions would be collapsed.  If the website visitor wished to review the terms and conditions, they would click on the expandable/collapsible document viewer (within the form).  They would then place a check in a checkbox within the form.  This would be very similar to the terms and conditions viewer in the WooCommerce checkout page.  The link to the document view should have a configurable link name (e.g. 'Click here to view Terms & Conditions').
- **What are you expecting to occur?**
  - I expected to have an expandable/collapsible document viewer to be added as a form component using the form editor.  The document could be simple HTML in an expandable/collapsible frame within the form.
- **What is occurring instead?**
  - There is no expandable/collapsible document viewer component.

**Comment by wpnzach** [comment]
Hey, @TonyC5 !  The best way to handle this would be to use your own custom HTML (or even WordPress shortcode) in our HTML field within the form.  

It would be out of scope for Ninja Forms core, but that's the best recommendation I have, and I've seen others use it successfully within their forms as well.
