### ISSUE TITLE
Consider using input[type=date] instead of Pikaday for supported browsers

### ISSUE THREAD

**Issue by nyordanov** [wpninjas/ninja-forms#3386]
Doing this will reduce the amount of JS loaded by this plugin by 47.5KB (gzipped, 182KB uncompressed).

[Current best practice is to limit the JS loaded on any page to about 150KB.](https://infrequently.org/2017/10/can-you-afford-it-real-world-web-performance-budgets/). It's pretty hard to do that, when 43.8KB is taken up by Ninja Forms with just text fields (not counting jQuery), and another 47.5KB are added if you use a date field.

**Comment by wpnzach** [comment]
This doesn't have enough browser support to be considered at this time, but we'll be watching wider browser adoption for consideration in future releases.
