### ISSUE TITLE
Hidden Fields show on form when a Calc is the default value

### ISSUE THREAD

**Issue by Curtisbrownlee** [wpninjas/ninja-forms#3388]
- **What actions are you taking?**
  - What had happened was... 
Create a calculation.  Next, add a hidden field and set the default value to that calculation: https://goo.gl/ihaUDe
- **What are you expecting to occur?**
  - What I was expecting to happen was...
The hidden field would remain hidden, but retain the value from the calculation 
- **What is occurring instead?**
  - What *actually* happened was...
The hidden field displayed on the form, showing the calculation as well as     ">     to the right of it:
https://goo.gl/vEBP8y

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/58b9d19f18c9f511001769ff/event/5a9056edf610f50001ec9cf3

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/59c5842e89e4c70011b76e96/event/5a9435ceb8a9b20001de4694

**Comment by jmcelhaney** [comment]
This issue only happens in 3.2.14 and later versions. It does not happen in versions before 3.2.14
