### ISSUE TITLE
Uncaught TypeError: Cannot read property 'fields' of undefined

### ISSUE THREAD

**Issue by paulxb** [wpninjas/ninja-forms#3404]
I've got an error where some people cannot submit my forms. I can't reproduce the error :( but I have installed [Bugsnag](http://bugsnag.com), which logs all the JS errors and there are a few similar ones occurring:

![image](https://user-images.githubusercontent.com/2284008/36754704-b303e606-1c01-11e8-8577-2d0d63112f6a.png)

It looks to me like `response.errors` is `undefined`, so probably needs to check on that first?
(I would fix it, but don't know what to do if it is undefined...)

Also, I don't think this is the actual cause of the forms not working, but its a start!

**Comment by wpnzach** [comment]
Please reach out to our support team with support requests like this.  You can reach them at http://ninjaforms.com/contact/
