### ISSUE TITLE
Feature Request: Settings Toggle for Font Awesome Enqueue

### ISSUE THREAD

**Issue by williamb-egov** [wpninjas/ninja-forms#3410]
Themes or other plugins are sometimes enqueuing Font Awesome, without an option to toggle it site owners may have multiple versions of Font Awesome being downloaded.

**Comment by wpnzach** [comment]
This is probably not something we're going to add as a toggle, as font-awesome is only enqueued with our opinionated styles and most users wouldn't know/understand what that toggle does.  The best option would be to write a plugin to de-enqueue it if needed.

**Comment by lonix1** [comment]
@wpnzach Please advise how to dequeue it?

When adding our own (latest) fontawesome from a CDN, it bloats the final bundle as FA is included at least twice (possible moreso by other plugins too).

````php
  add_action('wp_print_styles', function() {
    wp_dequeue_style('????');     <-------- what goes here?
  }, 100);
````

What key is used to enqueue the ninjaform's fontawesome stylesheet?

**Comment by mnlmaier** [comment]
@lonix1 I guess this is what you are looking for:
https://github.com/wpninjas/ninja-forms/blob/develop/includes/Display/Render.php#L645

Haven't managed to get rid of FA myself, though. I really like this plugin but this is pretty annoying, considering that FA usually takes some 1000s ms to load properly while blocking everything else.
