### ISSUE TITLE
MailChimp Plugin API - Fatal Error

### ISSUE THREAD

**Issue by matthewfarlymn** [wpninjas/ninja-forms#3425]
Hello,

I just recently installed your MailChimp plugin v 3.1.3 and attempted to add an API key after activating my plugin license. It doesn't look like I entered the correct API key since I received the following PHP error.

`Fatal error: Uncaught Error: Cannot use object of type WP_Error as array in /app/public/wp-content/plugins/ninja-forms-mail-chimp/ninja-forms-mail-chimp.php on line 209`

This took error took over my entire site and admin area. I was unable to use or access my site. By adding the following line above the response code line 209 in the plugin file I was able to get out of the error.

```
if ( is_wp_error( $response ) ) {
  return;
}
```
Hope this is able to be fixed ASAP to avoid this happening in the future.

![screen shot 2018-03-08 at 16 09 52](https://user-images.githubusercontent.com/5617870/37176718-36cc3fd4-22eb-11e8-8172-aaaf3e7aa78d.png)

**Comment by wpnzach** [comment]
This repo is for Ninja Forms core only, please submit a support request to https://ninjaforms.com/contact/ for issues with addons.

As an aside, this is patched in the MailChimp addon, expect a release soon.

**Comment by raptor235** [comment]
We just ran into the same issue... the site went offline without any human intervention... it's like a cron caused it to go down... we're a bit out of date on main plugin (3.3.4) but addon is latest... caused a 500 error... trying to update now.
