### ISSUE TITLE
Displaying a dynamic list of WordPress post titles for a custom select field

### ISSUE THREAD

**Issue by jwhayman** [wpninjas/ninja-forms#3448]
Hello, I'd like visitors to be able choose from a dynamic list of WordPress posts from a <select> element via NinjaForms.

I've created a custom field type and template, but I don't know where best to hook into the Ninja Forms pipeline to set the options dynamically.

I've tried setting the default options as so `$this->_settings[ 'options' ][ 'value' ] = $this->get_options();` but at this point I can't use the WP_Query object as I think the hook is too early. Also, I don't want a full list of posts displayed to the admin, just on the front end.

Each <option> on the front end should have the Post ID as the value and the Post Title as the label.

Any help would be greatly appreciated!

**Comment by wpnzach** [comment]
Hey @jwhayman I'd recommend reaching out to our development community here: http://developer.ninjaforms.com/slack/
