### ISSUE TITLE
The submission numbering is fragile

### ISSUE THREAD

**Issue by philippze** [wpninjas/ninja-forms#3457]
For some reason, we have entries with key `_seq_num` and value `0` in the `wp_nf3_form_meta` table.

When calculating the `_seq_num` (simply the number) of a new submission, this value (0) is taken as the previous number.

As a result, **all entries in our submissions list in the Wordpress admin have the number 1**; but they should be consecutively numbered, of course.

There's a **very simple fix** for that problem: Add `order by value desc` in the query [here](https://github.com/wpninjas/ninja-forms/blob/master/includes/Database/Models/Form.php#L71). Thus, we always find the largest entry, and never the smallest, which happened to us.

If you like, I can make a merge request.

An even more robust solution would be to search for the largest `_seq_num` of the appropriate form in the `postmeta` table.

I know that the strange entries in our database should not be there. But in case they emerge, the ninja-forms plugin should properly deal with that - it's easy.

**Comment by wpnzach** [comment]
This will happen with old forms that were imported into the site, but it should not be hapenning with newer forms.  If you're seeing it on new forms, please reopen this issue.  we have plans for more robust submissions numbering in the future.
