### ISSUE TITLE
Conditional logic checkbox settings are not preserved with upgrade from 3.0.17 to 3.0.19

### ISSUE THREAD

**Issue by TonyC5** [wpninjas/ninja-forms#3461]
- **What actions are you taking?**
- Upgraded Ninja Forms Conditional Logic from version 3.0.17 to 3.0.19
- **What are you expecting to occur?**
  - I expected my conditional logic to be preserved and continue to work in 3.0.19 as with 3.0.17.
- **What is occurring instead?**
  - Conditions based on checkboxes are lost and must be reconfigured.  For example, the condition in version 3.0.17 'When Checkbox A Is Checked' becomes 'When Checkbox A is Select One' in version 3.0.19.

Re-selecting the condition, saving and publishing restores the setting.  I have not observed this problem for any conditions other than checkbox-related conditions.

**Comment by wpnzach** [comment]
This was caused by a bugfix and should only impact a small number of users.  I'm sorry for any trouble this caused.
