### ISSUE TITLE
Conditional Logic version 3.0.19 breaks checkbox-related conditions on Safari

### ISSUE THREAD

**Issue by TonyC5** [wpninjas/ninja-forms#3462]
- **What actions are you taking?**
  - Upgraded from Conditional Logic 3.0.17 to 3.0.19.
- **What are you expecting to occur?**
  - I expected conditional logic to continue working in 3.0.19 as with 3.0.17 (on all previously supported browsers).
- **What is occurring instead?**
  - Conditions based on checkbox states do not work in Safari/iPhone 5s and OSX Sierra/Safari 11.1.  For example, the condition 'When Checkbox A Is Checked' Do 'Field A Show Field' does not show Field A in version 3.0.19 when Checkbox A is Checked.  Note that this problem is observed and reproduced on both mobile (iOS) and Desktop (OSX Sierra), so it appears that this is a Safari compatibility problem and not an OS problem.

**Comment by wpnzach** [comment]
Is this only in Safari on iPhone 5s? If so, this will likely not be fixed.

**Comment by TonyC5** [comment]
@wpnzach I'm not sure.  The issue was reported to me after our website was broken by the 3.0.19 update.  What is your standard mobile device test suite?

**Comment by wpnzach** [comment]
We strive to support all modern browsers.  Apple doesn't define EOL for any
of their browsers, but more than a year or two without updates from the
browser developer means we're not going to continue supporting it either in
most cases.  We would need more information on what exact version of iOS is
running, this isn't something we're able to replicate.  The best option is
to reach out to our support team here: https://ninjaforms.com/contact/ for
troubleshooting

**Comment by TonyC5** [comment]
@wpnzach I just tested and reproduced the problem with OSX Sierra/Safari 11.1. This appears to be a Safari compatibility problem, not a mobile/iOS problem

**Comment by kjohnson** [comment]
If this is an issue with the current version of Safari, then we would need to investigate further.
PING @wpninjas/developers @wpnzach

**Comment by TonyC5** [comment]
I conducted two more tests with Ninja Forms 3.2.21 and Conditional Logic 3.0.19.  The checkbox conditional logic works.
