### ISSUE TITLE
Radio List value 

### ISSUE THREAD

**Issue by WisienSDA** [wpninjas/ninja-forms#3463]
Hi,
I have problem with 'value' in radio list. 

I can't do the space in value between words in radio list and in e-mail everything looks like one long word.

I need 'Drill Your Skill - Masterclass 180 EUR' but ninja forms automatically deletes spaces between words. The same thing I got in another radio list (packages, access etc.).

But in value at level up 'without masterclass' everything work good (maybe because this option is from my last registration event, I don't know)

How can I fix it ?

![radio list](https://user-images.githubusercontent.com/37961732/38165985-84a424c2-351c-11e8-9648-d6116e24e69f.jpg)
![radio list 2](https://user-images.githubusercontent.com/37961732/38165986-84c3b512-351c-11e8-8d80-a83dd389c267.jpg)

**Comment by wpnzach** [comment]
This is by design.  This is the HTML value passed into the backend for processing, and it cannot accept special characters or it can break form processing.
