### ISSUE TITLE
The v3.2.20 release on wordpress.org contains v3.2.19 code

### ISSUE THREAD

**Issue by LartTyler** [wpninjas/ninja-forms#3474]
**What actions are you taking?**
Updated Ninja Forms to 3.2.20

**What are you expecting to occur?**
Expected the AJAX error introduced in 3.2.19 would be resolved.

**What is occurring instead?**
The 3.2.20 release published to wordpress.org does not contain the 3.2.20 code. Instead, the main plugin code is 3.2.19, and a new `trunk/` folder containing the 3.2.20 code has been added to the plugin, doubling it's size.

**Comment by wpnzach** [comment]
@LartTyler looking into this now.

**Comment by wpnzach** [comment]
@LartTyler confirmed, will re-release ASAP

**Comment by LartTyler** [comment]
@wpnzach Just to clarify, by "re-release" do you mean replace the existing 3.2.20 release? If so, my recommendation would be to increment your patch version again to avoid conflicts with sites that already have 3.2.20.

**Comment by LartTyler** [comment]
Nevermind, I see the new release. Testing it now.

**Comment by LartTyler** [comment]
Never mind, I see the new release. Once it's up on wordpress.org, I'll give it a test.

**Comment by LartTyler** [comment]
Looks good, thanks for fixing this!
