### ISSUE TITLE
After duplicating fields that use option Repeater, you can't add options to the new field

### ISSUE THREAD

**Issue by ericwindham** [wpninjas/ninja-forms#3479]
- **What actions are you taking?**
  - Add a field that uses the optionRepeater(Select, Radio List, Checkbox List, MultiSelect)
  - Copy that field
  - Try to add options to the new duplicated field
 
- **What are you expecting to occur?**
  - To be able to add options
- **What is occurring instead?**
  - You can't add new options unless you publish the form and reload the builder

**Comment by kjohnson** [comment]
Follow-up with https://wpninjas.kustomerapp.com/app/customers/588223abcb574a1100ea0ead/event/5ac8be79758d1735ca26c251

**Comment by ericwindham** [comment]
Closing due to existing issue for this case #2642
