### ISSUE TITLE
Plain Text Message for Form Notifications

### ISSUE THREAD

**Issue by BFTrick** [wpninjas/ninja-forms#348]
When you're adding a new email notification we have a nice UI with a visual editor that lets you not only bold, italicize, etc the text but also add NF fields. It would be great if we could have a plain text version of this functionality. That way when you're creating custom functionality for something like a text message notification or a plain text email, you can still select fields without confusing the user with bold & italics which don't make sense.

The existing UI:
![forms_ _nf_2_8_ _wordpress](https://cloud.githubusercontent.com/assets/1065372/4630856/ec97a532-53b0-11e4-8ebd-24171f285fc8.jpg)

**Comment by kstover** [comment]
I really like the idea of generalising the insert field stuff. :+1:
