### ISSUE TITLE
Confirm field does not display Admin Label of fields

### ISSUE THREAD

**Issue by Curtisbrownlee** [wpninjas/ninja-forms#3498]
- **What actions are you taking?**
  - What had happened was... 
A user wanted to add a Confirm field to their form.  When trying to pair this field with another field, the Admin Labels did not display, but instead, only the field Labels were in the dropdown list.  Several field Labels were the same, so it was unclear of which one was the desired field.
https://www.dropbox.com/s/f3ds03pp8e6o58c/2018-04-18_11-07-15.png?dl=0

- **What are you expecting to occur?**
  - What I was expecting to happen was...
User expected Admin Labels to display within the dropdown list if they were present.

- **What is occurring instead?**
  - What *actually* happened was...
Only the Labels of the fields displayed within the dropdown list even though some fields had Admin Labels

**Comment by Curtisbrownlee** [comment]
https://wpninjas.kustomerapp.com/app/customers/5ad0f2066db7c52b0c83614e/event/5ad66291c259d20ae8b37ffb

**Comment by wpnzach** [comment]
Admin labels are not meant to display on the front end, this is working as intended.
