### ISSUE TITLE
Feature Request: Add ability for Single Line Text fields with a Currency Mask to work with Calculations

### ISSUE THREAD

**Issue by Curtisbrownlee** [wpninjas/ninja-forms#3516]
A user would like the ability for Single Line Text fields with a Currency mask to work within Calculations

Adding ":calc" to the field merge tag was mentioned as a method to do this under Ninja Forms 2.x

**Comment by Curtisbrownlee** [comment]
https://wpninjas.kustomerapp.com/app/customers/5ae224cbe671c1eb1c446f49/event/5ae224cb1ba411073301da0a

**Comment by Curtisbrownlee** [comment]
https://wpninjas.kustomerapp.com/app/customers/5af59b7d059e567c50154d40/event/5af6f4107aa7a122a74fc46f

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/5aec6158121e2a52178bcfd4/event/5afb3424162c4b2951187967
