### ISSUE TITLE
Submit error on console

### ISSUE THREAD

**Issue by bdogan** [wpninjas/ninja-forms#3517]
With last update of NinjaForms;

![e94b3f8d-7f53-4559-a2cd-827ae8d554df](https://user-images.githubusercontent.com/1773731/39294817-5f1dcca2-4945-11e8-89ec-adab61ccd11a.jpg)

and when submit form on console

<img width="391" alt="platinmarket_e-ticaret_yazilimlari-_e-ticaret_siteni_hemen_ac" src="https://user-images.githubusercontent.com/1773731/39396165-dd788efe-4af1-11e8-9673-db52e3457910.png">

Wordpress: 4.9.5–tr_TR
Theme: [TheFox](https://themeforest.net/item/thefox-responsive-multipurpose-wordpress-theme/11099136) - 3.3
NinjaForms version: 3.2.22. (with 3.2.14 no problem).
NinjaForms - Layout & Styles version: 3.0.25 

all are licensed

**Comment by wpnzach** [comment]
Cannot replicate, please reach out to our support team here: https://ninjaforms.com/contact/
