### ISSUE TITLE
Individual Form Translation

### ISSUE THREAD

**Issue by devinbalram** [wpninjas/ninja-forms#3525]
Instead of having every form adhere to the language setting in the WordPress Dashboard - users are asking for a feature that can select the language for a specific form. 

Ex: If a user duplicates a form, instead of manually having to translate the form, either have a setting/action that allows the user to translate the form into the desired language. 

https://wpninjas.kustomerapp.com/app/customers/5ae97188b6cee4bbfdac7c7a/event/5ae97188b6cee4f553ac7c7d

**Comment by wpnzach** [comment]
at this time, this isn't something we're looking to do in core.
