### ISSUE TITLE
Form submitted once sends two emails instead of just one.

### ISSUE THREAD

**Issue by sbrereton** [wpninjas/ninja-forms#3531]
- **What actions are you taking?**
  - Submitting a form with an single "Email" action and a single email address.
- **What are you expecting to occur?**
  - Receiving a single email with the form submission contents.
- **What is occurring instead?**
  - Receiving two emails with the exact same content even though the form was submitted once.

Ninja Forms version is **3.2.24** running on Wordpress **4.9.5**

**Comment by wpnzach** [comment]
I would recommend installing a mail logging plugin to see at what step this duplicate email is occurring.  Alternatively, please reach out to our support team at https://ninjaforms.com/contact/

**Comment by sbrereton** [comment]
Thanks for your reply, with a mail logging plugin, I can confirm that it is definitely occuring at the plugin level. There are even two submissions in the NinjaForms interface.

![image](https://user-images.githubusercontent.com/39055860/39728237-63d29324-5299-11e8-9535-7f47c11e930a.png)
![image](https://user-images.githubusercontent.com/39055860/39728281-9262b6ec-5299-11e8-8bd8-e9605cb69c0b.png)

**Comment by 360webexpert** [comment]
Did you get any solution ??
