### ISSUE TITLE
Remove "Append a Ninja Form" from sidebar.

### ISSUE THREAD

**Issue by heytricia** [wpninjas/ninja-forms#3536]
Hello Ninja Folks!

I use Ninja Forms in all new builds along with a custom base theme. I like to keep customer dashboards simple and would like to remove the “append a ninja form” box from all user sidebars. I tried the solution here: https://github.com/wpninjas/ninja-forms/issues/1106
But no love. What is the magic snippet?

**Comment by mindfullsilence** [comment]
I've used the following with success:
```php
add_action('add_meta_boxes', function() {
    remove_meta_box('nf_admin_metaboxes_appendaform', ['page', 'post'], 'side');
}, 99);
```

Also for the wysiwyg editor, I've used this to remove the "Insert Ninja Form" button:
```php
add_action('plugins_loaded', function() {
    if(!class_exists('Ninja_Forms')) {
        return;
    }
    $inst = Ninja_Forms::instance()->add_form_modal;
    remove_filter('media_buttons_context', [$inst, 'insert_form_tinymce_buttons'], 999);
    add_filter('media_buttons_context', function() {
        wp_dequeue_script('nf-combobox');
    }, 999);
    remove_action('admin_footer', [$inst, 'output_tinymce_button_js'], 999);
});
```

**Comment by heytricia** [comment]
That first function worked! Thanks much.

Normally, I would leave the form button in the editor... but I'm using ACF wysiwyg fields and the form button doesn't work. So I tried your 2nd function... no love. I need to search and see if someone else has had this problem.

**Comment by geertvdheide1** [comment]
Can confirm that the first fragment by @mindfullsilence above works to remove the meta box (thanks!), but also that the second fragment doesn't work to remove the Insert Form button from the text editor. Tried in a fresh project with no luck. Can't find any other documentation on how to remove that button. If anyone can chime in, please do.

**Comment by apmeyer** [comment]
Same issue here. "Add Form" button is not working in ACF wysiwyg field. Would be nice to be able to disable it. A workaround is to hide it with CSS. If you include an admin stylesheet you can use:

```
.acf-input .wp-editor-tools a.nf-insert-form {
  display: none;
}
```

```
add_action('admin_enqueue_scripts', 'enqueue_admin_styles_and_scripts');
function enqueue_admin_styles_and_scripts() {
    wp_enqueue_style( 'admin_css_foo', 'path/to/styelsheet', false, 1.0);
}
```

**Comment by jnorell** [comment]
The code by @mindfullsilence probably works for plugins using the global namespace, but needs slight tweaking to use in a theme and/or within another namespace:
`
/**
 * Remove Ninja Forms' 'Add Form' button from TinyMCE
 */
add_action( 'wp_loaded', function() {
    if( ! class_exists( 'Ninja_Forms' ) ) {
        return;
    }
    $inst = \Ninja_Forms::instance()->add_form_modal;
    remove_filter( 'media_buttons_context', [$inst, 'insert_form_tinymce_buttons'] );
    add_filter( 'media_buttons_context', function() {
        wp_dequeue_script('nf-combobox');
    }, 999 );
    remove_action( 'admin_footer', [$inst, 'output_tinymce_button_js'] );
}, 999);
`
