### ISSUE TITLE
Localization settings that change product fields decimal separators, the product amount in the email will be multiplied by 100

### ISSUE THREAD

**Issue by Curtisbrownlee** [wpninjas/ninja-forms#3554]
If a user's site is using a locale setting that changes the product fields decimal separators to commas, the values will be multiplied by 100.  If you have a product that is 7, it will turn into 700.

The Total will still be correct, at 7, but in the all_fields_table merge tag, that product will say 700.

Replication steps:
Set your site to nederlands.
create a new form and change the per forms currency setting to euros.
add product and total fields.
set up an email action that sends you the all fields merge tag.
preview and submit the form and view the email.

**Comment by Curtisbrownlee** [comment]
https://wpninjas.kustomerapp.com/app/customers/5ae5bbf9dd8edd65d497e690/event/5ae5bbf9dd8edd716197e693

**Comment by wpnzach** [comment]
related #2950
