### ISSUE TITLE
The User Meta merge tag code displays when a user is not logged in

### ISSUE THREAD

**Issue by Curtisbrownlee** [wpninjas/ninja-forms#3556]
When you are logged in, user meta tags populate normally when you set it as the Default Value of a field.

When you are not logged in, however, the merge tag displays on the front end:
https://www.dropbox.com/s/7yo0oqp6qakiaeq/2018-05-14_09-38-16.png?dl=0

**Comment by jmcelhaney** [comment]
https://github.com/wpninjas/ninja-forms/issues/3192

**Comment by harlet** [comment]
Any fix on this?
Thank you!

**Comment by Curtisbrownlee** [comment]
https://wpninjas.kustomerapp.com/app/customers/5976807f91047a0011ff4c68/event/5b44e53f79cfd78184f5e89b
