### ISSUE TITLE
Submit button stuck on processing when required field is missing

### ISSUE THREAD

**Issue by jdj1971** [wpninjas/ninja-forms#3665]
If a required field is missing and I hit the submit button, it'll switch to 'processing' and stays that way. I can correct the field and hit the button again and it will successfully submit but the button should be reverting to 'submit' if there's a missing field.

![image](https://user-images.githubusercontent.com/19350065/57875487-ef63c080-77c7-11e9-922c-0f994f02c7ae.png)

**Comment by ericwindham** [comment]
Yes, we have a fix in review for this. Thanks, for letting us know.
