### ISSUE TITLE
Extra space after field shortcode in subject line

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#373]
From user, reproduced on local machine:
I want to create an email notification that has a title like:
", we heard you!"

However, when using the "field picker" and custom text to create this subject line, the actual result looks like:

" , we heard you!"

NOTE: extra space between name and column.

1. Create a form
2. Create an email notification
3. For the email subject use any combination of a field and custom text

RESULT: extra space between field and custom text
EXPECT: no extra space

**Comment by pippinsplugins** [comment]
I've confirmed the bug.
