### ISSUE TITLE
When character limit text is blank, limit text shows anyway

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#386]
Default character limit text shows regardless of text set in field settings.

**Comment by pippinsplugins** [comment]
I'm not sure what you're referring to either. I've just tested the limit options and it seems to be behaving as expected for me.

**Comment by wpnzach** [comment]
This may have been resolved at some point.  Definitely was an issue but is no longer reproducible that I can tell.  Closing.
