### ISSUE TITLE
Create a field grouping / fieldset item

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#40]
Some times you may want to have groups of fields that belong together. This would be extremely helpful for more advanced layouts, etc.

In the admin I think this could be represented just like a field but fields that belong to that fieldset could be nested underneath it's title.

**Comment by codecowboy** [comment]
@kstover iamntz  Whats the current status of being able to group fields? Is it possible via the API if not in the UI?  I couldn't see anything in the developer docs. I sent a support request about this via the ninja forms website. Use case is adding bootstrap field groups http://getbootstrap.com/css/#forms-horizontal

**Comment by kstover** [comment]
Moved to internal feature tracking.
