### ISSUE TITLE
Ajax and ninja_forms_process !! 

### ISSUE THREAD

**Issue by mostafaprin** [wpninjas/ninja-forms#410]
i noticed that you had problems with Ajax, so did i :) 
my problem i have a form that submits through Ajax in custom Admin menu page. 
Issues :
1- it inserts data correctly but submit button convert into processing and disabled their.
2-it doesn't clear the form after re-submission. 
3-Finally, need to take the data from this submission and make some custom manipulation so i used  this code as you provided in ninja DOCS

        function on_ninja_forms_process(){
		add_action( 'ninja_forms_process', 'ninja_forms_processed' );
	}
	add_action( 'init', 'on_ninja_forms_process' );

	function ninja_forms_processed(){
                //code goes here
        }

but nothing goes right and the code doesn't work in the 'ninja_forms_process' hook
Note: if i disabled the Ajax form submission EVERYTHING goes well ??
Note: this issue both in frontend and backend 
What do you think about this ??

**Comment by mostafaprin** [comment]
Wow very long time to respond ....

**Comment by kstover** [comment]
Hi,
I haven't had a chance to attempt a replication on this issue, so haven't responded yet. You also submitted this ticket on Christmas Eve, and we just got back into our office on Monday of this week. Once I've had the chance to test, I'll reply with more detail.

**Comment by NetcraftStudio** [comment]
Actually, after upgrading to WP 4.1, this issue is back.

**Comment by kstover** [comment]
Hey. Can you attach the code that you used to reproduce this error?

**Comment by NetcraftStudio** [comment]
HI. I had this issue ont two different sites. Both of them have wp 4.1 and Deflector by wpXtreme installed. The problem seems to be an incompatibility of Deflector with Forms and other plugins that are using ajax.
