### ISSUE TITLE
Submissions date range glitch if no value is set in end date field

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#412]
Submitted by Kevin Hjälte 

On the Submissions admin menu page (Forms -> Submissions), when setting a date to filter a chosen forms submissions with, if you pick only a start date in the past and submit the form comes back with todays date as start date and the selected date in the past as end date.

**Comment by wpnzach** [comment]
I will look into this later today.

**Comment by kstover** [comment]
Seems to be fixed in the current version of 3.0.
