### ISSUE TITLE
Make error/success message visible for forms that are "below the fold"

### ISSUE THREAD

**Issue by clayteller** [wpninjas/ninja-forms#415]
Hi, this is not an issue, just a much desired enhancement for a particular use case of ninja forms. My ninja form is "below the fold" in my page layout. So, when you submit the form and the page reloads, the form is in it's original position "below the fold" and the error/success message is not visible unless the user realizes they can scroll down to the form to see if there's a message. Is there any way to place the message at the top of the page, or make the browser auto scroll to the form when the page reloads after form submission? Currently, I'm afraid users won't know if the form was submitted or not. Thank you for your help.

**Comment by kstover** [comment]
This is something that we're thinking about internally. Once we have some solutions, I'll throw them out in a new issue for everyone to discuss.

**Comment by clayteller** [comment]
Sounds good, thanks for the update.

**Comment by leecollings** [comment]
Any update on when this will be released?

**Comment by kjohnson** [comment]
This is made moot with v3 AJAX submissions.

**Comment by leecollings** [comment]
Why close this? Your message doesn't make any sense, can you please clarify what you mean?

**Comment by jameslaws** [comment]
In version three there is only Ajax submission so this is no longer applicable.

**Comment by leecollings** [comment]
Is there still the option to redirect to another page after a submission has been made though? Because this is a very important feature, to be able to set up Goals, and landing pages to track inside Google Analytics to see forms that have been completed etc.

**Comment by jameslaws** [comment]
Yes. You can still set up redirects without a problem.

**Comment by jameslaws** [comment]
September 6th.
