### ISSUE TITLE
Add ability to limit number of checkbox choices

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#421]
Man yusers have requested a feature to limit the number of checkboxes which can be checked in a list to a number greater than 1 (making a radio button unfit for their use case)

**Comment by leaninonlife** [comment]
Was this ever implemented? The only way I have been able to achieve this is with the conditional add-on, which is extremely tedious process for a feature that is standard in 90% of all form building systems I've ever used in the past.
