### ISSUE TITLE
Can't prefill field value with "0"

### ISSUE THREAD

**Issue by hobailey** [wpninjas/ninja-forms#426]
Is perhaps slightly related to #425 but you can't prefill field values with a "0"
Eg: I'm trying to update field ID 50 with the value of "0" (but clearly it works with any field ID, not just 50!) but it just doesn't work when it does for any other value
```
add_action( 'init', 'init_plse' );
function init_plse(){
   add_action('ninja_forms_display_init', 'ninja_forms_prefill_fields');
}
function ninja_forms_prefill_fields($form_id) {
  global $ninja_forms_loading;
  $ninja_forms_loading->update_field_value(50, "0");
}
```

**Comment by kstover** [comment]
I can't seem to repro this on my local environment. Can you send me a full copy of your custom code?
