### ISSUE TITLE
Autototal bug on AJAX submit

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#427]
Form Setup:
1. Set up a form without using Ajax
2. Add a textbox - select required field
3. Add a checkbox - enter an amount into the checked calculation value, check include in auto-total
4. Add a total field - enter some default amount, calculation method set to "Automatically Total Calculation Values"
5. Add a submit button

Form Test:
Submit the form without the required field filled but the checkbox checked... the total value should continue to increase (by checked amount) each time form is submitted.

I worked around this issue by using "Use An Equation" calculation method. Just thought you might be interested in this bug. Love the product, keep up the good work.

Cheers,
-Tim Brush

**Comment by kjohnson** [comment]
The "Autototal" is deprecated as of v3.
