### ISSUE TITLE
HTML 5 placeholder text for calc fields

### ISSUE THREAD

**Issue by helgatheviking** [wpninjas/ninja-forms#430]
If you've not disabled the calc field's input then it can be helpful to have a placeholder. (Why aren't all fields using placeholder attributes?)

For example:
Donate: $5, $10, enter your own amount. 

Don't know if it is worth making a new issue, but calc fields should also be able to be set as required. In the example I just stated, the radio buttons for $5, and $10 might not be required, but ultimately in the calc field there would need to be a value.

**Comment by kstover** [comment]
Required calc fields might be an issue; I suppose you could just check them for an empty value?

HTML5 fields are on the roadmap for this year, and someone cool submitted a pull request already to add them to textboxes. :)

**Comment by kjohnson** [comment]
Calculation fields have been deprecated as of v3, in favor of number fields and calculation models.
