### ISSUE TITLE
Clicking the Add New Form button...

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#441]
A few thoughts...

Edit: In the All Forms screen.
Clicking contact form title or edit should lead to the Field Settings page as that is the page where most of the adjustments happen.

--

Clicking the add new form button. Goes straight to Field Settings (which is moved to the left switching places with Form Settings).

At the top a title text line with the words in grey "form title". A checkbox that says add standard form settings to favorite fields OR add standard settings to form. Click it and the fields are added. On the right side a drop down to quickly jump to other forms.

Below follows the various field settings.

**Comment by kstover** [comment]
If you check out the 2.9-beta branch, you can see our progress towards a UI that is very similar. :)

**Comment by paaljoachim** [comment]
I am looking forward to checking it out!

**Comment by kstover** [comment]
Version 2.9 will at least modify this enough that you will need to create a new issue. :)
