### ISSUE TITLE
Auto save on switching screen or popup dialog box asking to save?

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#442]
Lets say one is creating a form in the Field Settings and switches to another tab/screen a dialog box could come up asking do you want to save your changes. Right now I could create a form and switch to another tab and then go back again to the fields and notice whatever I had one was not automatically saved.

I see two options here.
Switching to another screen a save dialog box comes up OR the form is automatically saved on exiting the screen.

**Comment by kstover** [comment]
The 2.9-beta branch should make this experience much better.

**Comment by paaljoachim** [comment]
Great!
