### ISSUE TITLE
Thoughts on features

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#443]
I am once again going through the existing form....

<b>All Forms screen.</b>
Add a Screen Options to turn on/off Shortcode, Template Function, Date Updated. (As mentioned earlier Submission Entries with a link to submissions and views could be nice to add in.)
Showing Template Function here seems a bit overkill on this screen and should be moved to a better place for instance Form Settings.
<b>Quick Edit:</b> Preview Form and view submissions perhaps just change these to Preview and Submissions.

<b>Clicking Add New</b> goes straight to Field Settings with a text field for name of form at the top.

<b>Submissions</b>. Have the most active form with most submissions be automatically selected. Or just have the first form automatically selected. When one is looking at the submissions of a contact form exits the screen and goes back again. It is blank again and one needs to once again select a form. Here atleast the last form submissions one looked at should come up again.

Mark submission as unread. 
Limit character in Message field. If someone sends a long message it will take a lot of space in the Submissions screen. Have a predefined character limit for messages seen on this page (or keep it to max two lines)  and have the user just click the submission to view the full message.
Number takes a lot of space. There are other fields that need more space. Find a way to make the number field smaller. Perhaps move number next to Date.

<b>Edit Submission: </b>
Have a textfield below the values to where one can add a note and a way to send the note and the submission to another person. For instance one wants someone to followup on a submission.

<b>Import / Export looks good. </b>
A hack could be that Ninja Forms will read xml files from other contact forms. Today Ninja Forms will import an xml file from Gravity Forms and a new form will show up with no title and no field settings.

<b>Settings.</b>
What other settings can be placed into General?
Labels: Having a way to return to default value for various labels.

<b>System Status</b> could be moved into a new tab inside Settings (one less sidebar menu item.)

<b>Notification</b> could be a new sidebar tab. 
Notification screen:
Beside Date a field showing which form each notification is used in with a checkbox next to each form. First check box could be use in all forms. Or add a area below the list to do something like this. The point is to have it visible on the list page in where the notifications are used.

<b>Extend</b>: It would be a good idea with a short video tutorial showing each extension. I can help.
This could mean having an accordion for each extension open up showing a short video. Sales would very likely pick up because of it.

**Comment by paaljoachim** [comment]
Do you guys want me to split the above Thoughts issue into separate issues?

**Comment by jameslaws** [comment]
It's definitely best to keep any issues and requests as focused as possible so if you wanted to break them up it would make it a lot easier for discussion to happen around each one individually.

**Comment by kstover** [comment]
Split into individual issues.
