### ISSUE TITLE
Translations not working on front-end

### ISSUE THREAD

**Issue by tomasz-drgas** [wpninjas/ninja-forms#444]
Hey.
So I'm working on a multi-language website (English, Polish and Japanese) and I discovered that language files are not loading properly for front-end. Translations work fine for admin section though.
I had an issue with translating error messages visible after form submission. In order to solve this problem I placed this code in `functions.php` file in my theme:
```
function caps_ninja_forms_settings($ninja_settings){
	if( ! is_admin() && defined( 'NF_PLUGIN_DIR' ) ) {
		load_textdomain( 'ninja-forms', NF_PLUGIN_DIR . '/lang/' . get_locale() . '.mo' );
	}
	return $ninja_settings;
}
add_filter( 'ninja_forms_settings', 'caps_ninja_forms_settings' );
```
Some additional info:
Ninja Forms: v2.8.13
Wordpress: v4.1
Polylang: v1.6.3

**EDIT**: I was actually wrong, loading the `.mo` file again didn't solve the problem. After I disabled the "Polylang" plugin it loaded the lang file correctly, so there must be a conflict between those 2 plugins.

**Comment by kstover** [comment]
Thank you for the heads up! I'll contact the author of that plugin and see what's going on there.
