### ISSUE TITLE
Add "Remove" Field option on the field metabox header

### ISSUE THREAD

**Issue by amansaini** [wpninjas/ninja-forms#448]
Removing a field from a Form requires opening the metabox and clicking on remove link at the bottom of field options.
This takes up a lot of time if you want to remove more than 2-3 fields.
A close icon at the header fields metabox can solve this problem.

**Comment by kstover** [comment]
I like this idea, but we haven't found a good graphical solution yet. I've moved this to 3.0 because it will likely be fixed there.
