### ISSUE TITLE
Prestyled forms

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#449]
Hey

I came across a mention of the following plugin:
http://gravitystyles.com/

A plugin on github with prestyled forms. Seems like an interesting idea for Ninja Forms as well.
A settings area for prestyled forms. Create various styles and add them to your prestyled forms section.
Share your forms with others as well.

**Comment by kstover** [comment]
I think that's an interesting idea. We have something similar planned for our Layout and Styles extension, so I'm not sure how much of this bleeds over to that extension, but we can definitely discuss it internally.

**Comment by paaljoachim** [comment]
What about having it as a free extension that people can include if they want (or with a low one time purchase price). As it would be nice for sharing prestyled forms similar to gravitystyles.

**Comment by jameslaws** [comment]
We want to create an entire repository of pre-built forms covering almost any use case. With Layout & Styles we have plans on adding templates as well. 

This is one of those things that if someone wanted to build it they are welcome to but I'm not sure it's anything we would have time to consider for quite some time. Our roadmap is pretty well set for the year through version 3.6 if all goes as planned.

**Comment by paaljoachim** [comment]
Sounds great James!
Where can I see the roadmap?

**Comment by jameslaws** [comment]
As far as set planned versions for Ninja Forms we don't have a publicly accessible roadmap.

Loosely I can tell you that the big stuff looks something like this:

* 3.0 - New field registration class
* 3.2 - Processing into a singleton
* 3.3 - Front-end overhaul
* 3.4 - Submissions update / Possible complete UI redesign
* 3.5 - Performance update
* 3.6 - Overhaul Calculations

These are merely the main focuses of these releases and are always subject to change as time and plugin progresses. It doesn't account for all the small stuff that will also be worked on during the development process. This also doesn't include any of the work that will be done with extensions.

**Comment by paaljoachim** [comment]
Thanks for posting the roadmap James!

**Comment by jameslaws** [comment]
Closed as irrelevant due to 3.0
