### ISSUE TITLE
Is it possible to remove css filter / action?

### ISSUE THREAD

**Issue by codecowboy** [wpninjas/ninja-forms#454]
I'd like to prevent Ninja forms from loading its own css file.  I've tried using ```remove_filter()``` and ```remove_action()``` and also overriding ```ninja_forms_display_css()``` but not having much luck.

I want to remove the styles enqueued here:

```
function ninja_forms_display_css(){
  wp_enqueue_style( 'ninja-forms-display', NINJA_FORMS_URL .'/css/ninja-forms-display.css' );
  wp_enqueue_style( 'jquery-qtip', NINJA_FORMS_URL .'/css/qtip.css' );
}
add_action( 'ninja_forms_display_css', 'ninja_forms_display_css', 10, 2 );
```

But without editing the plugin. Is this possible?

**Comment by codecowboy** [comment]
Looks like this can be done with ```remove_filter('ninja_forms_display_css','ninja_forms_display_css', 10, 2 );```

**Comment by kstover** [comment]
Sorry to just now be getting to this. Glad you found it. :)

**Comment by brunorios1** [comment]
How can I remove only qtip.css since I already have this file in my theme?

I tried:
wp_dequeue_style( 'jquery-qtip');
wp_deregister_style( 'jquery-qtip');
but didn't work.

thanks.

**Comment by heytricia** [comment]
This no longer works with 3.0. The new method is:

```
/**
 * Remove ninja form stylesheets
 */
function wpgood_nf_display_enqueue_scripts(){
    wp_dequeue_style( 'nf-display' );
}
add_action( 'nf_display_enqueue_scripts', 'wpgood_nf_display_enqueue_scripts');
```
