### ISSUE TITLE
Add custom class to form

### ISSUE THREAD

**Issue by helgatheviking** [wpninjas/ninja-forms#455]
You can add a custom class to a field, but if you could add a custom class to the entire form you could style certain groups of forms a particular way without needing the NF form ID.

**Comment by kstover** [comment]
You can do this now using a filter. I don't know if this will make it into core as an option, as I don't think it's something a majority of users would be using. (I'm willing to be wrong, though.)

The filter you want is: ninja_forms_form_class. It gets passed two things: current class and form id.

**Comment by helgatheviking** [comment]
Great thanks. I have no idea how many people might want it. I think it could be practical for anyone making lots of similar forms.

**Comment by kstover** [comment]
We can think about it and see if it's something that should be an option, or should stay a filter.

**Comment by kstover** [comment]
I think that the filter is the best solution at the moment, because we don't get a ton of requests for this.

**Comment by markouver** [comment]
I know this is closed but I'd just like to add my vote for this. Having CSS littered with #ninja_forms_form_x  selectors is not very intuitive. Also, the filter solution still requires you to know the form ID and to edit PHP code when adding a new form. The class solution could be utilized by designers without PHP knowledge.

Anyways, thanks for listening. Keep up the great work.

**Comment by tomalex0** [comment]
I'm also looking a way to add  a custom css to form element. I'm kinda very new to wordpress. How can i do this without using any extension. Where should  i add the code snippet?
