### ISSUE TITLE
Currency without the currency symbol

### ISSUE THREAD

**Issue by helgatheviking** [wpninjas/ninja-forms#457]
If you had an option for currency without the symbol, you could probably add that value safely to the auto-total.

**Comment by kstover** [comment]
I like this idea; I think that our currency/number masking overall can be improved.

**Comment by helgatheviking** [comment]
FYI, I was playing around with this all day today... and it seems that auto-total already works if you add a text field with currency mask.

**Comment by kstover** [comment]
Is it ok to close this? I have some plans to improve our masking and totalling. I'll detail those in another issue later.

**Comment by helgatheviking** [comment]
Totally, almost my all my issues were more for throwing ideas at you than really needing an urgent fix.
