### ISSUE TITLE
Taxonomy Term Splitting in WP 4.2

### ISSUE THREAD

**Issue by BFTrick** [wpninjas/ninja-forms#461]
WordPress core is changing the way it is splitting taxonomy terms and Ninja Forms is affected.

> In brief, any plugin that independently stores term IDs in the database – postmeta, usermeta, the options table, etc. mboynes and I looked over the top 100 most popular plugins on wordpress.org, and found eleven that will need changes in order to anticipate term splitting: Jetpack, WordPress SEO by Yoast, Google XML Sitemaps, All in One SEO Pack, Mailpoet, Advanced Custom Fields, Ninja Forms, Types, Custom Sidebars, Paid Memberships Pro, WordPress Download Manager. If you’ve written a plugin, theme, or other customization that stores term IDs in a static way, you’ll be affected too.

https://make.wordpress.org/core/2015/02/16/taxonomy-term-splitting-in-4-2-a-developer-guide/

They released some steps you can take now to make sure when users update to 4.2 that NF is good to go. :)

**Comment by kstover** [comment]
Thanks for the heads up; James and I were just discussing this.
