### ISSUE TITLE
Metabox output submit and button types need separate label and value parameters

### ISSUE THREAD

**Issue by helgatheviking** [wpninjas/ninja-forms#462]
I'm trying to move the Aweber extension settings into a tab with the rest of the NF settings. 

I went to create a submit type setting and this is what I am getting:

![image](https://cloud.githubusercontent.com/assets/507025/6255147/30e895dc-b7ae-11e4-9831-ad5e08a31077.png)

Essentially the label is serving as both the label and the button text. This seems redundant and it would be better to have a separate value parameter.

**Comment by kstover** [comment]
You should be able to pass an empty label.

**Comment by helgatheviking** [comment]
The button's value is pulling from the label attribute of the array. So you can't leave it blank or you get this:

![image](https://cloud.githubusercontent.com/assets/507025/6255435/30fc479c-b7b0-11e4-9e9a-a7e56ba82e8d.png)

**Comment by kstover** [comment]
Gotcha. I'm not sure when I'll be able to work on this; I'm trying to finish up stuff for the 2.9-beta.

I'll get to it as soon as I can.

**Comment by helgatheviking** [comment]
What about adding a 'text' parameter (or 'button text' or whatever you want to call it) to the settings array? Then check for it and fall back to the 'label'. I'll send a PR.

**Comment by kstover** [comment]
I think maybe using "value" would be good. It would also keep in line with the way that input HTML buttons work: value="label"

**Comment by helgatheviking** [comment]
I thought that too, but `$value` is all over the place in the metaboxes file and it seemed confusing.

**Comment by helgatheviking** [comment]
![image](https://cloud.githubusercontent.com/assets/507025/6255799/254c62d0-b7b3-11e4-840d-8cd4c74f0ed5.png)
