### ISSUE TITLE
Add IP Address to user fields

### ISSUE THREAD

**Issue by helgatheviking** [wpninjas/ninja-forms#465]
I have this in AWeber, but it seems like it might be better in core. I almost have a PR ready, but I got stuck because the user fields are added directly the DB and I keep getting errors when trying to add my new field. 

Sorry to be deluging you guys with issues right when you are working on 2.9, but I figured I may as well make notes while I happen to be working with NF.

**Comment by kstover** [comment]
Hey Kathy,

No problem at all! I'm not sure if this will go into core as a separate field. We'll have to do some internal discussion to see if we think it should. There is already a function in core to get the IP, but adding a field is something we'll have to think about.

**Comment by kstover** [comment]
Ha! There are other extensions that use IP addresses, but I am a little wary of putting it directly into core when extensions like User Analytics offer this feature. Maybe it could be something like the credit-card field which exists in core, but isn't shown to the user unless an extension uses a filter to turn it on?

**Comment by helgatheviking** [comment]
That seems like a good idea. It would be nice to have the input standardized even if it is up to the different extensions to *do* something with the input.

**Comment by kjohnson** [comment]
The IP Address is now accessible as a merge tag in field default values as of v3.
