### ISSUE TITLE
"Add New List Option" button for list fields external to the "Expand/Collapse Options" link

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#466]
Many users are confused how to add options to list fields because they do not realize they first need to click "Expand/Collapse" options to add a value to their list.  We should discuss a way to make this more intuitive, such as moving the "add value" button outside of the container normally hidden by "Expand/Collapse Options" that can also unhide that container.

**Comment by jameslaws** [comment]
What if we got rid of the expand and collapse option completely? Also, what if when adding a list field it has three generic options already added this showing how the field should be used?

**Comment by wpnzach** [comment]
We just added a change in the beta to address this by clarifying the language.  I'm not opposed to having at two selections auto added, as that's the minimum use case for a list field and shouldn't require the user to delete anything in any circumstance.  I can still see a use case for collapsing the list options, so I don't know about removing the option entirely.  For users with long lists, that can clutter the UI a bit to have them always expanded.

**Comment by jameslaws** [comment]
What would be the use case for collapsing the list above just collapsing that entire field. It is a list field and those options are the most important part of the field. Seem strange to have them hidden by default.

**Comment by wpnzach** [comment]
That's probably a fair point, especially since in 2.9 all fields will be closed by default when the builder page is viewed.  It would fit into that redesign well, I think.  Definitely something to consider.

**Comment by kstover** [comment]
Fixed in 284df171a37e0e0ee4955aad3ec816d2932e9301
