### ISSUE TITLE
Add option for error message color

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#477]
Users often submit support requests stating that no error messages are appearing on their site after filling out a form and missing required fields.  The error messages are appearing, but users are not seeing them because there is no default styling applied to them. A form setting with an error message color picker or at least an input to accept an RGB value could go a long way in preventing these kinds of issues.

**Comment by jameslaws** [comment]
I can change this to red by default but we won't be adding a specific styling option as that can easily be done with CSS or Layout & Styles.

**Comment by wpnzach** [comment]
Can we have an option for at least  a few by default?  Red/black/white or something?  Red might not be a good default for all use cases.  Just looking for a way to lower support contact for something this simple.

**Comment by jameslaws** [comment]
That option is in Layout & Styles. I'm not keen in adding random color stylings or options into the core plugin. It muddies the water and later makes it difficult to decide what are reasonable CSS options and what aren't. It's a huge snowball in my opinion.

Just create a document that has this rule explained:

.ninja-forms-field-error {
    color: red;
}
