### ISSUE TITLE
Ajax Forms not submitting in Safari 

### ISSUE THREAD

**Issue by iamlasse** [wpninjas/ninja-forms#478]
I am having an issue with a clients site. I have tracked down the error to being a javascript error, [Error] TypeError: 'undefined' is not an object (evaluating 'i.hide_complete')
	ninja_forms_update_success_msg (ninja-forms-display.min.js, line 1)
	ninja_forms_default_response (ninja-forms-display.min.js, line 1)
	(anonymous function) (ninja-forms-display.min.js, line 1)
	dispatch (jquery.min.js, line 3)
	handle (jquery.min.js, line 3)
	trigger (jquery.min.js, line 3)
	triggerHandler (jquery.min.js, line 3)
	ninja_forms_response (ninja-forms-display.min.js, line 1)
	success (jquery.form.min.js, line 11)
	j (jquery.min.js, line 2)
	fireWith (jquery.min.js, line 2)
	x (jquery.min.js, line 4)
	b (jquery.min.js, line 4)

I have googled and searched but found nothing, the forms work fine in Chrome.

**Comment by jameslaws** [comment]
This might be better addressed through a support ticket at https://ninjaforms.com/contact

The reason is that I can't reproduce this in my installs so it's like site specific. We would need a link to the forms and some other details.

**Comment by iamlasse** [comment]
I submitted a request Yesterday, but figured it could be a bug so i tried here too, since my client is on my back about it.. The site is www.gpius.net

**Comment by jameslaws** [comment]
I see that we replied to you ticket yesterday at 3:33pm est.

It would have come from support@wpninjas.com

**Comment by iamlasse** [comment]
Hi James, Sorry about that but I just checked and I haven't received an email. COuld you email lasse (at) krispinteractive (dot) com

**Comment by jameslaws** [comment]
I've resent it. Make sure you check your spam.

**Comment by iamlasse** [comment]
Thank you, and apologies for double submissions. The problem was a plugin called Hammy for responsive images.

**Comment by nikonratm** [comment]
Im having this issue too. Any more details on the fix? (I'm not using Hammy)
