### ISSUE TITLE
Undefined variable: field_class  for radio button fields in submission admin

### ISSUE THREAD

**Issue by sparkalow** [wpninjas/ninja-forms#480]
Ninja Forms Version 2.8.13

Notice: Undefined variable: field_class in ....../wp-content/plugins/ninja-forms/includes/fields/list.php on line 818

set wordpress to debug mode in wp-config.php  (should always be in this if dev'ing plugins)

1. Create a form with a list field - displayed as radio button.
2. View the form on frontend and create a successful submission.
3. View your submission in the NF admin.

**Comment by kstover** [comment]
I can't repro this locally with those steps. Can you give me a form export?
