### ISSUE TITLE
Datepicker dont display calendar in local language

### ISSUE THREAD

**Issue by eduardoarandah** [wpninjas/ninja-forms#485]
When displaying calendar it would be great to show it in local language, my visitors don't speak english 

example: spanish
jQuery( "#datepicker" ).datepicker( jQuery.datepicker.regional[ "es" ] );
http://jqueryui.com/datepicker/#localization

**Comment by eduardoarandah** [comment]
datepicker displays only english
![fecha](https://cloud.githubusercontent.com/assets/4065733/6420704/24cf4f2a-be8e-11e4-9049-edb6c1f8e43c.png)

**Comment by kstover** [comment]
We added a filter in PHP to the datepicker a few versions ago. I wonder if this is something that can be modified there? I don't have a ton of experience localising in jQuery UI components. If we can modify the local in the original setup, I would think we could setup a filter to do it.

**Comment by eduardoarandah** [comment]
it is really easy.

Just include localization file and add a line. Localization files are ready.
here: https://github.com/jquery/jquery-ui/tree/master/ui/i18n

Example:

<html lang="en">
<head>
<meta charset="utf-8">
<script src="http://code.jquery.com/jquery-1.10.2.js"></script>
<script src="http://code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
<script src="datepicker-es.js"></script>
<script>
$(function() {
$( "#datepicker" ).datepicker( $.datepicker.regional[ "es" ] );
});
</script>
</head>
<body>
Date: <input type="text" id="datepicker">
</body>
</html>


More info: http://jqueryui.com/datepicker/#localization

Im sending you attachment with example

**Comment by baden03** [comment]
What would be the best method of hooking into the ninja forms WordPress plugin so that the language files would a) be loaded in the correct place and b) not be overwritten during theme / plugin updates?
In short, is there a build in hook that a thrid-party plugin can add the language javascript file and also initalize the date-picker object with the localization?
