### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#486]
(Splitting up my thoughts on features list)

Notifications is a bit tricky to get to. One has to go to All Forms -> select a form -> then go to Notifications.

Notification could be a new sidebar tab. 
In the Notification screen:
Have the notifications show in which forms they are active.
I do believe I have some additional thoughts on notifications and will also need to come back to that.

What are the plans for modifying notifications?
I used the word notifications in every line in this post except the first.....:)

**Comment by kstover** [comment]
Thanks for the notes! Notifications are being changed to "emails and actions" and are designed to be specific to a particular form. Eventually, this is where extensions, like post creation, will add their settings. Because they're meant to be per-form, they really fit best under each form.

**Comment by paaljoachim** [comment]
Btw it looks really nice in 2.9. Nice and tight and to the point!

**Comment by jameslaws** [comment]
Closed as irrelevant due to 3.0
