### ISSUE TITLE
All Forms screen

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#487]
(From the thoughts on features thread)

All Forms screen.
Add a Screen Options to turn on/off Shortcode, Template Function, Date Updated. (As mentioned earlier Submission Entries with a link to submissions and views could be nice to add in.)
Showing Template Function here seems a bit overkill on this screen and should be moved to a better place for instance Form Settings.
Quick Edit: Preview Form and view submissions perhaps just change these to Preview and Submissions.

**Comment by kstover** [comment]
Thanks for the suggestions. Currently, we don't track views, so that would need to be added to the plugin before we displayed it. I agree that the all forms table could use an overhaul, and we'll definitely take your suggestions into account when we revisit it!

**Comment by paaljoachim** [comment]
Great!

**Comment by jameslaws** [comment]
Closed as irrelevant due to 3.0 and new coming UI for all forms screen.
