### ISSUE TITLE
Submissons

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#488]
Submissions. 

- Have the most active form by default show submissions. So one does not have to select perhaps the most used form and see the submissions. After having selected whichever form and leaves the submissions area and returns again have the last view be seen again.

- A better shift in color between entries. It is too light today hardly visible.
- Screen option for turning of the # hex (id for each entry) symbol.
- Checkboxes and other field labels could have somekind of symbol and text included in an entry.
(For instance I have a checkbox in a form for signing up to the newsletter. It would be nice to have this represented in the entries.) It shows up when I click the edit button of an entry.

- Entries take too much space in the submissions screen. They could have a max height. An entry could be clicked to open like an accordion showing the full message if needed. Click Edit to go into edit mode.

Edit Submission: 
A note text box below the entry and a way to send entry and note to another person.

Submission Stats:
Moving the mouse over the pins beside hex number, Status: Submitted and Form: Kontakt oss brings a hover effect. A clickable effect with no link.

**Comment by paaljoachim** [comment]
Edit/viewing a submission
Instead of having a scroll bar inside the message field (text area) it would be nice if the box just became bigger so a user would not need to click into the message field and scroll to see the message.

**Comment by jameslaws** [comment]
UI to be moved into 3.0 UI in a future release. Closed as irrelevant due to 3.0
