### ISSUE TITLE
Sidebar and Settings and Forms

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#489]
<b>Sidebar</b>

All Forms
Add New
Submissions 
Import/Export (can be moved)
Settings
System Status  (can be moved)
Extend

It would be nice to show the most used sections in the sidebar and hide other areas in the visible sections.

What if we moved Import/Export (merge the Forms and Favorite Fields tabs) and moved System Status into Settings? 

Forms: A hack for Ninja Forms to import and read the best it can xml files from other contact forms. Today Ninja Forms will import an xml file from Gravity Forms and a new form will show up with no title and no field settings.

<b>Settings</b>
General - Add turn on or off Append A Ninja Form into post/page. 
Labels - Add a revert to default values button.

Move from Settings: Licenses into Extend as another tab since they are connected.

**Comment by jameslaws** [comment]
Soon all these things will be moved out of the WordPress admin menu into a new UI. Closed as irrelevant due to 3.0
