### ISSUE TITLE
Comments on Email & Actions in 2.9

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#491]
<b>Email & Actions</b> a very good name! 

Clicking Email Admin, email User or Success Message.
A huge - ID shows up beside each. The id could be made a lot smaller and moved all the way to the right (as it grabs a lot of attention today). Back to List could be aligned to the other text field boxes. The tab Email & Actions could be clickable so one can either click the Back To List button or the tab.

Email Admin
From Name - default could be user submitted name field.
From Address - default could be user submitted email address field.
To - default address admin e-mail. 
Use the same procedure which is done in the Subject area. Where it says Ninja Form Submission and then the greyed out text that says Subject Text or search for....the rest of the grey text is hidden as there is not enough field character space. Be sure to extend the various fields to include a default and the full greyed out text. The same procedure can transfer over to Email User.

**Comment by jameslaws** [comment]
Closed as irrelevant due to 3.0
