### ISSUE TITLE
(Form) Settings 2.9

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#492]
Form <b>Settings</b> change to <b>Form Settings</b>. A different name then the other sidebar Settings section.

Display - 
A ? question mark with a tooltip beside Submit via AJAX would be nice as for me the question comes up what is AJAX? (ok I know what it is..:) What good does it do? Should I turn this on or off?

Regards to Build Your Form section
To the far right of the Submissions tab add a drop down to jump to other forms.

**Comment by jameslaws** [comment]
Closed as irrelevant due to 3.0
