### ISSUE TITLE
In 2.9 - Edit Form Sidebar item.

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#493]
I noticed that
in the All Forms screen -> click an existing form so it enters the Build Your Form and within a few seconds (not instant) the left sidebar adds Edit Form item to it.

Click Email & Actions and Settings tab and the Edit Form is there. 

![screen shot 2015-02-28 at 13 09 55](https://cloud.githubusercontent.com/assets/5323259/6426146/2955b2b0-bf4b-11e4-99f4-f415a2d14601.png)

**Comment by kstover** [comment]
Yup. This is so that you know you're editing a form and not adding a new one or on the all forms section.

**Comment by paaljoachim** [comment]
Ahhh. Gotcha..:)
