### ISSUE TITLE
Remove "Include in the Auto-Total" option from "Total" fields where "Automatically Total Calculation Values" is selected as the calc method.

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#502]
Remove "Include in the Auto-Total" option from "Total" fields where "Automatically Total Calculation Values" is selected as the calc method.

**Comment by wpnzach** [comment]
This causes an infinite loop and out-of-memory php errors.

**Comment by kstover** [comment]
Not an issue in 3.0.
