### ISSUE TITLE
Remove "Specify operations and fields (Advanced)" as a Calculation Method

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#503]
Redundant with and less powerful than "Use an equation" method.  Will need a conversion process to convert to "Use an Equation" calculation method, so will likely need to wait for a larger release.  To maintain the user friendly nature, adding a JavaScript button as in the email notifications to add field shortcodes from a dropdown would be a nice addition if possible.

**Comment by kstover** [comment]
Not an issue in 3.0.
