### ISSUE TITLE
Tag Manager validation not working

### ISSUE THREAD

**Issue by vladiiancu** [wpninjas/ninja-forms#508]
Hi, here's the situation.

I have Ninja Forms installed on a website. I also have Google Tag Manager on the same site. The tag manager loads Google Analytics. It also has a Form Submit Listener.
I use the Form Submit Listener to send events in GA for both the Ninja Form and the mailchimp subscribe form. 

The problem is, that if the Form Submit Listener has the option to Check for Validation, then when the user submits the form correctly via AJAX and display the success message the tag doesn't fire. 
If you uncheck it, then the tag fires as it should. However it fires even when the form was not completed correctly. 

Something is surely blocking the event to fire. More info about the Check for Validation Option is here https://support.google.com/tagmanager/answer/3415369#CheckValidation

Ninja Forms version used is 2.8.13

**Comment by glenp** [comment]
I'm having the same issue. Did you have any luck figuring this out? Have no idea why it won't fire.

**Comment by vladiiancu** [comment]
Nope. I searched for another way without using Tag Manager.

**Comment by kstover** [comment]
I apologise for coming back to this ticket years later. I'm going to close it; if it's an issue, feel free to open it again with current details.
