### ISSUE TITLE
Creating or editing a form

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#512]
I will just think a bit out loud here...

All Forms.
Duplicating a form the name could be something like this: contact form copy.

Renaming the form.
There could be a rename link added to the quick edit in the all forms screen.
Today has to go to Settings -> Form title to rename which is a bit out of the way...

Edit form.
Title up top could be editable so it is easy to rename the form.

I am actually also trying to get rid of the popup dialog box finding a way around it. As it is nice to avoid having these at all I think. As I am not sure about the accessibility of these popup dialog boxes.

Creating a new form no title exists above the tabs. What about adding a visible title text box above the tabs? To which the user can just go ahead and add a title. Default title could be New Form.  

Lets see...
The user fills in the title in the title text box above the form. User gets to name the form right away and they also know that they can click the title and rename it anytime.
If a user leaves the form without adding a Submit button they can get a dialog popup box asking if they want to add the submit button or perhaps even better if they do not add a submit button one will automatically be added.... like magic..:)

I think that was it for now.
Have a great day!..:)

**Comment by kstover** [comment]
Editing a title inline is something we are considering, and I think the rest are taken care of in 3.0.
