### ISSUE TITLE
Site Crash After 2.9.2 Update

### ISSUE THREAD

**Issue by eki2015** [wpninjas/ninja-forms#513]
Getting this error after the update. Anyone please out there that can help me?

Fatal error: Call to undefined function ninja_forms_get_form_by_id() in /home/ayfcamp/public_html/wp-content/plugins/ninja-forms-style/includes/admin/pages/ninja-forms/tabs/form-layout/form-layout-mp-div.php on line 17

**Comment by eki2015** [comment]
Got the site back up but all the forms are gone.

**Comment by kstover** [comment]
Sorry you're having issues. It sounds like the form conversion wasn't properly completed.

The error above comes from Layout & Styles; if you have updated that plugin, you shouldn't see it again.

Do you see a prompt to update your forms?

**Comment by kstover** [comment]
Closing for lack of response.
