### ISSUE TITLE
Email and Actions and the relationship with forms.

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#520]
Hey

I noticed when switching from Gravity Forms to Ninja Forms on my web site easywebdesigntutorials.com that no Email and actions were asked for so I forgot to create any. For whatever reason there were no premade ones. Meaning when I happened to check the submissions I noticed there were a few e-mails I had missed (no biggie). So this got me thinking about the relationship of the form and email/actions.

When a person creates a new form and has no actions it would be nice with a light blue warning bar along the top of the edit/create form area. Saying create an action to get user submitted e-mail or a reminder that the admin needs to turn on the deactivated action(s). It will help the user along into creating an action to what is to be done after the user submits a form. 

Even better is having default ones prefilled with the most logical choices.

**Comment by kstover** [comment]
Default actions are added for email fields and the admin user address in 3.0.
