### ISSUE TITLE
Individual Field Class

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#535]
Unlike the field-type class, this class will be access via Ninja_Forms()->field( id ), and it will store specific field setting data. This is where that data will be cached so that future calls to this method don't hit the database again.

**Comment by kstover** [comment]
There should be a method to refresh the data, and whenever any field data is updated, it should automatically run this.

**Comment by kjohnson** [comment]
`Ninja_Forms()->form( 1 )->field( 1 )->get()` or `Ninja_Forms()->form( 1 )->get_field( 1 )`
