### ISSUE TITLE
New Field Types

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#537]
Since we're introducing the field class registration, we need to add some more HTML field types.

- [ ] Color
- [ ] Range
- [ ] Time / Week / Month
- [ ] URL
- [ ] Phone

**Comment by paaljoachim** [comment]
Perhaps this is the wrong place for this but
does image field type fit into this?
Giving the opportunity to add image to any field.

**Comment by jameslaws** [comment]
Not really. image isn't really a field type. You can add images to any field now by using the description and adding an image to that.

**Comment by paaljoachim** [comment]
Hey James. I am not following. Could you elaborate?
