### ISSUE TITLE
Backwards Compatibility for Field Keys

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#540]
Related to #539, in order to prevent breaking custom code, the field conversion process should use the Field ID as the default field key. Then, $ninja_forms_processing->get_field_value() function should be modified to look first at the key and then for the field ID. This should ensure that custom code written now that targets field IDs will still work after the update.

**Comment by kjohnson** [comment]
@kstover Is this still desired behavior moving forward?

**Comment by kjohnson** [comment]
The model class check for an integer and uses it as a field id, otherwise, it is uses as a field key.
