### ISSUE TITLE
Favourite Fields

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#541]
Since we are now storing field data in the custom nf_fields, nf_fieldmeta tables, we need to re-work the way that favourite fields works. Currently, the data for each favourite is stored in the ninja_forms_fav_fields table as a serialised array. The new nf_fieldmeta solution will mean that we can just give the field a meta key of "favourite" instead of needing an extra table for favourite fields.

**Comment by jameslaws** [comment]
We've gone a different direction for this.
