### ISSUE TITLE
Field Conversion

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#542]
Since we are using the nf_fields and nf_fieldmeta tables to hold data, we need to convert the current ninja_forms_fields table to the new object - objectmeta structure. This will entail:

- [ ] Creating a new nf_fields entry for each field.
- [ ] Unserialising the array and creating a new nf_fieldmeta value for each piece of data.
- [ ] Converting list fields to either: radio, checkboxes, multi-select, or select.
- [ ] Converting email, First Name, Last Name, Address1, Address 2, City, State, Zip, Country, Phone, Sub Total, Total, Tax, Credit Card to their respective new fields.
- [ ] Converting Favourite Fields

**Comment by jameslaws** [comment]
We've gone a different direction for this.
