### ISSUE TITLE
Field Groups

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#544]
Add the ability to group fields on the back-end. In the builder, this group would act as one field, while in submissions each field would have its own value.

This should also allow extensions like Conditional Logic to show/hide entire field groups.

**Comment by paaljoachim** [comment]
This seems very interesting! I look forward to testing this out. How this will work with and without the Conditional Logic extension.

**Comment by paaljoachim** [comment]
Thinking about groups...

One way could be to have a group filed with a space below that shows that fields and be dragged into it. Another way would be to have a indent similar to the WP menus are handled in creating submenus.
![group-field](https://cloud.githubusercontent.com/assets/5323259/7029134/753e76e8-dd5b-11e4-902c-67cc741b9f24.jpg)

Showing and hiding children/group members.
![screen shot 2015-04-07 at 19 11 12](https://cloud.githubusercontent.com/assets/5323259/7029145/931303b4-dd5b-11e4-9777-9523c4572b05.png)

To be used with for instance with billing address. As oftentimes one can click a checkbox to open billing address information. Or just leave it unchecked if shipping and billing address is the same.
Bringing a simple show hide into Ninja Forms core would be really nice, and could then be done so through a group. Creating a dropdown, checkbox etc with a show or hide group members.

**Comment by jameslaws** [comment]
Closing this for a rethink for the THREE UI. It's definitely planned for a future release.
