### ISSUE TITLE
Change Field Type

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#545]
When a field is added, you should be able to change its type with a dropdown selector. This would let you change a field from a radio to a select to a textbox, keeping all the settings that were the same.

**Comment by jameslaws** [comment]
@kstover, Do we need something like this for our list field in THREE? I could see having a long list and wanting to simply change the type of list it is.

**Comment by kstover** [comment]
This is something that we'll do for list types, but not for other types. Once you add a textbox, it will be a textbox.

**Comment by kstover** [comment]
I don't think that this is planned any longer. If you add a field, that's the field it will remain.
