### ISSUE TITLE
Basic File Upload Field

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#546]
In version 3.0, we plan on adding a basic file upload field to Ninja Forms. This field will upload to the WordPress Media section.

**Comment by paaljoachim** [comment]
Great!

**Comment by respectyoda** [comment]
How would this feature be different than the File Uploads extension?

**Comment by jameslaws** [comment]
The big difference is it wouldn't include any of the renaming, uploads restriction settings, off-site integrations, etc.

It would just be a standard field that uploads the files as is to a singular location. No bells or whistles.

**Comment by brandbrilliance** [comment]
Thanks. I also believe all HTML basic fields should be part of a form plugin. Bells and whistles should be all the special stuff like renaming, moving to dropbox, restrictions, etc. Some stuff we could also program in using actions (I'll write stuff small things like that for my sites). I used to use Contao CMS and it included every single HTML form field for free. I then wrote advanced processing like e-mail duplicates,

**Comment by brandbrilliance** [comment]
Did this make it into 3.0?

**Comment by kstover** [comment]
We'll be putting this into a 3.x release, although we aren't sure which yet.

**Comment by rjpedrosa** [comment]
Hi,

Was this actually included on version 3.0? Can't find any file upload field.

Thanks

**Comment by jameslaws** [comment]
It was not.i believe we're aiming for 3.1.

**Comment by dpacmittal** [comment]
Basic file upload should be a must for a forms plugin, I believe. It doesn't seem fair to pay for such simple functionality. I tried extending ninja-forms to include a basic file upload form but the documentations are not complete. I require file uploads and it seems like the only solution is to move away from ninja-forms.
