### ISSUE TITLE
Problem with localization on version 2.9.6

### ISSUE THREAD

**Issue by maxleonca** [wpninjas/ninja-forms#550]
Hello,
I just started to use WordPress and looking for a Forms plugin stumble upon yours.
Is really good, congratulations on an outsanding product.

Just in case you want to know, the localisation seems broken or maybe I'm a moron.
I have WP installed and set with es_ES and everything seems consistent, but for some reason the ninja_form_settings is not picking up the localilzation.  Oddly enought everything else is but not the settings for the forms themselves, so the miscellaneous texts like the captcha or the Marked fields are requiered are being displayed in english.

BTW:
WP: 4.1.1
PH: 5.6.6
OS: ARCH Linux
DB: MariaDB 10.0.17
Web: Nginx 1.6.2
Arch: x86_64

Cheers,

Max L

**Comment by kstover** [comment]
Hey Max,

The ninja_forms_settings are all stored in the database, so you'll need to change those to your appropriate language on the Forms->Settings->Labels tab.

**Comment by kstover** [comment]
Hey Max,

Any update on this issue?

**Comment by kjohnson** [comment]
Translations are now handled by the WordPress.org Plugin Directory.
