### ISSUE TITLE
Importing List Items doesn't display values if "Show list item values" is checked.

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#559]
Step One
![Step One](https://lh4.googleusercontent.com/fO4GydDsibcbf0Lh_k7vtaA4cEcq21S00qR3krp5x6B_rbQCt1QE-kKZVh7U5e2x5OOVvQCtRqCTl0I=w1889-h1020)

Step Two
![Step Two](https://lh3.googleusercontent.com/ZIP59c_dg35hOue748IkYQf-D81CPfzm_ejPUmX-DuLIG05zSqrQtgdOHVCj1J__L_inLbV8ieae-cs=w1889-h1020)

Result
![Result](https://lh4.googleusercontent.com/hsaMbbYjL3g3qTjbJppYps4QJdjIenpfgV_xfizXuolmyBw09BmmuSdVmN5u63eW-dnGfnhqT2Q6NY8=w1889-h1020)

**Comment by wpnzach** [comment]
Values are saved, this is purely a cosmetic bug but can be confusing for users.

**Comment by kjohnson** [comment]
Importing list items is being deprecated. We are looking at a re-usable list source feature instead.
