### ISSUE TITLE
Wrap Session Start in TryCatchThrow

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#562]
On line 652 of `ninja-forms.php`, Ninja Forms attempts to start a `session` if a `session id` is not set. However, there is an issue with headers already being sent. If we wrap the `session_start` in a `TryCatchThrow` then we can throw our own exception.

**Comment by kstover** [comment]
Added an instance of WP Session manager and removed any use of PHP Sessions as of version 2.9.18.
