### ISSUE TITLE
how to add cancel button side submit button?

### ISSUE THREAD

**Issue by premier213** [wpninjas/ninja-forms#566]
hi tnx for this plugin !

how to add cancel button side submit button?

**Comment by kjohnson** [comment]
Are you wanting to clear the form, like a reset button?

**Comment by premier213** [comment]
no i want add button like submit for close window !

**Comment by kjohnson** [comment]
Could you give me a little more details on the scenario?

**Comment by respectyoda** [comment]
@premier213 Are you using a modal window to display the form?
