### ISSUE TITLE
[ninja_forms_all_fields] has blank label for 'Total'

### ISSUE THREAD

**Issue by helgatheviking** [wpninjas/ninja-forms#571]
When viewing all the form field responses all the fields get a label, except for the calculation total:

![image](https://cloud.githubusercontent.com/assets/507025/6830158/52baba52-d318-11e4-8522-c8a591097232.png)

**Comment by kjohnson** [comment]
The shortcodes have been deprecated as of v3 in favor of the new merge tag system.
