### ISSUE TITLE
Hide hidden fields in "All Fields" Merge Tag

### ISSUE THREAD

**Issue by helgatheviking** [wpninjas/ninja-forms#572]
The `[ninja_forms_all_fields]` shortcode could use an optional attribute that would hide all hidden fields.

`[ninja_forms_all_fields show_hidden="false"]`

Or something along those lines. There are a few hidden fields that I don't want to show the user in the success email, but I don't want to manually create an email for all the other fields either.

**Comment by kjohnson** [comment]
With the new merge tag system we could add something like `{fields:all_fields:visible}` as an advanced feature.

**Comment by kstover** [comment]
@kjohnson @jameslaws and I were kicking some around like this the other day. I've added this to our internal tracker, and while I'm cleaning up our GitHub issues, I'm going to remove it from here.
