### ISSUE TITLE
Field type descriptions appear on same line as label elements

### ISSUE THREAD

**Issue by sumobi** [wpninjas/ninja-forms#575]
The descriptions on many of the field types inside the advanced settings menus (eg textbox, list, checkbox etc) run into the same line as the `label`. 

![screen shot 2015-03-26 at 3 33 26 pm](https://cloud.githubusercontent.com/assets/52581/6856344/803d98e0-d3cd-11e4-9f8e-5f7837b9543e.png)

This could potentially be fixed (at least for now) by making the `span` a block level element. Eg:

    .field-option span.description {
	    display: block;
    }

### After:

![screen shot 2015-03-26 at 3 33 01 pm](https://cloud.githubusercontent.com/assets/52581/6856348/87c92f8e-d3cd-11e4-887b-8cb653a13d14.png)

**Comment by kstover** [comment]
Merged here: https://github.com/wpninjas/ninja-forms/pull/576
