### ISSUE TITLE
TinyMCE field?

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#577]
Hey

Just a quick thought. What about a TinyMCE visual editor field to where one can add images etc....?

**Comment by wpnzach** [comment]
This already exists in core.  There is a "Text" layout element in the Layout Elements field group for this purpose.

**Comment by paaljoachim** [comment]
Ahh.... Thanks Zachary!

**Comment by i2g-lweiss** [comment]
Any chance of having Tiny MCE or minimal formatting controls in an input field?

**Comment by i2g-lweiss** [comment]
Ugh nevermind it's there.  Under Paragraph text / Display / Show rich text editor.  Helps to read the documentation i guess.
