### ISSUE TITLE
Form cannot be submitted properly when ajax enabled but JS off in browser

### ISSUE THREAD

**Issue by sumobi** [wpninjas/ninja-forms#578]
If a form has `Submit via AJAX (without page reload)?` enabled and JS is disabled in the browser, when a form is submitted the URL changes to

    http://ninjaforms.affwp.dev/wp-admin/admin-ajax.php?action=ninja_forms_ajax_submit

And the page shows:

    {"form_id":7,"errors":false,"success":true,"fields":{"12":"","11":"","36":"unchecked","13":false,"34":"0.00","35":"0.00"},"form_settings":{"form_url":"http:\/\/ninjaforms.affwp.dev\/wp-admin\/admin-ajax.php?action=ninja_forms_ajax_submit","date_updated":"2015-03-26 21:32:18","clear_complete":"1","hide_complete":"1","show_title":"0","status":"","form_title":"EDD","last_sub":"29","append_page":"","ajax":"1","logged_in":"0","not_logged_in_msg":"","sub_limit_number":"","sub_limit_msg":"","sub_id":108,"admin_attachments":[],"user_attachments":[],"admin_mailto":[],"admin_subject":false,"user_subject":false,"admin_email_msg":false,"user_email_msg":false,"save_msg":"","landing_page":"http:\/\/google.com\/something"},"extras":{"_wpnonce":"c9da475187","_wp_http_referer":"\/edd-form\/","_ninja_forms_display_submit":"1","_form_id":"7","_ninja_forms_field_13":"Submit"}}

![screen shot 2015-03-26 at 5 46 22 pm](https://cloud.githubusercontent.com/assets/52581/6858840/2b3d1b1e-d3e0-11e4-9601-d21bb729100b.png)

**Comment by wpnzach** [comment]
This is expected behavior.  AJAX requires JavaScript to function properly.  If the user has it turned off in their browser, there is no way to submit properly via AJAX and it will cause an error.

**Comment by jameslaws** [comment]
I think @sumobi is aware of how AJAX works. Perhaps he's wondering if there should or can be some graceful fallback?

**Comment by kstover** [comment]
We use the jQuery plugin ajaxForm, which is included with WP. The issue is that on the PHP side of processing, we can't check to see if the browser has JS disabled, so we output the AJAX response, even though the form has been submitted. We could probably use the WP DOING_AJAX constant and process the form normally if it isn't true, even if Ajax is turned on for the form.

**Comment by jameslaws** [comment]
I think that sounds like a graceful compromise.

**Comment by sumobi** [comment]
@jameslaws That's the one :+1:

**Comment by pippinsplugins** [comment]
I'd definitely love to see a graceful fallback here.

**Comment by davpsh** [comment]
I'm using small hack in this situation:
just call this snippet before ```ninja_forms_display_form($formID);``` in template
```php
<script type="text/javascript">
    window['ninja_forms_form_<?php echo $formID?>_settings'] = { ajax:"1",  hide_complete:"1",  clear_complete:"1"}
</script>
```
```php
//if need load this script too
<script src="<?php echo NINJA_FORMS_URL.'js/min/ninja-forms-display.min.js?nf_ver=' . NF_PLUGIN_VERSION;?>" type="text/javascript"></script>
```

My full example looks like:
```php
if($_GET['rel']=='dynamic'){?>
    <script type="text/javascript">
        window['ninja_forms_form_<?php echo $formID?>_settings'] = { ajax:"1",  hide_complete:"1",  clear_complete:"1"}
    </script>
    <script src="<?php echo NINJA_FORMS_URL.'js/min/ninja-forms-display.min.js?nf_ver=' . NF_PLUGIN_VERSION;?>" type="text/javascript"></script>
<?php
 }
ninja_forms_display_form($formID);
 ?>

**Comment by saetia** [comment]
how is this closed? this is insane

**Comment by kjohnson** [comment]
@saetia The `ajax` setting is being deprecated.

**Comment by saetia** [comment]
@kjohnson is it still an issue in ninja forms 3? which version will see ajax removed entirely?

**Comment by pascalwacker** [comment]
I just stumbled across this thread, if it isn't resolved yet, maybe this would be a nice feature to implement. just before returning the data as JSON make a check if it's an xmlhttp request (http://stackoverflow.com/a/8553669/2989952) and if so redirect the browser instead of returning the JSON. (However, it's 2016 so 99.9% will have Javascript enabled)
