### ISSUE TITLE
The one page webshop - brainstorming

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#579]
Hey

Right now I have a few clients that need a basic web shop. Easy to create and easy to run.
So I thought I would brainstorm the idea right here...

Basic
I could create a regular form with product names and amount drop downs. 
With a send me the invoice button on the end.

Intermediate
The above and the Conditional Logic extension to calculate the sum of the products selected.
And an extension for paying (PayPal Express) or the person can choose to get an invoice.
Perhaps even add in the Text Message Notifications extension.

It seems this could be a perfect how to create a one page Ninja Forms web shop.
Thoughts?

**Comment by BFTrick** [comment]
Hey @paaljoachim GitHub is really not the place for brainstorming. This is exclusively used for bugs and sometimes feature requests.

If you can find a bug with reproducible steps please create an issue for that but we can't have open issues for brainstorming.

I'd look at solutions like this: http://www.woothemes.com/products/woocommerce-one-page-checkout/

I vote that we close this.

**Comment by paaljoachim** [comment]
Hey Patrick I was kinda thinking that I might be a bit off posting this here..:)
O'well no harm done.
