### ISSUE TITLE
"Template Function" value does not wrap in Firefox

### ISSUE THREAD

**Issue by gitname** [wpninjas/ninja-forms#592]
Refer to the "Template Function" column on the "Forms" > "All Forms" page in the Admin area.

In Chrome, the value wraps, allowing the user to see the entire value. See top half of attached screenshot.

In Firefox, the value does not wrap, preventing the user from seeing the entire value. See bottom half of attached screenshot.

![ninja-forms-template-function-display](https://cloud.githubusercontent.com/assets/7143133/6990605/b499c44e-da24-11e4-8d6c-89daa98d2e8a.png)

WordPress version: 4.1.1
Ninja Forms version: 2.9.7

**Comment by kjohnson** [comment]
This is being removed form the table display.
