### ISSUE TITLE
Character limit for Favorite Fields titles

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#595]
Hey

The dialog box for Favorite Fields:
What would you like to name this favorite? 

Add a max characters of 15 (or 16). Character 16 touches the right edge of the button. Over 16 then it begins to go outside the right edge of the button.

**Comment by kstover** [comment]
I've added this to our internal tracker while I'm cleaning up our GitHub issues. I will evaluate re-adding it here later.
