### ISSUE TITLE
PayPal Express add currency

### ISSUE THREAD

**Issue by joeguilmette** [wpninjas/ninja-forms#599]
class-paypal-settings.php:113

`array( 'name' => __( 'Russian Rubles', 'ninja-forms-paypal-express' ),       'value' => 'RUB' ),`

Should also be a way to just add a missing currency according to PayPal slug.

**Comment by kstover** [comment]
Thanks for the heads up! I'll add a filter to this in the near future for PayPal Express.

This isn't a feature of the main Ninja Forms product, though, so I'm going to close this issue.

**Comment by joeguilmette** [comment]
That would be great. Client uses Rubles, so if he updates this Add-On and doesn't tell me... his customers are going to accidentally send 50x too much money. There are worse problems in the world, but this is less than ideal :)
