### ISSUE TITLE
Blank checkbox label gives a selected checkbox in preview 

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#603]
Hey

Add a list. Select Checkboxes. Remove the checkboxes label names (option 1, option 2, option 3). Be sure that the selected checkbox for each is blank.

Save and preview.
All the checkboxes will now be selected.

Btw
I happen to click list when I was supposed to click checkbox as I was going to add the sentence I have read and accepted the terms. The word terms links to a terms page. It would be nice to do something like this (adding additional options for adjusting the text):

![ninja-forms-checkboxes-linking](https://cloud.githubusercontent.com/assets/5323259/7062086/fdfd94c0-de99-11e4-90f4-c9f31155495b.jpg)

**Comment by kstover** [comment]
Hey Paal,

In your initial scenario is that each option has a value of "", or an empty string. This is the default value of any field, so they are all being selected.

Adding HTML helpers to labels might be a good idea for the future, but that can be a big undertaking.

**Comment by paaljoachim** [comment]
Hey Kevin

Probably a good idea to create a we want it list..:)
Let me know how I can help out. Not much of a developer as I have more focus on the UI part but can help out with the right amount of guidance.

Btw It is probably another good idea to have a we are now working on list. So whomever adds ideas can have a certain feel for when things are being worked on, and can have an openness to when some extra help is needed.

Anyhow I really like how Ninja Forms is slowly progressing improving in leaps along the way.

**Comment by jameslaws** [comment]
We are using milestones for this. We have them for minor and major versions. This at least let's you know what we are working on for each version.

As far as a we want it list. Issues can be placed here labeled suggestions. Discussion can happen around that issue and if it get's blessed it will be added to a milestone. Otherwise it may get closed and labeled accordingly.
