### ISSUE TITLE
Query String Vars

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#607]
A nice advanced setting would be allowing fields to be filled by query string variables. This should be a pretty easy feature to add.

**Comment by jameslaws** [comment]
This is asked for so frequently. Really makes sense to add this.

**Comment by kjohnson** [comment]
Had it on my whiteboard as an idea. Should be pretty easy.

**Comment by kjohnson** [comment]
@wpnzach suggested that we add a query string option to the default value field setting.

**Comment by jameslaws** [comment]
I think this could be like the custom default mask or something. If you select query string then a custom input would be revealed where you would enter the key name.

**Comment by wpnzach** [comment]
@jameslaws Exactly.  Instead of choosing "Custom" in the default field value, you choose "Query" and input the key name in the revealed input.

**Comment by jameslaws** [comment]
Well, at least we now know we can both describe the exact same thing in slightly different ways. :P
