### ISSUE TITLE
Range Slider issue update

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#623]
I did a search to see if Ninja Forms have had an issue in regards to range sliders. I found it and decided to blow the dust off the old issue and bring it up again. 

I decided to create a new issue instead of adding on to the following issue:
https://github.com/wpninjas/ninja-forms/issues/140
(Not sure if that was the correct choice to make a new issue in regards to updating the old.)

I have a client who is asking me to add a profit calculator with a range slider that looks something like this: 
http://www.dugnadsportalen.no/dugnadsguide/

Translation:
2. Select amount & percipients.
Select the amount the group wishes to earn kr 43 230
Amount of products to sell 330
Select amount of percipients - 30
Amount of sales per percipient. - 11.0
Amount of sales per percipient.

![screen shot 2015-04-16 at 23 08 17](https://cloud.githubusercontent.com/assets/5323259/7192230/f1e5f4d4-e493-11e4-834f-0825757cdedc.png)

or
(scroll down to Dugnadskalkulator) http://godfortjeneste.no/

![screen shot 2015-04-16 at 23 07 37](https://cloud.githubusercontent.com/assets/5323259/7192233/feb0eba6-e493-11e4-8d42-47a9d8b8dda8.png)

Sliders that show the total on the bottom. 

Btw
The second slider. Translation.
The amount of people - 10
Toilet paper. Amount of bags of toilet paper each person sells - 8
Kichen paper. Amount of bags of kicthen paper each person sells - 4
You earn 13200 kroner
This is a common thing in Norway for non profit groups and students.

Thoughts on adding something like this to Ninja Forms?

**Comment by kjohnson** [comment]
It seems like it would be simple enough to use a JS slider plugin that updates a hidden field.

Also, I do believe sliders are slated for the 3.0 release.

**Comment by paaljoachim** [comment]
Great!

**Comment by kstover** [comment]
I've added this to our internal tracker while I'm cleaning up our GitHub issues. I will evaluate re-adding it here later.
