### ISSUE TITLE
For word/character count restrictions add a minimum restriction

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#624]
With Ninja Forms, you can set a maximum word count within elements of the form. I am wondering if there was a reverse feature whereby you can set a minimum number of words required.. E.g. a textarea must have more than 100 words/ characters for successful validation and form submit?

**Comment by kstover** [comment]
I've added this to our internal tracker while I'm cleaning up our GitHub issues. I will evaluate re-adding it here later.
