### ISSUE TITLE
#bug list field radio buttons not retaining value when the value is zero

### ISSUE THREAD

**Issue by thesrc** [wpninjas/ninja-forms#639]
list field radio buttons with an option value of zero does not retain the selected value of zero if any required fields are not filled out and the form is submitted.
I fixed this by changing line 258 of list.php from
if( isset( $data['default_value'] ) AND !empty( $data['default_value'] ) )
to
if( isset( $data['default_value'] ) AND !is_null( $data['default_value'] ) )

**Comment by kstover** [comment]
That's a good catch. I think that the best fix would be to check against a string empty '' rather than NULL. That way, we have a good method to check and see if a required field isn't being filled in.
