### ISSUE TITLE
Email & Actions - Submission CSV

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#640]
I do believe that Submission CSV should be unchecked by default. Today by default it is checked.

**Comment by kstover** [comment]
It should be unchecked by default. I just tested this out, and it wasn't checked.

**Comment by paaljoachim** [comment]
Weird....I have had the same thing happen for three sites. Perhaps something happened on updating from one version to another. Well let's not use time on this for now. It is just a minor thing.
