### ISSUE TITLE
After editing page, image disappears.

### ISSUE THREAD

**Issue by devinbalram** [wpninjas/ninja-forms#650]
"A user creates a new post from the front and uploads an image. They submit and this seems to work fine. All Good.

The user then edits the page and resubmits - this time, the image no longer displays.

In addition to this, if a user has created a post on the front end and then I (as an admin) go to that post in wp-admin...the image is not stored in the metabox there. The metabox is empty. Though at this stage, the image is still correctly displayed on the front end. However as with the front end, as soon as I click update to re-save the post - the image then no longer displays on the front end."

**Comment by kstover** [comment]
Moved to private repo issues/PRs
