### ISSUE TITLE
Make password fields 100% width

### ISSUE THREAD

**Issue by sumobi** [wpninjas/ninja-forms#661]
For consistency with the other fields I've seen so far, the password fields would look much nicer if they were the same width as other field types, such as the textbox:

![screen shot 2015-04-23 at 3 25 44 pm](https://cloud.githubusercontent.com/assets/52581/7306755/41de0a56-e9cd-11e4-91d1-e160bf9acbd5.png)

Anyone oppose?

**Comment by jameslaws** [comment]
I really thought they were at one point so no objections from me. :-)
