### ISSUE TITLE
Cannot modify header information - headers already sent

### ISSUE THREAD

**Issue by jasonhendriks** [wpninjas/ninja-forms#665]
NinjaForms (welcome.php) is writing it's style header across all admin pages, not just its own.

The [codex](https://codex.wordpress.org/Function_Reference/wp_enqueue_script#Link_the_script.aculo.us_Library) says:
> ... however, this would enqueue it on all the administration screens, which often leads to plugin/core
> conflicts, **ultimately breaking the WordPress administration screens experience**. Instead, you
> should only link [the javascript] on the individual screens you need it, see the [Link Scripts Only
> on a Plugin Administration Screen](https://codex.wordpress.org/Function_Reference/wp_enqueue_script#Link_Scripts_Only_on_a_Plugin_Administration_Screen) section for an example of that.

The advice applies to enqueue_style as well as enqueue_script.

This is what's being written:

`
<style type="text/css">
img.wp-smiley,
img.emoji {
	display: inline !important;
	border: none !important;
	box-shadow: none !important;
	height: 1em !important;
	width: 1em !important;
	margin: 0 .07em !important;
	vertical-align: -0.1em !important;
	background: none !important;
	padding: 0 !important;
}
</style>`

**Comment by Dwarve** [comment]
The above <style> block is added by wordpress. To test, I just created a 100% clean install of Wordpress 4.1.1 and the text was not there. I immediately updated to 4.2.2 and it exists now. Nothing else was watched. So it is either intended or unintended by Wordpress and unrelated to Ninja Forms.

**Comment by jasonhendriks** [comment]
This block is definitely Ninja Forms:

`<style type="text/css" media="screen">
		/*<![CDATA[*/
		.nf-badge {
			padding-top: 125px;
			height: 52px;
			width: 185px;
			color: #fff;
			font-weight: bold;
			font-size: 14px;
			text-align: center;
			margin: 0 -5px;
			background: url('http://dev.wp-macpro.com/~jasonhendriks/wordpress/wp-content/plugins/ninja-forms/assets/images/nf-badge.png') no-repeat;
		}

		.about-wrap .nf-badge {
			position: absolute;
			top: 0;
			right: 0;
		}

		.nf-welcome-screenshots {
			float: right;
			margin-left: 10px!important;
		}

		.about-wrap .feature-section {
			margin-top: 20px;
		}
		.about-overview {
			padding: 20px;
		}
		.about-overview iframe {
			display: block;
			margin: 0 auto;
		}

		/*]]>*/
		</style>
`

**Comment by jameslaws** [comment]
That block would definitely be Ninja Forms. That's not the block originally posted thought so Dwarve was looking for this:

<style type="text/css"> img.wp-smiley, img.emoji { display: inline !important; border: none !important; box-shadow: none !important; height: 1em !important; width: 1em !important; margin: 0 .07em !important; vertical-align: -0.1em !important; background: none !important; padding: 0 !important; } </style>

That block, that you originally posted, is not Ninja Forms and I think that's where the confusion was.

**Comment by jasonhendriks** [comment]
my bad. cut + paste error.
