### ISSUE TITLE
Renaming a form

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#666]
Today renaming a form is somwhat difficult...

Options:
Adding rename to quick edit bar in the all forms area.

![rename-quick-edit-ninja-forms-form](https://cloud.githubusercontent.com/assets/5323259/7314043/95f312c4-ea60-11e4-9921-ce1844987d9e.jpg)

Being able to rename a form. By clicking the form title. As if it was a title of a post/page.

![rename-edit-form-ninja-forms](https://cloud.githubusercontent.com/assets/5323259/7314056/c27bdb3c-ea60-11e4-9dd5-ee1133ace105.jpg)

**Comment by kjohnson** [comment]
While renaming a form isn't the quickest task, it also isn't a frequently performed task. I, personally, would like a power user UI like an on hover inline editing. But, there is a lot to consider.

**Comment by paaljoachim** [comment]
I am just thinking that this is one part that should become more intuitive.

When you say an UI like an on hover inline editing what options would it contain? Where would it pop up?

**Comment by klhall1987** [comment]
@kjohnson is this something we would like to do for three?

**Comment by kstover** [comment]
I've added this to our internal tracker while I'm cleaning up our GitHub issues. I will evaluate re-adding it here later.

**Comment by Luke-SF** [comment]
It seems like the issue persists for the latest Ninja forms 3.1.6, renaming requires digging into the advanced display settings.

**Comment by jameslaws** [comment]
Yeah, at the moment we're ok with this convention, but may revisit in the future when more important things are off the agenda.
