### ISSUE TITLE
Adding default CSS name to Custom CSS.

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#667]
Advanced Setting -> Custom CSS

Listing the default name of each field inside the Custom CSS. Leaving it up to the user to change the default to something else that better says what the field name is.
 
![custom-css-ninja-forms-hr-field](https://cloud.githubusercontent.com/assets/5323259/7314213/87f1d582-ea62-11e4-9258-a6e8c480bce6.jpg)

Btw hr could instead be called divider.

**Comment by kstover** [comment]
I've added this to our internal tracker while I'm cleaning up our GitHub issues. I will evaluate re-adding it here later.
