### ISSUE TITLE
Addition of a Custom Callback option

### ISSUE THREAD

**Issue by Jake-Hall** [wpninjas/ninja-forms#669]
When multiple Ninja Forms are used on one page, say within named tabbed content - when the user submits the form they shouldn't have to click on the tab they were on to see the success message. (See an example on my website, http://rockstarwire.net/jobs/)

Essentially, each tab can be accessed via the ?target= parameter, so /?target=graphic-designer will open the Graphic Designer tab. When submitting a form, I wanted the tab to be by default, opened.

The easiest way to achieve this is to hook into the action parameter of the form, which currently with NinjaForms is not possible - I managed to get it working, but unfortunately had to edit two core files. I really feel this feature would be useful for more than just tabbed content - it would also allow webmasters to add link achors as a callback, so for a form that is below the fold can be displayed with very little effort required by webmasters and devs.

The files that required tweaking:

- ninja-forms\includes\admin\pages\ninja-forms\tabs\form-settings\form-settings.php
- ninja-forms\includes\display\form\open-form-tag.php

and the changes made:

On line 97 of form-settings.php, addition of the following form setting:

`array(
				'name' 				=> 'callback',
				'type' 				=> 'text',
				'desc' 				=> '',
				'label' 			=> __( 'Custom Callback', 'ninja-forms' ),
				'display_function' 	=> '',
				'desc' 				=> __( 'Allows you to set a custom callback for the form', 'ninja-forms' ),
				'default_value' 	=> "",
			),`

and on line 9 of open-form-tag.php:

`$callback = Ninja_Forms()->form( $form_id )->get_setting( 'callback' );`

and editing line 48, 
`<form id="ninja_forms_form_<?php echo $form_id;?>" enctype="multipart/form-data" method="post" name="" action="<?php echo $url . $callback;?>" class="ninja-forms-form<?php echo $form_class;?><?php echo $hide_class;?>">`

to add the custom callback to the action parameter of the form tag.

**Comment by kjohnson** [comment]
Couldn't you use a Redirect in the Emails & Actions tab to the url with the query parameters?

**Comment by Jake-Hall** [comment]
Problem with that is it will just redirect the user back to the form without the success message, so all they will see is the form they just filled out and would probably assume it didn't send, refilling the form.

**Comment by kstover** [comment]
I'll do some more research into this, but I think that the best solution would be to add a filter for the action. That way it would be easy to append whatever querystring variables you need.

**Comment by Jake-Hall** [comment]
> but I think that the best solution would be to add a filter for the action.
But would that not mean you can only have one for all forms setup?

**Comment by kstover** [comment]
Nope. The filter would fire for every form and pass along the form id.

**Comment by kstover** [comment]
Since you know what your querystring is going to be every time, you'd just look for it and change it at every filter based upon the form id.

**Comment by Jake-Hall** [comment]
Does that not seem like a lot more work than necessary? Whilst yes, it would work - it would also require manually updating every time a new form is added (if I am following you here). If you went down the route of adding it as an option within form settings, it would be way more user friendly and require less fiddling.

There is issue 415 that either would solve, I just get the feeling the filter would require far more fiddling for a user.

**Comment by kstover** [comment]
Yes, the filter would require more work from a user's perspective, but there are two reasons that I suggested a filter:

1) 80% of users aren't going to use this setting. It has a very niche use-case. 
2) I can foresee it causing us support issues when it's used improperly by users who aren't developers.

There are several things that we don't include as options because they wouldn't be used by a majority of our users. 

Our options section is already fairly cluttered, and, while we haven't always done a good job at it, our design goal is the same as WordPress: create decisions, not options. 

I hope that helps explain a bit why I suggested the filter route.

**Comment by Jake-Hall** [comment]
kstover, yeah that's understandable. It is pretty niche, and I agree with the design ethos. I look forward to whatever solution you do come up with, so then I don't have to edit core files!

**Comment by kjohnson** [comment]
It could be packaged into a custom plugin. I have a few re-useable features that I keep in small custom plugins for projects.

**Comment by kstover** [comment]
In version 3.0, every form submits via AJAX, so this shouldn't be an issue as the page doesn't reload.
