### ISSUE TITLE
Auto preview in the Edit Form screen

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#674]
Auto preview of a form in the edit form screen.

Moving the cursor outside of the active fields area one sees a preview of the form.

![edit-form-preview](https://cloud.githubusercontent.com/assets/5323259/7440999/0c2b4a14-f0d4-11e4-9616-3c4f32053e7f.jpg)

Moving the cursor inside the active fields area one gets the standard fields list.

![edit-form-preview2](https://cloud.githubusercontent.com/assets/5323259/7441012/73d3c236-f0d4-11e4-9a3a-bb1b8c70e082.jpg)

**Comment by jameslaws** [comment]
I don't think this is something we will likely do just because the reason we do the preview the way we do is so people can see what the firm will actually look like on their site. Simulated previews like this are much less useful as they cause confusion when the form looks very different live.

**Comment by jameslaws** [comment]
That being said we are about to have some larger discussions around a new UI so we'll keep this has part of the discussion.

**Comment by paaljoachim** [comment]
Will this be an internal discussion or can others contribute to the discussion as well?
I have a lot more thoughts around the UI aspect of Ninja Forms. Some I have already shared other thoughts I have not shared yet.

Perhaps have a discussion in a Ninja Forms Slack channel.... where a lot of people can share their thoughts.

**Comment by jameslaws** [comment]
Perhaps a little of both. We're pursuing hiring a company that specializes in UI/UX design to assist with reworking the entire form builder screen and process.

**Comment by paaljoachim** [comment]
I will think out some additional solutions and continue to share them here at Github. Then you can bring it along to the internal and external discussion. I might even make a wireframe video showing some of the possibilities that I envision.
