### ISSUE TITLE
Custom Field Wrapper Class adds unnecessary '-wrap'

### ISSUE THREAD

**Issue by coryshaw1** [wpninjas/ninja-forms#676]
In [includes/display/fields/display-fields.php on line 209](https://github.com/wpninjas/ninja-forms/blob/master/includes/display/fields/display-fields.php#L209) there is what seems to be an unnecessary renaming of a user's custom css class for a field wrapper. 

```php
if($custom_class != ''){
	$custom_class = str_replace( ' ', '-wrap ', $custom_class );
	$field_wrap_class .= ' '.$custom_class.'-wrap';
}
```

I understand that you would like to add a space between the already declared `$field_wrap_class`, but what is the point of renaming a user's pre-defined CSS class by adding '-wrap' to the end of it? Why isn't it just as follows?

```php
if($custom_class != ''){
	$field_wrap_class .= ' '.$custom_class;
}
```

I would make a pull request, but I wanted to see if there was any reasoning behind adding the '-wrap' suffix.

**Comment by kstover** [comment]
@jameslaws would have to chime in here, but I think that the purpose is that the custom CSS name is applied to the actual element, and this would let you target that custom wrapper more easily.

**Comment by jameslaws** [comment]
There is a valid reason. The class is added unaltered to the input field itself. This is so the element can be targeted by JS or CSS. But you may also want to be able to target stuff within the wrapping div with a custom class name as well, such as the label and other elements. If you apply that same unaltered class to the wrap as well then there will be JS and styling issues. 

Eventually we will change the by giving users the ability to add a class name to the wrap, label, and field separately.

**Comment by coryshaw1** [comment]
Thank you for the responses. I didn't notice that it was added on the field itself. The ability to add a class name to the wrap, label, and field separately would fix everything. And I look forward to that feature implemented.

I'll just hook onto `ninja_forms_field_wrap_class` for the time being, and preg_match my custom classes to remove '-wrap'.

**Comment by johannesmutter** [comment]
Commenting it out helps for a while (line 209)

`	if($custom_class != ''){
		/* $custom_class = str_replace( ' ', '-wrap ', $custom_class ); */
		$field_wrap_class .= ' '.$custom_class.' ';
	}
`

I would suggest an option to add separate classes for the wrapper, the label, the input field, the description and things like “this field is required”. There should also be an option to remove the wrapper and output just the plain form.

**Comment by marekmaurizio** [comment]
Really an odd idea. What if I need a bootstrap class there?

**Comment by ethanbeyer** [comment]
I'm with @marekmaurizio - there is no possible way to add, say, `col-sm-6` there and have it work. I've found a workaround by using the *Ninja Forms Blocks* plugin, but that is resulting in extremely slow output of forms, and a very cluttered Field Editing page.

**Comment by kjohnson** [comment]
Separate class name settings (for element and wrapper) have been added in v3.
