### ISSUE TITLE
Cannot create conditional statement for Star Rating Field

### ISSUE THREAD

**Issue by devinbalram** [wpninjas/ninja-forms#680]
Forms 
Select Form
Add Star Rating Field
Add another field - then conditional settings, when you try to change value, the conditional statement looks like : 

If Star Rating is (Equal, Not Equal, Less than, Greater than)-then nothing shows-.

**Comment by musamamasood** [comment]
I am getting same issue with Ninja form 3.0.27 and Ninja Forms - Conditional Logic 3.0.11, Could you please give me direction how to fix that issue?

**Comment by musamamasood** [comment]
Could you please help with this? @kstover
