### ISSUE TITLE
Make preview page published and private instead of draft mode

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#684]
The 10,000 results that show when "ninja_forms_preview_page" is searched is indicative of users incorrectly publishing their preview page.  A user recommended changing these to published private pages to prevent them from showing in a users site map as a possible resolution.

**Comment by kjohnson** [comment]
Would it work to dynamically generate a temporary page at time of preview, instead of using the WP page CMS?

**Comment by wpnzach** [comment]
I think this would have the unintended effect of creating artificially high page numbers on the site.  Is there a way to do it without a dedicated page at all somehow?

**Comment by kjohnson** [comment]
That is what I was getting at. I'm not sure of how it would work, but I've been wanting to look into it.

**Comment by kjohnson** [comment]
Moot with v3 preview system.
