### ISSUE TITLE
Multi-select fields not working as required

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#688]
2 users reported that Multi-select fields will process without selections even if the required option is set. I created a simple form containing a list that had 3 multi--select options to confirm this.
Steps to reproduce:
New form
create list
change list type to multi-select
check required under the restriction settings
add submit button
save form and preview
select nothing and submit the form

The form processes without notifying the user that the field is required. When the list is changed to check boxes the required option works properly.

**Comment by kstover** [comment]
Not an issue in version 3.0.
