### ISSUE TITLE
Disabling enter key on entire DOM instead of only NF

### ISSUE THREAD

**Issue by tripflex** [wpninjas/ninja-forms#701]
You are disabling the enter key on the entire DOM for any form, instead of your specific case scenario, which has caused multiple issues for multiple clients.

https://github.com/wpninjas/ninja-forms/blob/master/js/dev/ninja-forms-admin.js#L185

You should be attaching the event handler to something specific to your plugin not to the entire DOM.

**Comment by kjohnson** [comment]
@kstover is there someplace particular that you are trying to stop submission on `enter`?

I can add a `.nf-disable-enter` class and attach it where it is needed.

**Comment by tripflex** [comment]
As long as the script is only enqueued on NF pages there shouldn't be any issues (unless someone is using some type of search input box form in admin menu, or something weird) ... looks like the latest update for the enqueue has fixed my problems:

https://github.com/wpninjas/ninja-forms/commit/42841dc9449eef978ecfb2905f8396b7fd55e040

Just an FYI the major problem was preventing searching on plugin repo because JS was loaded on `plugin-install.php` page, but this has been fixed :+1: 

Thanks guys!
