### ISSUE TITLE
Javascript dependencies in frontend

### ISSUE THREAD

**Issue by jonalvarezz** [wpninjas/ninja-forms#706]
Hi!

In the file: `includes/display/scripts.php` the action `ninja_forms_display_js` enqueue scripts even if the form has not AJAX enabled. It would be nice if ajaxForm related scripts are not included when AJAX is disabled.

Also, the scripts with handle name `ninja-forms-display`, includes `backbone` and `underscore` as dependencies in the frontend. I checked the code and backbone is only used in the admin. It's really necessary to include it in the frontend?

**Comment by jameslaws** [comment]
This will not be an issue in THREE.
