### ISSUE TITLE
Issue with translation

### ISSUE THREAD

**Issue by juniormayhe** [wpninjas/ninja-forms#710]
Ninja forms javascript files "word-and-character-counter.js" and "word-and-character-counter-min.js" are not getting the translated sentence for "character(s) left". 

In other idioms, this sentence can have more parentesis such as 
"caractere(s) restante(s)" -> português
"carácter(es) restante(s)" -> español
"caractère(s) restant(s)" -> français
"übrig(en) Charakter??" -> german

To put that in portuguese I had to tweek word-and-character-counter-min.js as follows:

1) set msg attribute in default array:
var n = { /* minified name for "default" array */
  // {char || word}
  type: 'char',
  // count {up || down} from or to the goal number
  count: 'down',
  // count {to || from} this number
  goal: 140,
  // Show description of counter
  text: true,
  // Specify target for the counter
  target: false,
  // Append target, otherwise prepend
  append: true,
  // Provide translate text for counter message
  translation: '',
  // Custom counter message
  msg: 'caractere(s) restante(s)' //finally!!!

2) add a line in setMsg function:
setMsg: function() {
   t.msg=n.msg /*where n is minified name for "default" array*/;

Maybe messages supposed to be fired through javascript could be in plugins admin page: http://your-page/wp-admin/admin.php?page=ninja-forms-settings&tab=label_settings

Or we could have versions of javascript in other languages:

word-and-character-counter-min.pt_BR.js
word-and-character-counter-min.es_ES.js
word-and-character-counter-min.fr_FR.js
and so on

**Comment by jameslaws** [comment]
This will be fixed in THREE
