### ISSUE TITLE
Check ignore_user_abort enabled before running

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#719]
Check that the "ignore_user_abort" is enabled by the host before running.  Some server configurations have this functionality disabled in their php.ini and it generates error text as below:

Warning: ignore_user_abort() has been disabled for security reasons in
/wp-content/plugins/ninja-forms/includes/admin/upgrades/class-upgrade-handler.php
on line 32

Warning: session_start() [function.session-start]: Cannot send session
cache limiter - headers already sent (output started at
wp-content/plugins/ninja-forms/includes/admin/upgrades/class-upgrade-handler.php:32)
in
wp-content/plugins/ninja-forms/ninja-forms.php
on line 664

Warning: ignore_user_abort() has been disabled for security reasons in
/wp-content/plugins/ninja-forms/classes/step-processing.php
on line 58

Warning: ignore_user_abort() has been disabled for security reasons in
/wp-content/plugins/ninja-forms/classes/step-processing.php
on line 58

**Comment by klhall1987** [comment]
@kjohnson @wpnzach Is this something that needs to be added three?

**Comment by kstover** [comment]
This has created at least two support tickets that I know of.
