### ISSUE TITLE
Sequential Number

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#722]
Because the form object is cached in a transient, the seq_num value isn't being properly updated.

**Comment by jameslaws** [comment]
This still isn't working. Just tested with an up to date Develop branch and all submissions come through as zero: https://db.tt/UiK9bG1I

**Comment by jameslaws** [comment]
wrong issue I think. Investigating.

**Comment by jameslaws** [comment]
Ok, the correct issue is actually #2001
