### ISSUE TITLE
Hide fields not in use

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#726]
Hey

Hiding fields. This time (as I have mentioned user selected hiding of fields earlier) 
I am thinking about hiding fields that might not be used. 
Perhaps having an eye next to the field name (or another place). 
Click the eye to close the eye to hide the field.
While building a form one experiments with the fields. Choosing to hide/show fields based on figuring out how to build the form in an optimum way.

**Comment by jameslaws** [comment]
@kstover, Thoughts?

**Comment by kstover** [comment]
I've added this to our internal tracker while I'm cleaning up our GitHub issues. I will evaluate re-adding it here later.
