### ISSUE TITLE
Cross site scripting issue on "Default Value" -> Querystring variable

### ISSUE THREAD

**Issue by bderemon** [wpninjas/ninja-forms#731]
There seem to be an issue when setting a Field Default Value -> Querystring variable -> "my-param-name"
When adding a field to the form, going to advance settings and then adding a Default value based on a Querystring variable.

This is working well, but on the live form on the WordPress website, modifying the value for "my-param-name" directly in the url address bar, allow to add content that is not escaped and then creating injection of code.

**Comment by kstover** [comment]
Hmm. I seem to have fat-fingered my commit. It should have closed 732, not this issue.

**Comment by kstover** [comment]
That was the actual closing.
