### ISSUE TITLE
Remove arguments from refresh_plugin_settings( $old_value, $value )

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#735]
Arguments are no longer used and should be removed.  Line 722 of main plugin file

	public function refresh_plugin_settings( $old_value, $value ) {
		self::$instance->plugin_settings = self::$instance->get_plugin_settings();
	}

**Comment by kjohnson** [comment]
Do these need to be kept for backwards compatibility? If this is used anywhere with arguments, then removing them from the function declaration will throw an error.
