### ISSUE TITLE
Error from Cleverreach

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#737]
I am getting the following errors when I have the Cleverreach plugin activated. 

Notice: Undefined variable: forms in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/ninja-forms-cleverreach/includes/class-nf-cleverreach.php on line 330

Notice: Undefined variable: forms in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/ninja-forms-cleverreach/includes/class-nf-cleverreach.php on line 348

### Environment ###

Home URL:                http://localhost:8888/wordpress
Site URL:                http://localhost:8888/wordpress
Ninja Forms Version:     2.9.18
WP Version:              4.2.2
WP Multisite Enabled:    No
Web Server Info:         Apache/2.2.29 (Unix) mod_wsgi/3.4 Python/2.7.8 PHP/5.6.7 mod_ssl/2.2.29 OpenSSL/0.9.8zd DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.8 Perl/v5.20.0
PHP Version:             5.6.7
MySQL Version:           5.5.42
PHP Locale:              decimal_point: .thousands_sep: int_curr_symbol: currency_symbol: mon_decimal_point: mon_thousands_sep: positive_sign: negative_sign:
WP Memory Limit:         40 MB
WP Debug Mode:           Yes
WP Language:             Default
WP Max Upload Size:      32 MB
PHP Post Max Size:       32 MB
Max Input Nesting Level: 64
PHP Time Limit:          30
PHP Max Input Vars:      1000
SUHOSIN Installed:       No
SMTP:                    localhost
smtp_port:               25
Default Timezone:        Default timezone is UTC

### Plugins ###

Installed Plugins:       Ninja Forms - AWeber by Kathy Darling version 1.2
                         Ninja Forms - Batchbook CRM by Stuart Sequeira version 1.2
                         Ninja Forms - Capsule CRM by Stuart Sequeira version 1.5.1
                         Ninja Forms - Conditional Logic by The WP Ninjas version 1.3.9
                         Ninja Forms Add Datepicker Options by WPN Zach version 1.0
                         Ninja Forms - Elavon Payment Gateway by Stuart Sequeira version 1.3
                         Ninja Forms - File Uploads by The WP Ninjas version 1.4.5
                         Ninja Forms - Front-End Editor by The WP Ninjas version 1.0.7
                         Ninja Forms - GetResponse by Aman Saini version 1.2
                         Ninja Forms - iContact by Aman Saini version 1.0
                         Ninja Forms Insightly CRM by Stuart Sequeira version 1.5.1
                         Ninja Forms - Layout & Styles by The WP Ninjas version 1.2.7
                         Ninja Forms - Mad Mimi by Patrick Rauland version 1.0.0
                         Ninja Forms - MailPoet by Patrick Rauland version 1.1.2
                         Ninja Forms - Modal by The WP Ninjas version 1.0.2
                         Ninja Forms - Multi-Part Forms by The WP Ninjas version 1.3.4
                         Ninja Forms - PayPal Express by The WP Ninjas version 1.0.10
                         Ninja Forms - PDF Form Submissions by Patrick Rauland version 1.3.3
                         Ninja Forms - Pushover by Patrick Rauland version 1.0.3
                         Ninja Forms - SalesForce CRM by Stuart Sequeira version 1.1.1
                         Ninja Forms - Save Progress by The WP Ninjas version 1.2.1
                         Ninja Forms - Sendy Integration by Aman Saini version 1.0.2
                         Ninja Forms - Signatures by wpnzach version 0.1
                         Ninja Forms - Slack Notifications by Nikhil Vimal version 1.0
                         Ninja Forms - Stripe by The WP Ninjas version 1.0.8
                         Ninja Forms - Text Message Notifications by Patrick Rauland version 1.1
                         Ninja Forms - User Analytics by Patrick Rauland version 1.2.3
                         Ninja Forms - White Label by Patrick Rauland version 1.0.2
                         Ninja Forms - Zapier by Fatcat Apps version 1.1.2
                         Ninja Forms - Zoho Creator by Stuart Sequeira version 1.1
                         Ninja Forms - Zoho CRM by Stuart Sequeira version 1.7
                         Ninja Forms by The WP Ninjas version 2.9.18

**Comment by kstover** [comment]
This should be placed in the cleaver-reach git repo, not the core plugin. @klhall1987
