### ISSUE TITLE
Delete form submissions when a form is deleted

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#744]
When a form is deleted, the user is prompted and warned that deleting the form is irreversible.   We should also warn the user that submissions will be unrecoverable and delete submissions when the form is deleted.  Currently, despite the warning, users are deleting their forms and creating support tickets to gain access to the submissions again since they are still visible in the DB.  A clearer warning to users and deletion of form submissions when a form is deleted (since there's no way within Ninja Forms to recover them anyway) would be a good solution.

**Comment by jameslaws** [comment]
How do we want to handle this in THREE.

**Comment by kjohnson** [comment]
Could we not delete submissions? They are saved to a custom post type, so can't they just stay there?
