### ISSUE TITLE
NF_WP_Session Cookie always Set

### ISSUE THREAD

**Issue by alistek** [wpninjas/ninja-forms#749]
Hello,

The most recent release, v2.9.18, introduced a version of WP_Session to alleviate the PHP $_SESSION concern in ticket #370. Although I certainly prefer the use of WP_Session, the same issue is there. On every page, Ninja Forms is setting a NF_WP_Session cookie. Therefore any caching, be it Varnish or NGINX FastCgiCache, does not work without stripping those cookies off entirely. It should only make a new cookie on the actual pages where a form is used. Since on "nf_init", it creates an instance of the WP_Session library, it will make a cookie everywhere.

Would it be possible to only create the cookie's on pages that actually had forms or even make it optional for cookie creation at all, since many forms are simple enough not to need it? Thanks!

-Adam

**Comment by kstover** [comment]
Hey Adam,

The challenge is that we don't know a form is on a page until the page itself loads. The session variables are only really used if you have a redirect page or use the PayPal extension.  A good compromise may be an option to turn off session altogether.

**Comment by alistek** [comment]
I completely understand, I was looking at that too as to a good approach. I was actually attempting to do a remove_action on nf_init so it only loaded on admin and select pages but that didn't work so well. I would be ok with the option for the session to be optional. Thanks!

-Adam

**Comment by frnkoc** [comment]
Hi. Just want to ask if you found a solution to disable the NF_WP_Session cookie? I just found my SQL slowing down and crashing. I found over 3 million entries in the wp-options created by the session cookies from ninja forms.

**Comment by alistek** [comment]
Hello,

That actually prompted me to go look at the DB since I've had strange random slowdowns at times. I found about 69K entries in mine, the majority are _wp_session_###... option names with "nf_transient_id" in the option_value. It looks like these aren't being cleared and new one's being created.

I happen to use the wp_session for another feature on my site and I see that it has created about an equal number of entries. This is a problem with wp_session more than it is with Ninja Forms in particular. Either we both aren't clearing it correctly or the code isn't handling it right. I will look into what it's actually doing to see if there is a better way.

-Adam

**Comment by kstover** [comment]
Hey @alistek @frnkoc,

We're working on something that will delete expired transients, although I'm not sure that that will take care of the wp_session items. I'm going to ping @pippinsplugins to see if he has any experience with this in EDD. Thanks for the deep dive on this. If you can get something together that clears them after they've expired, I'd definitely be interested in getting it into the plugin.

**Comment by frnkoc** [comment]
This is what the Rackspace linux administrator just sent me a couple of minutes ago:

Hi Francisco,

I had to temporarily stop MySQL and then Apache because your server was becoming unresponsive.

The reason for the very slow DB access is because sovsoc2014.wp_options has a row count of nearly 3 million:

mysql> select count(1) from sovsoc2014.wp_options;
+----------+
| count(1) |
+----------+
|  2813250 |
+----------+
1 row in set (26.45 sec)


Of these, most of the rows are _wp_session_ entries created by your Ninja Forms plugin. Here's an example of one such entry:

   option_id: 2095306
 option_name: _wp_session_a6a95dd588d313a6ed71a7fbb3916032
option_value: a:1:{s:15:"nf_transient_id";s:10:"AFaIkpkZPG";}
    autoload: no

As you requested, I've deleted the _wp_session entries:

mysql> delete from sovsoc2014.wp_options where option_name like '_wp_session%';
Query OK, 2800556 rows affected (48.30 sec)


It looks like they are quickly coming back, though:

mysql> select count(1) from sovsoc2014.wp_options where option_name like '_wp_session%';
+----------+
| count(1) |
+----------+
|      192 |
+----------+
1 row in set (0.00 sec)

At this point, your server's load is hovering around 2.0 and still dropping. The sites are much more responsive and I am no longer seeing issues. You will still need to ensure that your application/plugin doesn't fill wp_options again.

**Comment by alistek** [comment]
Working on it now to try and figure out what's exactly happening. I have wp_cron turned off and am doing it by a real Cron job and I'm beginning to think that's not working right as PHP is having a hard time completing. I am wondering if in my case, the code that removes the old sessions (by default I think the WP_Session code said 3600 min) is never finishing or truly running. @frnkoc do you have this same setup or just using regular wp_cron? Thanks @kstover

-Adam

**Comment by frnkoc** [comment]
I honestly don't know how to answer that question @kstover.

**Comment by alistek** [comment]
So, by default WP_Session creates an hourly wp_cron job called "wp_session_garbage_collection". This cleans up old sessions, but I don't see a corresponding one for Ninja Forms in my cron list. The code they use is:

`wp_schedule_event( time(), 'hourly', 'wp_session_garbage_collection' );`

This ultimately calls:

`WP_Session_Utils::delete_old_sessions( $batch_size );`

The batch size is set at 1000, so as not to overload the DB if there is a really high number of calls.

It gets the keys to delete by doing a DB select looking for:

`LIKE '_wp_session_expires_%`

In the option_name. This should cover both regular WP_Session calls and also the Ninja Forms calls, since only the data is different in the option_value.

I think in my case, WP_Cron wasn't properly running, I am trying a different method and making the expiration time much lower to see if it clears the DB properly. I'll let you know. Thanks!

-Adam

**Comment by frnkoc** [comment]
Let me know if you find a solution. I installed the WP Crontrol plugin to see the current cron jobs and i see the "ninja_forms_daily_action" that looks for an updated version and also the wp_session_garbage_collection" but i don't see the "wp_session_cleanup" listed.

![cronjobs](https://cloud.githubusercontent.com/assets/7507695/8755112/77ecc3c4-2c96-11e5-8360-6b74b08cb8bc.jpg)

**Comment by alistek** [comment]
The "wp_session_garbage_collection" should be cleaning up the sessions but it doesn't appear to be working. It looks like the cron job is running for me but just not clearing the sessions, though I'm working on figuring out exactly why that might be.

-Adam

**Comment by kstover** [comment]
Hey guys, I appreciate all your help in digging into this. This isn't something that I can recreate locally, so I need all the help with this that I can get. @frnkoc @alistek

**Comment by frnkoc** [comment]
For now i just deleted them all manually but they come back at a high speed again.

delete from db.wp_options where option_name like '_transient%';

**Comment by frnkoc** [comment]
i apologize this is the sql quuery i'm running:
delete from db.wp_options where option_name like '_wp_session%';

**Comment by alistek** [comment]
This looks like a strange case, so I can run the SQL that the delete_old_sessions code would run and it brings back 812 rows for me that were created in the past 2 hours or so. It's deleting the keys based on this:

```
$now = time();

if ( $now > $expires ) {
 .... more code...
}
```

At least with the 812 keys created in the past two hours none of them will meet that criteria at least not for a while.

I am going to see if some drop off (hard to tell) when it runs correctly but it's looking more that just a huge amount of sessions are being created faster than the cleanup can handle it. This may be case where setting the expiration time down on a higher traffic site might help or finding ways for the sessions to not be created (i.e. if bots checking the site are creating sessions also).

-Adam

**Comment by frnkoc** [comment]
I have high traffic sites sovereignsociety.com, dentresearch.com, economyandmarkets.com and thesovereigninvestor.com and all of them have the same issue with the wp_sessions. I get all kind of traffic: legitimate, bots and many hack attempts too.

**Comment by kstover** [comment]
@frnkoc Would you be willing to give me some admin access on Monday? I'd like to investigate this, but on my local machine I can't reproduce the build up of wp_session entries.

**Comment by frnkoc** [comment]
yes i would like to solve this issue. i have good use of the ninja forms in my sites. how do i send you my email so we can do this on monday.

**Comment by kstover** [comment]
You can shoot me an email: kevin[at]wpninjas[dot]com.

We'll need wp-admin, phpmyAdmin, and FTP access. Those three will let us really dig into what's going on.

**Comment by alistek** [comment]
I will say in my case, it's looking like crawlers are hammering my site too much and since I have an event driven site with around 8k events on there it just can't keep up with expiring them fast enough.

I blocked one particular user agent that was hammering my site "SEOkicks-Robot" and I decreased the session expiration time:

`add_filter( 'wp_session_expiration', function() { return 60 * 10; } );` 

I'll see if this has a positive effect on the growth of the sessions. Please note that the default is 24 min. from last time the session was active.

-Adam

**Comment by kstover** [comment]
@alistek Did that have any impact? I think that if we throttle the life of the sessions, it will make a big difference.

I'm currently working with @frnkoc to troubleshoot their site. I can confirm that the sessions are being removed properly for me locally, but I'm not creating them faster than they are being deleted, either.

**Comment by alistek** [comment]
I agree with you, unfortunately I am not having much luck with that. Not sure why but the times are not matching right. Even though they are supposed to be ~24 min. expiration times, based on my calculations the times are more like 24 hours which doesn't seem at all right and hence why nothing is ever really expiring very quickly. I am wondering if there is some PHP time mismatch, everything on mine is set to Central Time but clearly something isn't calculating right. I will be troubleshooting more tonight as the weekend got away from me.

-Adam

**Comment by kstover** [comment]
@alistek Thanks for the report. Can you try editing the core file where the time is being set to make sure that your filter is applied properly? It's in ninja-forms/classes/session.php, lines 122 and 133.

**Comment by alistek** [comment]
Will do, I'll let you know how that goes!

-Adam

**Comment by kstover** [comment]
Hey @alistek. I've done some testing, and this what I came up with for lines 114-135 of that file:

`
/**
	 * Force the cookie expiration variant time to 23 minutes
	 *
	 * @access public
	 * @since 2.9.18
	 * @param int $exp Default expiration (1 hour)
	 * @return int
	 */
	public function set_expiration_variant_time( $exp ) {
		return 60 * 23;
	}
	/**
	 * Force the cookie expiration time to 24 minutes
	 *
	 * @access public
	 * @since 2.9.18
	 * @param int $exp Default expiration (1 hour)
	 * @return int
	 */
	public function set_expiration_time( $exp ) {
		return 60 * 24;
	}
`

That sets it to 23 and 24 minutes respectively. I think we could go down lower if we needed. When you're testing, make sure that you test form submissions in an incognito window. If you have a browser cookie set, it will just update that cookie rather than setting a new time.

**Comment by after8** [comment]
Hi kstover, just wanted to let you know, that we have the exact same problem as described by frnkoc. Our website was slowing down and in the end didn't show anything at all. We had about 3 million entries in wp_options and it was about 2.7GB big. I put your code from you last entry in ninja-forms/classes/session.php now and observe what's happening. Thank you for your effort

**Comment by after8** [comment]
Unfortunately wp_options still running full of _wp_session_. Today it was 2GB and after deleting _wp_session_ it was only 20MB.
Do you have any further suggestions? Have you been successful with your investigations in @frnkoc site?

**Comment by kstover** [comment]
Just wanted to drop in and say that with the latest version, you shouldn't see as many wp_session values set. If you delete them, they shouldn't re-appear unless a form is actually submitted.

**Comment by craiglondon** [comment]
I think this fix is working!   Thank you!
