### ISSUE TITLE
Error after upgrade, please help fast

### ISSUE THREAD

**Issue by aexol** [wpninjas/ninja-forms#754]
PHP Fatal error:  Call to a member function get() on a non-object in /home2/aexolcom/public_html/trinter/wp-content/plugins/ninja-forms/includes/display/form/display-form.php on line 45

**Comment by kstover** [comment]
Hey @aexol this isn't the best place to get support. If you submit a ticket at our site: http://ninjaforms.com, we'll help you get it taken care of quickly. This isn't something that I'm aware of anyone else seeing.

**Comment by aexol** [comment]
Ok I've just wrote you an e-mail it happened after upgrade

**Comment by aexol** [comment]
SOLVED - It happened after auto update from wordpress admin. I erased all the files and copied files from github to plugin directory. Now everything seems to be OK. Check auto-update.
