### ISSUE TITLE
Reply-To does not have a Name

### ISSUE THREAD

**Issue by isleshocky77** [wpninjas/ninja-forms#755]
Would be great to have the ability to specify a "Reply-To" name. If one is not specified it should use the "From Name" field.

**Comment by klhall1987** [comment]
There is a "Replay-To" field in the email action under the "Advanced Settings" dropdown.

**Comment by isleshocky77** [comment]
@klhall1987 Correct, but you don't have a way of adding a name to it, only the "Reply-To" email address.  This causes an issue for me because we use your forms to send mail to a CRM system. It creates an issue using either the "Reply-To" or the "From".  The "From" is from our system and and the "Reply-To" is the customer.

But because you can't add a name to the "Reply-To" the system does not put a correct name on the ticket.

i.e.
From: "Company Support System" <do-not-reply@company.exmple.org>
Reply-To: "John S. Customer" <john.smith@example.org>

The Ninja Form will only allow me to have:

From: "Company Support System" <do-not-reply@company.exmple.org>
Reply-To: john.smith@example.org

So when the system reads the "Reply-To" header, it doesn't know a name for it. I've tried to figure out work-arounds; however, currently it doesn't seem like one exists besides hacking the code to make this work - I'd rather not do that.

**Comment by isleshocky77** [comment]
@klhall1987 Any change of having this re-opened? I have to keep a fork of your project to apply one commit every time you have a release. (b5e490d)  If you'd like I can send a PR.
