### ISSUE TITLE
cannot translate ninja forms field and messages

### ISSUE THREAD

**Issue by koraysels** [wpninjas/ninja-forms#756]
I use polylang for translations on a multi language website. 

I cannot change any of the ninja forms fields stringtranslations ... even if I explicitly added them like below.. 
what is wrong? and why doesn't it show up in the polylang stringtranslations panel like other plugins ? (e.g. twitter widget, yoast SEO, ...)

```
function stash_translate_ninja_forms($data, $field_id)
{

    if (isset ($data['default_value'])) {
        $default_value = $data['default_value'];
    } else {
        $default_value = $data['label'];
    }

    pll_register_string($data['label'], $default_value);

    return $data;
}

add_filter('ninja_forms_field', 'stash_translate_ninja_forms', 10, 2);
```

this doesn't do the trick for me.. still no string translations for ninja forms appear in the polylang panel.. :(

**Comment by jameslaws** [comment]
We don't know anything about the polylang plugin. All our translations are handled through WordPress.org: https://translate.wordpress.org/projects/wp-plugins/ninja-forms

**Comment by kstover** [comment]
I apologise for coming back to this ticket years later. I'm going to close it; if it's an issue, feel free to open it again with current details.
