### ISSUE TITLE
Backbone/Underscore dependency usage?

### ISSUE THREAD

**Issue by farneman** [wpninjas/ninja-forms#758]
It appears Backbone and _ are always loaded on the frontend. In what scenarios are those actually used? From a casual glance at the code it appears they're only used in the admin?

**Comment by pbowyer** [comment]
They're necessary to get the ninjaforms AJAX form submission to work. Why it depends on them I haven't yet investigated, but it'd be great to remove the dependency and stop loading this additional JS on the frontend.

**Comment by pbowyer** [comment]
Related: https://github.com/wpninjas/ninja-forms/issues/706

**Comment by jameslaws** [comment]
In our current version we don't include these libraries at all. We will however in THREE.
