### ISSUE TITLE
Lists with "other" should offer a text box for further info

### ISSUE THREAD

**Issue by helgatheviking** [wpninjas/ninja-forms#768]
Suggestion: I think this is a pretty common scenario, where you expect the majority of answers to fall into certain categories, but you still want to collect data about the outliers.

As an example:

Select fruit:
- [ ] Apple
- [ ] Banana
- [ ] Cherry
- [ ] Date
- [ ] Other .
- - [ textbox here ]

Right now this isn't possible with Lists.

**Comment by jameslaws** [comment]
This will be in version THREE

**Comment by helgatheviking** [comment]
:+1: When will we need to update our extensions? And will you have any good examples you can share because I am very, painfully new to JS frameworks?

**Comment by jameslaws** [comment]
As soon is core is in beta (we're thinking 2 to 3 weeks), we will be working with all devs to update add-ons. We will also be writing extensive docs over at developer.ninjaforms.com. With WordPress moving the way of JS and us being on the cutting edge of that transition, we will be doing everything we can to make that transition smooth for devs new or less experienced with JS.

**Comment by helgatheviking** [comment]
Cool! I look forward to learning JS from Ninja Forms.
