### ISSUE TITLE
Multiple forms on one page success messages

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#770]
When you have multiple forms on a page and don't use AJAX submissions, success messages cause an empty success div to show up for the other forms.

**Comment by kstover** [comment]
My initial fix wasn't working for AJAX submissions. This needs to be a more thoroughly tested fix.

**Comment by klhall1987** [comment]
Is this something that will be addressed in three?

**Comment by jameslaws** [comment]
We have another ticket on this for discussion.
