### ISSUE TITLE
Add option to trigger form actions from Submissions page

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#772]
With the increasing number of actions being deployed it would be helpful for many users to reprocess those notifications at a time other than form processing.  For example, lets say a submission comes in but the email was not sent for some reason.  It would be ideal for a user to be able to click that submission (or even more with a bulk action) and trigger the email to be sent again. 

As a dream use case, if a user got the webhooks extension after already receiving several submissions, the ability to bulk select the submissions and run that webhook on all of them for either testing puroses or to simply bulk send the data would be a really great feature that all extensions with actions would benefit from.

**Comment by helgatheviking** [comment]
SO. MUCH. THIS. :100: WooCommerce does a nice job of this in its orders admin UI. Might also be able to incorporate #458.

**Comment by kstover** [comment]
This is something that we would really like to do, but it will require us to think about all the possible edge cases before we implement. You might want to be able to select which actions to fire again, especially if your form collected money using something like PayPal.

**Comment by helgatheviking** [comment]
I was thinking any email actions would be ideal candidates for triggering a second time, but a filter that allows you to define which actions are allowed would be idea

I don't think you wouldn't want to re-trigger the entire form submission, which could possibly (though I think unlikely) result in a duplicate charge to a payment processor.

**Comment by helgatheviking** [comment]
I started playing with this. 
![metabox](http://tinyurl.com/qdmqtja)

Not sure if I should add more commits to my [custom notifications](https://github.com/helgatheviking/ninja-forms/tree/custom-notifications) branch or create a new branch. Which will be better/easier for you guys?

If I remove the attachments code then it does send the email, which makes me happy for a first hack-through. Where I am getting stuck is with the `process()` method's reliance on the `$ninja_forms_processing` global, which doesn't exist here. 

I was able to get the form id and form title from the notification itself:
```
$form_id = Ninja_Forms()->notification( $id )->form_id;
$form_title = Ninja_Forms()->form( absint( $form_id ) )->get_setting( 'form_title' );
```

But I'm stumped on how to get the submission ID. On the edit submission screen it is readily available as the `$post->ID`, but what's the best way to retrieve that in `process()` ? Add a second param? A variable for the notification class? After all, a notification is always in response to a submission.

**Comment by helgatheviking** [comment]
It's a little messy but I got it functioning in my [retrigger notifications](https://github.com/helgatheviking/ninja-forms/tree/retrigger-notifications) branch.

**Comment by helgatheviking** [comment]
If you guys are rewriting NF completely for 3.0 then now might be a good time to consider re-writing notifications such that any notification instance can accept a submission ID and be populated with the data of that submission. Or in the absence of one try to default to the currently processing form. Having that in the core correctly could mean these later triggers could be much less "janky".

**Comment by kstover** [comment]
Hey @helgatheviking. First, thank you for the hard work! We've been discussing how we update processing and actions, and one of the things we've discussed is having actions check for a sub ID being passed. If no sub ID is passed, then it would default to the form currently being processed, which is exactly what you describe. Once we have some more fleshed out details for the new processing system, I'll be creating a post explaining it.

**Comment by helgatheviking** [comment]
@kstover that sounds ideal! And would make NF even more powerful. I think ultimately you could get to @wpnzach's "dream case" of bulk re-sending notifications.

**Comment by kstover** [comment]
Right. We're also going to be adding in some priority so that action types can be fired at specific times.

**Comment by kstover** [comment]
The goal is to move away from just using processing hooks and encouraging devs to put their custom processing into actions instead.

**Comment by helgatheviking** [comment]
Cool. I think it's gonna be awesome! I look forward to reading your post and testing the 3.0 stuff out when it's ready.
