### ISSUE TITLE
Don't add ninja-forms-field to layout elements (hr, text)

### ISSUE THREAD

**Issue by johanmoberg** [wpninjas/ninja-forms#778]
I don't think it's a good idea to add the class ninja-form-field to layout elements like hr and text. The reason is simply that if you want to add some custom css to a field (input, text, etc.) without having to add a custom class for each field in the admin. You probably don't want this to be applied to layout elements like hr and text.

**Comment by jameslaws** [comment]
I think this will be resolved in THREE
