### ISSUE TITLE
Form does not take submissions if user is logged out

### ISSUE THREAD

**Issue by bryan-snyder** [wpninjas/ninja-forms#780]
I have the most recent release of Ninja Forms and I can submit when logged in as admin but not when logged out and I NEED this to submit pretty much to ONLY logged out users... no email and no submission entry is made. Where can i start to look to solve this.?

**Comment by bryan-snyder** [comment]
the checkbox to only show form to logged in users is UNCHECKED.  just FYI.

**Comment by bryan-snyder** [comment]
really?

**Comment by wpnzach** [comment]
Bryan, can you submit a support request here so we can better assist you (https://ninjaforms.com/contact/)?  Our GitHub is reserved for development issues and should not be used for support requests or you may wait a very long time for a response.  

This sounds like something else on your site, like caching, is interfering with the form processing.
