### ISSUE TITLE
Remove expired transients

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#782]
Users are reporting large numbers of transients being created/not cleared in their database.  We need a way to remove these to prevent users DB's from becoming bloated.

**Comment by kstover** [comment]
@wpnzach I'm working on a fix for this. Do you have a user who is having this issue currently that we can run a real-world test on?

**Comment by frnkoc** [comment]
I'm having this problem with my websites. I found today more than 3 million entries in the wp-options table. I had to delete them on one site because mysql was crashing. 
Francisco C

**Comment by jameslaws** [comment]
I believe this has been resolved. Not sure why this wasn't closed.
