### ISSUE TITLE
Special Unicode characters in CSV not displaying correctly in Microsoft Excel

### ISSUE THREAD

**Issue by unfa** [wpninjas/ninja-forms#803]
Is there a way to add encoding information to the CSV file? Or something? No problems with Libre Office, but Microsoft Excel seems to interpret the files with wrong encoding, replacing special charactes with total mess.

I'm talking about diacritics like:

       ą ę ć ż ź ł ó ń

**Comment by fredriklaason** [comment]
Same with å ä ö.

**Comment by kstover** [comment]
Sorry for missing this issue for so long! We have an Excel Export extension that should take care of those character issues; it's definitely an issue with how Excel interprets those non-English characters.

**Comment by fredriklaason** [comment]
Anything we can do here https://github.com/wpninjas/ninja-forms/blob/master/classes/download-all-subs.php#L36 ?

**Comment by jameslaws** [comment]
Closed as issue is solved with an add-on.
