### ISSUE TITLE
Error when upgrading from 2.6.5 to 2.9.21

### ISSUE THREAD

**Issue by Peneheals** [wpninjas/ninja-forms#809]
Error

Bad Response :'(
SyntaxError: Unexpected token <

( ! ) Warning: implode(): Invalid arguments passed in wp-content/plugins/ninja-forms/includes/admin/upgrades/convert-notifications.php on line 107
Call Stack
#	Time	Memory	Function	Location
1	0.0016	381440	{main}(  )	../admin-ajax.php:0
2	0.4612	30386160	do_action(  )	../admin-ajax.php:86
3	0.4612	30387768	call_user_func_array
(  )	../plugin.php:496
4	0.4612	30387800	NF_UpgradeHandler->ajax_response(  )	../plugin.php:496
5	0.4612	30388664	NF_Upgrade->_step(  )	../class-upgrade-handler.php:104
6	0.4613	30391848	NF_Upgrade_Notifications->step(  )	../class-upgrade.php:130
7	0.5469	30799968	implode
(  )	../convert-notifications.php:107

{"upgrade":"notifications","total_steps":21,"args":{"forms":{"1":"2","2":"3","3":"4","4":"5","5":"6","6":"7","7":"8","8":"9","9":"10","10":"11","11":"12","12":"13","13":"14","14":"15","15":"16","16":"17","17":"18","18":"19","19":"20","20":"21","21":"22"}},"step":6}

---

### Environment ###

Home URL:                http://xxx.elte.hu
Site URL:                http://xxx.elte.hu
Ninja Forms Version:     2.9.21
WP Version:              4.2.3
WP Multisite Enabled:    No
Web Server Info:         nginx
PHP Version:             5.4.41-0+deb7u1
MySQL Version:           5.5.44
PHP Locale:              decimal_point: .thousands_sep: int_curr_symbol: currency_symbol: mon_decimal_point: mon_thousands_sep: positive_sign: negative_sign:
WP Memory Limit:         40 MB
WP Debug Mode:           No
WP Language:             hu_HU
WP Max Upload Size:      64 MB
PHP Post Max Size:       65 MB
Max Input Nesting Level: 64
PHP Time Limit:          30
PHP Max Input Vars:      1000
SUHOSIN Installed:       No
SMTP:                    localhost
smtp_port:               25
Default Timezone:        Default timezone is UTC

### Plugins ###

Installed Plugins:       Bootstrap 3 Shortcodes by Filip Stefansson
                         Simon Yeldon
                         and Michael W. Delaney version 3.3.6
                         jonradio Multiple Themes by David Gewirtz version 7.1
                         Ninja Forms by The WP Ninjas version 2.9.21

**Comment by kstover** [comment]
@Peneheals Can you submit a support request here:  http://ninjaforms.com/contact/ ? I think we'll need to do some deep-diving into this issue with you.

**Comment by Peneheals** [comment]
Sure, I did it, and got a reply message too.
