### ISSUE TITLE
Empty all submissions in forms (or selected forms)

### ISSUE THREAD

**Issue by Peneheals** [wpninjas/ninja-forms#810]
Feature request: I would love to see a button to empty all the submissions on my forms (or the selected ones).

**Comment by jameslaws** [comment]
@Peneheals, Can you possibly clarify what you are looking for here. I'm not sure I follow.

**Comment by kjohnson** [comment]
@Peneheals, we have a PR for a "Delete All Submissions" button. Is that what you were looking for?

**Comment by Peneheals** [comment]
@jameslaws @kjohnson  Sure! If I'm right, the old "Delete submissions" button works on the selected form. If I have eg. 30 forms, and every month I have to delete all the forms' submissions, it means that I have to go to every form's admin page and push that button (or something equal solution).

I imagine a batch or selectable solution where I can select some (or every) forms, and empty all the submissions (like in phpmyadmin, where you can select the tables and empty them). That would be even better than having just one "main" option/button somewhere in the admin section to delete all submissions in all forms.

I saw jacobschweitzer's work (#947), but atm. I can not test it. It looks good for me from "outside".
