### ISSUE TITLE
Ninja Forms needs to process 4 upgrade(s). This may take a few minutes to complete.

### ISSUE THREAD

**Issue by str** [wpninjas/ninja-forms#812]
This is the error I get after activating the plugin. Why should I need to run any upgrade process?

![wordpress 2015-07-29 14-47-14](https://cloud.githubusercontent.com/assets/123817/8966698/bcfbd090-3600-11e5-8ad3-0dc84db95767.png)

**Comment by kstover** [comment]
@str If you had a previous version of Ninja Forms installed and that data is still in the database, it can still need to upgrade. If the tables from a previous version still existed, even though they were empty, you can still be prompted to upgrade. As with the other issue, I'd point you toward ninjaforms.com/contact/ to get quicker support.

**Comment by str** [comment]
OK, so. after forcing the 'delete_on_uninstall' flag in the code, I deleted the plugin to have a fresh start. All database tables and options were purged. All files (if modified) were deleted in this process. I then installed the plugin from scratch, brand new, no previous versions nor corrupted data. 

I still get the same error message.

**Comment by kstover** [comment]
I just did a completely fresh installation of Ninja Forms, and didn't see an upgrade notice. We are doing some more internal testing to see if we can reproduce what you're seeing.

In the meantime, let's take a few steps on your end to see if we can track down what's going on.

Do you still see the notice now? Can you try the following:

1) Deactivate and delete the plugin.
2) In your database, search for and remove any tables that being with nf_ and ninja_forms.
3) Search your options table for anything LIKE % % nf_ and ninja_forms_ and delete them.
4) Re-add the plugin from WordPress.org

Then let me know if you still see that notice.

**Comment by str** [comment]
There is an option with the nf_ substring but it's the option_name = 'cron'. Is it safe to delete that? Here I post the value.

a:14:{i:1438199820;a:1:{s:20:"wp_maybe_auto_update";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:10:"twicedaily";s:4:"args";a:0:{}s:8:"interval";i:43200;}}}i:1438204814;a:1:{s:26:"upgrader_scheduled_cleanup";a:1:{s:32:"7c8dfc5d9d85d4ef7b59997202954a79";a:2:{s:8:"schedule";b:0;s:4:"args";a:1:{i:0;i:957;}}}}i:1438207027;a:1:{s:16:"itsec_purge_logs";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:5:"daily";s:4:"args";a:0:{}s:8:"interval";i:86400;}}}i:1438224579;a:1:{s:29:"wp_session_garbage_collection";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:10:"twicedaily";s:4:"args";a:0:{}s:8:"interval";i:43200;}}}i:1438237677;a:3:{s:16:"wp_version_check";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:10:"twicedaily";s:4:"args";a:0:{}s:8:"interval";i:43200;}}s:17:"wp_update_plugins";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:10:"twicedaily";s:4:"args";a:0:{}s:8:"interval";i:43200;}}s:16:"wp_update_themes";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:10:"twicedaily";s:4:"args";a:0:{}s:8:"interval";i:43200;}}}i:1438267611;a:1:{s:24:"akismet_scheduled_delete";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:5:"daily";s:4:"args";a:0:{}s:8:"interval";i:86400;}}}i:1438281126;a:2:{s:20:"nf_maybe_delete_form";a:1:{s:32:"fe0b93ca214a68210e7bc5a7b10fd4b9";a:2:{s:8:"schedule";b:0;s:4:"args";a:1:{s:7:"form_id";i:1;}}}s:24:"ninja_forms_daily_action";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:5:"daily";s:4:"args";a:0:{}s:8:"interval";i:86400;}}}i:1438281286;a:1:{s:19:"wp_scheduled_delete";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:5:"daily";s:4:"args";a:0:{}s:8:"interval";i:86400;}}}i:1438283411;a:1:{s:24:"ninja_forms_daily_action";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:5:"daily";s:4:"args";a:0:{}s:8:"interval";i:86400;}}}i:1438283493;a:1:{s:24:"ninja_forms_daily_action";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:5:"daily";s:4:"args";a:0:{}s:8:"interval";i:86400;}}}i:1438283513;a:1:{s:20:"nf_maybe_delete_form";a:1:{s:32:"da42e2263958687afe90c31c614f55c9";a:2:{s:8:"schedule";b:0;s:4:"args";a:1:{s:7:"form_id";i:5;}}}}i:1438284028;a:2:{s:20:"nf_maybe_delete_form";a:1:{s:32:"fe0b93ca214a68210e7bc5a7b10fd4b9";a:2:{s:8:"schedule";b:0;s:4:"args";a:1:{s:7:"form_id";i:1;}}}s:24:"ninja_forms_daily_action";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:5:"daily";s:4:"args";a:0:{}s:8:"interval";i:86400;}}}i:1438285530;a:1:{s:30:"wp_scheduled_auto_draft_delete";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:5:"daily";s:4:"args";a:0:{}s:8:"interval";i:86400;}}}s:7:"version";i:2;}

**Comment by kstover** [comment]
Yes. That's ok to delete.

**Comment by str** [comment]
OK, this is what I did:

* Deactivated the plugin
* Modified the wp-content/plugins/ninja-forms/uninstall.php to force the purge of the databse tables and settings
* Deleted the plugin.
* In the database, searched for and remove any tables that being with nf_ and ninja_forms (none found now)
* Searched options table for anything LIKE % % nf_ and ninja_forms_ and delete them.
* Re-add the plugin from WordPress.org

I still get the same "needs to process 4 upgrade(s)" error message

**Comment by kstover** [comment]
Ok. This isn't something that we can recreate on our end; I think we'll need to do a deep-dive for support. If you can fill out a ticket here: http://ninjaforms.com/contact/ we'll get into it and see what may be going on there.
