### ISSUE TITLE
From Name and Subject should not use htmlentities

### ISSUE THREAD

**Issue by wandl** [wpninjas/ninja-forms#813]
Hi,

When adding the From Name, Subject to the Email & Actions on a form if I use an ampersand one saved it converts to a htmlentity these fields should be plain text.

![screen shot 2015-07-30 at 1 03 56 pm](https://cloud.githubusercontent.com/assets/7665399/8975291/95832e58-36bb-11e5-9683-74d1beb814bd.png)

![screen shot 2015-07-30 at 1 04 07 pm](https://cloud.githubusercontent.com/assets/7665399/8975293/9c831ad8-36bb-11e5-81de-833fecf086a2.png)

**Comment by klhall1987** [comment]
@jameslaws @kstover is this a known issue with our tokenizer?

**Comment by jameslaws** [comment]
I'm not sure about a known issue, but irrelevant due to THREE. We are using merge tags instead.
