### ISSUE TITLE
Add default actions upon form creation

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#814]
When creating a new form from scratch it can be confusing to go to the actions tab and see a table with no actions set. We know that there are certain actions that almost everyone will need and adding them by default could vastly improve the users experience.

Possible default actions could be:
* Send Admin Email
* Display Success Message
* Save Submissions

The admin email should probably be populated as such:
* From Name: Site Title
* From Email: Admin Email
* Subject: New submission from {form name}
* Message: include all fields shortcode

**Comment by paaljoachim** [comment]
Great! I will hook in my own issue that I posted some time ago.

Email & Actions - Initial Save
https://github.com/wpninjas/ninja-forms/issues/641
