### ISSUE TITLE
Option to close a form

### ISSUE THREAD

**Issue by Peneheals** [wpninjas/ninja-forms#815]
Feature request: There are several occasions when I have to show my forms publicly, but do not let users to submit it. It would be great to see a setting at every form, which can close it (=restrict to submit, for example the submit button will be inactive or somehow like this).

Atm. I'm in the finalizing phase of form creation, and the best way to do this with the client is to show them the form, and wait for the final decision or modification requests.

**Comment by klhall1987** [comment]
This is being implemented in Three.
