### ISSUE TITLE
Should the Submission CSV be turned off by default?

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#818]
Should the Submission CSV be turned off by default in the Email & Actions?

It would be better to manually turn it on if the CSV is needed. Then to have to remember to turn it off.

**Comment by epigeyre** [comment]
I agree with you. I would assume that, most of the time, you don't want CSV attached. If true, it would best practice to turn it off.

**Comment by kstover** [comment]
I think I can agree with this. We can modify the default fairly easily.

**Comment by jameslaws** [comment]
@kstover What's the status of this? Punt to THREE?

**Comment by kjohnson** [comment]
@jameslaws @kstover I would agree with punting to THREE, as opposed to changing a default behavior last minute.

**Comment by paaljoachim** [comment]
It seems pretty natural to punt everything that is not vital to 3..... Since this specific feature has been like this for a while a few more weeks would not matter. As it seems like a pretty simple thing to get done for 3.

**Comment by kstover** [comment]
Defaults to "OFF" in version 3.
