### ISSUE TITLE
Turning off the visibility of Fields marked with an * are required.

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#820]
It would be nice to just turn off: 
Fields marked with an * are required section but keeping fields required.

Meaning if someone does not fill in a (name, email etc) they will get the message saying field needs to be filled in etc. But one does not need to tell the user this before hand.

This means turning off the Fields marked with an * are required text above the fields and all the stars next to the field names. Just keeping a nice and clean form.

Having a setting inside Settings -> Display called turn off required field message. Making the form even more clean, but still alerting the user of fields he/she did not fill in.

**Comment by jameslaws** [comment]
Currently you can technically do this under Forms > Settings > Forms Labels > and remove the desired text. If that's blank it won't show up in the form. 

The only problem with that is its site wide. This would impact all forms.

**Comment by kstover** [comment]
My fear with having mystery "required" fields is that it's not necessarily a great user experience. I could see that being confusing and annoying from a user perspective.

**Comment by jameslaws** [comment]
@kstover, I don't disagree with you. Standard practice is to always notify the use of fields are required. But that leading message isn't necessarily crucial for this.

**Comment by kstover** [comment]
@jameslaws Sure. He's suggesting removing all noticed before the form is filled out: both the message above the form and the per-field indicators.

**Comment by jameslaws** [comment]
While technically that can be done now, I agree that I don't know that I like the user experience with all those elements missing. 

I guess we have to decide what our responsibility is in end user experience vs giving admins control when they want to make those poor UX choices.

**Comment by paaljoachim** [comment]
Lets say it is a very simple form. Name, Email, Message. It is expected of the user to fill in the three fields. Having a Required message is not really needed in this case. But as you guys are saying in most cases it is needed. To alert the user to what really needs to be filled in and not. 

What about changing the following CSS tags to become DIV tags:
.ninja-forms-required-items ->#ninja-forms-required-items-form1
.ninja-forms-req-symbol -> #ninja-forms-req-symbol-form1.
So one can just use a display none in the CSS to hide required text and * (stars) if the developer choices to do so.... for artistic reasons..:)

**Comment by epigeyre** [comment]
Have you seen this article: http://uxmovement.com/forms/why-users-fill-out-less-if-you-mark-required-fields/ ? It seems that marking **optional field only** could be more efficient in some situations.

**Comment by kstover** [comment]
Cleaning up issues; moving this to an internal tracker.

**Comment by helgatheviking** [comment]
I was just wondering how to do this myself and this came up in Google. For mailing list signups and other potentially 1-2 field forms, the notice does seem like overkill. 

Here's an example that I like, the asterisk is inside the input. If you are signing up for a mailing list you should expect to provide your email right?

![image](https://cloud.githubusercontent.com/assets/507025/19061197/30b41134-89b4-11e6-8c32-2d25fcbcdf5d.png)

**Comment by zmogus** [comment]
@jameslaws, I followed your advice to go to "Forms > Settings > Forms Labels >", but there is no "Forms Labels" here. Any Idea where to look for it now?

**Comment by kennkelly** [comment]
Correct @zmogus there is no setting for a standard account. However, as seen on Ninja you can use the following to remove it:

`.nf-form-fields-required {
  display: none;
}`

**Comment by gabrielalexis** [comment]
@kennkelly : how can i use that code in ninja forms?

**Comment by kennkelly** [comment]
Simply add that line of CSS to your style.css file in your theme.

**Comment by gabrielalexis** [comment]
how can i edit the plug-ins back end source codes?

**Comment by kennkelly** [comment]
@gabrielalexis that's more complicated and not what I mentioned. You need to add that one single line to your "themes" style sheet file named "style.css" If you are not familiar with it simply ask any developer friend and they can point you in the right direction.  In source code it’s under 

wp-content > themes > [theme name] > style.css

**Comment by NikkiC123x** [comment]
I also have the same issue.   I want to remove the text, and I have fields without labels, so I want the asterisk to display after the form field to denote required without actually having to say it!  Tried this, but it didn't work.  Anyone else got any ideas?

.nf-form-fields-required {
display: none;
}

#nf-field-29::after { 
    content: "*";
color: red;
}
