### ISSUE TITLE
Making columns part of the Edit form view

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#821]
It would be nice to have a way to easily create columns inside the form area in edit form view.
Perhaps placing fields into rows that can be split or merged to create columns. 

Caldera does this in an ok way https://wordpress.org/plugins/caldera-forms/screenshots/

**Comment by jameslaws** [comment]
We are working on a new UX/UI for Ninja Forms and a part of that process is considering how we bring the new layout creator right into the main build your form page. 

This will still require the Layout & Styles add-on, however. It won't be built into Ninja Forms.
