### ISSUE TITLE
Sending data through NF

### ISSUE THREAD

**Issue by vajrasar** [wpninjas/ninja-forms#824]
I have the following code - 

```
global $wp_session;

$wp_session = WP_Session::get_instance();

$cart = $wp_session->toArray();



echo "<div id='onload-cart-sidebar'>";

if( !empty( $cart ) ) {

  foreach( $cart['wpscart'] as $key=>$value ) {

      echo "<br />" . get_the_title( $key ) . " " . $value . " units";

      echo "<hr />";

  }

}

echo "</div>";

ninja_forms_display_form( 5 );
```

I need to send the data contained within `'onload-cart-sidebar` div. I tried using `text` and `textarea` to append that data into them and its gets appended too but it never gets sent to the mail. Mail gets send without that `text` or `textarea` field.

Any ideas?

**Comment by kjohnson** [comment]
Have you had a chance to look at the documentation for Ninja Forma loading ?
