### ISSUE TITLE
Addon notices for Save Progress/MPF display on all forms until dismissed

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#826]
Should only display on very long forms.

**Comment by jameslaws** [comment]
I'm actually not able to reproduce this on any of my sites. Could this be isolated to you for some reason?

**Comment by klhall1987** [comment]
Could we ever reproduce this issue, if so has it been solved?

**Comment by jameslaws** [comment]
@wpnzach PING
