### ISSUE TITLE
Input type for Email field is "text" instead of "email"

### ISSUE THREAD

**Issue by epigeyre** [wpninjas/ninja-forms#832]
Maybe it's just me but it seems that the input type for an Email field is "text". When the **validate as an email address** checkbox is checked, I don't see any reason why the type shouldn't be "email".

**Comment by kstover** [comment]
Hey @epigeyre. This has to do with how our field registration currently works. We don't have the ability to hide the option on textboxes. We're going to fix this in the future with a new field registration system.
