### ISSUE TITLE
Meta boxes in new post/new page screen become locked with version 2.9.25

### ISSUE THREAD

**Issue by Mario-M** [wpninjas/ninja-forms#837]
When activated, Ninja Forms locks the ability to drag and drop the meta boxes on the right column in the new post/new page screens. You can still collapse and expand the meta boxes, however they are not moveable. When Ninja Forms is deactivated, the meta boxes become moveable again.

I've tried this on three sites, all running WP 4.2.4. Two of the sites running the most recent version of Ninja Forms (2.9.25) had the issue where the meta boxes were locked. However on the last site I tested, the meta boxes WERE movable. I then noticed that the site was running a slightly older build of Ninja Forms (2.9.18). Lo and behold, immediately after updating to Ninja Forms 2.9.25, the meta boxes became locked and as far as I can see there is no toggle for this.

Any help from the Ninja team would be greatly appreciated. If you need any more information, just let me know!

**Comment by jameslaws** [comment]
I've confirmed this issues on a local install and will push this up the development chain.

**Comment by kstover** [comment]
@Mario-M Thanks for the heads up! We're digging into this now and should have a fix up soon?

**Comment by Mario-M** [comment]
My pleasure! Glad to help contribute to a great project.

**Comment by kstover** [comment]
Releasing version 2.9.26 now.
