### ISSUE TITLE
Suggestion: ajax submit fails with restricted access to /wp-admin

### ISSUE THREAD

**Issue by bundeskassner** [wpninjas/ninja-forms#847]
Hi Ninjas,

for security reasons I like to completely restrict access to /wp-admin in the webserver configuration using IP ranges or passwords. Unfortunately this messes with the ability of Ninja-forms to use Ajax submission because it needs to access /wp-admin/admin-ajax.php. Since your plugin resides in /wp-content/plugins/ninja-forms I'm wondering if it was possible to have the needed ajax components also stored there and not in /wp-admin?!

Just wondering. KR
  Ulli

**Comment by kstover** [comment]
Hey,

There isn't a good way to do that, unfortunately. The default WordPress method for accessing data via AJAX is to use the admin-ajax.php. This isn't something that we are able to do in the foreseeable future. :(
