### ISSUE TITLE
Translate the return messages

### ISSUE THREAD

**Issue by kevin-lesterius** [wpninjas/ninja-forms#855]
Hello,

I've a multi-language site, I've been able to translate all the form, but I can't find a solution to translate the return messages that are set in settings -> titles.

Is there a hook or something I could use to programmatically translate the return messages before the form is shown in the function.php ?

Thanks

**Comment by kstover** [comment]
Those labels are actually saved in the database. If you leave them empty, they will return to defaults that you can use with the translation files. You can also use WordPress filters to modify the labels before they are shown to the user. They are found in the main ninja-forms.php file on line 719.
