### ISSUE TITLE
Lot's of include / require_once before usage

### ISSUE THREAD

**Issue by Ciantic** [wpninjas/ninja-forms#86]
I'm hesitant to use the plugin now that I've checked the code, reason being the main file `ninja-forms.php` loads up *a lots of PHP files* on each request. This should be avoided. 

Instead one should include PHP files only when you need them. Usually inside some WP action e.g. when loading admin view or inside the shortcode.

I'm aware this change requires sea change in this program, but I think it should be fixed.

**Comment by kjohnson** [comment]
v3 now uses a php5.2 compatible autoloading.
