### ISSUE TITLE
Submissions

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#866]

**Comment by jameslaws** [comment]
@klhall1987 Is submissions something that is actually in progress? I figured it was done.

**Comment by jameslaws** [comment]
@klhall1987 What exactly is this?

**Comment by kjohnson** [comment]
@jameslaws we still need to add the download all button and are incorporating a delete all button. Also, submissions need a review to make sure we didn't miss anything.

**Comment by kjohnson** [comment]
Need to verify that each field displays in the submission editor appropriately, as different fields may require special display functions.

**Comment by kjohnson** [comment]
Also need a way to add `_extra` data to display in submissions, ie Payment Status, etc.

**Comment by kjohnson** [comment]
Added an `abstract` metabox class for submissions.
