### ISSUE TITLE
Add Rename Modal on Form Duplication

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#881]
Based on [housetwelve](https://wordpress.org/support/profile/housetwelve)'s [feedback](https://wordpress.org/support/topic/great-forms-5#post-7313965), we should add a modal for renaming the new form created on form duplication. This will create a smoother user experience when duplicating forms.

**Comment by jameslaws** [comment]
@kstover, thoughts?

**Comment by kstover** [comment]
I think that this is a good idea, but I'm punting it to version 3.x.

**Comment by kstover** [comment]
I've added this to our internal tracker while I'm cleaning up our GitHub issues. I will evaluate re-adding it here later.
