### ISSUE TITLE
Fatal Error Line 345

### ISSUE THREAD

**Issue by timm088** [wpninjas/ninja-forms#882]
Hi, 

We are running ninja forms 2.9.27 with Ninja Forms - Mailchimp 1.3.4 
We get the following fatal error when enabling wp_debug (in Form Actions)

Notice: Undefined property: MailChimp::$lists in /wp-content/plugins/ninja-forms-mailchimp/ninja-forms-mailchimp.php on line 345

Fatal error: Call to a member function mergeVars() on a non-object in /wp-content/plugins/ninja-forms-mailchimp/ninja-forms-mailchimp.php on line 345

**Comment by kjohnson** [comment]
Hey @timm088,

I am copying this issue over to the private repo for the MailChimp Add-On, with a link back to this issue for reference.

**Comment by timm088** [comment]
Thanks Kyle. 

The end result of this issue is we cannot import anything from the mailchimp list/s we have. 
Coincidentally, we dont see this problem on earlier versions of PHP (i.e. PHP 5.3), it occurs in our current version of 5.5.9-1

**Comment by kjohnson** [comment]
@timm088,

Are you running any other plugins related to MailChimp?

**Comment by timm088** [comment]
Hi Kyle,

Plugins no, however, there was a small mailchimp integration in the theme
we used which was causing the conflict.

(Pippin, the plugin developer, helped me diagnose it)

This issue can be closed.
