### ISSUE TITLE
Email confirmation

### ISSUE THREAD

**Issue by nicoesiea** [wpninjas/ninja-forms#883]
Hello everyone,
Is it possible (directly with the plugin) to add a confirmation email field? You should know it (although I can not explain it, nor his request by customers - for every user make a simple copy / past), this field is well known, almost become a standard.

At first, I thought about doing this validation in javascript: via methods OnFocusInForm / OnFocusOutForm on fields and email confirmation [on html tag: onfocusin = "OnFocusInForm (event)"] - they (this two function) just verify the equality between the two email values . But this solution is pretty ... ugly.

Have you a better way to do ???

**Comment by kjohnson** [comment]
Hey @naomicbush,

I previously put together a [verification field](https://github.com/kjohnson/ninja-forms-verification-field) for a customer as a small integration. This free add-on create two input field, with the added validation that the two values match.

It has been a little while since I put this together, but let me know if it works for you.

You can download it from GitHub and install it like any other Ninja Forms add-on.

**Comment by nicoesiea** [comment]
Hey @kjohnson 
Can you quickly explain to me how to add an addon on form ninja?
(I'm using WordPress 4.2.2 and Ninja form version 2.9.18)

**Comment by kjohnson** [comment]
You install it like  any other plugin.

After you [download the zip](https://github.com/kjohnson/ninja-forms-verification-field/archive/master.zip) from GitHub, then upload that zip file into your WordPress admin (Plugins -> Add New -> Upload ).

Does that help?

**Comment by nicoesiea** [comment]
Yes, Thank you @kjohnson 

I did not think it was necessary to add a new wordpress plugin! I thought it was just necessary to add a code in the existing NinjaForm plugin.
I added it. And it is now activated.
But that does not change my form - how to enable the duplication of the email field in my form? Is there a field to add (to be linked to my email field) or an option box in the email field ??

**Comment by nicoesiea** [comment]
Ohhh there is a new type of field : Verification !!
I had not seen it !!! And it is the first of the list !!

**Comment by kjohnson** [comment]
We extend Ninja Forms by adding code in new plugins. This allows us to update Ninja Forms without overwriting your new code.

The verification plugin creates a new field in the Ninja Forms form builder. You would use the new field in place of the field that you want to verify.

**Comment by nicoesiea** [comment]
Ok - that seem to be a good result for my issue !
BUT :
- Is there possible to add a placeholder message in the confirmation field ?
- I suggest to change the error message when the first email is added but when the form is submit without a good confirmation value

**Comment by nicoesiea** [comment]
Maybe change line 290 in nf-verification-field.php : 
$invalid_email = __( 'Please enter a valid email address.', 'ninja-forms' );
To : 
$invalid_email = __( 'Please confirm your email address', 'ninja-forms' );

But I don't know where (and how) to add a placeholder

**Comment by kjohnson** [comment]
Do you mind submitting a [pull request](https://github.com/kjohnson/ninja-forms-verification-field) for the Error Message?

**Comment by kjohnson** [comment]
The placeholder would go on [line 279](https://github.com/kjohnson/ninja-forms-verification-field/blob/master/nf-verification-field.php#L279). There isn't a setting for this, but you could add it inline.
