### ISSUE TITLE
Hide form Title + display a confirmation message

### ISSUE THREAD

**Issue by nicoesiea** [wpninjas/ninja-forms#884]
Hello,
I add this javascript in my template page to hide the form Title and to display a message after my form submitting (I add this form in a event calendar plugin page)
```
<?php
   $currentDate = date('Y-m-d');
   if ($eventDate >= $currentDate) { //Verify if event is past or not
?>
  <div class="eventRegisterForm">
  <style>
     div.eventRegisterForm .hide {display:none;}
  </style>
      <h2 id="eventRegisterFormTitle">Register for this upcoming event</h2>
      <?php 
         if( function_exists( 'ninja_forms_display_form' ) ){  
            ninja_forms_display_form( 5 ); 
         }
         echo '<div id="eventRegistrationConsidered" class="hide"><ul><li> Registrations will be accepted in the order of their arrival.</li></ul></div>';
      ?>
      <script>
         var y = document.getElementById("ninja_forms_form_5").className;//ninja-forms-no-display
         if (y=='ninja-forms-form ninja-forms-no-display') {
            console.log("Form submit - I must hide the title and display a confirmation message"); 
            document.getElementById("eventRegisterFormTitle").className = "hide";
            document.getElementById("eventRegistrationConsidered").className = "tribe-events-notices";
         }
         else {
            console.log("start filling the form: eventTitle[<?php echo $eventTitle;?>] eventDate[<?php echo $eventDate;?>]"); 
            document.getElementById('ninja_forms_field_35').value = '<?php echo $eventTitle;?>'; 
            document.getElementById("ninja_forms_field_35_div_wrap").className = "hide";
            document.getElementById('ninja_forms_field_36').value = '<?php echo $eventDate;?>';      
            document.getElementById("ninja_forms_field_36_div_wrap").className = "hide"; 
         }
         
      </script>
  </div>
<?php 
   } //End of event date no paste if
   else {
        echo '<div class="tribe-events-notices"><ul><li>This event has passed.</li></ul></div>';
   }
?>
```

Is this code good according to you ? And maybe can you suggest me another way to do the same thing... 
Thx

**Comment by kjohnson** [comment]
Hey @nicoesiea,

Ninja Forms core comes with confirmation messages. After building your form, go to the "Email & Actions" tab, click "Add New", then select "Success Message" for the Type.

Also, for adding an event title dynamically to a field, you can use the [Ninja Forms Loading Global](http://docs.ninjaforms.com/customer/en/portal/articles/1981039-processing-ninja_forms_loading?b_id=9172) and update the value of a field. You can use this global inside of a PHP function, hooked into the WordPress 'init' action.

```php
add_action( 'init', 'nf_tribe_event_title');
function nf_tribe_event_title(){
    global $ninja_forms_loading;
    
    $ninja_forms_loading->update_field_value( 35, 'TRIBE EVENT TITLE HERE' );
}
```

**Comment by nicoesiea** [comment]
Wow thank you very much, it is much cleaner indeed (the Email & Action menu doesn't seems to have an explicit name...to me).
However, with this technique, the title is still visible after submitting the form ! Is there a option to hide it ?

I do not understand how to set the form fields (event title and date) with your solution - can you show me an example ?

**Comment by kjohnson** [comment]
@nicoesiea, using the above example action, you can replace the number `35` with the ID of the form field that you want to update and replace `TRIBE EVENT TITLE HERE` with the value of the field.

Does that help?

**Comment by nicoesiea** [comment]
Ohhh yes, it's perfect. Thx @kjohnson

**Comment by nicoesiea** [comment]
Hello Kyle,
Could you help me on this issue:
https://github.com/wpninjas/ninja-forms/issues/1497

Here is the answer provided by the Ninja Forms support and I'm a little bit
lost. Could you help me to develop a PHP code to replace this submit URL
please ??
*Devin Balram* replied:

Nicolas,

Unfortunately we do not have an out of the box way of doing this currently
within Ninja Forms. We are working on making this a feature in Ninja Forms
Three & Webhooks, but at this time it would take custom code. Unfortunately
we do not have the resources to provide custom code. You may be able to
connect with one of our Collaborating Developers,
<https://ninjaforms.com/about> to see if they can provide you with a custom
solution.

I apologize that I don’t have a better answer for you.
Devin Balram
Happiness Ninja
The WP Ninjas Support Team

Respectueusement,

DUMONT Nicolas <http://copocorp.free.fr/>
0033 6 75 45 10 10 (FR)
00352 621 451 409 (LU)
2 allée des rossignols, 57535 Marange-Silvange
<https://www.google.fr/maps/place/2+All%C3%A9e+des+Rossignols,+57535+Marange-Silvange/@49.2133346,6.1161331,17z/data=!3m1!4b1!4m2!3m1!1s0x4795278df5de235d:0x51d54276486b2c67>

2015-08-24 18:16 GMT+02:00 Kyle B. Johnson <notifications@github.com>:

**Comment by kjohnson** [comment]
@nicoesiea can you ping me in the [Ninja Forms Developer Slack Team](http://developer.ninjaforms.com/slack/)?
