### ISSUE TITLE
FEATURE: Front-End Form Submissions Display & CSV Download Link

### ISSUE THREAD

**Issue by brandbrilliance** [wpninjas/ninja-forms#892]
Features:

![caldera-forms-export](https://cloud.githubusercontent.com/assets/1362479/9541119/62734ec4-4d65-11e5-8ff9-069298788a87.jpg)

* You can display submissions in a (hardcoded) table in the front-end using a shortcode
* Optional download link (with class) support to make a link/button that is only valid for that DAY, as the download link is md5 encoded and checked to match all forms and current day and if not, doesn't do anything (data spread safety precaution).
* Intention is that you can place form submissions shortcode on a password protected page (easier to control access) and provide entries to clients/organisers/others, etc.

I've coded this as a separate plugin item, for easier testing, but you're welcome to incorporate the code into the base. I'm using it for personal event registration management usage.

[Download as Plugin](https://dl.dropboxusercontent.com/u/28931329/_code/caldera-forms-export.zip)

**Comment by jameslaws** [comment]
@kstover, thoughts?

**Comment by kjohnson** [comment]
@jameslaws @kstover I think the download link would be easily added as a parameter in the shortcode. Would be easy enough to add.

**Comment by AshutoshSwain** [comment]
I Need This Plugin...

**Comment by sp9mrn** [comment]
link is broken ;-(
