### ISSUE TITLE
Honeypot-field not hidden as of 2.9.22

### ISSUE THREAD

**Issue by baspapen** [wpninjas/ninja-forms#893]
Since 2.9.22 a honeypot-field appears on my website. This should be hidden, it seems that the ninja-forms css file is not loaded. It concerns a footer, displayed on each page. The field appears random an several pages, but not all. I tested all releases as of 2.9.22 to 2.9.27, but they all came up with the same problem, therefore I reinstalled 2.9.21.

**Comment by aureliendebord** [comment]
Hi, I  see the same problem on IE. Any solution ?

**Comment by jameslaws** [comment]
@kstover, @kjohnson, @klhall1987, @wpnzach Can any of you reproduce?

**Comment by kstover** [comment]
@jameslaws I cannot.

**Comment by klhall1987** [comment]
@jameslaws I cannot reproduce this issue either.

**Comment by kjohnson** [comment]
I'm checking with @wpnzach about testing this in Browser Stack, to see if I can find any weird OS / browser combo issues.

**Comment by kjohnson** [comment]
@jameslaws could not replicate.
