### ISSUE TITLE
Field Types

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#897]
Inventory current core fields, group by type, and create classes. For inventory, create checklist groups in this issue for tracking.

## Group A

- [ ] Field Type 1
- [ ] Field Type 2

**Comment by klhall1987** [comment]
## standard_field

- [ ] calc.php
- [ ] checkbox.php
- [ ] country.php
- [ ] credit-card.php
- [ ] desc.php
- [ ] hidden.php
- [ ] honeypot.php
- [ ] list.php
- [ ] number.php
- [ ] password.php
- [ ] rating.php
- [ ] recaptcha.php
- [ ] spam.php
- [ ] submit.php
- [ ] tax.php
- [ ] textarea.php
- [ ] textbox.php
- [ ] timed-submit.php

## layout_elements

- [ ] desc.php
- [ ] hr.php
- [ ]

**Comment by jameslaws** [comment]
Closed. Pre development issue. Completed.
