### ISSUE TITLE
Extend Textbox Field Class

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#900]
## Textbox

- [x] textbox
- [x] email
- [x] password
- [x] hidden
- [x] checkbox

**Comment by jameslaws** [comment]
Seems like there are a lot of html5 fields that could be added here. Are these a part of a different step?

**Comment by kjohnson** [comment]
Baby steps, @jameslaws :)

**Comment by jameslaws** [comment]
Closed. Pre development issue. Completed.
