### ISSUE TITLE
Test Deprecation

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#903]
- [x] Create a New Form
- [x] Display the Form
- [x] Create an Email
- [x] Create required field. 
- [x] Create a Success Message
- [x] Create a Redirect (separate form)
- [x] Submit the Form
- [x] Fire an Email Action
- [x] Receive Email
- [x] See Success Message
- [x] See Redirect (separate form)
- [x] Edit the Form
- [x] View Submissions
- [x] Edit Submission
- [x] Delete an Action
- [x] Delete the Form

**Comment by klhall1987** [comment]
- [ ] Create a New Form
- [ ] Display the Form
- [ ] Create an Email
- [ ] Create required field. 
- [ ] Create a Success Message
- [ ] Create a Redirect (separate form)
- [ ] Submit the Form
- [ ] Fire an Email Action
- [ ] Receive Email
- [ ] See Success Message
- [ ] See Redirect (separate form)
- [ ] Edit the Form
- [ ] View Submissions
- [ ] Edit Submission
- [ ] Delete an Action
- [ ] Delete the Form

**Comment by klhall1987** [comment]
When Cleverreach is active the following errors: 
Notice: Undefined variable: forms in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/ninja-forms-cleverreach/includes/class-nf-cleverreach.php on line 330

Notice: Undefined variable: forms in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/ninja-forms-cleverreach/includes/class-nf-cleverreach.php on line 348

**Comment by klhall1987** [comment]
If any other plugin is activated after Cleverreach, I am getting a white screen with the following errors:

Notice: Undefined variable: forms in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/ninja-forms-cleverreach/includes/class-nf-cleverreach.php on line 330

Notice: Undefined variable: forms in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/ninja-forms-cleverreach/includes/class-nf-cleverreach.php on line 348

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/wordpress/wp-content/plugins/ninja-forms-cleverreach/includes/class-nf-cleverreach.php:330) in /Applications/MAMP/htdocs/wordpress/wp-includes/pluggable.php on line 1207

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/wordpress/wp-content/plugins/ninja-forms-cleverreach/includes/class-nf-cleverreach.php:330) in /Applications/MAMP/htdocs/wordpress/wp-includes/pluggable.php on line 1207

**Comment by klhall1987** [comment]
Upon activation of Front-End Editor I am receiving the following message: 

The plugin generated 193 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

**Comment by klhall1987** [comment]
Upon activation of PDF Editor I am being redirected to the "Welcome to Ninja Forms 2.9.27" page.

**Comment by klhall1987** [comment]
When creating an email action, the "From Name" field seems to duplicate itself if the arrow keys are used enter is pressed select and populate the field.

**Comment by klhall1987** [comment]
Cannot use bulk action selector to delete or deactivate actions.

**Comment by klhall1987** [comment]
When selecting edit on a form in the front end. I am receiving the following errors: 

Warning: Invalid argument supplied for foreach() in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/ninja-forms-front-end-editor/includes/display/fields/profile-meta-filter.php on line 13

Warning: Invalid argument supplied for foreach() in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/ninja-forms-front-end-editor/includes/display/fields/post-values-filter.php on line 15

Warning: Invalid argument supplied for foreach() in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/ninja-forms-front-end-editor/includes/display/fields/post-meta-filter.php on line 9

Warning: Invalid argument supplied for foreach() in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/ninja-forms-front-end-editor/includes/display/fields/profile-meta-filter.php on line 13

Warning: Invalid argument supplied for foreach() in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/ninja-forms-front-end-editor/includes/display/fields/post-values-filter.php on line 15

Warning: Invalid argument supplied for foreach() in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/ninja-forms-front-end-editor/includes/display/fields/post-meta-filter.php on line 9

Warning: Invalid argument supplied for foreach() in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/ninja-forms-front-end-editor/includes/display/fields/profile-meta-filter.php on line 13

Warning: Invalid argument supplied for foreach() in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/ninja-forms-front-end-editor/includes/display/fields/post-values-filter.php on line 15

Warning: Invalid argument supplied for foreach() in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/ninja-forms-front-end-editor/includes/display/fields/post-meta-filter.php on line 9

Warning: Invalid argument supplied for foreach() in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/ninja-forms-front-end-editor/includes/display/fields/profile-meta-filter.php on line 13

Warning: Invalid argument supplied for foreach() in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/ninja-forms-front-end-editor/includes/display/fields/post-values-filter.php on line 15

Warning: Invalid argument supplied for foreach() in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/ninja-forms-front-end-editor/includes/display/fields/post-meta-filter.php on line 9
