### ISSUE TITLE
Allow Sign Language in your Contact Form

### ISSUE THREAD

**Issue by binarykitchen** [wpninjas/ninja-forms#906]
Hello there

I'm Michael, a Deaf programmer and have something in mind for a long time I'd like to share with some bigger CMS contact plugin maintainers.

You probably know that there are around 200 million Deaf people who communicate in Sign Language, not in spoken language. And probably only half of them have unfortunately almost no literacy skills (social issue). Hence I've been working on a prototype for three years that enables Deaf people to communicate in Sign Language.

It's a pure HTML5 + JavaScript solution based on websockets, is Open Source and works very well.

If you are interested and wouldn't mind to integrate this in your plugin, that would be so awesome and improves accessibility a lot. I wouldn't mind to assist and to do Pull Requests containing this feature.

Feel free to ask me anything.

Greetings from Auckland,
Michael

**Comment by kstover** [comment]
Hey Michael,

I'd definitely be open to discussing it! Could you send me a link to a demo? Does it care what sign system the user is in? (American vs international sign, etc?)

**Comment by binarykitchen** [comment]
Cool!

No, it doesn't matter what Sign Language. All it does is to record the signings through a webcam (getUserMedia) and returns you an encoded video (mp4 and webm both).

Check this out
https://www.npmjs.com/package/videomail-client

Here an example how it can be integrated to any contact form
https://www.binarykitchen.com/contact

And here's videomail's main website where Deaf people already exchange lots of emails every day
https://videomail.io

I know many WordPress driven websites who want to enable Sign Language in contact forms. This very very badly. That would be a good opportunity for us.

Ask me anything :)

**Comment by klhall1987** [comment]
Is this something we want to look into for Three?

**Comment by binarykitchen** [comment]
Yeah, it would be awesome. I do not mind doing a PR if you'd accept it. It would give your plugin a good boost since lots of members of the Deaf community use WordPress but still can't express their messages in their native language: Sign Language, not English.

**Comment by binarykitchen** [comment]
moved to https://github.com/wpninjas/ninja-forms/issues/1078
