### ISSUE TITLE
Update File Naming Convention

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#910]
- [x] address2
- [x] address
- [x] button
- [x] checkbox
- [x] checkboxlist
- [x] city
- [x] country
- [x] date
- [x] email
- [x] firstname
- [x] lastname
- [x] multiselectlist
- [x] password
- [x] phone
- [x] radiolist
- [x] selectlist
- [x] state
- [x] textarea
- [x] textbox
- [x] zip

**Comment by jameslaws** [comment]
Closed. Pre development issue. Completed.
