### ISSUE TITLE
Errors on fresh install

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#911]
In a fresh install of the current master branch (9/3) I cannot add fields to forms or activate Front End Editor without getting a fatal error.

The first time, I received the error below in a form title.  I have not been able to reproduce this mystery form.
<img width="229" alt="2015-09-03_10-58-31" src="https://cloud.githubusercontent.com/assets/7498743/9665162/7135a214-523c-11e5-8832-823e74e9c8f1.png">

**Comment by kjohnson** [comment]
@wpnzach Was not able to reproduce.

**Comment by wpnzach** [comment]
FEE activated for you fine after the fresh install?  I still can't get it working.  :-/

**Comment by klhall1987** [comment]
@wpnzach What error are receiving? I received the following error, if I activated FEE without Ninja Forms core active. 

Fatal error: Call to undefined function ninja_forms_get_all_forms() in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/ninja-forms-front-end-editor/includes/activation.php on line 19

**Comment by wpnzach** [comment]
"Notice: Undefined index: form_title in F:\MAMP\htdocs\wordpress\wp-content\plugins\ninja-forms-front-end-editor\includes\activation.php on line 21"

There's also a fatal error but WordPress won't report it to me even with debugging turned on, it just won't let me activate.

**Comment by kjohnson** [comment]
@wpnzach, Can you install a fresh copy of WordPress and a fresh copy of Ninja Forms from master and see if you can replicate the issue? If so, please provide reproduction steps, as we are not seeing the issue.

**Comment by jameslaws** [comment]
@wpnzach, Is this still an issue?

**Comment by jameslaws** [comment]
Or is it better meant for the FEE repo?
