### ISSUE TITLE
If forms not saved, fields added to form will error

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#912]
Create a form.  Add a field.  Close or reload the page (do not save the form.)

Open the form again (or use the reloaded page).  Fields will be present, but trying to expand them gives the javascript error below:

Uncaught TypeError: Cannot read property 'toggleMetabox' of undefined(anonymous function) @ builder.min.js?nf_ver=2.9.27&ver=4.2.4:1m.event.dispatch @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:3m.event.add.r.handle @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:3

**Comment by followfung** [comment]
I have this issue as well. It may be worth it to note that I cannot remove these fields either.

**Comment by wpnzach** [comment]
If you save the form, you should then be able to remove these fields.  Unfortunately, this will likely not be fixed in lieu of the 3.0 update in a few months.

**Comment by followfung** [comment]
^ That helps a lot :+1:

**Comment by ScottDeLuzio** [comment]
I recreated the same error while using Chrome, however I was not able to remove the fields even with saving as @wpnzach suggested. I was able to open the same form in Firefox and the form was functioning as expected. No errors in Firefox.

**Comment by jameslaws** [comment]
This is fixed in future 3.0
