### ISSUE TITLE
Refactor template methods into template name properties

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#914]
Field Classes should have the `template()` methods removed (from all abstract and child classes).

Also, template protected properties should be added as needed:

- [x] NF_Abstracts_Field
- [x] NF_Abstracts_Input
- [x] NF_Field_Checkbox
- [x] NF_Abstracts_List
- [x] NF_Field_ListSelect

**Comment by jameslaws** [comment]
Closed. Pre development issue. Completed.
