### ISSUE TITLE
Custom CSS Class for form

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#915]
We do this for fields...why not the form container as well?

**Comment by wpnzach** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;9I3atM1E&#x2F;1-ghjfg"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> ghjfg</a>

**Comment by jameslaws** [comment]
This is blessed for 3.0
