### ISSUE TITLE
Not creating submissions table

### ISSUE THREAD

**Issue by kevinlangleyjr** [wpninjas/ninja-forms#916]
If you look in the activation file, you don't ever create the `$wpdb->prefix . 'ninja_forms_subs'` or `NINJA_FORMS_SUBS_TABLE_NAME` table.

On fresh install, I received upgrade notices from the plugin which when trying to perform those upgrades, I obviously get the warning `WordPress database error: [Table 'talisequity.wp_ninja_forms_subs' doesn't exist]`

**Comment by kjohnson** [comment]
Hey @kevinlangleyjr,

This is a remnant of an older version that used a separate table for form submissions. The most current version uses a CPT for submissions.

You should not be seeing an error, however.

Have you been in touch with out [support department](http://ninjaforms.com/contact/) regarding this issue? That will be the fastest method for us to troubleshoot this issue on you site.

**Comment by kevinlangleyjr** [comment]
Thanks but I'm not really asking for help with it on my site. I actually just decided to abandon using the plugin after seeing it referencing a table that never gets created by the plugin.

Just wanting to report that a fresh install from WP.org is throwing errors so you can correct it. 

I am seeing the error because you have the upgrade function running regardless of if the table exists or not. https://github.com/wpninjas/ninja-forms/blob/be80b5aed725966baaf18784cec69540f261a7d4/deprecated/includes/admin/upgrades/convert-subs.php#L94

**Comment by kjohnson** [comment]
@kevinlangleyjr we have not seen this as a reported issue previously, and have not seen this error in our own testing, however, we are happy to address the issues that you are seeing. I will bring this to the development team.

Thank you for reporting this issue.

**Comment by e-roc** [comment]
I am having the exact same problem with a fresh install. Just downloaded and installed from your site, and it immediately tries to install the upgrade and reports the missing table. This seems to be a legitimate issue.

**Comment by kjohnson** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;JRifOgJn&#x2F;62-github"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Github</a>

**Comment by spiderwisp** [comment]
Same issue here and ninja forms is stuck in limbo trying to upgrade, so I'll have to 1) create this table that doesn't exist 2) hack ninja core code to not check for the table

Either way costing more dev time :/

**Comment by spiderwisp** [comment]
So, after creating the table with 3 columns (id, form_id, action), the forms upgrade pane proceeds to the Notifications pane which produces the following error:

Bad Response :'(
SyntaxError: Unexpected token N

Notice: Undefined index: admin_subject in /var/www/html/wp-content/plugins/ninja-forms/includes/admin/upgrades/convert-notifications.php on line 118
{"upgrade":"notifications","total_steps":25,"args":{"forms":{"1":"1","2":"2","3":"4","4":"8","5":"9","6":"11","7":"12","8":"6","9":"7","10":"14","11":"15","12":"42","13":"55","14":"57","15":"58","16":"3","17":"59","18":"60","19":"61","20":"62","21":"63","22":"64","23":"65","24":"66","25":"67"}},"step":2}

**Comment by kstover** [comment]
Hey @spiderwisp. If you add this option to your WP options table, you won't be prompted to update the submissions table: nf_convert_subs_step. Setting it to "complete" without the quotes will prevent the update from showing. As @kjohnson said, this isn't something that we've been able to replicate or reproduce. We are currently working on a complete rewrite of Ninja Forms, and this is something that shouldn't be an issue once we are finished with the code changes.

**Comment by spiderwisp** [comment]
I did find a work around. 
1) deactivate all ninja forms extensions
2) export ninja forms tables from database
3) uninstall core ninja forms plugins
4) drop ninja forms tables from database
5) reinstall latest version of ninja forms
6) goto wp-admin/Forms and upgrade if prompted
7) drop new ninja forms tables
8) import original ninja forms tables

This also solved an error I was having between my local dev environment and the remote server using the file uploads extension (added the ability to drag n drop).

One thing I noticed during this process is that the table `wp_ninja_forms` which existed previously is no longer used.

**Comment by spiderwisp** [comment]
Perhaps not the best place for this suggestion, but one thing I have noticed from a development perspective is that the ability to import a form and maintain the id would be very handy. Since much of the code I've inherited relies upon field ids this becomes problematic when importing/exporting forms, which is why I've been relying on the database - however that seems to have presented its own set of problems, such as the one above.

**Comment by kstover** [comment]
We've actually decided to add form and field key names. This will let you target something with custom code that doesn't change upon import, as long as you don't have another form with the same key.

**Comment by jameslaws** [comment]
Closed due to enhamcements in 3.0
