### ISSUE TITLE
Ninja Forms overwrites admin post update messages not translatable

### ISSUE THREAD

**Issue by hatsumatsu** [wpninjas/ninja-forms#924]
For some reason Ninja Form overwrites the messages that appear in the edit post/page/CPT admin interface globally (f.e. "post updated. Preview post"). 

To make it worse these messages are not translatable, so non-english sites end up with a confusing language mix on all post / page / custom post type edit actions. The code in question lies in https://github.com/wpninjas/ninja-forms/blob/master/deprecated/classes/subs-cpt.php#L636. 
I wonder why this function is there neccassary and not filtered by the form / submission post type.

Using WP 4.3.1 and Ninja Forms 2.9.27

**Comment by kstover** [comment]
Admin messages for post/pages/cpts shouldn't be changed unless they are the "nf_sub" post type. I've assigned this to a developer to investigate.

**Comment by hatsumatsu** [comment]
Any news on this, could you reproduce the issue?

**Comment by kjohnson** [comment]
@hatsumatsu we are currently building a 3.0 version of Ninja Forms. As that release is fast approaching, we will make sure that this bug does not appear in 3.0.

**Comment by hatsumatsu** [comment]
I know you're busy with 3.0, but this bug is really annoying on non-english setups.You might consider merging my pull request on the 2.9.X branch...

**Comment by jameslaws** [comment]
This issue is fixed by #948
