### ISSUE TITLE
User complained of tooltips not working due to ourdated qtip version

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#925]
"Recently I installed your plug-in, Ninja-forms (and bought your plug-ins
'Conditionals' and 'Multi-part'). Which are all very nice and easy to use!
Thanks for that :) But I found out that the plug-in Ninja-forms is using an
outdated version of qTip2. My tooltips were not working in the form. 

The qTip jQuery was using version 2.0.0 and gave and error for 'msie',
which is removed from the jQuery librarie. So here is the new version of
qTip without any error:

http://cdnjs.cloudflare.com/ajax/libs/qtip2/2.2.1/jquery.qtip.min.js

And again, thanks a lot for the great plugins!"

**Comment by jameslaws** [comment]
I know we've changed the tooltips we are using, but are we adding this setting into 3.0 like we had it in version 2.9.x?

**Comment by kstover** [comment]
We don't use QTip in 3.0.
