### ISSUE TITLE
how Can I hide to textarea/textbox ?

### ISSUE THREAD

**Issue by yassara** [wpninjas/ninja-forms#926]
Hi,
I want to take from product page when customer send a messega us. I added a textarea in form input page title but I dont want to show it. 
How can I do?
https://heryeretoner.com/toner/hp-ce285a-orjinal-toner/

**Comment by kstover** [comment]
I think your best bet would be to add a hidden field with a default value of the current Page/Post ID or title.

**Comment by yassara** [comment]
thanx so much.
