### ISSUE TITLE
How to refer to a field using the field_name?

### ISSUE THREAD

**Issue by followfung** [wpninjas/ninja-forms#927]
I'm trying to write a custom post processing hook, and I need to identify the fields by their name.

`$all_fields = $ninja_forms_processing->get_all_fields();` returns an array using the field_id as keys. Is there a similar function that returns an array with the name as keys?

**Comment by kstover** [comment]
There isn't currently a way to do this, although field keys are something we're going to be adding in version 3.0 of Ninja Forms.

At the moment, your best option would be to grab all the fields and loop through them looking for a specific label or class name.

**Comment by jameslaws** [comment]
I'm not sure who should be assigned this issues, but I'm blessing it for 3.0.

**Comment by followfung** [comment]
:+1:

**Comment by kstover** [comment]
Should be closed with #963.

**Comment by kjohnson** [comment]
@followfung in 3.0, fields will be callable by either a field key or an id.

**Comment by kjohnson** [comment]
@followfung Example:

`Ninja_forms()->form( $form_id )->get_field( $field_key )`

or

```php
$fields = Ninja_Forms()->form( $form_id )->get_fields();

foreach( $fields as $field ){
    if( 'foo' != $field->get_key() ) continue;

    // Custom Code Here
}
```

**Comment by followfung** [comment]
Is this available now (v2.9.33)?

**Comment by kjohnson** [comment]
@followfung this will be available in Ninja Forms THREE (v3.0).

**Comment by followfung** [comment]
Ah, I cannot read. But this is great news! :)

**Comment by kjohnson** [comment]
I updated my previous comment to specify v3.0+.

We are very excited about this new feature, which you can checkout in the
beta: http://developer.ninjaforms.com/ready-set-develop/
