### ISSUE TITLE
Style sheets loading in the footer causing chrome rendering issue

### ISSUE THREAD

**Issue by DustinJSilk** [wpninjas/ninja-forms#929]
In chrome one of my forms is rendering a duplicate form (Incorrect styling) behind the correctly rendered form. When i resize the browser it figures it out and comes right. It's most prominent when in Incognito mode but does happen on occasion in normal chrome.

I added these to my functions file in "wp_enqueue_scripts" action and now the stylesheets load in the head and the layout issue is resolved.

```php
        wp_deregister_script( 'ninja-forms-style-display' ); 
        wp_deregister_script( 'ninja-forms-display' ); 
        wp_deregister_script( 'jquery-qtip' ); 
        wp_deregister_script( 'jquery-rating' ); 
        wp_enqueue_style( 'ninja-forms-style-display', NINJA_FORMS_STYLE_URL.'/css/ninja-forms-style-display.css' );
        wp_enqueue_style( 'ninja-forms-display', NINJA_FORMS_URL .'css/ninja-forms-display.css?nf_ver=' . NF_PLUGIN_VERSION );
        wp_enqueue_style( 'jquery-qtip', NINJA_FORMS_URL .'css/qtip.css' );
        wp_enqueue_style( 'jquery-rating', NINJA_FORMS_URL .'css/jquery.rating.css' );
```

**Comment by kstover** [comment]
Hey Dustin,

Thanks for the information. This isn't something that I've seen before, but from what I can gather, our current version of 3.0 should take care of the issue.
