### ISSUE TITLE
How to submit new translation?

### ISSUE THREAD

**Issue by datagutten** [wpninjas/ninja-forms#930]
I have made a norwegian translation for ninja forms 2.9.27. The guidelines says that I should submit a pull request on the master branch, but all language files and data on master branch is inside a folder named "deprecated".
Should I put my translation inside that or should I use another branch or tag?

**Comment by kstover** [comment]
We're in the middle of a massive re-write of Ninja Forms, which will require a new translation. For 2.9.x code, the best place to put that would be in the /deprecated/lang/ folder in the master branch. You can submit a pull request with those changes to master, I'll see about merging them in for users who are on 2.9.x.

**Comment by datagutten** [comment]
Submitted pull request #933
