### ISSUE TITLE
Allow custom classes and attributes for list items

### ISSUE THREAD

**Issue by JacobDorman** [wpninjas/ninja-forms#937]
**Use case:** adding a `data-bind` attribute to each checkbox (or failing that, a custom class).

in `ninja-forms/includes/fields/list.php\ninja_forms_field_list_display` the markup for the input element is output with:
```php
<input
    id="ninja_forms_field_<?php echo $field_id; ?>_<?php echo $x; ?>"
    name="ninja_forms_field_<?php echo $field_id; ?>[]" type="checkbox"
    class="<?php echo $field_class; ?> ninja_forms_field_<?php echo $field_id; ?>"
    value="<?php echo $value; ?>" <?php echo $checked; ?>
    rel="<?php echo $field_id; ?>"/>
```

It would be handy to be able to filter `$field_class`, or a `$other` similar to `$checked` for any content.
Ideally a $attributes array that would output key=value.

or is there an different approach i'm missing?

**Comment by jameslaws** [comment]
@kstover, thoughts?

**Comment by kstover** [comment]
We're going to be adding the ability to add custom data attributes in version 3.0. This should take care of this.
