### ISSUE TITLE
Add custom WP-CLI command

### ISSUE THREAD

**Issue by fjarrett** [wpninjas/ninja-forms#938]
It would be great if a custom WP-CLI command was available for managing forms programmatically.

The sub-commands for forms could be modeled off of the [`wp post`](http://wp-cli.org/commands/post/) command.

**EXAMPLES**

```shell
# Manage forms
$ wp ninja-form list
$ wp ninja-form create [--<field>=<value>]
$ wp ninja-form update <form_id> [--<field>=<value>]
$ wp ninja-form delete <form_id> [--force]
$ wp ninja-form get <form_id> [--<field>=<value>]

# Manage form fields
$ wp ninja-form field list <form_id>
$ wp ninja-form field add <form_id> <field_type> [--<field>=<value>]
$ wp ninja-form field update <form_id> <field_id> [--<field>=<value>]
$ wp ninja-form field delete <form_id> <field_id>
$ wp ninja-form field get <form_id> [--<field>=<value>]

# Manage form submissions
$ wp ninja-form submission list <form_id>
$ wp ninja-form submission delete <form_id> <submission_id>
```

cf. https://github.com/wp-cli/wp-cli/wiki/List-of-community-commands

**Comment by kstover** [comment]
I think that this would be a really cool addition, and something that we can look at adding once 3.0 is out the door.

**Comment by jameslaws** [comment]
I know we've already added this to version 3.0. Is it in a position that it should be considered closed?
