### ISSUE TITLE
Global Label Text translation required for ninja_forms_field_profile_pass_pre_process

### ISSUE THREAD

**Issue by Badgott** [wpninjas/ninja-forms#939]
Hello,

it seems that the Password mismatch Error text will not got over the Settings and could not be manipulated by an hook.

Please see the provides screen for the Method: ninja_forms_field_profile_pass_pre_process
![password php](https://cloud.githubusercontent.com/assets/9559452/10497983/587d9ec2-72c9-11e5-9171-aee9a22fefa9.png)

**Comment by jameslaws** [comment]
Let make sure this isn't an issue in 3.0.

**Comment by kjohnson** [comment]
`ninja_forms_password_confirm_mismatch`
