### ISSUE TITLE
A way to edit HTML output via filter?

### ISSUE THREAD

**Issue by zerodburn** [wpninjas/ninja-forms#941]
Hi,

I use an inline-block grid system and it requires that there is no whitespace between elements. I have googled around but I can't find any info on editing the actual html output of a ninja form. Is there a way to remove the html whitespace around individual `.field-wrap` `div` elements?

E.g. 

`<div class="field-wrap">....</div><div class="field-wrap">.....</div>` 

not

`<div class="field-wrap">....</div>
<div class="field-wrap">.....</div>`

**Comment by zerodburn** [comment]
For now I'm just using w3 total cache to remove line breaks in HTML code, but I hope this can be looked at in v3.

Cheers

**Comment by kjohnson** [comment]
@zerodburn This would be much easier in v3. You can stay up to date on the progress on our site https://ninjaforms.com/ninja-forms-3-0/

**Comment by jameslaws** [comment]
I'm thinking this isn't something that's going to be looked at in our current 2.9.x versions and may very well already be taken care of in the 3.x versions. Closing until notified otherwise.
