### ISSUE TITLE
Make it easier to NOT load the jquery-smoothness stylesheet

### ISSUE THREAD

**Issue by ericnicolaas** [wpninjas/ninja-forms#942]
We hit an incompatibility issue with our plugin, Charitable, and Ninja Forms, because of the jquery-smoothness stylesheet. The issue is that we are using jQuery datepicker in our admin UI as well, and we have defined custom styles for jQuery UI. But with Ninja Forms installed, the addition of `jquery-smoothness` causes a phantom extra calendar to be displayed randomly at the bottom of the window. 

I found a way to unset this, but it seems like this is the kind of thing other plugin developers may run into problems with too. Wondering if adding a simple conditional filter around the enqueue call in `NF_Admin_AddFormModal` might be worth providing as an easy way for plugin devs to NOT load that. 

Cheers, 
Eric

**Comment by jameslaws** [comment]
Is this on the post or page editing screen? Where we have the Add Form modal?

**Comment by ericnicolaas** [comment]
@jameslaws Sorry for not following up with this. The good news is that this doesn't happen with 3.0 anymore. Reverting back to 2.9 does result in it rearing its head again. But given that 3.0 is the official version now, I'm happy to close this and just remove our workaround code in a future release.
