### ISSUE TITLE
Plain text alternative part

### ISSUE THREAD

**Issue by diegosf93** [wpninjas/ninja-forms#943]
Recently I was researching why my emails from the forms arrive to spam folder and I notice this rule of spamassassin: http://wiki.apache.org/spamassassin/Rules/MIME_HTML_ONLY
I  think would be a good feature add plain text alternative option to improve spam score.

Thanks !

**Comment by jameslaws** [comment]
In 3.0, could we provide a plain text alternative by default, even if the users selects HTML? Just the same message, but stripped of all html.

**Comment by markvankampen** [comment]
Would be great! I just ran into the same issue on my site.

**Comment by diegosf93** [comment]
I'm agree with that !

**Comment by jameslaws** [comment]
See issue #952 as well.

**Comment by kjohnson** [comment]
Looks like `wp_mail()` has a patch being reviewed for support of multiple message types:

- http://wordpress.stackexchange.com/a/191974
- https://core.trac.wordpress.org/ticket/15448

However, it has not currently been implemented as of 4.4.1.
https://core.trac.wordpress.org/browser/tags/4.4.1/src/wp-includes/pluggable.php#L230

**Comment by kjohnson** [comment]
Possible solution as a work around (have not tested): http://wordpress.stackexchange.com/a/194131

**Comment by jameslaws** [comment]
@kjohnson, I wonder if this is a patch we could champion and try to drum up support for? If it's a big enough issue that is.

**Comment by kjohnson** [comment]
I'm not sure of the magnitude of the issue, but the patch hasn't raised much support.
