### ISSUE TITLE
Datepicker Localization

### ISSUE THREAD

**Issue by raducretu** [wpninjas/ninja-forms#944]
Hi guys,

I wanted to share a filter for localization the datepicker in case you decide to include it:
```

/** Localize Ninja Forms Datepicker Filter */
		add_filter( 'ninja_forms_forms_display_datepicker_args', 'localize_datepicker' , 10, 1 );

/** Ninja Localization */
	function localize_datepicker( $datepicker_args ){
		
		global $wp_locale;
		
		$datepicker_args['monthNames'] = array_values( $wp_locale->month );
		$datepicker_args['monthNamesShort'] = array_values( $wp_locale->month_abbrev );
		$datepicker_args['dayNames'] = array_values( $wp_locale->weekday );
		$datepicker_args['dayNamesShort'] = array_values( $wp_locale->weekday_abbrev );
		$datepicker_args['dayNamesMin'] = array_values( $wp_locale->weekday_initial );
		
		return $datepicker_args;
	}
```

It uses the basic WP localization.

**Comment by jameslaws** [comment]
Are we going to be using jQuery UI date picker in 3.x? Wondering if this is better to close for our 3.0 solution?

**Comment by kjohnson** [comment]
@raducretu @jameslaws

I've been distributing this micro plugin via the support office as it has been needed: https://github.com/kjohnson/ninja-forms-datepicker-localize

Also, it seems like we will be using the jQuery UI Datepicker for 3.0, being that it is already included with WordPress.
