### ISSUE TITLE
Ninja Forms AJAX initialisation function

### ISSUE THREAD

**Issue by samloomes** [wpninjas/ninja-forms#949]
Hey guys,

I'm trying to use Ninja forms AJAX submission on a site where the forms are being pulled in via AJAX themselves, it seems that all event handlers are attached on $(document).ready() which means that forms pulled in after that event don't have the event handlers bound.

Is there a function I can use to rebind the event handlers to new forms? Or another way of going about this?

Cheers

**Comment by kstover** [comment]
Hey sam,

Unfortunately, there isn't a way to do this currently. If you took the code inside the document.ready() block in the ninja-forms-display.js file, you could wrap all that code in a function, and then call that function after the AJAX has finished pulling. With 3.0, this will be the case by default, so you'll be able to re-init the display stuff whenever necessary.

**Comment by samloomes** [comment]
Understood, thanks for the quick reply!

**Comment by bucketpress** [comment]
Hi Sam,

Now that 3.0 is out and we no longer have ninja-forms-display.js . How do we init a ninja form after the form is added to the dom via ajax? By the way, 3.0 is awesome.

**Comment by mycarrysun** [comment]
@kstover Having this problem too, when we need to manipulate the form DOM after it is loaded via ajax, how can we determine when the DOM is fully loaded in our js?

**Comment by mycarrysun** [comment]
@kstover is there a way to use the nfRadio object to add another handler to the loaded event? I've been trying to do something like:

```
nfRadio.channel('form-2').on('loaded', function(){
    console.log('test2');
});
```

**Comment by mycarrysun** [comment]
@kstover  Update for anyone who wants to know how to hook into this.

I had to tweak a couple of things with the code above to make this work (you can arrange the code structure to how you prefer)

```
var checkNfRadio = setInterval(check_nf_radio_exists, 100); //check every 100ms

function check_nf_radio_exists(){
    if (typeof nfRadio !== 'undefined' ) {
        clearInterval(checkNfRadio);
        nfRadio.channel('form').on('render:view', function(){
            console.log('form is ready here');
        });
    }
}
```

**Comment by Pamps** [comment]
You can listen for nfFormReady which fires when the form is loaded and ready.

```
jQuery( document ).on( 'nfFormReady', function() {
  // do something
}
```
