### ISSUE TITLE
Poedit, Ninja Forms, WPML - can't create MO file

### ISSUE THREAD

**Issue by magadc** [wpninjas/ninja-forms#951]
Hello.
In case this info is important: we're using Flatsome theme with 3 language versions (we're using WPML plugin).

We've one form for each language and we use Ninja forms. The error messages need to be translate and the plugin has already a mo and po file for spanish version but we're having issues in creating the portuguese mo.

There are the error messages we get when saving the file in the Poedit:

"duplicate message definition.."
"this is the location of the first definition"

Thanks for the help.

**Comment by jameslaws** [comment]
We actually handle all translations from the WordPress translation system now. According to that we already have a Portuguese version as fully translated as the Spanish. Have you looked there?

**Comment by magadc** [comment]
Hello.
Problem solved. We update the Poedit version.
Thanks.
