### ISSUE TITLE
Form submissions from Ninja Forms marked as spam

### ISSUE THREAD

**Issue by markvankampen** [wpninjas/ninja-forms#952]
Recently a new mail filter was implemented on our server. Since then, I no longer receive form submissions via mail. The mails from Ninja Forms get high SPAM scores in Spamassassin and are therefore quarantained. Particularly the following rules have a high score:

* HTML_MIME_NO_HTML_TAG=0.635 (HTML message doesn't start with <html>)
* MIME_HTML_ONLY=1.105 (no plain text alternative)
* TO_NO_BRKTS_HTML_ONLY=1.999 (no quotes around mail address)
* XPRIO=1.568 (mail priority)

**Comment by kjohnson** [comment]
Is the same true for other WordPress emails? We use `wp_mail` to send emails, so they should be similar.

**Comment by jameslaws** [comment]
Kyle, we send that data the way it is to wp_mail though. The question to me is, can we send the data with these things in mind to at least help prevent them?

**Comment by markvankampen** [comment]
@kjohnson No, WordPress emails get through the filter. The problem is in the message content and mail headers set by Ninja Forms.

**Comment by markvankampen** [comment]
The HTML_MIME_NO_HTML_TAG score is probably fixed by adding < html > at the beginning of the HTML message content (if it isn't already - see #943 )

MIME_HTML_ONLY is fixed by adding a plain text alternative (see #943 too)

TO_NO_BRKTS_HTML_ONLY should be fixed by adding quotes around the name of the recipient (To:  "J Random User" <jrnd@email>).

Don't know about XPRIO. I suppose this isn't set by Ninja Forms - why would it?
