### ISSUE TITLE
Localize Field Type Sections

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#959]

**Comment by jameslaws** [comment]
@kjohnson Can you add a little bit if a description on this. Not sure how involved it is without it.

**Comment by kjohnson** [comment]
@kstover I hard coded the new `pricing` field section. I also created a new config file with field sections, for translating, filtering, etc. The array is localized as `var fieldTypeSections`.

**Comment by kstover** [comment]
I'm not sure what I'm supposed to do with this?

**Comment by kstover** [comment]
Hard-coded Field Type Section names should be pulled from the localized JS data.
